/* tokenizer-compare/logic.js — L2 'climb-tokenizer-compare' beat: the SIDE-BY-SIDE we lacked.

   The chapter teaches three tokenizer FAMILIES (BPE merges by frequency, WordPiece by likelihood
   gain + `##` continuations, Unigram by likelihood loss / Viterbi decode) and the byte-level upgrade.
   bpe-steps shows ONE cutter's loop; bpe-merge-ledger shows its result. This widget puts all FOUR
   cutters on the SAME sample input, trained at the SAME vocab size, and ranks them by token count so
   "fewer tokens = more efficient" reads at a glance. Numbers come from data/l2-tokenizers.json (the
   source of truth, generated by _research/gen_l2_tokenizers.py with HuggingFace `tokenizers`).

   STEP MODEL (maxStep = 5):
     • s0 — the raw input (one word-chip row), nothing cut yet;
     • s1..s4 — reveal each tokenizer's segmentation, in count-rank order (fewest first): BPE → then
                WordPiece → Unigram → Byte-level BPE, each as its token chips + a token-count badge;
     • s5 — the ranked comparison: every row colour-graded by rank (green=fewest … amber=most), the
            "fewer = more efficient" read locked in.

   DRIVER-AGNOSTIC (REFERENCE_IMPL_L2 a.6): exposes setStep(k)/maxStep, binds NO keyboard and NO
   scroll — the SLIDE driver (deck arrow keys) and the BOOK driver (Scrollama) both call setStep(k).
   All human text comes from i18n keys in `labels`; all colour comes from CSS role/categorical tokens
   (no raw colour literals here — the contract scan is HARD on off-token paint).

   Built on the shared widgets/_widget-base.js factory (wgt-root/wgt-fade host, caption/counter
   scaffold, the setStep clamp + host.dataset.step, esc()). render() builds the scaffold and returns
   an update(k) that reveals rows + recolours on the final ranked step. */
import { defineWidget, esc } from '../_widget-base.js';

// rank (1..4) → row accent class. Green = fewest (most efficient), amber = most; the two middle
// ranks use distinct categorical hues (accent / violet) so each cutter is told apart. All map to
// design-token CSS vars in style.css (the "one colour = one meaning" contract).
const RANK_CLASS = { 1: 'tc-row--best', 2: 'tc-row--mid1', 3: 'tc-row--mid2', 4: 'tc-row--worst' };

export const mountTokenizerCompare = defineWidget({
  id: 'tokenizer-compare',
  rootClass: 'tc-root',
  exportName: 'mountTokenizerCompare',
  maxStep: 5,
  render({ host, data, labels }) {
    const sample = data.sample || '';
    const sampleWords = data.sampleWords || sample.split(/\s+/).filter(Boolean);
    // tokenizers ordered by count rank (fewest → most) so the reveal order is meaningful.
    const toks = (data.tokenizers || []).slice().sort((a, b) => (a.rank || 99) - (b.rank || 99));
    const maxCount = toks.reduce((m, t) => Math.max(m, t.count || 0), 1);

    const panel = document.createElement('div');
    panel.className = 'wgt-panel tc-panel';
    host.appendChild(panel);

    // ── region 1: the raw input (revealed at s0) ──────────────────────────────
    const input = document.createElement('div');
    input.className = 'tc-region tc-input';
    const inputHead = document.createElement('div');
    inputHead.className = 'tc-head';
    inputHead.textContent = labels.inputHead || 'The same input, four cutters';
    input.appendChild(inputHead);
    const inputRow = document.createElement('div');
    inputRow.className = 'tc-input-row';
    sampleWords.forEach((w) => {
      const chip = document.createElement('span');
      chip.className = 'tc-tok tc-tok--word';
      chip.textContent = w;
      inputRow.appendChild(chip);
    });
    input.appendChild(inputRow);
    panel.appendChild(input);

    // ── region 2: one row per tokenizer (revealed s1..s4, recoloured at s5) ────
    const grid = document.createElement('div');
    grid.className = 'tc-grid';
    panel.appendChild(grid);

    // marker → human note (Ġ = leading space, ## = continuation). i18n-driven, falls back to ''.
    const markerNote = (m) => (m === '##' ? (labels.markerHash || '')
      : m === 'Ġ' ? (labels.markerSpace || '') : '');

    const rows = toks.map((t) => {
      const row = document.createElement('div');
      row.className = 'tc-row is-hidden';

      // header: name + family + count badge
      const rowHead = document.createElement('div');
      rowHead.className = 'tc-row-head';
      const name = document.createElement('span');
      name.className = 'tc-name';
      name.textContent = t.name;
      const fam = document.createElement('span');
      fam.className = 'tc-fam';
      fam.textContent = t.family || '';
      const badge = document.createElement('span');
      badge.className = 'tc-badge';
      badge.innerHTML = `<span class="tc-badge-n">${esc(t.count)}</span>` +
        `<span class="tc-badge-lab">${esc(labels.tokensLab || 'tokens')}</span>`;
      rowHead.appendChild(name);
      rowHead.appendChild(fam);
      rowHead.appendChild(badge);
      row.appendChild(rowHead);

      // chips: each token; marker prefixes (Ġ / ##) get a muted accent so they read as structure
      const chips = document.createElement('div');
      chips.className = 'tc-toks';
      (t.tokens || []).forEach((tok) => {
        const c = document.createElement('span');
        c.className = 'tc-tok';
        // split a leading marker so it can be tinted without changing the glyph
        if (t.marker === '##' && tok.startsWith('##')) {
          c.classList.add('tc-tok--cont');
          c.innerHTML = `<span class="tc-mark">##</span>${esc(tok.slice(2))}`;
        } else if (t.marker === 'Ġ' && tok.startsWith('Ġ')) {
          c.classList.add('tc-tok--space');
          c.innerHTML = `<span class="tc-mark">␣</span>${esc(tok.slice(1)) || ''}`;
        } else {
          c.textContent = tok;
        }
        chips.appendChild(c);
      });
      row.appendChild(chips);

      // efficiency bar: width ∝ token count (longer bar = more tokens = less efficient)
      const bar = document.createElement('div');
      bar.className = 'tc-bar';
      const fill = document.createElement('span');
      fill.className = 'tc-bar-fill';
      fill.style.width = Math.max(6, Math.round(((t.count || 0) / maxCount) * 100)) + '%';
      bar.appendChild(fill);
      const note = document.createElement('span');
      note.className = 'tc-note';
      note.textContent = markerNote(t.marker);
      row.appendChild(bar);
      row.appendChild(note);

      grid.appendChild(row);
      return { row, rank: t.rank };
    });

    // verdict line (revealed at the final ranked step)
    const verdict = document.createElement('div');
    verdict.className = 'tc-verdict is-hidden';
    verdict.textContent = labels.verdict || 'Fewer tokens = more efficient';
    panel.appendChild(verdict);

    // per-step update (factory clamps k to [0,maxStep] and owns the scrolly caption/counter).
    //   k=0 → only the raw input; k=1..4 → reveal the row at that rank; k=5 → all revealed, ranked.
    return function update(k) {
      const revealed = Math.max(0, Math.min(rows.length, k));   // how many tokenizer rows are shown
      const ranked = k >= rows.length + 1;                      // the final ranked-comparison step
      rows.forEach((r, i) => {
        const show = i < revealed;
        r.row.classList.toggle('is-hidden', !show);
        // the row revealed THIS step gets a brief "just-arrived" emphasis (drops on the ranked step)
        r.row.classList.toggle('is-new', show && i === revealed - 1 && !ranked);
        // colour-grade by rank only once everyone is on screen (the ranked verdict step)
        const rankCls = RANK_CLASS[r.rank];
        if (rankCls) r.row.classList.toggle(rankCls, ranked);
        r.row.classList.toggle('is-ranked', ranked);
      });
      verdict.classList.toggle('is-hidden', !ranked);
    };
  },
});
