// assignments.js — the catalog of course activities (labs + homeworks).
// Data-driven: add a new activity = append one object to `assignments`.
// EN canonical + RU. TT falls back (handled by t() in the pages).
// NOTE: this module is NOT scanned by the i18n-coverage gate (only ui.js /
// course.json / book chapters / widget i18n are), so rich bilingual prose is
// fine here. Keep EN present on every {en,ru} node anyway.

// Shared front-matter + common setup, rendered once on the index page.
export const assignmentsMeta = {
  intro: {
    en: 'These activities turn the lectures into working code. Each Lab is a small, hands-on build; each Homework is a deeper experimental study plus a paper-reading essay. In all of them, you implement the core retrieval and ranking algorithms by hand — that is the point. Pick an activity below.',
    ru: 'Эти активности превращают лекции в работающий код. Каждая лаба — небольшая практическая сборка; каждая домашка — более глубокое экспериментальное исследование плюс эссе по статье. Во всех ключевые алгоритмы поиска и ранжирования вы реализуете руками — в этом и смысл. Выберите активность ниже.',
    tt: 'Бу биремнәр лекцияләрне эшләүче кодка әйләндерә. Һәр лаборатор эш — кечкенә, кулдан башкарыла торган җыелма; һәр өй эше — тирәнрәк эксперименталь тикшеренү һәм мәкалә уку буенча эссе. Барысында да эзләү һәм ранжлауның төп алгоритмнарын кулдан язасың — мәгънә шунда. Түбәндә бер бирем сайла.',
  },
  topic: {
    en: 'From classical IR (BM25, rank fusion, ranking metrics) to neural retrieval — bi-/cross-encoders and the reranking cascade, ColBERT late interaction, SPLADE learned sparse, hybrid fusion, and Learning to Rank — then indexing at scale (IVF, Product Quantization, HNSW) and retrieval-augmented generation with its evaluation (chunking, query rewriting, RAGAS-style metrics, LLM-as-judge bias).',
    ru: 'От классического IR (BM25, слияние рангов, метрики ранжирования) к нейропоиску — bi-/cross-энкодеры и каскад реранкинга, позднее взаимодействие ColBERT, выученная разрежённость SPLADE, гибридное слияние и Learning to Rank — далее индексирование на масштабе (IVF, Product Quantization, HNSW) и retrieval-augmented generation с его оценкой (чанкинг, переписывание запроса, метрики в духе RAGAS, смещения LLM-как-судьи).',
    tt: 'Классик IR’дан (BM25, ранг берләштерү, ранжлау метрикалары) нейроэзләүгә — bi-/cross-энкодерлар һәм реранкинг каскады, ColBERT соңгы тәэсир итешүе, SPLADE өйрәнелгән сирәклеге, гибрид берләштерү һәм Learning to Rank — аннары масштабта индексләү (IVF, Product Quantization, HNSW) һәм retrieval-augmented generation аны бәяләү белән (чанклау, сорауны яңадан язу, RAGAS рухындагы метрикалар, LLM-хөкемче смещениеләре).',
  },
  groups: {
    lab: { en: 'Labs', ru: 'Лабораторные', tt: 'Лаборатор эшләр' },
    homework: { en: 'Homeworks', ru: 'Домашние задания', tt: 'Өй эшләре' },
  },
  setup: {
    heading: { en: 'Common setup (applies to every activity)', ru: 'Общий setup (для всех активностей)', tt: 'Гомуми setup (һәр бирем өчен)' },
    rulesH: { en: 'Ground rules', ru: 'Общие правила', tt: 'Гомуми кагыйдәләр' },
    rules: [
      { en: 'Implement the core scoring, fusion, reranking, indexing and ranking logic by hand: the inverted index, TF-IDF, BM25, RRF, ColBERT MaxSim, the SPLADE sparse dot, RankNet/LambdaRank, the ANN index structures (IVF inverted lists + nprobe scan, PQ codes + the ADC table, the exact re-rank), RAG chunking and query-rewrite recombination, and every metric (nDCG, MAP, MRR, context precision/recall). No rank_bm25, no pytrec_eval, no library rank-fusion or learning-to-rank scorers, no faiss / hnswlib / scann / annoy or a managed vector DB, and no RAGAS/ragas library for the graded parts.', ru: 'Ключевую логику скоринга, слияния, реранкинга, индексирования и ранжирования реализуйте руками: инвертированный индекс, TF-IDF, BM25, RRF, ColBERT MaxSim, sparse-dot SPLADE, RankNet/LambdaRank, структуры ANN-индекса (инвертированные списки IVF + скан nprobe, коды PQ + таблица ADC, exact re-rank), чанкинг и рекомбинацию переписанных запросов для RAG и все метрики (nDCG, MAP, MRR, context precision/recall). Без rank_bm25, pytrec_eval, библиотечных слияний/LTR-скореров, без faiss / hnswlib / scann / annoy и управляемых векторных БД, без библиотеки RAGAS в оцениваемых частях.', tt: 'Скорлау, берләштерү, реранкинг, индексләү һәм ранжлауның төп логикасын кулдан яз: инверт индексы, TF-IDF, BM25, RRF, ColBERT MaxSim, SPLADE sparse-dot, RankNet/LambdaRank, ANN индекс структуралары (IVF инверт исемлекләре + nprobe скан, PQ кодлары + ADC таблицасы, exact re-rank), RAG чанклау һәм яңадан язылган сорауларны берләштерү, һәм һәр метрика (nDCG, MAP, MRR, context precision/recall). Бәяләнә торган өлешләрдә rank_bm25, pytrec_eval, китапханә берләштерү/LTR скорерлары, faiss / hnswlib / scann / annoy һәм идарә ителә торган вектор МБ, RAGAS китапханәсеннән башка.' },
      { en: 'Allowed helpers: dataset loading (ir_datasets / beir / HuggingFace datasets), numpy, plotting, a tokenizer/stemmer, pretrained encoders (sentence-transformers, cross-encoders, SPLADE, ColBERT), k-means (sklearn) for the ANN coarse quantizer and PQ codebooks, and — where an activity allows it — a small local generator for query rewrites / judging. The encoders and generator only supply embeddings, logits or text; you do not train them, and the scoring, fusion, reranking, indexing, chunking and metric logic stays yours.', ru: 'Разрешено: загрузка датасета (ir_datasets / beir / HuggingFace datasets), numpy, графики, токенизатор/стеммер, претренированные энкодеры (sentence-transformers, cross-encoders, SPLADE, ColBERT), k-means (sklearn) для coarse-квантизатора ANN и кодбуков PQ и — где задание это разрешает — маленький локальный генератор для переписывания запросов / судейства. Энкодеры и генератор лишь дают эмбеддинги, логиты или текст; вы их не обучаете, а логику скоринга, слияния, реранкинга, индексирования, чанкинга и метрик пишете сами.', tt: 'Рөхсәт ителгән ярдәмчеләр: мәгълүмат җыелмасын йөкләү (ir_datasets / beir / HuggingFace datasets), numpy, графиклар, токенизатор/стеммер, өйрәтелгән энкодерлар (sentence-transformers, cross-encoders, SPLADE, ColBERT), ANN coarse-квантизаторы һәм PQ кодбуклары өчен k-means (sklearn), һәм — бирем рөхсәт иткәндә — сорауларны яңадан язу / хөкем итү өчен кечкенә җирле генератор. Энкодерлар һәм генератор бары тик эмбеддинглар, логитлар яки текст бирә; син аларны өйрәтмисең, ә скорлау, берләштерү, реранкинг, индексләү, чанклау һәм метрика логикасын үзең язасың.' },
      { en: 'Be reproducible: fixed random seed (20260605), the fixed query subsets stated per activity, deterministic output. A grader must reproduce your numbers by re-running.', ru: 'Воспроизводимость: фиксированный seed (20260605), фиксированные поднаборы запросов (указаны в задании), детерминированный вывод. Проверяющий воспроизводит ваши числа повторным запуском.', tt: 'Кабатлап була торган бул: ныгытылган seed (20260605), биремдә күрсәтелгән ныгытылган сорау поднаборлары, детерминистик нәтиҗә. Тикшерүче синең саннарны яңадан җибәреп кабатлый алырга тиеш.' },
      { en: 'Submit code that runs end-to-end plus a short report (PDF). State every formula variant you chose (tf scheme, idf form, gain function).', ru: 'Сдавайте код, работающий от начала до конца, плюс краткий отчёт (PDF). Укажите все выбранные варианты формул (схема tf, форма idf, gain-функция).', tt: 'Башыннан ахырына кадәр эшләүче код һәм кыска отчёт (PDF) тапшыр. Сайлаган һәр формула вариантын күрсәт (tf схемасы, idf формасы, gain функциясе).' },
    ],
    dataH: { en: 'Dataset & access', ru: 'Датасет и доступ', tt: 'Мәгълүмат җыелмасы һәм керү' },
    dataLead: {
      en: 'Activities 1 and 2 use BEIR: the Labs use nfcorpus (≈3.6K docs, 323 test queries, graded qrels); the Homeworks may additionally repeat the headline run on scifact. Lab 3 and Homework 3 instead use EnterpriseRAG-Bench (onyx-dot-app, MIT) — a synthetic enterprise corpus (Slack, Gmail, GitHub, Jira, Confluence, Drive, …) with ground-truth documents AND gold answers per question — loaded and subset inside those two activities. The neural activities also load small pretrained encoders (named per activity, all CPU-runnable on the subset). Load the BEIR corpus via ir_datasets:',
      ru: 'Активности 1 и 2 используют BEIR: Лабы — nfcorpus (≈ 3,6 тыс. документов, 323 test-запроса, градуированные qrels); в домашках можно дополнительно повторить основной прогон на scifact. Лаба 3 и Домашка 3 вместо этого используют EnterpriseRAG-Bench (onyx-dot-app, MIT) — синтетический корпоративный корпус (Slack, Gmail, GitHub, Jira, Confluence, Drive, …) с ground-truth документами И gold-ответами на каждый вопрос — он грузится и субсетится внутри этих двух активностей. Нейро-активности также загружают небольшие претренированные энкодеры (указаны в задании, все CPU-runnable на подвыборке). Загрузка BEIR-корпуса через ir_datasets:',
      tt: 'Активностьлар 1 һәм 2 BEIR куллана: Лаборатор эшләр — nfcorpus (≈3,6 мең документ, 323 test-сорау, градуацияле qrels); өй эшләрендә төп прогонны scifact өстендә кабатларга мөмкин. Лаб 3 һәм Өй эше 3 моның урынына EnterpriseRAG-Bench (onyx-dot-app, MIT) куллана — синтетик корпоратив корпус (Slack, Gmail, GitHub, Jira, Confluence, Drive, …), ground-truth документлар ҺӘМ һәр сорауга gold-җаваплар белән — ул шул ике активность эчендә йөкләнә һәм субсетлана. Нейро-биремнәр шулай ук кечкенә өйрәтелгән энкодерлар йөкли (биремдә күрсәтелгән, барысы да подвыборкада CPU-да эшләрлек). BEIR корпусын ir_datasets аша йөклә:',
    },
    dataCode: `import ir_datasets
ds = ir_datasets.load("beir/nfcorpus/test")     # graded relevance (0..2)
docs    = {d.doc_id: d.text for d in ds.docs_iter()}
queries = {q.query_id: q.text for q in ds.queries_iter()}
qrels   = {}
for qr in ds.qrels_iter():
    qrels.setdefault(qr.query_id, {})[qr.doc_id] = qr.relevance

# Homework deeper run (optional):
# ds = ir_datasets.load("beir/scifact/test")`,
    dataNote: {
      en: 'Alternatives: the beir package GenericDataLoader, or HuggingFace datasets (BeIR/nfcorpus). Fixed query set: the first 30 test queries sorted by query_id for the Lab; the full test query set for the Homework. If memory is tight, restrict the corpus to documents that appear in any qrel plus a seed-20260605 random sample, and document the subsetting.',
      ru: 'Альтернативы: пакет beir (GenericDataLoader) или HuggingFace datasets (BeIR/nfcorpus). Фиксированный набор запросов: первые 30 test-запросов по возрастанию query_id для Лабы; полный test-набор для домашки. Если мало памяти — ограничьте корпус документами из qrels плюс случайная выборка с seed 20260605 и опишите это.',
      tt: 'Альтернативалар: beir пакеты GenericDataLoader яки HuggingFace datasets (BeIR/nfcorpus). Ныгытылган сорау җыелмасы: Лаборатор эш өчен query_id буенча тәртипкә салынган беренче 30 test-сорау; өй эше өчен тулы test-сорау җыелмасы. Хәтер аз булса — корпусны берәр qrel’да очраган документлар һәм seed-20260605 очраклы үрнәк белән чикләп, бу подбюлүне яз.',
    },
    logiH: { en: 'Logistics', ru: 'Организация', tt: 'Оештыру' },
    logi: {
      en: 'Deadlines follow the course schedule. Submit code + report PDF (coding parts) and the scanned essay + figure (essay part). Late and collaboration policy per the syllabus.',
      ru: 'Дедлайны — по расписанию курса. Сдача: код + отчёт PDF (кодовые части) и скан эссе + фигура (часть с эссе). Политика просрочек и сотрудничества — по программе.',
      tt: 'Сроклар курс расписаниесе буенча. Тапшыру: код + отчёт PDF (код өлешләре) һәм сканланган эссе + рәсем (эссе өлеше). Соңга калу һәм хезмәттәшлек сәясәте — программа буенча.',
    },
  },
};

export const assignments = [
  {
    slug: 'lab-bm25',
    kind: 'lab',
    code: 'Lab 1',
    status: 'ready',
    title: { en: 'Build BM25 by hand, compare two rankers', ru: 'BM25 руками, сравнение двух ранжировщиков', tt: 'BM25’не кулдан яз, ике ранжлаучыны чагыштыр' },
    blurb: {
      en: 'Inverted index + TF-IDF + BM25 from scratch on a real judged corpus; compare TF-IDF vs BM25 on a fixed query set with nDCG@10.',
      ru: 'Инвертированный индекс + TF-IDF + BM25 с нуля на реальном judged-корпусе; сравнение TF-IDF и BM25 на фиксированном наборе запросов по nDCG@10.',
      tt: 'Инверт индексы + TF-IDF + BM25’не чын бәяләнгән корпуста нульдән; TF-IDF белән BM25’не ныгытылган сорау җыелмасында nDCG@10 буенча чагыштыр.',
    },
    due: { en: 'Small · 1 dataset · ~1 evening', ru: 'Небольшая · 1 датасет · ~вечер', tt: 'Кечкенә · 1 мәгълүмат җыелмасы · ~бер кич' },
    blocks: [
      { t: 'h4', v: { en: 'Goal', ru: 'Цель', tt: 'Максат' } },
      { t: 'p', v: { en: 'Implement an inverted index, TF-IDF, and BM25 from scratch on a real judged corpus, then compare TF-IDF against BM25 on a fixed query set and explain — with a concrete example from your own output — where and why they differ.', ru: 'Реализовать инвертированный индекс, TF-IDF и BM25 с нуля на реальном judged-корпусе, затем сравнить TF-IDF и BM25 на фиксированном наборе запросов и объяснить — на конкретном примере из своего вывода — где и почему они расходятся.', tt: 'Инверт индексы, TF-IDF һәм BM25’не чын бәяләнгән корпуста нульдән язып, аннары TF-IDF белән BM25’не ныгытылган сорау җыелмасында чагыштырып, кайда һәм нигә алар аерылганын — үз нәтиҗәңнән конкрет мисал белән — аңлат.' } },
      { t: 'h4', v: { en: 'Tasks', ru: 'Задачи', tt: 'Биремнәр' } },
      { t: 'ol', v: [
        { en: 'Load BEIR nfcorpus/test and build the fixed query set (first 30 by query_id).', ru: 'Загрузите BEIR nfcorpus/test и постройте фиксированный набор запросов (первые 30 по query_id).', tt: 'BEIR nfcorpus/test’ны йөклә һәм ныгытылган сорау җыелмасын төзе (query_id буенча беренче 30).' },
        { en: 'Tokenize with one fixed scheme: lowercase → strip punctuation → split on whitespace. (The Lab holds tokenization fixed; the Homework varies it.)', ru: 'Токенизация одной фиксированной схемой: нижний регистр → убрать пунктуацию → разбиение по пробелам. (В Лабе токенизация фиксирована; в домашке варьируется.)', tt: 'Бер ныгытылган схема белән токенлаштыр: кече хәреф → пунктуацияне ал → буш урыннар буенча бүл. (Лаборатор эштә токенлаштыру ныгытылган; өй эшендә үзгәртелә.)' },
        { en: 'Build an inverted index from scratch: term → postings [(doc_id, tf)]; also record document lengths and avgdl.', ru: 'Постройте инвертированный индекс с нуля: терм → postings [(doc_id, tf)]; запишите длины документов и avgdl.', tt: 'Инверт индексны нульдән төзе: терм → postings [(doc_id, tf)]; шулай ук документ озынлыкларын һәм avgdl’ны яз.' },
        { en: 'Implement TF-IDF by hand: w(t,d) = tf · log(N/df). State your tf and idf variant; score by summing query-term weights or by cosine (your choice, stated).', ru: 'Реализуйте TF-IDF руками: w(t,d) = tf · log(N/df). Укажите вариант tf и idf; скоринг — сумма весов термов запроса или косинус (на ваш выбор, укажите).', tt: 'TF-IDF’ны кулдан яз: w(t,d) = tf · log(N/df). tf һәм idf вариантыңны күрсәт; скорлауны сорау термнары авырлыкларын кушу яки косинус белән башкар (үз сайлавың, күрсәт).' },
        { en: 'Implement BM25 by hand: k₁ = 1.5, b = 0.75, smoothed idf ln(1 + (N−df+0.5)/(df+0.5)). Reuse the same index.', ru: 'Реализуйте BM25 руками: k₁ = 1.5, b = 0.75, сглаженный idf ln(1 + (N−df+0.5)/(df+0.5)). Тот же индекс.', tt: 'BM25’не кулдан яз: k₁ = 1.5, b = 0.75, шомартылган idf ln(1 + (N−df+0.5)/(df+0.5)). Шул ук индексны куллан.' },
        { en: 'For each query, retrieve the top-10 under TF-IDF and under BM25.', ru: 'Для каждого запроса выдайте top-10 по TF-IDF и по BM25.', tt: 'Һәр сорау өчен TF-IDF буенча һәм BM25 буенча top-10’ны тап.' },
        { en: 'Compute nDCG@10 (by hand, graded gain 2^rel−1, log₂(i+1) discount) per query for both rankers; report the mean for each and show one query where they rank differently.', ru: 'Посчитайте nDCG@10 (руками, gain 2^rel−1, дисконт log₂(i+1)) по каждому запросу для обоих; дайте среднее и покажите запрос, где ранжирование различается.', tt: 'nDCG@10’ны (кулдан, градуацияле gain 2^rel−1, log₂(i+1) дисконты) һәр сорау өчен ике ранжлаучыга да исәплә; һәрберсенең уртачасын бир һәм ранжлау аерылган бер сорауны күрсәт.' },
        { en: 'Write a half-page analysis: where does BM25 diverge from TF-IDF, and why? Point to term-frequency saturation and document-length normalization using your concrete example.', ru: 'Напишите полстраницы анализа: где BM25 расходится с TF-IDF и почему? Сошлитесь на насыщение tf и нормировку длины на своём примере.', tt: 'Ярым бит анализ яз: BM25 TF-IDF’дан кайда аерыла һәм нигә? Үз конкрет мисалыңда терм ешлыгы туенуына һәм документ озынлыгын нормалаштыруга ишарә ит.' },
      ] },
      { t: 'h4', v: { en: 'Deliverables', ru: 'Что сдавать', tt: 'Нәрсә тапшырырга' } },
      { t: 'p', v: { en: 'lab.py (or a notebook) that runs end-to-end and prints the comparison table, plus a 1-page report: the mean-nDCG@10 table, one divergent-query table, and the analysis paragraph.', ru: 'lab.py (или notebook), работающий от начала до конца и печатающий таблицу сравнения, плюс отчёт на 1 страницу: таблица среднего nDCG@10, таблица расходящегося запроса и абзац анализа.', tt: 'Башыннан ахырына кадәр эшләп, чагыштыру таблицасын бастыручы lab.py (яки notebook), һәм 1 битлек отчёт: уртача nDCG@10 таблицасы, бер аерылган сорау таблицасы һәм анализ абзацы.' } },
      { t: 'h4', v: { en: 'Grading (100)', ru: 'Оценка (100)', tt: 'Бәяләү (100)' } },
      { t: 'grade', rows: [
        { label: { en: 'Inverted index correct', ru: 'Инвертированный индекс', tt: 'Инверт индексы дөрес' }, w: '20' },
        { label: { en: 'TF-IDF correct', ru: 'TF-IDF', tt: 'TF-IDF дөрес' }, w: '20' },
        { label: { en: 'BM25 correct', ru: 'BM25', tt: 'BM25 дөрес' }, w: '30' },
        { label: { en: 'nDCG@10 correct', ru: 'nDCG@10', tt: 'nDCG@10 дөрес' }, w: '15' },
        { label: { en: 'Analysis', ru: 'Анализ', tt: 'Анализ' }, w: '15' },
      ] },
    ],
  },

  {
    slug: 'hw-ranking-metrics',
    kind: 'homework',
    code: 'A1',
    status: 'soon',
    title: { en: 'Deeper experiments + paper essay', ru: 'Глубже эксперименты + эссе по статье', tt: 'Тирәнрәк экспериментлар + мәкалә буенча эссе' },
    blurb: {
      en: 'Four rankers, three metrics, a parameter sweep, a tokenization study and a significance test — then read one paper and re-draw its hero figure by hand.',
      ru: 'Четыре ранжировщика, три метрики, свип параметров, исследование токенизации и тест значимости — затем прочитать статью и перерисовать её hero-фигуру рукой.',
      tt: 'Дүрт ранжлаучы, өч метрика, параметрлар свибы, токенлаштыруны өйрәнү һәм мөһимлек тесты — аннары бер мәкаләне укып, аның төп рәсемен кулдан яңадан сыз.',
    },
    due: { en: 'Extended · coding + handwritten essay', ru: 'Расширенная · код + рукописное эссе', tt: 'Киңәйтелгән · код + кулдан язылган эссе' },
    blocks: [
      { t: 'lead', v: { en: 'Build on the Lab. Part 1 is an extended experimental study; Part 2 is a close reading of one paper with a hand-drawn re-interpretation of its hero figure.', ru: 'На основе Лабы. Часть 1 — расширенное экспериментальное исследование; часть 2 — внимательное чтение одной статьи с рукописной переинтерпретацией её hero-фигуры.', tt: 'Лаборатор эшкә нигезләнеп. 1 нче өлеш — киңәйтелгән эксперименталь тикшеренү; 2 нче өлеш — бер мәкаләне игътибар белән уку һәм аның төп рәсемен кулдан язылган яңа интерпретация.' } },

      { t: 'h3', v: { en: 'Part 1 — Coding & experiments (60%)', ru: 'Часть 1 — Код и эксперименты (60%)', tt: '1 нче өлеш — Код һәм экспериментлар (60%)' } },
      { t: 'p', v: { en: 'Use BEIR nfcorpus/test over the full test query set (optionally repeat the headline experiment on scifact/test).', ru: 'BEIR nfcorpus/test на полном test-наборе запросов (опционально повторите основной эксперимент на scifact/test).', tt: 'BEIR nfcorpus/test’ны тулы test-сорау җыелмасында куллан (опциональ рәвештә төп экспериментны scifact/test өстендә кабатла).' } },
      { t: 'ol', v: [
        { en: 'Rankers (by hand): a Boolean-OR baseline, TF-IDF (cosine), BM25, and RRF fusion (Σ 1/(k+rank), k=60) of BM25 + TF-IDF.', ru: 'Ранжировщики (руками): Boolean-OR базлайн, TF-IDF (косинус), BM25 и RRF-фьюжн (Σ 1/(k+rank), k=60) BM25 + TF-IDF.', tt: 'Ранжлаучылар (кулдан): Boolean-OR базлайны, TF-IDF (косинус), BM25 һәм BM25 + TF-IDF’ның RRF-фьюжны (Σ 1/(k+rank), k=60).' },
        { en: 'Metrics (by hand): nDCG@10, MAP, MRR over all queries — report the mean and the per-query distribution (box/violin or histogram). Use graded gain 2^rel−1 and the log₂(i+1) discount.', ru: 'Метрики (руками): nDCG@10, MAP, MRR по всем запросам — среднее и распределение по запросам (box/violin или гистограмма). gain 2^rel−1, дисконт log₂(i+1).', tt: 'Метрикалар (кулдан): барлык сораулар буенча nDCG@10, MAP, MRR — уртачасын һәм һәр сорау буенча таралышын бир (box/violin яки гистограмма). Градуацияле gain 2^rel−1 һәм log₂(i+1) дисконтын куллан.' },
        { en: 'BM25 parameter study: sweep k₁ ∈ {0.5,1.0,1.2,1.5,2.0,3.0} and b ∈ {0,0.25,0.5,0.75,1.0}; plot nDCG@10 vs k₁ (b fixed) and vs b (k₁ fixed); identify the best (k₁,b) and explain the shape (saturation; the b=0/1 extremes).', ru: 'Свип параметров BM25: k₁ ∈ {0.5,1.0,1.2,1.5,2.0,3.0}, b ∈ {0,0.25,0.5,0.75,1.0}; графики nDCG@10 от k₁ (b фикс.) и от b (k₁ фикс.); найдите лучшую (k₁,b) и объясните форму (насыщение; крайние b=0/1).', tt: 'BM25 параметрларын өйрәнү: k₁ ∈ {0.5,1.0,1.2,1.5,2.0,3.0} һәм b ∈ {0,0.25,0.5,0.75,1.0} буенча свип; nDCG@10’ны k₁’дан (b ныгытылган) һәм b’дан (k₁ ныгытылган) графикларын сыз; иң яхшы (k₁,b)’ны тап һәм формасын аңлат (туену; b=0/1 чикләре).' },
        { en: 'Tokenization study: compare ≥3 pipelines on the same BM25 — (a) lowercase+whitespace, (b) + stopword removal, (c) + Porter stemming, (optional d) subword/BPE. Report nDCG@10 / MAP / MRR for each and explain why each choice helps or hurts (vocabulary size, df shifts, conflation vs over-conflation). Tie back to Lecture 02 and 03.', ru: 'Исследование токенизации: сравните ≥3 пайплайна на одном BM25 — (a) нижний регистр+пробелы, (b) + удаление стоп-слов, (c) + стемминг Портера, (опц. d) subword/BPE. nDCG@10 / MAP / MRR для каждого и объяснение, почему помогает/вредит (размер словаря, сдвиги df, конфляция). Свяжите с лекциями 02 и 03.', tt: 'Токенлаштыруны өйрәнү: шул ук BM25 өстендә ≥3 пайплайнны чагыштыр — (a) кече хәреф+буш урын, (b) + стоп-сүзләрне алу, (c) + Портер стеммингы, (опц. d) subword/BPE. Һәрберсе өчен nDCG@10 / MAP / MRR бир һәм һәр сайлавның нигә ярдәм иткәнен яки зыян иткәнен аңлат (сүзлек күләме, df күчешләре, конфляция). 02 һәм 03 лекцияләргә бәйлә.' },
        { en: 'Statistical significance: is your best system better than the BM25 baseline, or is it chance? Run a paired test (t-test and/or Wilcoxon signed-rank) on per-query nDCG@10; report the mean difference, a 95% CI, and the p-value, and interpret it (necessary-not-sufficient; the small-n caveat).', ru: 'Статистическая значимость: лучшая система действительно лучше BM25-базлайна или это случайность? Парный тест (t-test и/или Wilcoxon) по per-query nDCG@10; средняя разница, 95% CI, p-value и интерпретация (необходимо-но-недостаточно; малое n).', tt: 'Статистик мөһимлек: синең иң яхшы системаң BM25 базлайныннан чыннан да яхшырак, әллә бу очраклымы? Һәр сорау буенча nDCG@10’да парлы тест (t-test һәм/яки Wilcoxon signed-rank) үткәр; уртача аерманы, 95% CI’ны һәм p-value’ны бир, аны аңлат (кирәкле-әмма-җитәрлек түгел; кечкенә n кисәтүе).' },
        { en: 'Report: plots + tables + a discussion connecting the parameter sweep, the tokenization study, and the significance test into one story about what actually moves ranking quality.', ru: 'Отчёт: графики + таблицы + обсуждение, связывающее свип, токенизацию и значимость в одну историю о том, что реально двигает качество.', tt: 'Отчёт: графиклар + таблицалар + параметр свибын, токенлаштыруны өйрәнүне һәм мөһимлек тестын ранжлау сыйфатын чыннан да нәрсә хәрәкәтләндергәне турында бер хикәягә бәйләүче фикер алышу.' },
      ] },
      { t: 'h4', v: { en: 'Part 1 grading (60)', ru: 'Оценка части 1 (60)', tt: '1 нче өлешне бәяләү (60)' } },
      { t: 'grade', rows: [
        { label: { en: 'Four rankers correct', ru: 'Четыре ранжировщика', tt: 'Дүрт ранжлаучы дөрес' }, w: '15' },
        { label: { en: 'Three metrics correct', ru: 'Три метрики', tt: 'Өч метрика дөрес' }, w: '15' },
        { label: { en: 'Parameter study + plots', ru: 'Свип + графики', tt: 'Параметрларны өйрәнү + графиклар' }, w: '10' },
        { label: { en: 'Tokenization study', ru: 'Токенизация', tt: 'Токенлаштыруны өйрәнү' }, w: '12' },
        { label: { en: 'Significance', ru: 'Значимость', tt: 'Мөһимлек' }, w: '8' },
      ] },

      { t: 'h3', v: { en: 'Part 2 — Paper reading & hand-written essay (40%)', ru: 'Часть 2 — Чтение статьи и рукописное эссе (40%)', tt: '2 нче өлеш — Мәкалә уку һәм кулдан язылган эссе (40%)' } },
      { t: 'p', v: { en: 'Pick one of the five papers below, read it closely, and write a two-page A4 hand-written essay in your own words — your interpretation, not a summary. Then complete the hero-figure sub-task.', ru: 'Выберите одну из пяти статей ниже, внимательно прочитайте и напишите рукописное эссе на две страницы A4 своими словами — ваша интерпретация, не пересказ. Затем выполните подзадачу с hero-фигурой.', tt: 'Түбәндәге биш мәкаләнең берсен сайла, аны игътибар белән укы һәм үз сүзләрең белән ике битлек A4 кулдан язылган эссе яз — синең интерпретация, кыскача эчтәлек түгел. Аннары төп рәсем подбиремен башкар.' } },
      { t: 'callout', title: { en: 'Hero-figure sub-task', ru: 'Подзадача: hero-фигура', tt: 'Подбирем: төп рәсем' }, v: { en: 'Identify the paper’s hero figure — the one diagram that carries its central idea. Redesign it your own way (hand-drawn is fine) to expose the concept more deeply than the original: change the encoding, add the missing axis or annotation, show the failure case, or re-draw it using your own Lab/Homework numbers. Add a short caption stating what your version makes visible that the original did not.', ru: 'Определите hero-фигуру статьи — диаграмму, несущую её центральную идею. Перерисуйте её по-своему (можно от руки), чтобы раскрыть концепт глубже оригинала: смените кодировку, добавьте недостающую ось/подпись, покажите случай отказа или перерисуйте её на своих числах из Лабы/домашки. Добавьте короткую подпись — что ваш вариант делает видимым, чего не было в оригинале.', tt: 'Мәкаләнең төп рәсемен — аның үзәк идеясен йөртүче бер диаграмманы — билгелә. Аны үзеңчә (кулдан сызу да ярый) яңадан эшлә, концепцияне оригиналга караганда тирәнрәк ачар өчен: кодлауны үзгәрт, җитмәгән күчәр яки аңлатма өст, ялгышу очрагын күрсәт, яки аны үз Лаборатор эш/өй эше саннарың белән яңадан сыз. Синең вариантың оригиналда күренмәгән нәрсәне ничек күрсәткәнен әйтүче кыска аңлатма өст.' } },
      { t: 'h4', v: { en: 'Submission', ru: 'Что сдавать', tt: 'Нәрсә тапшырырга' } },
      { t: 'p', v: { en: 'A photo/scan of the two-page hand-written essay, the redesigned hero figure (hand-drawn or digital), and one paragraph naming the figure you chose and why it is the hero figure.', ru: 'Фото/скан рукописного эссе на две страницы A4, перерисованная hero-фигура (от руки или цифровая) и один абзац — какую фигуру выбрали и почему она hero.', tt: 'Ике битлек кулдан язылган эссенең фотосы/сканы, яңадан эшләнгән төп рәсем (кулдан яки санлы) һәм бер абзац — кайсы рәсемне сайлавың һәм нигә ул төп рәсем булуы турында.' } },
      { t: 'h4', v: { en: 'Choose one paper', ru: 'Выберите одну статью', tt: 'Бер мәкалә сайла' } },
      { t: 'papers', items: [
        { cite: 'Spärck Jones, K. (1972). A Statistical Interpretation of Term Specificity and Its Application in Retrieval. Journal of Documentation.', hero: { en: 'The origin of IDF. Hero figure: the term-specificity / frequency relationship.', ru: 'Происхождение IDF. Hero-фигура: связь специфичности терма и частоты.', tt: 'IDF чыганагы. Төп рәсем: терм спецификлыгы / ешлык бәйләнеше.' } },
        { cite: 'Robertson, S. & Zaragoza, H. (2009). The Probabilistic Relevance Framework: BM25 and Beyond. Foundations & Trends in IR.', hero: { en: 'The definitive BM25 treatment. Hero figure: the term-frequency saturation curve(s).', ru: 'Определяющий труд по BM25. Hero-фигура: кривая насыщения tf.', tt: 'BM25 буенча төп хезмәт. Төп рәсем: терм ешлыгы туену кәкресе(ләре).' } },
        { cite: 'Singhal, A., Buckley, C. & Mitra, M. (1996). Pivoted Document Length Normalization. SIGIR.', hero: { en: 'Hero figure: P(relevance) vs P(retrieval) as a function of document length — the crossing curves that motivate the b parameter.', ru: 'Hero-фигура: P(релевантность) против P(выдачи) от длины документа — пересекающиеся кривые, мотивирующие параметр b.', tt: 'Төп рәсем: P(релевантлык) каршы P(табу) — документ озынлыгы функциясе буларак — b параметрын нигезләгән кисешүче кәкреләр.' } },
        { cite: 'Järvelin, K. & Kekäläinen, J. (2002). Cumulated Gain-based Evaluation of IR Techniques. ACM TOIS.', hero: { en: 'The (n)DCG paper. Hero figure: cumulated and discounted gain curves across rank.', ru: 'Статья про (n)DCG. Hero-фигура: кривые cumulated/discounted gain по рангу.', tt: '(n)DCG турында мәкалә. Төп рәсем: ранг буенча cumulated/discounted gain кәкреләре.' } },
        { cite: 'Cormack, G. V., Clarke, C. L. A. & Büttcher, S. (2009). Reciprocal Rank Fusion Outperforms Condorcet and Individual Rank Learning Methods. SIGIR.', hero: { en: 'RRF. Hero element: the RRF formula and its results table — redesign it as a figure.', ru: 'RRF. Hero-элемент: формула RRF и таблица результатов — перерисуйте как фигуру.', tt: 'RRF. Төп элемент: RRF формуласы һәм аның нәтиҗәләр таблицасы — аны рәсем итеп яңадан эшлә.' } },
      ] },
      { t: 'h4', v: { en: 'Part 2 grading (40)', ru: 'Оценка части 2 (40)', tt: '2 нче өлешне бәяләү (40)' } },
      { t: 'grade', rows: [
        { label: { en: 'Interpretation depth & correctness', ru: 'Глубина и корректность интерпретации', tt: 'Интерпретация тирәнлеге һәм дөреслеге' }, w: '20' },
        { label: { en: 'Hero-figure redesign (insight added)', ru: 'Перерисовка hero-фигуры (добавленный инсайт)', tt: 'Төп рәсемне яңадан эшләү (өстәлгән инсайт)' }, w: '15' },
        { label: { en: 'Clarity, structure, handwriting', ru: 'Ясность, структура, почерк', tt: 'Ачыклык, структура, кулъязма' }, w: '5' },
      ] },
    ],
  },

  {
    slug: 'lab-cascade',
    kind: 'lab',
    code: 'Lab 2',
    status: 'soon',
    title: { en: 'Build the neural cascade: Scouts → Judges', ru: 'Собери нейронный каскад: Разведчики → Судьи', tt: 'Нейрон каскадны төз: Разведчиклар → Хөкемчеләр' },
    blurb: {
      en: 'A dense bi-encoder Scout and a cross-encoder Judge on top of your Lab-1 BM25 — wire the retrieve→rerank cascade and measure the lift and the rerank-depth tradeoff.',
      ru: 'Плотный bi-encoder-Разведчик и cross-encoder-Судья поверх твоего BM25 из Лабы 1 — собери каскад «найти→пересудить» и измерь прирост и компромисс глубины реранка.',
      tt: 'Лаб-1 BM25 өстендә тыгыз bi-encoder-Разведчик һәм cross-encoder-Хөкемче — «табу→яңадан хөкем итү» каскадын җый, прирост һәм реранк тирәнлеге компромиссын үлчә.',
    },
    due: { en: 'Small · 1 dataset · ~1 evening', ru: 'Небольшая · 1 датасет · ~вечер', tt: 'Кечкенә · 1 мәгълүмат җыелмасы · ~бер кич' },
    blocks: [
      { t: 'h4', v: { en: 'Goal', ru: 'Цель', tt: 'Максат' } },
      { t: 'p', v: { en: 'Put a fast dense Scout and a careful cross-encoder Judge on top of the BM25 you built in Lab 1, wire them into a retrieve→rerank cascade, and measure — with your own numbers — exactly how much the rerank buys and what it costs.', ru: 'Поставь быстрый плотный Разведчик и вдумчивый cross-encoder-Судью поверх BM25 из Лабы 1, собери их в каскад «найти→пересудить» и измерь — на своих числах — сколько именно даёт реранк и чего он стоит.' } },
      { t: 'h4', v: { en: 'Tasks', ru: 'Задачи', tt: 'Биремнәр' } },
      { t: 'ol', v: [
        { en: 'Load BEIR nfcorpus/test and the fixed query set (first 30 by query_id). Reuse your Lab-1 BM25 and nDCG@10 implementations as the first stage and the metric.', ru: 'Загрузи BEIR nfcorpus/test и фиксированный набор запросов (первые 30 по query_id). Переиспользуй свои реализации BM25 и nDCG@10 из Лабы 1 как первый этап и метрику.' },
        { en: 'Dense Scout (bi-encoder): encode queries and documents with a pretrained SBERT (sentence-transformers/all-MiniLM-L6-v2), L2-normalize, and retrieve the top-100 by cosine. The embeddings come from the model; the cosine search is yours.', ru: 'Плотный Разведчик (bi-encoder): закодируй запросы и документы претренированным SBERT (sentence-transformers/all-MiniLM-L6-v2), L2-нормируй и выдай top-100 по косинусу. Эмбеддинги — от модели; косинусный поиск пишешь сам.' },
        { en: 'Cross-encoder Judge: score (query, document) pairs jointly with a pretrained cross-encoder (cross-encoder/ms-marco-MiniLM-L-6-v2) — read each pair together, nothing precomputed.', ru: 'Cross-encoder-Судья: оцени пары (запрос, документ) совместно претренированным cross-encoder (cross-encoder/ms-marco-MiniLM-L-6-v2) — читай каждую пару вместе, без предпросчёта.' },
        { en: 'The cascade: for each query take the first-stage top-k and rerank it with the Judge, emitting a reranked top-10. Build it for both first stages — BM25→rerank and dense→rerank.', ru: 'Каскад: для каждого запроса возьми top-k первого этапа и пересортируй Судьёй, выдав пересортированный top-10. Сделай это для обоих первых этапов — BM25→реранк и dense→реранк.' },
        { en: 'The lift ladder: report nDCG@10 at three stages — BM25 alone, dense alone, and +cross-encoder rerank — in one table. Which Scout feeds the Judge a better shortlist?', ru: 'Лестница прироста: дай nDCG@10 на трёх стадиях — BM25, dense и +cross-реранк — одной таблицей. Какой Разведчик приносит Судье лучший short-list?' },
        { en: 'Rerank-depth sweep: vary the rerank depth k ∈ {5, 10, 20, 50, 100}; plot nDCG@10 vs k and the cost (cross-encoder passes per query = k). Where does going deeper stop paying off?', ru: 'Свип глубины реранка: меняй глубину k ∈ {5, 10, 20, 50, 100}; построй nDCG@10 от k и стоимость (прогонов cross-encoder на запрос = k). Где углубление перестаёт окупаться?' },
        { en: 'Show one query where the rerank pulled a buried relevant document up into the top-10 — give the before and after ranks.', ru: 'Покажи запрос, где реранк поднял зарытый релевантный документ в top-10 — дай ранги до и после.' },
      ] },
      { t: 'h4', v: { en: 'Deliverables', ru: 'Что сдавать', tt: 'Нәрсә тапшырырга' } },
      { t: 'p', v: { en: 'lab.py (or a notebook) that runs end-to-end and prints the lift-ladder table, plus a 1-page report: the three-stage nDCG@10 table, the depth-vs-nDCG plot, the one before/after query, and a short analysis paragraph (why the cross-encoder helps; why deeper reranking saturates).', ru: 'lab.py (или notebook), работающий от начала до конца и печатающий таблицу-лестницу, плюс отчёт на 1 страницу: таблица nDCG@10 по трём стадиям, график глубина-vs-nDCG, один запрос до/после и абзац анализа (почему cross-encoder помогает; почему глубокий реранк насыщается).' } },
      { t: 'h4', v: { en: 'Grading (100)', ru: 'Оценка (100)', tt: 'Бәяләү (100)' } },
      { t: 'grade', rows: [
        { label: { en: 'Dense bi-encoder retrieval', ru: 'Плотный bi-encoder-ретрив' }, w: '20' },
        { label: { en: 'Cross-encoder rerank + cascade', ru: 'Cross-encoder реранк + каскад' }, w: '30' },
        { label: { en: 'Lift ladder (3 stages)', ru: 'Лестница прироста (3 стадии)' }, w: '15' },
        { label: { en: 'Rerank-depth sweep + cost', ru: 'Свип глубины + стоимость' }, w: '20' },
        { label: { en: 'Analysis (before/after + why)', ru: 'Анализ (до/после + почему)' }, w: '15' },
      ] },
    ],
  },

  {
    slug: 'hw-alliance',
    kind: 'homework',
    code: 'A2',
    status: 'soon',
    title: { en: 'The Alliance: hybrid fusion + Learning to Rank', ru: 'Альянс: гибридное слияние + Learning to Rank', tt: 'Альянс: гибрид берләштерү + Learning to Rank' },
    blurb: {
      en: 'Run BM25, dense, SPLADE and ColBERT as four retrievers; fuse them (RRF vs convex); then learn a combiner by hand (RankNet → LambdaRank) — and read one paper, redrawing its hero figure.',
      ru: 'Запусти BM25, dense, SPLADE и ColBERT как четыре ретривера; слей их (RRF vs convex); затем обучи комбинатор руками (RankNet → LambdaRank) — и прочитай статью, перерисовав её hero-фигуру.',
      tt: 'BM25, dense, SPLADE һәм ColBERT’ны дүрт ретрив итеп җибәр; аларны берләштер (RRF vs convex); аннары комбинаторны кулдан өйрәт (RankNet → LambdaRank) — һәм бер мәкаләне укып, аның төп рәсемен яңадан сыз.',
    },
    due: { en: 'Extended · coding + handwritten essay', ru: 'Расширенная · код + рукописное эссе', tt: 'Киңәйтелгән · код + кулдан язылган эссе' },
    blocks: [
      { t: 'lead', v: { en: 'Build on Lab 2. Part 1 unites four retrievers under one banner (hybrid) and trains a captain to order them (Learning to Rank); Part 2 is a close reading of one paper with a hand-drawn re-interpretation of its hero figure.', ru: 'На основе Лабы 2. Часть 1 объединяет четыре ретривера под одним знаменем (гибрид) и обучает капитана упорядочивать их (Learning to Rank); часть 2 — внимательное чтение одной статьи с рукописной переинтерпретацией её hero-фигуры.' } },

      { t: 'h3', v: { en: 'Part 1 — Coding & experiments (60%)', ru: 'Часть 1 — Код и эксперименты (60%)' } },
      { t: 'p', v: { en: 'Use BEIR nfcorpus/test over the full test query set (optionally repeat the headline run on scifact/test). Reuse your Lab-1 BM25 and your Lab-2 dense retriever and cascade.', ru: 'BEIR nfcorpus/test на полном test-наборе запросов (опционально повтори основной прогон на scifact/test). Переиспользуй BM25 из Лабы 1 и dense-ретривер с каскадом из Лабы 2.' } },
      { t: 'ol', v: [
        { en: 'Four retrievers (each reranking the top-100 of a cheap first stage): BM25 (yours); the dense bi-encoder (SBERT, from Lab 2); SPLADE learned-sparse — run naver/splade-cocondenser-ensembledistil, take its log(1+ReLU) term weights, and compute the sparse dot by hand; and ColBERT late interaction — per-token embeddings from colbert-ir/colbertv2.0, MaxSim = Σ_i max_j E_qi·E_dj by hand. (If compute is tight, use ≥3 retrievers but include SPLADE or ColBERT.)', ru: 'Четыре ретривера (каждый пересортирует top-100 дешёвого первого этапа): BM25 (твой); плотный bi-encoder (SBERT, из Лабы 2); SPLADE — запусти naver/splade-cocondenser-ensembledistil, возьми его веса термов log(1+ReLU) и посчитай sparse-dot руками; и ColBERT late interaction — потокенные эмбеддинги из colbert-ir/colbertv2.0, MaxSim = Σ_i max_j E_qi·E_dj руками. (Если мало ресурсов — возьми ≥3 ретривера, но включи SPLADE или ColBERT.)' },
        { en: 'Hybrid fusion (by hand): fuse the rankings three ways — RRF (k=60), a convex combination α·dense+(1−α)·sparse (sweep α ∈ {0, 0.25, 0.5, 0.75, 1}), and a normalized score combination (min-max or z-score). Which fusion wins, and does it need score calibration across rankers?', ru: 'Гибридное слияние (руками): слей ранжирования тремя способами — RRF (k=60), выпуклая комбинация α·dense+(1−α)·sparse (свип α ∈ {0, 0.25, 0.5, 0.75, 1}) и нормализованная комбинация оценок (min-max или z-score). Что побеждает и нужна ли калибровка шкал между ранжировщиками?' },
        { en: 'Learning to Rank (by hand): build a per-(query, doc) feature vector [BM25, dense cosine, SPLADE score, ColBERT MaxSim, document length, …]; implement RankNet (pairwise P = σ(s_i − s_j), cross-entropy) and LambdaRank (gradients weighted by |ΔnDCG|); train a combiner and compare it to the best single feature and to the best fusion. (LambdaMART via a gradient-boosting library is allowed as a clearly-marked optional extra.)', ru: 'Learning to Rank (руками): построй вектор признаков на (запрос, документ) [BM25, dense-косинус, SPLADE, ColBERT MaxSim, длина документа, …]; реализуй RankNet (попарно P = σ(s_i − s_j), кросс-энтропия) и LambdaRank (градиенты, взвешенные на |ΔnDCG|); обучи комбинатор и сравни с лучшей одиночной фичей и лучшим слиянием. (LambdaMART через библиотеку градиентного бустинга — опциональный экстра, явно помеченный.)' },
        { en: 'Feature ablation: drop each feature in turn and report the nDCG@10 change; show concretely that the neural scores are "just features for the captain."', ru: 'Абляция признаков: выкидывай по одной фиче и фиксируй изменение nDCG@10; покажи конкретно, что нейронные оценки — «просто признаки для капитана».' },
        { en: 'Metrics & significance: nDCG@10, MAP, MRR (by hand) with the per-query distribution; run a paired test (t-test and/or Wilcoxon signed-rank) of your best system vs the BM25 baseline — mean difference, 95% CI, p-value, and an honest interpretation.', ru: 'Метрики и значимость: nDCG@10, MAP, MRR (руками) с распределением по запросам; парный тест (t-test и/или Wilcoxon) лучшей системы против BM25-базлайна — средняя разница, 95% CI, p-value и честная интерпретация.' },
        { en: 'Report: plots + tables + a discussion tying the fusion study and the Learning-to-Rank result into one story about what actually unites the armies.', ru: 'Отчёт: графики + таблицы + обсуждение, связывающее исследование слияния и результат Learning to Rank в одну историю о том, что реально объединяет армии.' },
      ] },
      { t: 'h4', v: { en: 'Part 1 grading (60)', ru: 'Оценка части 1 (60)' } },
      { t: 'grade', rows: [
        { label: { en: 'Retrievers correct (≥3, incl. SPLADE/ColBERT by hand)', ru: 'Ретриверы (≥3, вкл. SPLADE/ColBERT руками)' }, w: '15' },
        { label: { en: 'Hybrid fusion (RRF + convex + α-sweep)', ru: 'Гибридное слияние (RRF + convex + α-свип)' }, w: '12' },
        { label: { en: 'Learning to Rank by hand (RankNet→LambdaRank)', ru: 'Learning to Rank руками (RankNet→LambdaRank)' }, w: '18' },
        { label: { en: 'Feature ablation', ru: 'Абляция признаков' }, w: '8' },
        { label: { en: 'Metrics + significance', ru: 'Метрики + значимость' }, w: '7' },
      ] },

      { t: 'h3', v: { en: 'Part 2 — Paper reading & hand-written essay (40%)', ru: 'Часть 2 — Чтение статьи и рукописное эссе (40%)' } },
      { t: 'p', v: { en: 'Pick one of the five papers below, read it closely, and write a two-page A4 hand-written essay in your own words — your interpretation, not a summary. Then complete the hero-figure sub-task.', ru: 'Выбери одну из пяти статей ниже, внимательно прочитай и напиши рукописное эссе на две страницы A4 своими словами — твоя интерпретация, не пересказ. Затем выполни подзадачу с hero-фигурой.' } },
      { t: 'callout', title: { en: 'Hero-figure sub-task', ru: 'Подзадача: hero-фигура' }, v: { en: 'Identify the paper’s hero figure — the one diagram that carries its central idea. Redesign it your own way (hand-drawn is fine) to expose the concept more deeply than the original: change the encoding, add the missing axis or annotation, show the failure case, or re-draw it using your own Lab/Homework numbers. Add a short caption stating what your version makes visible that the original did not.', ru: 'Определи hero-фигуру статьи — диаграмму, несущую её центральную идею. Перерисуй её по-своему (можно от руки), чтобы раскрыть концепт глубже оригинала: смени кодировку, добавь недостающую ось/подпись, покажи случай отказа или перерисуй на своих числах из Лабы/домашки. Добавь короткую подпись — что твой вариант делает видимым, чего не было в оригинале.' } },
      { t: 'h4', v: { en: 'Submission', ru: 'Что сдавать' } },
      { t: 'p', v: { en: 'A photo/scan of the two-page hand-written essay, the redesigned hero figure (hand-drawn or digital), and one paragraph naming the figure you chose and why it is the hero figure.', ru: 'Фото/скан рукописного эссе на две страницы A4, перерисованная hero-фигура (от руки или цифровая) и один абзац — какую фигуру выбрал и почему она hero.' } },
      { t: 'h4', v: { en: 'Choose one paper', ru: 'Выбери одну статью' } },
      { t: 'papers', items: [
        { cite: 'Khattab, O. & Zaharia, M. (2020). ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT. SIGIR.', hero: { en: 'Late interaction. Hero figure: the MaxSim token×token interaction — per-token vectors, the max over doc tokens, the sum over query tokens.', ru: 'Позднее взаимодействие. Hero-фигура: взаимодействие MaxSim токен×токен — потокенные векторы, max по токенам документа, сумма по токенам запроса.' } },
        { cite: 'Formal, T., Piwowarski, B. & Clinchant, S. (2021). SPLADE: Sparse Lexical and Expansion Model for First Stage Ranking. SIGIR.', hero: { en: 'Learned sparse. Hero figure: the MLM-head → log(1+ReLU) sparsification and the term-expansion it produces over the vocabulary.', ru: 'Выученная разрежённость. Hero-фигура: MLM-голова → log(1+ReLU) и порождаемое расширение терминов по словарю.' } },
        { cite: 'Santhanam, K., Khattab, O., Saad-Falcon, J., Potts, C. & Zaharia, M. (2022). ColBERTv2: Effective and Efficient Retrieval via Lightweight Late Interaction. NAACL.', hero: { en: 'Making late interaction shippable. Hero figure: residual compression (centroid + quantized residual) and the denoised-supervision pipeline.', ru: 'Делаем позднее взаимодействие пригодным к проду. Hero-фигура: остаточное сжатие (центроид + квантованный остаток) и пайплайн обесшумленного надзора.' } },
        { cite: 'Burges, C. J. C. (2010). From RankNet to LambdaRank to LambdaMART: An Overview. Microsoft Research, MSR-TR-2010-82.', hero: { en: 'The Learning-to-Rank line. Hero element: the λ-gradient — a pairwise σ on score differences weighted by ΔnDCG — redesign it as one figure.', ru: 'Линия Learning to Rank. Hero-элемент: λ-градиент — попарная σ на разностях оценок, взвешенная на ΔnDCG — перерисуй как одну фигуру.' } },
        { cite: 'Cormack, G. V., Clarke, C. L. A. & Büttcher, S. (2009). Reciprocal Rank Fusion Outperforms Condorcet and Individual Rank Learning Methods. SIGIR.', hero: { en: 'Hybrid fusion. Hero element: the RRF formula and its results table — redesign it as a figure that shows why consensus beats a lopsided #1.', ru: 'Гибридное слияние. Hero-элемент: формула RRF и таблица результатов — перерисуй как фигуру, показывающую, почему консенсус бьёт однобокого лидера.' } },
      ] },
      { t: 'h4', v: { en: 'Part 2 grading (40)', ru: 'Оценка части 2 (40)' } },
      { t: 'grade', rows: [
        { label: { en: 'Interpretation depth & correctness', ru: 'Глубина и корректность интерпретации' }, w: '20' },
        { label: { en: 'Hero-figure redesign (insight added)', ru: 'Перерисовка hero-фигуры (добавленный инсайт)' }, w: '15' },
        { label: { en: 'Clarity, structure, handwriting', ru: 'Ясность, структура, почерк' }, w: '5' },
      ] },
    ],
  },

  {
    slug: 'lab-ann',
    kind: 'lab',
    code: 'Lab 3',
    status: 'soon',
    title: { en: 'The index at scale: build ANN by hand (IVF · PQ · IVF-PQ)', ru: 'Индекс на масштабе: ANN руками (IVF · PQ · IVF-PQ)', tt: 'Масштабта индекс: ANN кулдан (IVF · PQ · IVF-PQ)' },
    blurb: {
      en: 'Take your Lab-2 dense embeddings and index them the way billion-scale systems do — build IVF, Product Quantization and IVF-PQ by hand, and measure the recall / work / memory triangle against exact search.',
      ru: 'Возьми плотные эмбеддинги из Лабы 2 и проиндексируй их так, как это делают системы на миллиардах — собери IVF, Product Quantization и IVF-PQ руками и измерь треугольник recall / работа / память относительно точного поиска.',
      tt: 'Лаб-2 тыгыз эмбеддингларын ал һәм аларны миллиардлар масштабындагы системалар кебек индексла — IVF, Product Quantization һәм IVF-PQ’ны кулдан җый, recall / эш / хәтер өчпочмагын төгәл эзләүгә карата үлчә.',
    },
    due: { en: 'Small · 1 dataset · ~1 evening', ru: 'Небольшая · 1 датасет · ~вечер', tt: 'Кечкенә · 1 мәгълүмат җыелмасы · ~бер кич' },
    blocks: [
      { t: 'h4', v: { en: 'Goal', ru: 'Цель', tt: 'Максат' } },
      { t: 'p', v: { en: 'You already retrieve with exact cosine search (Lab 2) — that is O(N·d) per query, fine for a few thousand documents and hopeless for millions. Build the two orthogonal families of approximate nearest-neighbour index by hand — a partitioning index (IVF) and a compression index (Product Quantization) — compose them (IVF-PQ), and show with your own numbers exactly what each buys and what it costs against an exact baseline. "HNSW vs PQ" is a category error: partition-or-graph and how-many-bytes-per-vector are two different axes that compose.', ru: 'Ты уже ищешь точным косинусным поиском (Лаба 2) — это O(N·d) на запрос, нормально для тысяч документов и безнадёжно для миллионов. Собери руками два ортогональных семейства ANN-индекса — индекс разбиения (IVF) и индекс сжатия (Product Quantization) — соедини их (IVF-PQ) и покажи на своих числах, что именно даёт каждый и чего стоит, относительно точной базы. «HNSW против PQ» — категориальная ошибка: разбивать-или-граф и сколько-байт-на-вектор — две разные оси, которые композируются.' } },

      { t: 'h4', v: { en: 'Dataset & setup', ru: 'Датасет и setup', tt: 'Мәгълүмат җыелмасы һәм setup' } },
      { t: 'p', v: { en: 'This Lab (and Homework 3) use EnterpriseRAG-Bench. Subset it for a laptop: keep one source_type slice (~5K docs) plus every expected_doc_id of your fixed question subset (the first 30 by question_id), then embed the documents and questions with your Lab-2 SBERT (all-MiniLM-L6-v2) and L2-normalize to unit vectors (so cosine == dot). Relevance for the retrieval sanity-check is expected_doc_ids; but the ANN recall below is measured against your OWN exact top-10, not qrels — you are measuring index fidelity, not retrieval quality.', ru: 'Эта Лаба (и Домашка 3) используют EnterpriseRAG-Bench. Субсетируй под ноутбук: возьми один срез source_type (~5К документов) плюс все expected_doc_id из фиксированного набора вопросов (первые 30 по question_id), затем закодируй документы и вопросы своим SBERT из Лабы 2 (all-MiniLM-L6-v2) и L2-нормируй в единичные векторы (тогда косинус == скалярное произведение). Релевантность для sanity-check ретрива — expected_doc_ids; но ANN-recall ниже меряется относительно ТВОЕГО точного top-10, а не qrels — ты меряешь точность индекса, а не качество поиска.' } },
      { t: 'code', v: `from datasets import load_dataset   # EnterpriseRAG-Bench (onyx-dot-app) — MIT
# documents: {doc_id, source_type, title, content}
# questions: {question_id, question_type, source_types, question,
#             expected_doc_ids, gold_answer, answer_facts}
docs = load_dataset("onyx-dot-app/EnterpriseRAG-Bench", "documents")["test"]
qs   = load_dataset("onyx-dot-app/EnterpriseRAG-Bench", "questions")["test"]

# laptop subset: one source_type slice + every expected_doc_id of your 30-query set
# embed title+content and each question with your Lab-2 SBERT, then L2-normalize
# -> unit vectors X  (N x d).  Exact top-10 over X is your recall ground truth.` },

      { t: 'h4', v: { en: 'Tasks', ru: 'Задачи', tt: 'Биремнәр' } },
      { t: 'ol', v: [
        { en: 'Exact baseline (the recall ground truth): flat cosine search over the unit vectors; record the exact top-10 per query. Every ANN recall@10 below is measured against THIS list: recall@10 = |ANN top-10 ∩ exact top-10| / 10.', ru: 'Точная база (эталон recall): плоский косинусный поиск по единичным векторам; запиши точный top-10 на запрос. Каждый ANN recall@10 ниже меряется относительно ЭТОГО списка: recall@10 = |ANN top-10 ∩ exact top-10| / 10.' },
        { en: 'IVF by hand: run k-means (nlist ≈ √N centroids; sklearn KMeans is an allowed helper) to induce Voronoi cells; file each document into its nearest centroid’s inverted list. Query = rank the query against the nlist centroids, then exact-scan ONLY the top-nprobe lists. Sweep nprobe ∈ {1, 2, 4, 8, 16, nlist}; plot recall@10 and the fraction of the corpus scanned against nprobe, and mark the knee where recall saturates. Exhibit one query where nprobe=1 drops a true neighbour sitting just across a cell boundary.', ru: 'IVF руками: запусти k-means (nlist ≈ √N центроид; sklearn KMeans — разрешённый помощник), чтобы получить ячейки Вороного; определи каждый документ в инвертированный список ближайшего центроида. Запрос = ранжируй запрос по nlist центроидам, затем точно сканируй ТОЛЬКО top-nprobe списков. Свип nprobe ∈ {1, 2, 4, 8, 16, nlist}; построй recall@10 и долю просканированного корпуса от nprobe, отметь «колено», где recall насыщается. Покажи запрос, где nprobe=1 теряет истинного соседа сразу за границей ячейки.' },
        { en: 'Product Quantization by hand: split each d-dim vector into m contiguous subvectors; train one k=256 codebook per subspace (Lloyd’s k-means — track the falling inertia). Store each document as m one-byte codes. At query time build the m×256 asymmetric-distance (ADC) table once, then score every document as m table lookups + (m−1) adds — no decompression. Report bytes/vector = m·log₂(k)/8 and the compression ratio dim·4/bytes. Then EXACT-re-rank the PQ top-100 with full vectors and report recall@10 with and without the re-rank: PQ alone has a hard recall ceiling (~0.70 at m=4) whose loss is baked into the stored codes — the exact re-rank is what makes it shippable (the same "cheap retrieve, exact re-rank" division of labour as the cross-encoder cascade).', ru: 'Product Quantization руками: раздели каждый d-мерный вектор на m смежных подвекторов; обучи по одному кодбуку k=256 на подпространство (k-means Ллойда — следи за падающей инерцией). Храни каждый документ как m однобайтовых кодов. На запросе построй таблицу асимметричных расстояний (ADC) m×256 один раз, затем оцени каждый документ как m обращений к таблице + (m−1) сложений — без декомпрессии. Дай bytes/vector = m·log₂(k)/8 и коэффициент сжатия dim·4/bytes. Затем EXACT-re-rank PQ-top-100 полными векторами и дай recall@10 с re-rank и без: у PQ жёсткий потолок recall (~0.70 при m=4), его потеря «вшита» в коды — именно exact re-rank делает его пригодным (то же разделение труда «дёшево найти, точно пересудить», что и cross-encoder-каскад).' },
        { en: '(m, k) memory sweep: vary m ∈ {4, 8, 16} and k ∈ {16, 256}; plot recall@10 (after the exact re-rank) against bytes/vector. Read off the memory-vs-recall tradeoff and confirm the bytes formula against your measured sizes.', ru: 'Свип памяти (m, k): меняй m ∈ {4, 8, 16} и k ∈ {16, 256}; построй recall@10 (после exact re-rank) от bytes/vector. Сними компромисс память-vs-recall и сверь формулу байтов с измеренными размерами.' },
        { en: 'IVF-PQ (compose them): IVF decides which vectors (skip cells), PQ+ADC scores each survivor cheaply, then exact-re-rank the shortlist. Report one combined row: recall@10, fraction scanned, bytes/vector.', ru: 'IVF-PQ (композиция): IVF решает какие векторы (пропуск ячеек), PQ+ADC дёшево оценивает выживших, затем exact-re-rank shortlist. Дай одну строку: recall@10, доля просканирована, bytes/vector.' },
        { en: 'The tradeoff table + analysis: one table, rows {exact, IVF@knee, PQ+re-rank, IVF-PQ} × columns {recall@10, fraction of corpus scanned, bytes/vector, compression×}. Write a half-page analysis of the recall-vs-work-vs-memory triangle: why PQ never ships without an exact re-rank, why IVF’s speed comes from skipping (not shrinking), and the boundary-neighbour failure — each claim pinned to a concrete number from your run.', ru: 'Таблица компромиссов + анализ: одна таблица, строки {exact, IVF@knee, PQ+re-rank, IVF-PQ} × столбцы {recall@10, доля просканированного корпуса, bytes/vector, сжатие×}. Напиши полстраницы анализа треугольника recall-vs-работа-vs-память: почему PQ не ходит один без exact re-rank, почему скорость IVF — от пропуска (а не сжатия), и отказ на boundary-neighbour — каждое утверждение привяжи к конкретному числу из своего прогона.' },
        { en: 'Optional (HNSW trace): on a small graph, trace the greedy descent for one query and sweep efSearch — show ef=1 getting trapped in a local minimum (recall 0) while ef ≥ 2 escapes to recall 1.0. One sentence: why does a wider frontier escape the trap?', ru: 'Опционально (трасса HNSW): на маленьком графе проследи жадный спуск для одного запроса и посвипуй efSearch — покажи, как ef=1 застревает в локальном минимуме (recall 0), а ef ≥ 2 выходит к recall 1.0. Одно предложение: почему более широкий фронт выходит из ловушки?' },
      ] },
      { t: 'h4', v: { en: 'Deliverables', ru: 'Что сдавать', tt: 'Нәрсә тапшырырга' } },
      { t: 'p', v: { en: 'lab.py (or a notebook) that runs end-to-end and prints the tradeoff table, plus a 1-page report: the tradeoff table, the nprobe recall/work curves, the (m,k) memory-vs-recall plot, and the analysis paragraph.', ru: 'lab.py (или notebook), работающий от начала до конца и печатающий таблицу компромиссов, плюс отчёт на 1 страницу: таблица компромиссов, кривые recall/работа от nprobe, график память-vs-recall по (m,k) и абзац анализа.' } },
      { t: 'h4', v: { en: 'Grading (100)', ru: 'Оценка (100)', tt: 'Бәяләү (100)' } },
      { t: 'grade', rows: [
        { label: { en: 'IVF (cells + nprobe scan) correct', ru: 'IVF (ячейки + скан nprobe)' }, w: '25' },
        { label: { en: 'PQ (codebooks + ADC table + memory) + exact re-rank', ru: 'PQ (кодбуки + таблица ADC + память) + exact re-rank' }, w: '30' },
        { label: { en: 'IVF-PQ composition', ru: 'Композиция IVF-PQ' }, w: '15' },
        { label: { en: 'Sweeps & curves (nprobe, (m,k))', ru: 'Свипы и кривые (nprobe, (m,k))' }, w: '20' },
        { label: { en: 'Tradeoff table + analysis', ru: 'Таблица компромиссов + анализ' }, w: '10' },
      ] },
    ],
  },

  {
    slug: 'hw-rag',
    kind: 'homework',
    code: 'A3',
    status: 'soon',
    title: { en: 'Build the RAG retriever, then judge it', ru: 'Собери RAG-ретривер, потом суди его', tt: 'RAG-ретриверны җый, аннары аны хөкем ит' },
    blurb: {
      en: 'Chunk an enterprise corpus and measure the recall floor; lift retrieval with multi-query, HyDE and RAG-Fusion; then evaluate it by hand (context precision & recall from gold answer-facts) and expose an LLM-judge’s position, verbosity and Goodhart biases — plus one paper essay.',
      ru: 'Разбей корпоративный корпус на чанки и измерь «recall floor»; подними ретрив через multi-query, HyDE и RAG-Fusion; затем оцени его руками (context precision и recall из gold answer-facts) и вскрой у LLM-судьи смещения позиции, многословия и Гудхарта — плюс эссе по статье.',
      tt: 'Корпоратив корпусны чанклап, «recall floor»’ны үлчә; multi-query, HyDE һәм RAG-Fusion белән ретривны күтәр; аннары аны кулдан бәялә (gold answer-facts’тан context precision һәм recall) һәм LLM-хөкемченең позиция, күп сүзлелек һәм Гудхарт смещениеләрен ач — өстәп бер мәкалә эссесе.',
    },
    due: { en: 'Extended · coding + handwritten essay', ru: 'Расширенная · код + рукописное эссе', tt: 'Киңәйтелгән · код + кулдан язылган эссе' },
    blocks: [
      { t: 'lead', v: { en: 'Build on Lab 3. Part 1 builds the retrieval half of a RAG system on a real enterprise corpus and learns not to trust it blindly; Part 2 is a close reading of one paper with a hand-drawn re-interpretation of its hero figure. The central frame is the recall floor: if the answer is not in the retrieved context, no generator can recover it — so the retriever and its evaluation are where quality is won or lost.', ru: 'На основе Лабы 3. Часть 1 строит retrieval-половину RAG-системы на реальном корпоративном корпусе и учится ей не доверять слепо; часть 2 — внимательное чтение одной статьи с рукописной переинтерпретацией её hero-фигуры. Центральная рамка — recall floor: если ответа нет в извлечённом контексте, никакой генератор его не вернёт — значит, ретривер и его оценка и есть место, где выигрывается или проигрывается качество.' } },

      { t: 'h4', v: { en: 'Dataset & setup', ru: 'Датасет и setup', tt: 'Мәгълүмат җыелмасы һәм setup' } },
      { t: 'p', v: { en: 'Use EnterpriseRAG-Bench over the full question set (or a stated ≥200-question subset). Each question carries expected_doc_ids (ground-truth documents), a gold_answer, and answer_facts (a list of atomic facts the answer must contain) — the answer_facts are what make context recall and faithfulness hand-computable without a full generator. Subset the corpus to the source_type slices your questions reference plus a seed-20260605 sample; reuse your Lab-1 BM25 and Lab-2 dense retriever. Slice every result by question_type (Basic / Semantic / Intra-Document Reasoning / Constrained / Conflicting Info / Completeness / Info Not Found / …) — the categories are the whole point of this benchmark.', ru: 'Используй EnterpriseRAG-Bench на полном наборе вопросов (или на заявленной подвыборке ≥200). Каждый вопрос несёт expected_doc_ids (ground-truth документы), gold_answer и answer_facts (список атомарных фактов, которые ответ обязан содержать) — именно answer_facts делают context recall и faithfulness вычислимыми руками без полного генератора. Субсетируй корпус до срезов source_type, на которые ссылаются твои вопросы, плюс выборка с seed-20260605; переиспользуй BM25 из Лабы 1 и dense-ретривер из Лабы 2. Режь каждый результат по question_type (Basic / Semantic / Intra-Document Reasoning / Constrained / Conflicting Info / Completeness / Info Not Found / …) — категории и есть смысл этого бенчмарка.' } },
      { t: 'code', v: `from datasets import load_dataset   # EnterpriseRAG-Bench — MIT
qs   = load_dataset("onyx-dot-app/EnterpriseRAG-Bench", "questions")["test"]
docs = load_dataset("onyx-dot-app/EnterpriseRAG-Bench", "documents")["test"]
# q.expected_doc_ids -> the relevant-document set (qrels, binary)
# q.answer_facts     -> atomic gold facts -> context RECALL by hand
# q.question_type    -> slice every metric by category (Info Not Found = abstention)` },

      { t: 'h3', v: { en: 'Part 1 — Coding & experiments (60%)', ru: 'Часть 1 — Код и эксперименты (60%)' } },
      { t: 'ol', v: [
        { en: 'Chunking study (by hand, pure string ops): implement fixed-size and recursive (paragraph → sentence → word) chunking. On the long enterprise documents, sweep chunk size × overlap and measure recall as answer-fact containment — does any single chunk of an expected_doc contain a gold answer_fact? Report the chunk-count formula n = ⌈(L−overlap)/(size−overlap)⌉, exhibit one answer split across a chunk boundary at overlap 0 (recall 0) that a small overlap rescues (recall 1), and state the recall floor: the best any generator could do on your chunking.', ru: 'Исследование чанкинга (руками, чистые строки): реализуй fixed-size и recursive (абзац → предложение → слово) чанкинг. На длинных корпоративных документах посвипуй размер чанка × overlap и меряй recall как answer-fact containment — содержит ли хоть один чанк expected_doc целый gold-факт? Дай формулу числа чанков n = ⌈(L−overlap)/(size−overlap)⌉, покажи ответ, разорванный границей чанка при overlap 0 (recall 0), который спасает малый overlap (recall 1), и сформулируй recall floor: лучшее, что смог бы генератор на твоём чанкинге.' },
        { en: 'Query rewriting (retrieval lift): implement three techniques that edit the query and leave the retriever untouched — multi-query (retrieve several paraphrases, take the union), HyDE (embed a hypothetical answer and retrieve near it), and RAG-Fusion (merge the paraphrase runs with RRF, k=60, by hand). Hand-written paraphrases/hypotheticals are fine, or use a small local generator. Measure recall@k, MRR and nDCG lift over the plain query, and explain each result through the vocabulary gap between a short question and a long jargon-rich enterprise document.', ru: 'Переписывание запроса (lift ретрива): реализуй три техники, которые правят запрос и не трогают ретривер — multi-query (найти несколько парафраз, взять объединение), HyDE (закодировать гипотетический ответ и искать рядом) и RAG-Fusion (слить прогоны парафраз через RRF, k=60, руками). Рукописные парафразы/гипотезы допустимы, или маленький локальный генератор. Меряй прирост recall@k, MRR и nDCG над обычным запросом и объясни каждый результат через vocabulary gap между коротким вопросом и длинным жаргонным корпоративным документом.' },
        { en: 'RAG evaluation by hand (no RAGAS library): compute context precision = MAP over your ranked chunks (average of precision@k at the ranks that hold a relevant chunk — the Lecture-4 MAP, now over retrieved context, needs only the ranking + expected_doc_ids), and context recall = (# gold answer_facts present in the retrieved context) / (# answer_facts) — generator-free, entailment checked by string/embedding match or a small model. Report both per question_type; call out the Info-Not-Found category, where the right retrieval behaviour is to surface little (abstention), not much.', ru: 'Оценка RAG руками (без библиотеки RAGAS): посчитай context precision = MAP по твоим ранжированным чанкам (среднее precision@k на рангах, где стоит релевантный чанк — тот самый MAP из Лекции 4, теперь по извлечённому контексту, нужны лишь ранжирование + expected_doc_ids), и context recall = (# gold answer_facts в извлечённом контексте) / (# answer_facts) — без генератора, entailment проверяется строкой/эмбеддингом или маленькой моделью. Дай оба по question_type; выдели категорию Info-Not-Found, где правильное поведение ретрива — выдать мало (abstention), а не много.' },
        { en: 'LLM-judge bias lab: give an LLM-judge a fixed 1–5 rubric (relevance, grounding, completeness) and measure three biases — position (run each pairwise battle in both orderings; report the position-follow rate on genuine ties), verbosity (hold content fixed, vary only length; report the longer-answer win rate), and the Goodhart weight-flip by hand (honest answer A = mean[5,5,3] = 4.33 beats padded C = mean[4,3,5] = 4.0; re-weight completeness ×2 and C = 4.25 now wins with no word changed). Use a small frozen local judge (e.g. an 8B instruct model, temperature 0, fixed seed) or work the arithmetic fully by hand from provided answers. Then implement the swap-and-average mitigation (count a win only if the same answer wins both orderings) and re-measure the position component.', ru: 'Лаборатория смещений LLM-судьи: дай судье фиксированную рубрику 1–5 (relevance, grounding, completeness) и измерь три смещения — position (гоняй каждую парную дуэль в обоих порядках; дай долю следования позиции на честных ничьих), verbosity (держи содержание фиксированным, меняй только длину; дай долю побед более длинного ответа) и Goodhart-флип весов руками (честный A = mean[5,5,3] = 4.33 бьёт раздутый C = mean[4,3,5] = 4.0; удвой вес completeness — и C = 4.25 выигрывает без единого изменённого слова). Возьми маленького замороженного локального судью (например, 8B instruct, temperature 0, фикс seed) или проделай арифметику полностью руками на предоставленных ответах. Затем реализуй митигацию swap-and-average (победа засчитывается, только если один ответ выиграл в обоих порядках) и перемеряй позиционную компоненту.' },
        { en: 'Metrics & significance: over your best rewrite vs the BM25 baseline, run a paired test (t-test and/or Wilcoxon signed-rank) on per-query context precision — mean difference, 95% CI, p-value, and an honest interpretation (necessary-not-sufficient; the multiple-comparisons caveat once you sweep many configs).', ru: 'Метрики и значимость: для лучшего переписывания против BM25-базлайна прогони парный тест (t-test и/или Wilcoxon) по per-query context precision — средняя разница, 95% CI, p-value и честная интерпретация (необходимо-но-недостаточно; поправка на множественные сравнения, когда свипуешь много конфигов).' },
        { en: 'Report: plots + tables + a discussion tying the recall floor, the rewrite lift, the by-hand RAG metrics, and the judge-bias findings into one story — where quality is actually won in a RAG pipeline, and why you cannot optimise hard against an unaudited judge.', ru: 'Отчёт: графики + таблицы + обсуждение, связывающее recall floor, прирост от переписывания, RAG-метрики руками и находки о смещениях судьи в одну историю — где реально выигрывается качество в RAG-пайплайне и почему нельзя жёстко оптимизировать под неаудированного судью.' },
      ] },
      { t: 'h4', v: { en: 'Part 1 grading (60)', ru: 'Оценка части 1 (60)' } },
      { t: 'grade', rows: [
        { label: { en: 'Chunking sweep + recall floor', ru: 'Свип чанкинга + recall floor' }, w: '15' },
        { label: { en: 'Query rewriting (multi-query, HyDE, RAG-Fusion) + lift', ru: 'Переписывание запроса (multi-query, HyDE, RAG-Fusion) + прирост' }, w: '15' },
        { label: { en: 'RAG metrics by hand (context precision + recall, by category)', ru: 'RAG-метрики руками (context precision + recall, по категориям)' }, w: '12' },
        { label: { en: 'LLM-judge bias lab + swap-and-average', ru: 'Лаборатория смещений судьи + swap-and-average' }, w: '12' },
        { label: { en: 'Metrics + significance', ru: 'Метрики + значимость' }, w: '6' },
      ] },

      { t: 'h3', v: { en: 'Part 2 — Paper reading & hand-written essay (40%)', ru: 'Часть 2 — Чтение статьи и рукописное эссе (40%)' } },
      { t: 'p', v: { en: 'Pick one of the papers below, read it closely, and write a two-page A4 hand-written essay in your own words — your interpretation, not a summary. Then complete the hero-figure sub-task.', ru: 'Выбери одну из статей ниже, внимательно прочитай и напиши рукописное эссе на две страницы A4 своими словами — твоя интерпретация, не пересказ. Затем выполни подзадачу с hero-фигурой.' } },
      { t: 'callout', title: { en: 'Hero-figure sub-task', ru: 'Подзадача: hero-фигура' }, v: { en: 'Identify the paper’s hero figure — the one diagram that carries its central idea. Redesign it your own way (hand-drawn is fine) to expose the concept more deeply than the original: change the encoding, add the missing axis or annotation, show the failure case, or re-draw it using your own Homework numbers (your recall-floor curve, your rewrite lift, your judge-bias rates). Add a short caption stating what your version makes visible that the original did not.', ru: 'Определи hero-фигуру статьи — диаграмму, несущую её центральную идею. Перерисуй её по-своему (можно от руки), чтобы раскрыть концепт глубже оригинала: смени кодировку, добавь недостающую ось/подпись, покажи случай отказа или перерисуй на своих числах из домашки (твоя кривая recall floor, твой прирост от переписывания, твои доли смещений судьи). Добавь короткую подпись — что твой вариант делает видимым, чего не было в оригинале.' } },
      { t: 'h4', v: { en: 'Submission', ru: 'Что сдавать' } },
      { t: 'p', v: { en: 'A photo/scan of the two-page hand-written essay, the redesigned hero figure (hand-drawn or digital), and one paragraph naming the figure you chose and why it is the hero figure.', ru: 'Фото/скан рукописного эссе на две страницы A4, перерисованная hero-фигура (от руки или цифровая) и один абзац — какую фигуру выбрал и почему она hero.' } },
      { t: 'h4', v: { en: 'Choose one paper', ru: 'Выбери одну статью' } },
      { t: 'papers', items: [
        { cite: 'Lewis, P. et al. (2020). Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks. NeurIPS.', hero: { en: 'The original RAG. Hero figure: the retrieve-then-generate architecture with non-parametric memory — redesign it to show the recall floor (what generation can and cannot recover).', ru: 'Оригинальный RAG. Hero-фигура: архитектура retrieve-then-generate с непараметрической памятью — перерисуй, чтобы показать recall floor (что генерация может и чего не может вернуть).' } },
        { cite: 'Gao, L., Ma, X., Lin, J. & Callan, J. (2023). Precise Zero-Shot Dense Retrieval without Relevance Labels (HyDE). ACL.', hero: { en: 'Search with an embedded hypothetical answer. Hero figure: the question→hypothetical-answer→embedding→retrieve flow — redraw it on your own before/after ranks.', ru: 'Поиск с эмбеддингом гипотетического ответа. Hero-фигура: поток вопрос→гипотетический-ответ→эмбеддинг→поиск — перерисуй на своих рангах до/после.' } },
        { cite: 'Günther, M. et al. (Jina AI, 2024). Late Chunking: Contextual Chunk Embeddings Using Long-Context Embedding Models.', hero: { en: 'Embed the whole document first, chunk after the transformer. Hero figure: the isolation defect vs contextual chunk embeddings — show what context is restored.', ru: 'Сначала закодировать весь документ, чанковать после трансформера. Hero-фигура: дефект изоляции против контекстных эмбеддингов чанков — покажи, какой контекст восстановлен.' } },
        { cite: 'Liu, N. F. et al. (2024). Lost in the Middle: How Language Models Use Long Contexts. TACL.', hero: { en: 'Long-context position bias. Hero figure: the U-shaped accuracy-vs-position curve — redraw it to argue why ranking still matters even with huge context windows.', ru: 'Позиционное смещение длинного контекста. Hero-фигура: U-образная кривая точность-vs-позиция — перерисуй, чтобы обосновать, почему ранжирование важно даже при огромных окнах контекста.' } },
        { cite: 'Es, S., James, J., Espinosa-Anke, L. & Schockaert, S. (2023). RAGAS: Automated Evaluation of Retrieval Augmented Generation.', hero: { en: 'Reference-free decomposition into faithfulness / answer relevance / context precision / context recall. Hero element: the four-metric 2×2 (answer vs context) — redesign it as a diagnostic that localises blame between retriever and generator.', ru: 'Reference-free декомпозиция на faithfulness / answer relevance / context precision / context recall. Hero-элемент: 2×2 из четырёх метрик (ответ vs контекст) — перерисуй как диагностику, локализующую вину между ретривером и генератором.' } },
        { cite: 'Zheng, L. et al. (2023). Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena. NeurIPS.', hero: { en: 'The LLM-judge and its biases. Hero element: the position / verbosity / self-enhancement bias table — redraw it with your own measured bias rates and the swap-and-average correction.', ru: 'LLM-судья и его смещения. Hero-элемент: таблица смещений позиции / многословия / самопредпочтения — перерисуй со своими измеренными долями смещений и поправкой swap-and-average.' } },
        { cite: 'Yao, S. et al. (2023). ReAct: Synergizing Reasoning and Acting in Language Models. ICLR.', hero: { en: 'Interleaved reasoning + acting for multi-hop retrieval. Hero figure: the thought→action→observation loop — redraw it as a recall-by-hop curve (single-shot recall 0 → multi-hop recall 1).', ru: 'Чередование рассуждения и действия для multi-hop ретрива. Hero-фигура: петля мысль→действие→наблюдение — перерисуй как кривую recall-по-шагам (single-shot recall 0 → multi-hop recall 1).' } },
      ] },
      { t: 'h4', v: { en: 'Part 2 grading (40)', ru: 'Оценка части 2 (40)' } },
      { t: 'grade', rows: [
        { label: { en: 'Interpretation depth & correctness', ru: 'Глубина и корректность интерпретации' }, w: '20' },
        { label: { en: 'Hero-figure redesign (insight added)', ru: 'Перерисовка hero-фигуры (добавленный инсайт)' }, w: '15' },
        { label: { en: 'Clarity, structure, handwriting', ru: 'Ясность, структура, почерк' }, w: '5' },
      ] },
    ],
  },
];
