// glossary.js — the course term index: every core concept → a one-line trilingual definition →
// the lecture where it is taught. A study/review tool. NON-GATED (authored prose, no data/ facts,
// no i18n registration): edit freely; the `lec` id links each term to its Book chapter.
//
// Each entry: { id, term:{en,ru,tt}, def:{en,ru,tt}, lec:'NN' }. The page groups by `lec` (whose
// title + Book link come from course.json) and offers search + per-lecture filtering.

export const terms = [
  // ── L01 · Search & IR · ML System Design ─────────────────────────────────
  { id: 'information-retrieval', lec: '01',
    term: { en: 'Information Retrieval', ru: 'Информационный поиск', tt: 'Мәгълүмат эзләү' },
    def: { en: 'Finding, from a large collection, the documents that satisfy an information need.',
           ru: 'Нахождение в большой коллекции документов, отвечающих информационной потребности.',
           tt: 'Зур җыелмадан мәгълүмат ихтыяҗын канәгатьләндерүче документларны табу.' } },
  { id: 'retrieve-then-rank', lec: '01',
    term: { en: 'Retrieve-then-rank', ru: 'Извлечь-затем-ранжировать', tt: 'Табу, аннары ранжлау' },
    def: { en: 'The two-stage cascade: cheaply fetch many candidates, then carefully order the few.',
           ru: 'Двухэтапный каскад: дёшево извлечь много кандидатов, затем аккуратно упорядочить немногих.',
           tt: 'Ике этаплы каскад: арзан гына күп кандидат табу, аннары азларны җентекле тәртипкә салу.' } },
  { id: 'relevance', lec: '01',
    term: { en: 'Relevance', ru: 'Релевантность', tt: 'Релевантлык' },
    def: { en: "How well a document satisfies the information need behind a user's query.",
           ru: 'Насколько документ отвечает информационной потребности за запросом пользователя.',
           tt: 'Документ кулланучы соравы артындагы мәгълүмат ихтыяҗын никадәр канәгатьләндерә.' } },
  { id: 'corpus', lec: '01',
    term: { en: 'Corpus', ru: 'Корпус', tt: 'Корпус' },
    def: { en: 'The full collection of documents a search system indexes and searches over.',
           ru: 'Полная коллекция документов, которую поисковая система индексирует и по которой ищет.',
           tt: 'Эзләү системасы индекслаган һәм эзли торган документларның тулы җыелмасы.' } },

  // ── L02 · NLP · Tokenization · Similarity ────────────────────────────────
  { id: 'tokenization', lec: '02',
    term: { en: 'Tokenization', ru: 'Токенизация', tt: 'Токенлаштыру' },
    def: { en: 'Splitting text into the atomic units (tokens) a model or index works with.',
           ru: 'Разбиение текста на атомарные единицы (токены), с которыми работает модель или индекс.',
           tt: 'Текстны модель яки индекс эшли торган атом берәмлекләргә (токеннарга) бүлү.' } },
  { id: 'bpe', lec: '02',
    term: { en: 'Byte-Pair Encoding (BPE)', ru: 'Byte-Pair Encoding (BPE)', tt: 'Byte-Pair Encoding (BPE)' },
    def: { en: 'A subword tokenizer that merges frequent character pairs, balancing vocabulary size and coverage.',
           ru: 'Субсловный токенизатор, сливающий частые пары символов, балансируя размер словаря и покрытие.',
           tt: 'Еш очрый торган символ парларын берләштерүче субсүз токенизаторы; сүзлек күләмен һәм иңләүне тигезли.' } },
  { id: 'stemming', lec: '02',
    term: { en: 'Stemming', ru: 'Стемминг', tt: 'Стемминг' },
    def: { en: 'Chopping words to a crude root (e.g. "running" → "run") so variants match.',
           ru: 'Обрезание слов до грубого корня (например, «running» → «run»), чтобы варианты совпадали.',
           tt: 'Вариантлар туры килсен өчен сүзләрне тупас тамырга кисү (мәс., "running" → "run").' } },
  { id: 'lemmatization', lec: '02',
    term: { en: 'Lemmatization', ru: 'Лемматизация', tt: 'Лемматизация' },
    def: { en: 'Reducing a word to its dictionary form using morphology (e.g. "better" → "good").',
           ru: 'Приведение слова к словарной форме с помощью морфологии (например, «better» → «good»).',
           tt: 'Морфология ярдәмендә сүзне сүзлек формасына китерү (мәс., "better" → "good").' } },
  { id: 'stop-words', lec: '02',
    term: { en: 'Stop words', ru: 'Стоп-слова', tt: 'Стоп-сүзләр' },
    def: { en: 'Very common words (the, of, and) often dropped because they carry little signal.',
           ru: 'Очень частые слова (the, of, and), которые часто отбрасывают из-за малой информативности.',
           tt: 'Бик еш очрый торган сүзләр (the, of, and); мәгълүматлары аз булганга еш төшереп калдырыла.' } },
  { id: 'cosine-similarity', lec: '02',
    term: { en: 'Cosine similarity', ru: 'Косинусная близость', tt: 'Косинус охшашлыгы' },
    def: { en: 'Closeness of two vectors measured by the angle between them, ignoring length.',
           ru: 'Близость двух векторов, измеряемая углом между ними, без учёта длины.',
           tt: 'Ике вектор арасындагы почмак буенча үлчәнгән якынлык; озынлык исәпкә алынмый.' } },
  { id: 'jaccard', lec: '02',
    term: { en: 'Jaccard similarity', ru: 'Коэффициент Жаккара', tt: 'Жаккар охшашлыгы' },
    def: { en: 'Overlap of two sets: the size of their intersection over the size of their union.',
           ru: 'Пересечение двух множеств: размер пересечения, делённый на размер объединения.',
           tt: 'Ике җыелманың кисешүе: кисешү күләмен берләшмә күләменә бүлү.' } },
  { id: 'edit-distance', lec: '02',
    term: { en: 'Edit distance', ru: 'Редакционное расстояние', tt: 'Редакция ераклыгы' },
    def: { en: 'The minimum number of insert/delete/substitute edits to turn one string into another.',
           ru: 'Минимальное число вставок/удалений/замен, чтобы превратить одну строку в другую.',
           tt: 'Бер юлны икенчесенә әйләндерү өчен кирәкле минималь өстәү/бетерү/алмаштыру саны.' } },

  // ── L03 · Classical IR ───────────────────────────────────────────────────
  { id: 'inverted-index', lec: '03',
    term: { en: 'Inverted index', ru: 'Инвертированный индекс', tt: 'Инвертланган индекс' },
    def: { en: 'A map from each term to the list of documents that contain it — the backbone of full-text search.',
           ru: 'Отображение каждого терма в список содержащих его документов — основа полнотекстового поиска.',
           tt: 'Һәр термны аны эченә алган документлар исемлегенә бәйләү — тулы текст эзләвенең нигезе.' } },
  { id: 'tf-idf', lec: '03',
    term: { en: 'TF-IDF', ru: 'TF-IDF', tt: 'TF-IDF' },
    def: { en: 'A term weight that rises with frequency in a document and falls with how many documents use it.',
           ru: 'Вес терма, растущий с частотой в документе и падающий с числом документов, где он встречается.',
           tt: 'Документта ешлыгы белән арта, ничә документта очравы белән кими торган терм авырлыгы.' } },
  { id: 'bm25', lec: '03',
    term: { en: 'BM25', ru: 'BM25', tt: 'BM25' },
    def: { en: 'The classic probabilistic ranking function: TF-IDF with term saturation and length normalization.',
           ru: 'Классическая вероятностная функция ранжирования: TF-IDF с насыщением терма и нормировкой длины.',
           tt: 'Классик ихтимал ранжлау функциясе: терм туену һәм озынлык нормалаштыруы белән TF-IDF.' } },
  { id: 'idf', lec: '03',
    term: { en: 'Inverse document frequency (IDF)', ru: 'Обратная документная частота (IDF)', tt: 'Кире документ ешлыгы (IDF)' },
    def: { en: 'A weight that boosts terms appearing in few documents and discounts ubiquitous ones.',
           ru: 'Вес, повышающий значимость термов из немногих документов и понижающий вездесущие.',
           tt: 'Аз документта очрый торган термнарны күтәреп, гомуми термнарны кимүче авырлык.' } },
  { id: 'pagerank', lec: '03',
    term: { en: 'PageRank', ru: 'PageRank', tt: 'PageRank' },
    def: { en: 'Link-based authority: a page is important if important pages link to it.',
           ru: 'Авторитет по ссылкам: страница важна, если на неё ссылаются важные страницы.',
           tt: 'Сылтамага нигезләнгән абруй: мөһим битләр сылтаса, бит мөһим.' } },
  { id: 'rrf', lec: '03',
    term: { en: 'Reciprocal Rank Fusion (RRF)', ru: 'Reciprocal Rank Fusion (RRF)', tt: 'Reciprocal Rank Fusion (RRF)' },
    def: { en: 'Combining several ranked lists by summing 1/(k + rank) for each item across them.',
           ru: 'Объединение нескольких ранжированных списков суммированием 1/(k + ранг) по каждому элементу.',
           tt: 'Берничә ранжланган исемлекне һәр элемент өчен 1/(k + ранг) суммалап берләштерү.' } },
  { id: 'postings-list', lec: '03',
    term: { en: 'Postings list', ru: 'Список вхождений', tt: 'Кертемнәр исемлеге' },
    def: { en: 'The list of documents (and positions) stored for one term in the inverted index.',
           ru: 'Список документов (и позиций), хранимый для одного терма в инвертированном индексе.',
           tt: 'Инвертланган индекста бер терм өчен сакланган документлар (һәм урыннар) исемлеге.' } },

  // ── L04 · Ranking Metrics ────────────────────────────────────────────────
  { id: 'precision-at-k', lec: '04',
    term: { en: 'Precision@k', ru: 'Precision@k', tt: 'Precision@k' },
    def: { en: 'The fraction of the top-k results that are relevant.',
           ru: 'Доля релевантных среди первых k результатов.',
           tt: 'Беренче k нәтиҗә арасында релевантларның өлеше.' } },
  { id: 'recall-at-k', lec: '04',
    term: { en: 'Recall@k', ru: 'Recall@k', tt: 'Recall@k' },
    def: { en: 'The fraction of all relevant documents that appear within the top-k.',
           ru: 'Доля всех релевантных документов, попавших в первые k.',
           tt: 'Барлык релевант документларның беренче k эчендә күренгән өлеше.' } },
  { id: 'mrr', lec: '04',
    term: { en: 'Mean Reciprocal Rank (MRR)', ru: 'Средний обратный ранг (MRR)', tt: 'Уртача кире ранг (MRR)' },
    def: { en: 'The average of 1/(rank of the first relevant result) over queries.',
           ru: 'Среднее по запросам от 1/(ранг первого релевантного результата).',
           tt: 'Сораулар буенча 1/(беренче релевант нәтиҗәнең рангы) урталыгы.' } },
  { id: 'map-metric', lec: '04',
    term: { en: 'Mean Average Precision (MAP)', ru: 'Средняя точность (MAP)', tt: 'Уртача төгәллек (MAP)' },
    def: { en: 'The mean, over queries, of the average precision computed across a query’s relevant hits.',
           ru: 'Среднее по запросам от средней точности, посчитанной по релевантным попаданиям запроса.',
           tt: 'Сорауның релевант табышлары буенча исәпләнгән уртача төгәллекнең сораулар буенча урталыгы.' } },
  { id: 'ndcg', lec: '04',
    term: { en: 'nDCG', ru: 'nDCG', tt: 'nDCG' },
    def: { en: 'Normalized Discounted Cumulative Gain — rewards putting highly relevant results near the top.',
           ru: 'Нормированный DCG — награждает за размещение самых релевантных результатов ближе к началу.',
           tt: 'Нормалаштырылган DCG — иң релевант нәтиҗәләрне башка якын куюны бүләкли.' } },
  { id: 'dcg', lec: '04',
    term: { en: 'Discounted Cumulative Gain (DCG)', ru: 'Discounted Cumulative Gain (DCG)', tt: 'Discounted Cumulative Gain (DCG)' },
    def: { en: 'Sums graded relevance down the ranked list with a discount that grows with position.',
           ru: 'Суммирует градуированную релевантность по списку со скидкой, растущей с позицией.',
           tt: 'Ранжланган исемлек буенча дәрәҗәле релевантлыкны, урын белән арта торган ташлама белән суммалый.' } },
  { id: 'relevance-judgment', lec: '04',
    term: { en: 'Relevance judgment', ru: 'Оценка релевантности', tt: 'Релевантлык бәясе' },
    def: { en: 'A human label saying how relevant a document is to a query — the ground truth for metrics.',
           ru: 'Человеческая метка, насколько документ релевантен запросу — эталон для метрик.',
           tt: 'Документ сорауга никадәр релевант икәнен әйтүче кеше билгесе — метрикалар өчен эталон.' } },
  { id: 'goodharts-law', lec: '04',
    term: { en: "Goodhart's law", ru: 'Закон Гудхарта', tt: 'Гудхарт законы' },
    def: { en: 'When a measure becomes a target, it ceases to be a good measure.',
           ru: 'Когда мера становится целью, она перестаёт быть хорошей мерой.',
           tt: 'Үлчәм максатка әйләнгәч, ул яхшы үлчәм булудан туктый.' } },

  // ── L05 · Intro to DL · Word Embeddings · Dim-reduction ──────────────────
  { id: 'word-embedding', lec: '05',
    term: { en: 'Word embedding', ru: 'Векторное представление слова', tt: 'Сүз векторлавы' },
    def: { en: 'A dense vector for a word whose geometry captures its meaning and similarity to others.',
           ru: 'Плотный вектор слова, геометрия которого отражает его смысл и близость к другим.',
           tt: 'Геометриясе сүзнең мәгънәсен һәм башкаларга якынлыгын чагылдырган куе вектор.' } },
  { id: 'word2vec', lec: '05',
    term: { en: 'Word2Vec', ru: 'Word2Vec', tt: 'Word2Vec' },
    def: { en: 'A method that learns word embeddings by predicting a word from its context (or vice versa).',
           ru: 'Метод обучения векторов слов через предсказание слова по контексту (или наоборот).',
           tt: 'Сүзне контексты буенча (яки киресенчә) фаразлап сүз векторларын өйрәнү ысулы.' } },
  { id: 'dimensionality-reduction', lec: '05',
    term: { en: 'Dimensionality reduction', ru: 'Снижение размерности', tt: 'Үлчәмлелекне киметү' },
    def: { en: 'Projecting high-dimensional vectors into a few dimensions while preserving structure.',
           ru: 'Проекция многомерных векторов в несколько измерений с сохранением структуры.',
           tt: 'Күп үлчәмле векторларны структураны саклап берничә үлчәмгә проекцияләү.' } },
  { id: 'tsne', lec: '05',
    term: { en: 't-SNE', ru: 't-SNE', tt: 't-SNE' },
    def: { en: 'A nonlinear technique that lays out high-dimensional points in 2-D, preserving local neighbourhoods.',
           ru: 'Нелинейный метод, раскладывающий многомерные точки в 2-D с сохранением локальных соседств.',
           tt: 'Күп үлчәмле нокталарны локаль күршелекләрне саклап 2-Dда урнаштыручы сызыксыз ысул.' } },
  { id: 'pca', lec: '05',
    term: { en: 'PCA', ru: 'Метод главных компонент (PCA)', tt: 'Баш компонентлар ысулы (PCA)' },
    def: { en: 'Principal Component Analysis — a linear projection onto the directions of greatest variance.',
           ru: 'Анализ главных компонент — линейная проекция на направления наибольшей дисперсии.',
           tt: 'Баш компонентлар анализы — иң зур дисперсия юнәлешләренә сызыклы проекция.' } },
  { id: 'embedding-space', lec: '05',
    term: { en: 'Embedding space', ru: 'Пространство эмбеддингов', tt: 'Эмбеддинглар киңлеге' },
    def: { en: 'The vector space where meanings become positions you can measure and travel between.',
           ru: 'Векторное пространство, где смыслы становятся позициями, между которыми можно измерять и перемещаться.',
           tt: 'Мәгънәләр үлчәп һәм арасында хәрәкәт итеп була торган урыннарга әйләнгән вектор киңлеге.' } },

  // ── L06 · Dense & Contextual · Contrastive · Transformers ────────────────
  { id: 'dense-embedding', lec: '06',
    term: { en: 'Dense embedding', ru: 'Плотный эмбеддинг', tt: 'Куе эмбеддинг' },
    def: { en: 'A compact learned vector representation, as opposed to sparse term counts.',
           ru: 'Компактное обученное векторное представление, в отличие от разреженных счётчиков термов.',
           tt: 'Сирәк терм санауларына каршы буларак — компакт өйрәнелгән вектор күрсәтмәсе.' } },
  { id: 'contextual-embedding', lec: '06',
    term: { en: 'Contextual embedding', ru: 'Контекстный эмбеддинг', tt: 'Контекстлы эмбеддинг' },
    def: { en: 'A token vector that depends on the surrounding sentence, so "bank" differs by context.',
           ru: 'Вектор токена, зависящий от окружающего предложения, так что «bank» различается по контексту.',
           tt: 'Тирәдәге җөмләгә бәйле токен векторы; шуңа "bank" контекст буенча аерыла.' } },
  { id: 'contrastive-learning', lec: '06',
    term: { en: 'Contrastive learning', ru: 'Контрастивное обучение', tt: 'Контрастив өйрәнү' },
    def: { en: 'Training that pulls matching pairs together and pushes mismatched pairs apart.',
           ru: 'Обучение, притягивающее подходящие пары и отталкивающее неподходящие.',
           tt: 'Туры килгән парларны якынайтып, туры килмәгәннәрне этәрүче өйрәтү.' } },
  { id: 'self-attention', lec: '06',
    term: { en: 'Self-attention', ru: 'Само-внимание', tt: 'Үз-игътибары' },
    def: { en: 'A mechanism letting each token weigh and gather information from every other token.',
           ru: 'Механизм, позволяющий каждому токену взвешивать и собирать информацию от всех остальных.',
           tt: 'Һәр токенга калган һәр токеннан мәгълүматны үлчәп җыярга мөмкинлек бирүче механизм.' } },
  { id: 'transformer', lec: '06',
    term: { en: 'Transformer', ru: 'Трансформер', tt: 'Трансформер' },
    def: { en: 'The attention-based architecture underlying modern language and retrieval models.',
           ru: 'Архитектура на основе внимания, лежащая в основе современных языковых и поисковых моделей.',
           tt: 'Хәзерге тел һәм эзләү модельләре нигезендәге игътибарга корылган архитектура.' } },
  { id: 'positional-encoding', lec: '06',
    term: { en: 'Positional encoding', ru: 'Позиционное кодирование', tt: 'Позицион кодлау' },
    def: { en: 'Signals added to token vectors so the model knows their order.',
           ru: 'Сигналы, добавляемые к векторам токенов, чтобы модель знала их порядок.',
           tt: 'Модель тәртипне белсен өчен токен векторларына өстәлгән сигналлар.' } },

  // ── L07 · Bi-encoders · Cross-encoders · Pipelines ───────────────────────
  { id: 'bi-encoder', lec: '07',
    term: { en: 'Bi-encoder', ru: 'Би-энкодер', tt: 'Би-энкодер' },
    def: { en: 'Encodes query and document separately into vectors — fast, and enables precomputed indexes.',
           ru: 'Кодирует запрос и документ раздельно в векторы — быстро и позволяет предвычислять индексы.',
           tt: 'Сорауны һәм документны аерым векторларга кодлый — тиз һәм алдан исәпләнгән индекслар мөмкин.' } },
  { id: 'cross-encoder', lec: '07',
    term: { en: 'Cross-encoder', ru: 'Кросс-энкодер', tt: 'Кросс-энкодер' },
    def: { en: 'Jointly encodes query + document for an accurate but slower relevance score.',
           ru: 'Совместно кодирует запрос + документ для точной, но более медленной оценки релевантности.',
           tt: 'Төгәл, ләкин әкренрәк релевантлык бәясе өчен сорау + документны бергә кодлый.' } },
  { id: 'dpr', lec: '07',
    term: { en: 'Dense Passage Retrieval (DPR)', ru: 'Dense Passage Retrieval (DPR)', tt: 'Dense Passage Retrieval (DPR)' },
    def: { en: 'A bi-encoder trained to retrieve passages by dense vector similarity.',
           ru: 'Би-энкодер, обученный извлекать пассажи по близости плотных векторов.',
           tt: 'Куе вектор охшашлыгы буенча өзекләр табарга өйрәтелгән би-энкодер.' } },
  { id: 'sbert', lec: '07',
    term: { en: 'SBERT (Sentence-BERT)', ru: 'SBERT (Sentence-BERT)', tt: 'SBERT (Sentence-BERT)' },
    def: { en: 'BERT fine-tuned to produce sentence embeddings that are comparable by cosine similarity.',
           ru: 'BERT, дообученный выдавать эмбеддинги предложений, сравнимые по косинусной близости.',
           tt: 'Җөмлә эмбеддинглары чыгарырга өйрәтелгән BERT; алар косинус охшашлыгы буенча чагыштырыла.' } },
  { id: 'reranking', lec: '07',
    term: { en: 'Reranking', ru: 'Переранжирование', tt: 'Кабат ранжлау' },
    def: { en: 'Reordering a retrieved candidate set with a stronger, costlier model.',
           ru: 'Переупорядочивание извлечённого набора кандидатов более сильной, но дорогой моделью.',
           tt: 'Табылган кандидатлар җыелмасын көчлерәк, кыйммәтрәк модель белән яңадан тәртипләү.' } },
  { id: 'multi-stage-pipeline', lec: '07',
    term: { en: 'Multi-stage pipeline', ru: 'Многоступенчатый конвейер', tt: 'Күп баскычлы конвейер' },
    def: { en: 'A retrieval cascade where each stage narrows and refines the candidate set.',
           ru: 'Каскад извлечения, где каждая ступень сужает и уточняет набор кандидатов.',
           tt: 'Һәр баскыч кандидатлар җыелмасын тарайтып төгәлләштерә торган табу каскады.' } },

  // ── L08 · Late Interaction · SPLADE · Hybrid · Learning to Rank ──────────
  { id: 'late-interaction', lec: '08',
    term: { en: 'Late interaction', ru: 'Позднее взаимодействие', tt: 'Соңгы үзара тәэсир' },
    def: { en: 'Scoring by comparing per-token vectors of query and document at the end (e.g. MaxSim).',
           ru: 'Оценка через сравнение потокенных векторов запроса и документа в конце (например, MaxSim).',
           tt: 'Ахырда сорау һәм документның токен-векторларын чагыштырып бәяләү (мәс., MaxSim).' } },
  { id: 'colbert', lec: '08',
    term: { en: 'ColBERT', ru: 'ColBERT', tt: 'ColBERT' },
    def: { en: 'A late-interaction retriever matching each query token to its best document token.',
           ru: 'Поисковик позднего взаимодействия, сопоставляющий каждый токен запроса лучшему токену документа.',
           tt: 'Һәр сорау токенын иң яхшы документ токенына тәңгәлләштерүче соңгы тәэсир табучысы.' } },
  { id: 'splade', lec: '08',
    term: { en: 'SPLADE', ru: 'SPLADE', tt: 'SPLADE' },
    def: { en: 'A learned sparse retriever that expands text into weighted vocabulary terms.',
           ru: 'Обученный разреженный поисковик, расширяющий текст во взвешенные термы словаря.',
           tt: 'Текстны авырлыклы сүзлек термнарына киңәйтүче өйрәнелгән сирәк табучы.' } },
  { id: 'learned-sparse', lec: '08',
    term: { en: 'Learned sparse retrieval', ru: 'Обученный разреженный поиск', tt: 'Өйрәнелгән сирәк эзләү' },
    def: { en: 'Neural models that produce sparse, invertible term weights for fast inverted indexes.',
           ru: 'Нейросети, выдающие разреженные обратимые веса термов для быстрых инвертированных индексов.',
           tt: 'Тиз инвертланган индекслар өчен сирәк, кире кайтарыла торган терм авырлыклары чыгаручы нейромодельләр.' } },
  { id: 'hybrid-search', lec: '08',
    term: { en: 'Hybrid search', ru: 'Гибридный поиск', tt: 'Гибрид эзләү' },
    def: { en: 'Combining lexical (BM25) and dense retrieval to get the strengths of both.',
           ru: 'Сочетание лексического (BM25) и плотного поиска, чтобы взять сильные стороны обоих.',
           tt: 'Икесенең дә көчле якларын алу өчен лексик (BM25) һәм куе эзләүне берләштерү.' } },
  { id: 'learning-to-rank', lec: '08',
    term: { en: 'Learning to Rank (LTR)', ru: 'Learning to Rank (LTR)', tt: 'Learning to Rank (LTR)' },
    def: { en: 'Training a model to order results directly from labelled relevance data.',
           ru: 'Обучение модели упорядочивать результаты прямо на размеченных данных релевантности.',
           tt: 'Билгеләнгән релевантлык мәгълүматыннан нәтиҗәләрне тәртипләргә модельне өйрәтү.' } },
  { id: 'maxsim', lec: '08',
    term: { en: 'MaxSim', ru: 'MaxSim', tt: 'MaxSim' },
    def: { en: "ColBERT's operator: each query token takes its maximum similarity over the document's tokens.",
           ru: 'Оператор ColBERT: каждый токен запроса берёт максимум близости по токенам документа.',
           tt: 'ColBERT операторы: һәр сорау токены документ токеннары буенча максималь охшашлыкны ала.' } },

  // ── L09 · ANN · Vector Databases ─────────────────────────────────────────
  { id: 'ann', lec: '09',
    term: { en: 'Approximate Nearest Neighbour (ANN)', ru: 'Приближённый поиск соседей (ANN)', tt: 'Якынча иң якын күршеләр (ANN)' },
    def: { en: 'Trading a little recall for huge speed when searching vectors at billion scale.',
           ru: 'Обмен небольшой полноты на огромную скорость при поиске векторов на миллиардном масштабе.',
           tt: 'Миллиард масштабта векторлар эзләгәндә бераз тулылыкны зур тизлеккә алмаштыру.' } },
  { id: 'hnsw', lec: '09',
    term: { en: 'HNSW', ru: 'HNSW', tt: 'HNSW' },
    def: { en: 'A navigable small-world graph index enabling fast greedy nearest-neighbour search.',
           ru: 'Индекс-граф «тесного мира», обеспечивающий быстрый жадный поиск ближайших соседей.',
           tt: '"Тыгыз дөнья" граф-индексы; тиз ач иң якын күрше эзләвен мөмкин итә.' } },
  { id: 'ivf', lec: '09',
    term: { en: 'IVF (Inverted File)', ru: 'IVF (инвертированный файл)', tt: 'IVF (инвертланган файл)' },
    def: { en: 'Cluster vectors into cells, then search only the cells nearest to the query.',
           ru: 'Кластеризовать векторы в ячейки и искать только в ближайших к запросу ячейках.',
           tt: 'Векторларны күзәнәкләргә кластерлап, сорауга иң якын күзәнәкләрдә генә эзләү.' } },
  { id: 'pq', lec: '09',
    term: { en: 'Product Quantization (PQ)', ru: 'Продуктовое квантование (PQ)', tt: 'Продукт квантлау (PQ)' },
    def: { en: 'Compressing vectors into short codes by quantizing their sub-vectors independently.',
           ru: 'Сжатие векторов в короткие коды за счёт независимого квантования их подвекторов.',
           tt: 'Асвекторларны бәйсез квантлап векторларны кыска кодларга кысу.' } },
  { id: 'faiss', lec: '09',
    term: { en: 'FAISS', ru: 'FAISS', tt: 'FAISS' },
    def: { en: 'A library for efficient similarity search and clustering of dense vectors.',
           ru: 'Библиотека для эффективного поиска по близости и кластеризации плотных векторов.',
           tt: 'Куе векторларны нәтиҗәле охшашлык эзләү һәм кластерлау китапханәсе.' } },
  { id: 'vector-database', lec: '09',
    term: { en: 'Vector database', ru: 'Векторная база данных', tt: 'Вектор мәгълүмат базасы' },
    def: { en: 'A store that indexes embeddings for fast similarity search in production.',
           ru: 'Хранилище, индексирующее эмбеддинги для быстрого поиска по близости в проде.',
           tt: 'Продукцияда тиз охшашлык эзләү өчен эмбеддингларны индекслаучы саклагыч.' } },

  // ── L10 · RAG Fundamentals · Chunking · Query Understanding ──────────────
  { id: 'rag', lec: '10',
    term: { en: 'Retrieval-Augmented Generation (RAG)', ru: 'Retrieval-Augmented Generation (RAG)', tt: 'Retrieval-Augmented Generation (RAG)' },
    def: { en: "Grounding a language model's answer in freshly retrieved documents.",
           ru: 'Заземление ответа языковой модели на свежеизвлечённых документах.',
           tt: 'Тел моделе җавабын яңа табылган документларга нигезләү.' } },
  { id: 'chunking', lec: '10',
    term: { en: 'Chunking', ru: 'Чанкинг (нарезка)', tt: 'Кисәкләү' },
    def: { en: "Splitting documents into passages sized for retrieval and the model's context window.",
           ru: 'Разбиение документов на пассажи под извлечение и контекстное окно модели.',
           tt: 'Документларны табу һәм модель контекст тәрәзәсенә яраклы өзекләргә бүлү.' } },
  { id: 'query-rewriting', lec: '10',
    term: { en: 'Query rewriting', ru: 'Переписывание запроса', tt: 'Сорауны яңадан язу' },
    def: { en: 'Reformulating a user query to retrieve better — expansion, clarification, decomposition.',
           ru: 'Переформулирование запроса пользователя для лучшего извлечения — расширение, уточнение, декомпозиция.',
           tt: 'Яхшырак табу өчен кулланучы соравын яңадан төзү — киңәйтү, ачыклау, таркату.' } },
  { id: 'hyde', lec: '10',
    term: { en: 'HyDE', ru: 'HyDE', tt: 'HyDE' },
    def: { en: 'Hypothetical Document Embeddings — embed an LLM-drafted answer to retrieve real passages.',
           ru: 'Hypothetical Document Embeddings — эмбеддинг черновика ответа LLM для извлечения реальных пассажей.',
           tt: 'Hypothetical Document Embeddings — LLM язган җавап проектын эмбеддлап реаль өзекләр табу.' } },
  { id: 'semantic-router', lec: '10',
    term: { en: 'Semantic router', ru: 'Семантический маршрутизатор', tt: 'Семантик маршрутлаучы' },
    def: { en: 'Directing a query to the right tool or index by embedding similarity.',
           ru: 'Направление запроса к нужному инструменту или индексу по близости эмбеддингов.',
           tt: 'Эмбеддинг охшашлыгы буенча сорауны кирәкле корал яки индекска юнәлтү.' } },

  // ── L11 · RAG Evaluation · Agentic RAG ───────────────────────────────────
  { id: 'ragas', lec: '11',
    term: { en: 'RAGAS', ru: 'RAGAS', tt: 'RAGAS' },
    def: { en: 'A framework of reference-free metrics for evaluating RAG pipelines.',
           ru: 'Фреймворк безэталонных метрик для оценки RAG-конвейеров.',
           tt: 'RAG конвейерларын бәяләү өчен эталонсыз метрикалар кысасы.' } },
  { id: 'llm-as-judge', lec: '11',
    term: { en: 'LLM-as-judge', ru: 'LLM-как-судья', tt: 'LLM-хөкемче буларак' },
    def: { en: 'Using a language model to score or compare outputs in place of human raters.',
           ru: 'Использование языковой модели для оценки или сравнения ответов вместо людей.',
           tt: 'Кеше бәяләүчеләр урынына чыгышларны бәяләү яки чагыштыру өчен тел моделен куллану.' } },
  { id: 'faithfulness', lec: '11',
    term: { en: 'Faithfulness', ru: 'Достоверность (faithfulness)', tt: 'Тугрылык (faithfulness)' },
    def: { en: 'Whether a generated answer is actually supported by the retrieved context.',
           ru: 'Действительно ли сгенерированный ответ подкреплён извлечённым контекстом.',
           tt: 'Ясалган җавап табылган контекст белән чыннан да ныгытылганмы.' } },
  { id: 'agentic-rag', lec: '11',
    term: { en: 'Agentic RAG', ru: 'Агентный RAG', tt: 'Агентлы RAG' },
    def: { en: 'RAG where an agent plans, retrieves and acts over multiple steps.',
           ru: 'RAG, где агент планирует, извлекает и действует за несколько шагов.',
           tt: 'Агент берничә адымда планлаштыра, таба һәм эш итә торган RAG.' } },
  { id: 'react', lec: '11',
    term: { en: 'ReAct', ru: 'ReAct', tt: 'ReAct' },
    def: { en: 'An agent pattern interleaving reasoning traces with tool-use actions.',
           ru: 'Паттерн агента, чередующий рассуждения с действиями по использованию инструментов.',
           tt: 'Фикерләү эзләрен корал куллану гамәлләре белән чиратлаштыручы агент үрнәге.' } },
  { id: 'self-rag', lec: '11',
    term: { en: 'Self-RAG', ru: 'Self-RAG', tt: 'Self-RAG' },
    def: { en: 'RAG that decides when to retrieve and critiques its own generations.',
           ru: 'RAG, который решает, когда извлекать, и критикует собственные генерации.',
           tt: 'Кайчан табарга икәнен хәл итеп, үз генерацияләрен тәнкыйтьләүче RAG.' } },

  // ── L12 · Advanced RAG · Multimodal ──────────────────────────────────────
  { id: 'multi-hop', lec: '12',
    term: { en: 'Multi-hop retrieval', ru: 'Многошаговое извлечение', tt: 'Күп адымлы табу' },
    def: { en: 'Answering questions that require chaining evidence across several documents.',
           ru: 'Ответы на вопросы, требующие сцепления доказательств из нескольких документов.',
           tt: 'Берничә документтан дәлилләрне чылбырлауны таләп иткән сорауларга җавап бирү.' } },
  { id: 'graphrag', lec: '12',
    term: { en: 'GraphRAG', ru: 'GraphRAG', tt: 'GraphRAG' },
    def: { en: 'Building a knowledge graph over a corpus to retrieve and reason over connected facts.',
           ru: 'Построение графа знаний по корпусу для извлечения и рассуждения по связанным фактам.',
           tt: 'Бәйле фактлар буенча табу һәм фикерләү өчен корпус өстендә белем графы төзү.' } },
  { id: 'clip', lec: '12',
    term: { en: 'CLIP', ru: 'CLIP', tt: 'CLIP' },
    def: { en: 'A model aligning images and text in one embedding space for cross-modal search.',
           ru: 'Модель, выравнивающая изображения и текст в одном пространстве эмбеддингов для кроссмодального поиска.',
           tt: 'Кросс-модаль эзләү өчен рәсемнәрне һәм текстны бер эмбеддинг киңлегендә тигезләүче модель.' } },
  { id: 'colpali', lec: '12',
    term: { en: 'ColPali', ru: 'ColPali', tt: 'ColPali' },
    def: { en: 'A late-interaction retriever that searches document page-images directly, skipping OCR.',
           ru: 'Поисковик позднего взаимодействия, ищущий прямо по изображениям страниц, минуя OCR.',
           tt: 'OCRны узып, бит-рәсемнәр буенча туры эзләүче соңгы тәэсир табучысы.' } },
  { id: 'raptor', lec: '12',
    term: { en: 'RAPTOR', ru: 'RAPTOR', tt: 'RAPTOR' },
    def: { en: 'Recursive summary trees that let retrieval pick the right level of abstraction.',
           ru: 'Рекурсивные деревья резюме, позволяющие извлечению выбрать нужный уровень абстракции.',
           tt: 'Табуга кирәкле абстракция дәрәҗәсен сайларга мөмкинлек бирүче рекурсив йомгак агачлары.' } },

  // ── L13 · Hard Negative Mining ───────────────────────────────────────────
  { id: 'hard-negative', lec: '13',
    term: { en: 'Hard negative', ru: 'Трудный негатив', tt: 'Авыр негатив' },
    def: { en: 'A non-relevant document that looks deceptively similar — the most informative to train on.',
           ru: 'Нерелевантный документ, обманчиво похожий на релевантный — самый информативный для обучения.',
           tt: 'Ялгыш охшаш күренгән релевант булмаган документ — өйрәтү өчен иң мәгълүматлы.' } },
  { id: 'in-batch-negatives', lec: '13',
    term: { en: 'In-batch negatives', ru: 'Внутрибатчевые негативы', tt: 'Батч эчендәге негативлар' },
    def: { en: 'Reusing the other examples in a training batch as negatives for cheap contrast.',
           ru: 'Повторное использование прочих примеров батча как негативов для дешёвого контраста.',
           tt: 'Арзан контраст өчен батчтагы башка мисалларны негатив итеп куллану.' } },
  { id: 'negative-sampling', lec: '13',
    term: { en: 'Negative sampling', ru: 'Сэмплирование негативов', tt: 'Негатив сайлау' },
    def: { en: 'Choosing which non-relevant items to contrast against during training.',
           ru: 'Выбор нерелевантных элементов для контраста при обучении.',
           tt: 'Өйрәтү вакытында нинди релевант булмаган элементларга каршы куярга сайлау.' } },

  // ── L14 · Advanced Query Rewriting ───────────────────────────────────────
  { id: 'query-expansion', lec: '14',
    term: { en: 'Query expansion', ru: 'Расширение запроса', tt: 'Сорауны киңәйтү' },
    def: { en: 'Adding related terms to a query to catch more of the relevant documents.',
           ru: 'Добавление связанных термов к запросу, чтобы охватить больше релевантных документов.',
           tt: 'Күбрәк релевант документны эләктерү өчен сорауга бәйле термнар өстәү.' } },
  { id: 'step-back-prompting', lec: '14',
    term: { en: 'Step-back prompting', ru: 'Step-back промптинг', tt: 'Step-back промптинг' },
    def: { en: 'Asking a more general question first to retrieve grounding for a specific one.',
           ru: 'Сначала задать более общий вопрос, чтобы извлечь основу для конкретного.',
           tt: 'Конкрет сорау өчен нигез табарга башта гомумирәк сорау бирү.' } },
  { id: 'query-decomposition', lec: '14',
    term: { en: 'Query decomposition', ru: 'Декомпозиция запроса', tt: 'Сорауны таркату' },
    def: { en: 'Breaking a complex query into simpler sub-queries answered separately.',
           ru: 'Разбиение сложного запроса на более простые подзапросы, решаемые по отдельности.',
           tt: 'Катлаулы сорауны аерым җавап бирелә торган гадирәк асорауларга бүлү.' } },

  // ── L15 · BERT & other Transformers ──────────────────────────────────────
  { id: 'masked-language-modeling', lec: '15',
    term: { en: 'Masked language modeling', ru: 'Маскированное языковое моделирование', tt: 'Маскалы тел моделләштерүе' },
    def: { en: "BERT's objective: predict hidden tokens from their two-sided context.",
           ru: 'Задача BERT: предсказать скрытые токены по двустороннему контексту.',
           tt: 'BERT максаты: яшерен токеннарны ике яклы контекст буенча фаразлау.' } },
  { id: 'fine-tuning', lec: '15',
    term: { en: 'Fine-tuning', ru: 'Дообучение (fine-tuning)', tt: 'Өстәмә өйрәтү (fine-tuning)' },
    def: { en: 'Adapting a pretrained model to a task with further training on task-specific data.',
           ru: 'Адаптация предобученной модели к задаче дообучением на данных этой задачи.',
           tt: 'Алдан өйрәтелгән моделне бурыч мәгълүматында өстәмә өйрәтеп бурычка яраклаштыру.' } },
  { id: 'rlhf', lec: '15',
    term: { en: 'RLHF', ru: 'RLHF', tt: 'RLHF' },
    def: { en: 'Reinforcement Learning from Human Feedback — aligning a model to human preferences.',
           ru: 'Обучение с подкреплением на человеческой обратной связи — согласование модели с предпочтениями людей.',
           tt: 'Кеше кире бәйләнешеннән ныгытып өйрәтү — моделне кеше өстенлекләренә туры китерү.' } },
  { id: 'attention-head', lec: '15',
    term: { en: 'Attention head', ru: 'Голова внимания', tt: 'Игътибар башы' },
    def: { en: 'One of several parallel attention functions, each learning a different relation.',
           ru: 'Одна из нескольких параллельных функций внимания, каждая учит своё отношение.',
           tt: 'Берничә параллель игътибар функциясенең берсе; һәрберсе үз мөнәсәбәтен өйрәнә.' } },

  // ── L16 · Late Chunking ──────────────────────────────────────────────────
  { id: 'late-chunking', lec: '16',
    term: { en: 'Late chunking', ru: 'Позднее чанкование', tt: 'Соңгы кисәкләү' },
    def: { en: 'Embedding the whole document first, then pooling into chunks so each keeps full context.',
           ru: 'Сначала эмбеддинг всего документа, затем пулинг в чанки — каждый сохраняет полный контекст.',
           tt: 'Башта тулы документны эмбеддлап, аннары кисәкләргә пулинглау — һәрбер кисәк тулы контекстны саклый.' } },

  // ── L17 · Shannon Entropy ────────────────────────────────────────────────
  { id: 'entropy', lec: '17',
    term: { en: 'Entropy', ru: 'Энтропия', tt: 'Энтропия' },
    def: { en: 'The average surprise (in bits) of a source — how unpredictable its symbols are.',
           ru: 'Средняя неожиданность источника (в битах) — насколько непредсказуемы его символы.',
           tt: 'Чыганакның уртача көтелмәгәнлеге (битларда) — символлары никадәр фаразланмый.' } },
  { id: 'cross-entropy', lec: '17',
    term: { en: 'Cross-entropy', ru: 'Кросс-энтропия', tt: 'Кросс-энтропия' },
    def: { en: 'The average bits needed to encode data from one distribution using another.',
           ru: 'Среднее число битов для кодирования данных одного распределения через другое.',
           tt: 'Бер таралыш мәгълүматын икенчесе аша кодлау өчен кирәкле уртача бит саны.' } },
  { id: 'perplexity', lec: '17',
    term: { en: 'Perplexity', ru: 'Перплексия', tt: 'Перплексия' },
    def: { en: "A language model's uncertainty — the exponential of its cross-entropy.",
           ru: 'Неопределённость языковой модели — экспонента её кросс-энтропии.',
           tt: 'Тел моделенең билгесезлеге — аның кросс-энтропиясенең экспонентасы.' } },

  // ── L18 · The Curved Map · Geometry of Meaning ───────────────────────────
  { id: 'anisotropy', lec: '18',
    term: { en: 'Anisotropy', ru: 'Анизотропия', tt: 'Анизотропия' },
    def: { en: 'The tendency of embeddings to crowd into a narrow cone, distorting cosine similarity.',
           ru: 'Склонность эмбеддингов скучиваться в узкий конус, искажая косинусную близость.',
           tt: 'Эмбеддингларның тар конуска җыелу омтылышы; косинус охшашлыгын бозгалый.' } },
  { id: 'hubness', lec: '18',
    term: { en: 'Hubness', ru: 'Хабность (hubness)', tt: 'Хаблылык (hubness)' },
    def: { en: 'In high dimensions, a few points become nearest neighbours to disproportionately many others.',
           ru: 'В высоких размерностях немногие точки становятся ближайшими соседями непропорционально многим.',
           tt: 'Югары үлчәмнәрдә берничә нокта диспропорциональ рәвештә күпләргә иң якын күрше булып китә.' } },
];

// UI strings for the glossary page (trilingual, non-gated).
export const glossaryMeta = {
  intro: {
    en: 'Every core concept in the course — a one-line definition and the lecture where it is taught. A study and revision index.',
    ru: 'Каждое ключевое понятие курса — определение в одну строку и лекция, где оно преподаётся. Индекс для учёбы и повторения.',
    tt: 'Курсның һәр төп төшенчәсе — бер юллык билгеләмә һәм ул укытыла торган лекция. Уку һәм кабатлау индексы.',
  },
  ui: {
    search: { en: 'Search a term or definition…', ru: 'Поиск по термину или определению…', tt: 'Термин яки билгеләмә буенча эзләү…' },
    all: { en: 'All lectures', ru: 'Все лекции', tt: 'Барлык лекцияләр' },
    of: { en: 'of', ru: 'из', tt: 'дан' },
    count: { en: 'terms', ru: 'терминов', tt: 'термин' },
    reset: { en: 'reset', ru: 'сбросить', tt: 'ташлау' },
    none: { en: 'No terms match — try another word.', ru: 'Ничего не найдено — попробуйте другое слово.', tt: 'Туры килгәне юк — башка сүз кулланып карагыз.' },
    taughtIn: { en: 'Taught in', ru: 'Преподаётся в', tt: 'Укытыла' },
    filterByLecture: { en: 'Filter by lecture', ru: 'Фильтр по лекции', tt: 'Лекция буенча фильтр' },
  },
};

// Lecture ids that actually carry terms, in course order (for the filter chips).
export const lecturesWithTerms = [...new Set(terms.map((t) => t.lec))].sort();
