// midterm.js — the Midterm prep question bank, rendered by /midterm (interactive,
// filterable). Data-driven: add a question = append one object to `questions`.
// EN canonical + RU; TT falls back tt → ru → en (this module is NOT scanned by the
// i18n-coverage gate, so en+ru is the model — like assignments.js).
//
// Each question:
//   { id, lectures: ['03', ...], type: 'compute' | 'concept', q:{en,ru}, a:{en,ru} }
//   - lectures: course.json lecture ids ('01'..'08') — drives the filter chips AND the
//     "where to revise" deep-links into /book/<id>. Multiple ids = a cross-cutting topic.
//   - type: 'compute' = a by-hand calculation (🖊, the course's signature skill);
//           'concept' = explain / contrast / why (💡).
//   - a: the short answer/hint revealed on click (a study nudge, not a full key).

export const midtermMeta = {
  title: { en: 'Midterm — topics & prep questions', ru: 'Мидтерм — темы и вопросы для подготовки', tt: 'Аралык имтиханы — темалар һәм әзерлек сораулары' },
  intro: {
    en: 'The midterm (Week 4 · Wed Jun 24, 20%) covers Lectures L1–L8. This is the full topic bank — filter by lecture or by question type, click a question to reveal a short answer, and follow “revise in” to the lecture chapter. About 40% are by-hand calculations (🖊) — the skill the course drills — and 60% are conceptual (💡).',
    ru: 'Мидтерм (Неделя 4 · Ср 24 июня, 20%) покрывает лекции L1–L8. Это полный банк тем — фильтруй по лекции или типу вопроса, кликни вопрос, чтобы раскрыть краткий ответ, и переходи по «повторить в» к главе лекции. Примерно 40% — расчёты руками (🖊), тот навык, что тренирует курс, и 60% — концептуальные (💡).',
    tt: 'Аралык имтиханы (4 атна · Чәр 24 июнь, 20%) L1–L8 лекцияләрен үз эченә ала. Бу — тулы темалар банкы: лекция яки сорау төре буенча фильтрла, сорауга басып кыска җавапны ач, «кабатларга» сылтамасы буенча лекция бүлегенә күч. Якынча 40% — кул белән исәпләүләр (🖊), 60% — концептуаль (💡).',
  },
  // small page-chrome strings (not gated)
  legend: {
    compute: { en: 'by-hand calculation', ru: 'расчёт руками', tt: 'кул белән исәпләү' },
    concept: { en: 'concept / explain', ru: 'концепт / объяснить', tt: 'концепт / аңлат' },
  },
  page: {
    all: { en: 'All', ru: 'Все', tt: 'Барысы' },
    filterLec: { en: 'Filter by lecture', ru: 'Фильтр по лекции', tt: 'Лекция буенча фильтр' },
    filterType: { en: 'Filter by type', ru: 'Фильтр по типу', tt: 'Төр буенча фильтр' },
    show: { en: 'show answer', ru: 'показать ответ', tt: 'җавапны күрсәт' },
    revise: { en: 'revise in', ru: 'повторить в', tt: 'кабатларга' },
    counter: { en: 'questions shown', ru: 'вопросов показано', tt: 'сорау күрсәтелде' },
    none: { en: 'No questions match this filter.', ru: 'Под этот фильтр нет вопросов.', tt: 'Бу фильтрга сорау юк.' },
  },
};

export const questions = [
  // ───────────────────────── L1 · The Lost Record ─────────────────────────
  { id: 'l1-cascade', lectures: ['01'], type: 'concept',
    q: { en: 'Why is search done in two stages (retrieve → rank) instead of scoring the whole corpus with the best model?', ru: 'Почему поиск делают в два этапа (retrieve → rank), а не скорят весь корпус лучшей моделью?' },
    a: { en: 'The best scorer (a cross-encoder) costs O(N) per query and cannot scale; you retrieve cheap-and-wide, then rank careful-and-few.', ru: 'Лучший скорер (cross-encoder) стоит O(N) на запрос и не масштабируется; находим дёшево-вширь, затем судим точно-немногих.' } },
  { id: 'l1-iceberg', lectures: ['01'], type: 'concept',
    q: { en: '“ML code ≈ 5% of the iceberg.” Name three of the larger hidden components of a production search system.', ru: '«ML-код ≈ 5% айсберга». Назови три крупных скрытых компонента продакшн-поиска.' },
    a: { en: 'Config, data collection, serving infrastructure, monitoring, feature extraction — the engineering around the model dwarfs the model code.', ru: 'Config, сбор данных, serving-инфраструктура, мониторинг, извлечение признаков — инженерия вокруг модели много больше самого ML-кода.' } },
  { id: 'l1-lexgap', lectures: ['01'], type: 'concept',
    q: { en: 'What is the lexical gap? Give an example of a relevant document that keyword search misses.', ru: 'Что такое lexical gap? Приведи пример релевантного документа, который key-word-поиск пропускает.' },
    a: { en: 'Keyword matching cannot bridge synonyms/paraphrase: a query “couch” misses a relevant doc that only says “sofa”. BM25 has no notion of meaning.', ru: 'Поиск по словам не мостит синонимы/перефраз: запрос «couch» пропускает документ, где только «sofa». У BM25 нет понятия смысла.' } },
  { id: 'l1-flywheel', lectures: ['01'], type: 'concept',
    q: { en: 'Describe a feedback loop (“flywheel”) in a search system and how it becomes a rich-get-richer bias.', ru: 'Опиши feedback loop («flywheel») в поисковой системе и как он становится bias «rich-get-richer».' },
    a: { en: 'Clicks → logs → training → ranking → more clicks. Items shown high get clicked, get more training signal, get ranked higher — popularity compounds regardless of true relevance.', ru: 'Клики → логи → обучение → ранжирование → ещё клики. Что показано выше — кликают, оно получает больше сигнала и ранжируется выше; популярность накапливается независимо от истинной релевантности.' } },
  { id: 'l1-goodhart', lectures: ['01', '04'], type: 'concept',
    q: { en: 'State Goodhart’s law with a search-specific example.', ru: 'Сформулируй закон Гудхарта на примере из поиска.' },
    a: { en: 'When a measure becomes a target it stops being a good measure: optimizing CTR can tank real user satisfaction (clickbait ranks high).', ru: 'Когда метрика становится целью, она перестаёт быть хорошей метрикой: оптимизация CTR может топить реальное удовлетворение (кликбейт лезет наверх).' } },

  // ───────────────────────── L2 · First Contact ─────────────────────────
  { id: 'l2-bpe', lectures: ['02'], type: 'compute',
    q: { en: 'Run 2–3 BPE merge steps on a tiny vocabulary; show the merge ledger.', ru: 'Пройди 2–3 шага BPE-слияний на мини-словаре; покажи merge-ledger.' },
    a: { en: 'At each step merge the most frequent adjacent pair into a new symbol, update counts, repeat. The ledger lists each merge in order.', ru: 'На каждом шаге сливай самую частую соседнюю пару в новый символ, обновляй счётчики, повторяй. Ledger — список слияний по порядку.' } },
  { id: 'l2-subword', lectures: ['02'], type: 'concept',
    q: { en: 'Why do sub-word tokenizers (BPE/WordPiece) beat whole-word on OOV and morphology?', ru: 'Почему sub-word (BPE/WordPiece) бьёт whole-word на OOV и морфологии?' },
    a: { en: 'They share sub-units across words, so there is no UNK: a rare/inflected word decomposes into known pieces instead of falling out of the vocabulary.', ru: 'Они делят под-единицы между словами, поэтому нет UNK: редкое/словоформенное слово раскладывается на известные куски, а не выпадает из словаря.' } },
  { id: 'l2-zipf-heaps', lectures: ['02'], type: 'concept',
    q: { en: 'State Zipf’s and Heaps’ laws and what each implies for an IR system.', ru: 'Сформулируй законы Zipf и Heaps и что каждый значит для IR.' },
    a: { en: 'Zipf: frequency ∝ 1/rank (a few head terms, a long tail) → idf and stopwords matter. Heaps: vocabulary grows sub-linearly with corpus size → you keep seeing new terms.', ru: 'Zipf: частота ∝ 1/ранг (немного «головы», длинный хвост) → важны idf и стоп-слова. Heaps: словарь растёт сублинейно с размером корпуса → новые термы появляются постоянно.' } },
  { id: 'l2-cosine', lectures: ['02'], type: 'compute',
    q: { en: 'Compute the cosine similarity of two short vectors by hand; then say why text uses cosine rather than Euclidean.', ru: 'Посчитай cosine двух коротких векторов руками; объясни, почему для текста косинус, а не евклид.' },
    a: { en: 'cos = (a·b)/(‖a‖‖b‖). Cosine is length-invariant, so a long document is not penalized just for having more words — only direction (topic mix) matters.', ru: 'cos = (a·b)/(‖a‖‖b‖). Косинус инвариантен к длине: длинный документ не штрафуется за больший объём — важно только направление (смесь тем).' } },
  { id: 'l2-cos-vs-euclid', lectures: ['02'], type: 'concept',
    q: { en: 'Two vectors share a direction but differ in magnitude (e.g. (1,1) vs (10,10)). What does each measure say?', ru: 'Два вектора одного направления, но разной длины (напр. (1,1) и (10,10)). Что говорит каждая мера?' },
    a: { en: 'Cosine is identical (same angle); Euclidean distance is large. For text we usually want the angle, not the length.', ru: 'Косинус одинаков (тот же угол); евклидово расстояние велико. Для текста обычно нужен угол, а не длина.' } },
  { id: 'l2-curse', lectures: ['02'], type: 'concept',
    q: { en: 'The curse of dimensionality: what are distance concentration, hubness, and anisotropy, and how do they hurt nearest-neighbour search?', ru: 'Проклятие размерности: что такое концентрация расстояний, hubness и anisotropy и чем они вредят kNN-поиску?' },
    a: { en: 'Concentration: all pairwise distances become ~equal (no contrast). Hubness: a few points appear in everyone’s neighbour list. Anisotropy: vectors crowd into a narrow cone, so everything looks similar.', ru: 'Концентрация: все попарные расстояния становятся ~равны (нет контраста). Hubness: немногие точки попадают в соседи ко всем. Anisotropy: вектора жмутся в узкий конус, и всё кажется похожим.' } },

  // ───────────────────────── L3 · The Star Catalog ─────────────────────────
  { id: 'l3-invindex', lectures: ['03'], type: 'concept',
    q: { en: 'Why an inverted index instead of a linear scan? What does a postings list store?', ru: 'Зачем инвертированный индекс вместо линейного скана? Что хранит постинг-лист?' },
    a: { en: 'It maps term → [(doc_id, tf), …] so you jump straight to the docs containing a query term instead of scanning every document; postings also carry doc lengths/positions.', ru: 'Он отображает терм → [(doc_id, tf), …], так что прыгаешь сразу к документам с термом запроса, не обходя все; постинги хранят и длины/позиции.' } },
  { id: 'l3-bm25-compute', lectures: ['03'], type: 'compute',
    q: { en: 'Compute a BM25 term score given tf, df, N, |d|, avgdl, with k₁=1.5, b=0.75.', ru: 'Посчитай вклад терма BM25 при заданных tf, df, N, |d|, avgdl, k₁=1.5, b=0.75.' },
    a: { en: 'score = idf · tf·(k₁+1) / (tf + k₁·(1 − b + b·|d|/avgdl)), with smoothed idf = ln(1 + (N−df+0.5)/(df+0.5)).', ru: 'score = idf · tf·(k₁+1) / (tf + k₁·(1 − b + b·|d|/avgdl)), сглаженный idf = ln(1 + (N−df+0.5)/(df+0.5)).' } },
  { id: 'l3-k1-b', lectures: ['03'], type: 'concept',
    q: { en: 'In BM25, what do k₁ and b control, and what happens at b=0 and b=1?', ru: 'Что регулируют k₁ и b в BM25; что на краях b=0 и b=1?' },
    a: { en: 'k₁ sets term-frequency saturation (how fast extra occurrences stop helping); b sets document-length normalization. b=0 → no length normalization; b=1 → full normalization by |d|/avgdl.', ru: 'k₁ задаёт насыщение по частоте терма (как быстро лишние вхождения перестают помогать); b — нормировку длины документа. b=0 → нет нормировки; b=1 → полная по |d|/avgdl.' } },
  { id: 'l3-tfidf-vs-bm25', lectures: ['03'], type: 'compute',
    q: { en: 'Compute TF-IDF weights and rank two docs; contrast with BM25 on the same query — where do they diverge and why?', ru: 'Посчитай веса TF-IDF и отранжируй два документа; сравни с BM25 — где и почему расходятся?' },
    a: { en: 'TF-IDF grows linearly in tf and has no length normalization; BM25 saturates tf and normalizes length, so it down-weights term-spammy and long docs that TF-IDF over-rewards.', ru: 'TF-IDF растёт линейно по tf и без нормировки длины; BM25 насыщает tf и нормирует длину, поэтому занижает спамные по терму и длинные документы, которые TF-IDF переоценивает.' } },
  { id: 'l3-rrf', lectures: ['03'], type: 'compute',
    q: { en: 'RRF (k=60): fuse two ranked lists by hand; show how a consensus doc beats a list’s #1 that the other list ranks last.', ru: 'RRF (k=60): слей два списка руками; покажи, как консенсусный документ обходит чужого «#1», которого второй ставит последним.' },
    a: { en: 'score(d) = Σ 1/(60 + rankᵢ(d)). A doc ranked 2nd & 1st beats a doc ranked 1st & last, because two solid ranks sum higher than one great + one terrible.', ru: 'score(d) = Σ 1/(60 + rankᵢ(d)). Документ с рангами 2 и 1 обходит документ с рангами 1 и последний: два средних ранга в сумме больше, чем один отличный + один ужасный.' } },
  { id: 'l3-wand', lectures: ['03'], type: 'concept',
    q: { en: 'What do WAND / BlockMax-WAND solve, and how (one sentence)?', ru: 'Что решают WAND / BlockMax-WAND и как (одно предложение)?' },
    a: { en: 'Fast top-k: per-term (or per-block) max-score upper bounds let you skip documents/blocks that cannot beat the current k-th-best score, so retrieval is effectively sublinear.', ru: 'Быстрый top-k: верхние границы оценки по терму (или блоку) позволяют пропускать документы/блоки, что не побьют текущий k-й лучший балл — поиск становится почти сублинейным.' } },
  { id: 'l3-rrf-why', lectures: ['03', '08'], type: 'concept',
    q: { en: 'RRF is rank-based — why is that more robust than mixing raw scores across rankers?', ru: 'RRF работает по рангам — почему это устойчивее, чем смешивать «сырые» оценки разных ранкеров?' },
    a: { en: 'Different rankers’ score scales are incomparable (BM25 vs cosine vs a logit), so a raw sum is dominated by whichever scale is bigger; ranks are calibration-free.', ru: 'Шкалы оценок разных ранкеров несравнимы (BM25 vs косинус vs логит), и сырая сумма перекошена в сторону большей шкалы; рангам калибровка не нужна.' } },

  // ───────────────────────── L4 · The Proving Grounds ─────────────────────────
  { id: 'l4-graded', lectures: ['04'], type: 'concept',
    q: { en: 'Binary vs graded relevance — which metrics need graded qrels, and why?', ru: 'Binary vs graded релевантность — каким метрикам нужны градуированные qrels и почему?' },
    a: { en: 'nDCG needs graded judgments (its gain is 2^rel−1, so it distinguishes “highly” from “mildly” relevant); Precision/Recall/MRR/MAP work on binary relevance.', ru: 'nDCG нужны градуированные оценки (gain = 2^rel−1, он различает «очень» и «слегка» релевантное); Precision/Recall/MRR/MAP работают на бинарной.' } },
  { id: 'l4-pr-mrr', lectures: ['04'], type: 'compute',
    q: { en: 'Compute Precision@k, Recall@k and MRR for a given ranking and qrels.', ru: 'Посчитай Precision@k, Recall@k и MRR для данного ранжирования и qrels.' },
    a: { en: 'P@k = (#relevant in top-k)/k; R@k = (#relevant in top-k)/(total relevant); MRR = mean over queries of 1/(rank of the first relevant doc).', ru: 'P@k = (#релевантных в top-k)/k; R@k = (#релевантных в top-k)/(всего релевантных); MRR = среднее по запросам от 1/(ранг первого релевантного).' } },
  { id: 'l4-ndcg', lectures: ['04'], type: 'compute',
    q: { en: 'Compute nDCG@10 by hand: DCG (gain 2^rel−1, discount log₂(i+1)) → IDCG → ratio.', ru: 'Посчитай nDCG@10 руками: DCG (gain 2^rel−1, дисконт log₂(i+1)) → IDCG → отношение.' },
    a: { en: 'DCG = Σᵢ (2^relᵢ−1)/log₂(i+1); IDCG = the same on the ideal (sorted-by-rel) ranking; nDCG = DCG/IDCG ∈ [0,1].', ru: 'DCG = Σᵢ (2^relᵢ−1)/log₂(i+1); IDCG = то же на идеальном (отсортированном по rel) ранжировании; nDCG = DCG/IDCG ∈ [0,1].' } },
  { id: 'l4-map', lectures: ['04'], type: 'compute',
    q: { en: 'Compute Average Precision (and MAP) for a query: average the precision values at each relevant-doc rank.', ru: 'Посчитай Average Precision (и MAP) для запроса: усредни precision на каждом ранге релевантного документа.' },
    a: { en: 'AP = (1/R) Σ over relevant ranks r of P@r; MAP = mean of AP across queries. It rewards putting relevant docs early.', ru: 'AP = (1/R) Σ по рангам релевантных r от P@r; MAP = среднее AP по запросам. Награждает раннее размещение релевантных.' } },
  { id: 'l4-significance', lectures: ['04'], type: 'concept',
    q: { en: 'You beat BM25 by +2% nDCG — is it real? Which test, what does p mean, and the multiple-comparisons caveat?', ru: 'Ты обошёл BM25 на +2% nDCG — это реально? Какой тест, что значит p, и оговорка про multiple comparisons?' },
    a: { en: 'Use a paired test on per-query scores (t-test / Wilcoxon signed-rank). p = probability of a difference this large if the systems were equal. Testing many variants inflates false positives → correct for it.', ru: 'Парный тест по per-query оценкам (t-test / Wilcoxon). p = вероятность такой разницы при равных системах. Проверка многих вариантов раздувает ложные срабатывания → нужна поправка.' } },
  { id: 'l4-online', lectures: ['04'], type: 'concept',
    q: { en: 'Why do offline metrics + click logs mislead (position bias), and what does an A/B test add?', ru: 'Почему оффлайн-метрики и клик-логи вводят в заблуждение (position bias) и что добавляет A/B?' },
    a: { en: 'Clicks are biased by rank (top results get clicked because they are on top, not because they are best), so logs are not ground truth; an A/B test measures real user behaviour under each system.', ru: 'Клики смещены рангом (верх кликают потому что он сверху, а не потому что лучший), логи — не истина; A/B измеряет реальное поведение пользователей под каждой системой.' } },

  // ───────────────────────── L5 · The Map of Meaning ─────────────────────────
  { id: 'l5-lexgap', lectures: ['05'], type: 'concept',
    q: { en: 'Why do one-hot / BM25 representations make every pair of distinct words equidistant?', ru: 'Почему one-hot / BM25 делают любые два разных слова равноудалёнными?' },
    a: { en: 'One-hot vectors are orthogonal and share no dimensions, so every distinct pair has the same (maximal) distance — there is no notion of “near in meaning”.', ru: 'One-hot вектора ортогональны и не имеют общих измерений, поэтому любая пара разных слов на одинаковом (максимальном) расстоянии — нет понятия «близко по смыслу».' } },
  { id: 'l5-skipgram', lectures: ['05'], type: 'concept',
    q: { en: 'Write the skip-gram objective; why is the full softmax over the vocabulary intractable, and how does negative sampling fix it?', ru: 'Запиши skip-gram objective; почему полный softmax по словарю неподъёмен и как помогает negative sampling?' },
    a: { en: 'Maximize P(context | center) via softmax over |V|; that denominator sums over the whole vocabulary every step. Negative sampling replaces it with a few sampled “wrong” contexts in a logistic loss.', ru: 'Максимизируем P(контекст | центр) через softmax по |V|; знаменатель суммирует по всему словарю каждый шаг. Negative sampling заменяет его несколькими сэмплированными «неверными» контекстами в логистическом лоссе.' } },
  { id: 'l5-analogy', lectures: ['05'], type: 'compute',
    q: { en: 'Verify the analogy king − man + woman ≈ queen using cosine on given vectors.', ru: 'Проверь аналогию king − man + woman ≈ queen через cosine на данных векторах.' },
    a: { en: 'Compute v = king − man + woman, then find the word whose vector has the highest cosine with v (excluding the inputs) — it should be queen.', ru: 'Посчитай v = king − man + woman, затем найди слово с наибольшим косинусом к v (исключая входы) — должно быть queen.' } },
  { id: 'l5-pca', lectures: ['05'], type: 'compute',
    q: { en: 'PCA: from a covariance matrix → eigenvectors → project to 2D; state the variance the top-2 axes keep (≈37.7% in the lecture).', ru: 'PCA: ковариация → собственные вектора → проекция в 2D; назови долю дисперсии топ-2 осей (≈37.7% в лекции).' },
    a: { en: 'Eigen-decompose the covariance; project onto the top-2 eigenvectors. Variance explained = (λ₁+λ₂)/Σλ — in the lecture two axes keep ≈37.7%, so much is lost.', ru: 'Разложи ковариацию; спроецируй на топ-2 собственных вектора. Объяснённая дисперсия = (λ₁+λ₂)/Σλ — в лекции две оси держат ≈37.7%, многое теряется.' } },
  { id: 'l5-pca-tsne', lectures: ['05'], type: 'concept',
    q: { en: 'PCA vs t-SNE: what does each preserve, and why can a t-SNE map mislead about global distances and cluster sizes?', ru: 'PCA vs t-SNE: что сохраняет каждый и почему t-SNE-карта может врать про глобальные расстояния и размеры кластеров?' },
    a: { en: 'PCA is linear and preserves global variance/distances; t-SNE preserves local neighbourhoods only — cluster sizes, gaps and between-cluster distances on a t-SNE plot are not meaningful.', ru: 'PCA линеен и сохраняет глобальную дисперсию/расстояния; t-SNE сохраняет лишь локальные соседства — размеры кластеров, зазоры и межкластерные расстояния на t-SNE не значимы.' } },
  { id: 'l5-static-limit', lectures: ['05'], type: 'concept',
    q: { en: 'Why is a static word embedding insufficient for “bank” (river vs money)? (the bridge to L6)', ru: 'Почему статического эмбеддинга мало для «bank» (река/деньги)? (мост в L6)' },
    a: { en: 'A static embedding gives one vector per word regardless of context, so the two senses of “bank” are forced into a single averaged point — contextual embeddings (L6) fix this.', ru: 'Статический эмбеддинг даёт один вектор на слово вне контекста, поэтому два смысла «bank» сливаются в одну усреднённую точку — это чинят контекстные эмбеддинги (L6).' } },

  // ───────────────────────── L6 · The Council of Attention ─────────────────────────
  { id: 'l6-polysemy', lectures: ['06'], type: 'concept',
    q: { en: 'Polysemy: why can’t a static vector (L5) split the two senses of “bank”, and how do contextual embeddings fix it?', ru: 'Полисемия: почему статический вектор (L5) не разделяет смыслы «bank» и как чинят контекстные эмбеддинги?' },
    a: { en: 'A static vector is the same in every sentence; a contextual model lets the token attend to its neighbours, so “river bank” and “money bank” get different vectors.', ru: 'Статический вектор одинаков в любом предложении; контекстная модель даёт токену смотреть на соседей, и «river bank» и «money bank» получают разные вектора.' } },
  { id: 'l6-attention-compute', lectures: ['06'], type: 'compute',
    q: { en: 'Compute one step of scaled dot-product attention on toy Q, K, V: softmax(QKᵀ/√dₖ)·V.', ru: 'Посчитай один шаг scaled dot-product attention на toy Q, K, V: softmax(QKᵀ/√dₖ)·V.' },
    a: { en: 'Scores = QKᵀ/√dₖ; weights = softmax over each row; output = weights·V (a convex mix of value vectors).', ru: 'Scores = QKᵀ/√dₖ; веса = softmax по каждой строке; выход = веса·V (выпуклая смесь value-векторов).' } },
  { id: 'l6-sqrt-dk', lectures: ['06'], type: 'concept',
    q: { en: 'Why do we divide by √dₖ in attention?', ru: 'Почему делим на √dₖ в attention?' },
    a: { en: 'The dot product’s variance grows with dₖ; large scores push softmax into a near one-hot regime with vanishing gradients. Dividing by √dₖ keeps the scores at a stable scale.', ru: 'Дисперсия скалярного произведения растёт с dₖ; большие баллы загоняют softmax в почти one-hot режим с гаснущими градиентами. Деление на √dₖ держит масштаб стабильным.' } },
  { id: 'l6-block', lectures: ['06'], type: 'concept',
    q: { en: 'Assemble the Transformer block (multi-head → Add&Norm → FFN → Add&Norm); why residuals and LayerNorm?', ru: 'Собери Transformer-блок (multi-head → Add&Norm → FFN → Add&Norm); зачем residuals и LayerNorm?' },
    a: { en: 'Residual connections give gradients an identity path so deep stacks train; LayerNorm keeps activations at a stable scale per token. Both are what make many layers stackable.', ru: 'Residual-связи дают градиенту identity-путь, чтобы глубокие стопки обучались; LayerNorm держит активации на стабильном масштабе на токен. Вместе они позволяют стакать много слоёв.' } },
  { id: 'l6-infonce', lectures: ['06'], type: 'concept',
    q: { en: 'Write the InfoNCE / contrastive objective; why are in-batch negatives “free”, and why add hard negatives?', ru: 'Запиши InfoNCE / контрастив; почему in-batch негативы «бесплатны» и зачем hard negatives?' },
    a: { en: 'InfoNCE pulls a query to its positive and pushes it from negatives (a softmax over cosines). In-batch: the other examples in the batch serve as negatives at no extra cost; hard negatives (near-misses) teach fine discrimination.', ru: 'InfoNCE тянет запрос к позитиву и отталкивает от негативов (softmax по косинусам). In-batch: остальные примеры в батче — негативы без доп. затрат; hard negatives (почти-совпадения) учат тонкому различению.' } },
  { id: 'l6-anisotropy', lectures: ['06', '02'], type: 'concept',
    q: { en: 'What is anisotropy (callback L2), and how does contrastive training / whitening fix it?', ru: 'Что такое anisotropy (callback L2) и как её чинит контрастив / whitening?' },
    a: { en: 'Raw transformer embeddings crowd into a narrow cone, so cosines are all high and undiscriminative; contrastive training (or post-hoc whitening) spreads them to use the space.', ru: 'Сырые эмбеддинги трансформера жмутся в узкий конус, косинусы все высокие и неразличающие; контрастив (или whitening постфактум) раздвигает их, чтобы использовать пространство.' } },

  // ───────────────────────── L7 · Scouts and Judges ─────────────────────────
  { id: 'l7-bi-vs-cross', lectures: ['07'], type: 'concept',
    q: { en: 'Bi-encoder vs cross-encoder: independent vs joint encoding — which can precompute doc vectors, and why does that decide scalability?', ru: 'Bi- vs cross-encoder: независимое vs совместное кодирование — кто может предпосчитать вектора документов и почему это решает масштабируемость?' },
    a: { en: 'A bi-encoder encodes query and doc separately, so doc vectors are query-independent → precompute them offline and do cheap dot-products at query time. A cross-encoder scores the pair jointly (no precompute) → O(N) per query.', ru: 'Bi-encoder кодирует запрос и документ порознь, вектора документов не зависят от запроса → предпосчитываем офлайн, на запросе дешёвые dot-product’ы. Cross-encoder скорит пару совместно (без предпросчёта) → O(N) на запрос.' } },
  { id: 'l7-biencoder-compute', lectures: ['07'], type: 'compute',
    q: { en: 'Score a (query, doc) pair with a bi-encoder by hand (dot / cosine on toy vectors).', ru: 'Оцени пару (запрос, документ) bi-encoder’ом руками (dot / cosine на toy-векторах).' },
    a: { en: 'Encode q and d to vectors, then score = q·d (or cosine if L2-normalized). Both vectors live in one shared space, which is what makes the dot product meaningful.', ru: 'Закодируй q и d в вектора, затем score = q·d (или косинус при L2-нормировке). Оба вектора в одном общем пространстве — поэтому dot-product осмыслен.' } },
  { id: 'l7-cross-firststage', lectures: ['07'], type: 'concept',
    q: { en: 'Why is a cross-encoder more accurate but unusable as a first-stage retriever?', ru: 'Почему cross-encoder точнее, но не годится как первый этап?' },
    a: { en: 'Joint [CLS] q [SEP] d [SEP] → full cross-attention reads the pair together (high accuracy), but the score is a property of the pair, so nothing can be cached and it would cost one model pass per document.', ru: 'Совместный [CLS] q [SEP] d [SEP] → полное cross-attention читает пару вместе (точно), но оценка — свойство пары, кэшировать нечего, и это стоило бы прогон модели на каждый документ.' } },
  { id: 'l7-recall-ceiling', lectures: ['07'], type: 'concept',
    q: { en: 'In a cascade (retrieve top-k → rerank), why is the pipeline’s quality capped by the retriever’s recall@k?', ru: 'В каскаде (retrieve top-k → rerank) почему качество ограничено recall@k ретривера?' },
    a: { en: 'The reranker only reorders what it was given; a relevant doc the first stage never retrieved can never appear, so recall@k is a hard ceiling on the final result.', ru: 'Реранкер лишь переставляет данное ему; релевантный документ, который первый этап не извлёк, не появится — recall@k жёстко ограничивает итог.' } },
  { id: 'l7-rerank-depth', lectures: ['07'], type: 'concept',
    q: { en: 'Rerank depth k vs latency: what is the tradeoff, and when does going deeper stop helping?', ru: 'Глубина реранка k vs latency: компромисс и где углубление перестаёт помогать?' },
    a: { en: 'Cost grows linearly in k (k cross-encoder passes per query); quality rises only until the retriever’s recall is already captured — past that, deeper reranking buys latency, not nDCG.', ru: 'Стоимость растёт линейно по k (k прогонов cross-encoder на запрос); качество растёт лишь пока не собран recall ретривера — дальше глубина даёт latency, а не nDCG.' } },
  { id: 'l7-dense-not-free', lectures: ['07'], type: 'concept',
    q: { en: 'Refute “dense always beats BM25” using the zero-shot BEIR evidence.', ru: 'Опровергни «dense всегда бьёт BM25» данными zero-shot BEIR.' },
    a: { en: 'On out-of-domain BEIR, BM25 is a robust baseline that beats a vanilla dense retriever (e.g. BM25 ≈0.43 vs DPR ≈0.38); dense wins in-domain but degrades out-of-domain — hence hybrid/ColBERT (L8).', ru: 'На out-of-domain BEIR BM25 — устойчивый базлайн, обходящий обычный dense (напр. BM25 ≈0.43 vs DPR ≈0.38); dense выигрывает in-domain, но деградирует вне домена — отсюда hybrid/ColBERT (L8).' } },
  { id: 'l7-training', lectures: ['07'], type: 'concept',
    q: { en: 'Training a bi-encoder: what do in-batch negatives, hard negatives, and distillation from a cross-encoder each contribute?', ru: 'Обучение bi-encoder: что даёт каждое — in-batch негативы, hard negatives, дистилляция из cross-encoder?' },
    a: { en: 'In-batch negatives: cheap, plentiful contrast. Hard negatives: near-misses that teach fine discrimination. Distillation: a strong cross-encoder teacher gives soft, denoised relevance targets the bi-encoder learns from.', ru: 'In-batch негативы: дешёвый обильный контраст. Hard negatives: почти-совпадения для тонкого различения. Дистилляция: сильный cross-encoder-учитель даёт мягкие, обесшумленные таргеты, на которых учится bi-encoder.' } },

  // ───────────────────────── L8 · The Alliance ─────────────────────────
  { id: 'l8-late', lectures: ['08'], type: 'concept',
    q: { en: 'Late interaction: how does ColBERT differ from a bi-encoder (one vector) and a cross-encoder (full attention)? Where does it sit?', ru: 'Late interaction: чем ColBERT отличается от bi (один вектор) и cross (полное внимание) и где он «посередине»?' },
    a: { en: 'ColBERT keeps a vector per token (richer than one pooled vector), precomputes the doc tokens (unlike a cross-encoder), and interacts only at query time via MaxSim — the middle ground of cost vs detail.', ru: 'ColBERT хранит вектор на токен (богаче одного pooled-вектора), предпосчитывает токены документа (в отличие от cross-encoder) и взаимодействует только на запросе через MaxSim — середина между ценой и детальностью.' } },
  { id: 'l8-maxsim', lectures: ['08'], type: 'compute',
    q: { en: 'Compute MaxSim from a token-similarity matrix (row maxes → sum); show why one perfect token match (“bank” 0.98) still loses — the lexical trap.', ru: 'Посчитай MaxSim по матрице токен-сходств (макс по строке → сумма); покажи «лексическую ловушку»: один идеальный матч («bank» 0.98) всё равно проигрывает.' },
    a: { en: 'S = Σ_i max_j (E_qᵢ·E_dⱼ): take each query token’s best doc match, then sum. The relevant doc (0.90+0.50+0.95=2.35) beats the trap doc (0.20+0.98+0.12=1.30) — matching many tokens beats one loud match.', ru: 'S = Σ_i max_j (E_qᵢ·E_dⱼ): берём лучший матч документа для каждого токена запроса, затем сумма. Релевантный (0.90+0.50+0.95=2.35) бьёт ловушку (0.20+0.98+0.12=1.30) — много матчей важнее одного громкого.' } },
  { id: 'l8-splade', lectures: ['08'], type: 'concept',
    q: { en: 'SPLADE: how are the sparse weights produced (MLM logits → log(1+ReLU) → FLOPS), and why does it stay inverted-index compatible?', ru: 'SPLADE: как получаются разрежённые веса (MLM-логиты → log(1+ReLU) → FLOPS) и почему остаётся совместимым с инвертированным индексом?' },
    a: { en: 'The MLM head emits a logit per vocabulary word; log(1+ReLU) keeps positives and saturates them; ReLU + a FLOPS regularizer zero out most of |V|. The result is a sparse vector over the vocabulary that drops straight into postings.', ru: 'MLM-голова даёт логит на слово словаря; log(1+ReLU) оставляет положительные и насыщает их; ReLU + регуляризатор FLOPS обнуляют большую часть |V|. Итог — разрежённый вектор по словарю, который ложится в постинги.' } },
  { id: 'l8-splade-compute', lectures: ['08'], type: 'compute',
    q: { en: 'Compute a SPLADE term weight log(1+ReLU(logit)) and a sparse dot; identify which terms are expansion (not in the query).', ru: 'Посчитай вес SPLADE log(1+ReLU(logit)) и sparse-dot; укажи, какие термы — расширение (не из запроса).' },
    a: { en: 'w = log(1+ReLU(logit)) per term; sparse dot = Σ over shared terms of w_q·w_d. Terms with positive weight that were not typed in the query (e.g. “water”) are expansion terms.', ru: 'w = log(1+ReLU(logit)) на терм; sparse-dot = Σ по общим термам от w_q·w_d. Термы с положительным весом, которых не было в запросе (напр. «water»), — расширение.' } },
  { id: 'l8-hybrid', lectures: ['08'], type: 'concept',
    q: { en: 'Why are lexical and dense retrieval complementary (BEIR evidence), and when does hybrid NOT help?', ru: 'Почему лексика и dense комплементарны (BEIR) и когда гибрид НЕ помогает?' },
    a: { en: 'Lexical catches exact words, dense catches paraphrase — they fail on different queries, so fusing covers more. Hybrid hurts when one ranker is far weaker, or when score scales aren’t calibrated before combining.', ru: 'Лексика ловит точные слова, dense — перефраз; они ошибаются на разных запросах, слияние покрывает больше. Гибрид вредит, когда один ранкер сильно слабее или шкалы оценок не калиброваны перед смешиванием.' } },
  { id: 'l8-rrf-hybrid', lectures: ['08', '03'], type: 'compute',
    q: { en: 'Hybrid RRF by hand: fuse a sparse and a dense ranking and show the consensus doc winning.', ru: 'Гибрид RRF руками: слей разрежённый и плотный список и покажи победу консенсуса.' },
    a: { en: 'Same RRF as L3, now over neural partners: score(d)=Σ 1/(60+rank). The doc both rankers place near the top wins; a doc one ranker loves but the other buries falls.', ru: 'Тот же RRF, что в L3, но над нейронными партнёрами: score(d)=Σ 1/(60+rank). Документ, который оба ставят высоко, выигрывает; тот, кого один любит, а другой хоронит, падает.' } },
  { id: 'l8-ltr-compute', lectures: ['08'], type: 'compute',
    q: { en: 'Learning to Rank: compute RankNet P=σ(sᵢ−sⱼ) and LambdaRank λ = gradient·ΔnDCG; explain pointwise vs pairwise vs listwise.', ru: 'Learning to Rank: посчитай RankNet P=σ(sᵢ−sⱼ) и LambdaRank λ = grad·ΔnDCG; объясни pointwise vs pairwise vs listwise.' },
    a: { en: 'RankNet: P(i≻j)=σ(sᵢ−sⱼ), cross-entropy cost. LambdaRank scales the gradient by |ΔnDCG| (how much swapping i,j moves the metric). Pointwise scores each doc alone, pairwise learns orderings of pairs, listwise optimizes the whole list.', ru: 'RankNet: P(i≻j)=σ(sᵢ−sⱼ), кросс-энтропия. LambdaRank масштабирует градиент на |ΔnDCG| (насколько обмен i,j двигает метрику). Pointwise скорит документ отдельно, pairwise учит порядок пар, listwise оптимизирует весь список.' } },
  { id: 'l8-ltr-line', lectures: ['08'], type: 'concept',
    q: { en: 'Trace RankNet → LambdaRank → LambdaMART: what does each step add?', ru: 'Проследи RankNet → LambdaRank → LambdaMART: что добавляет каждый шаг?' },
    a: { en: 'RankNet: a pairwise probability from score differences. LambdaRank: weight each pair’s gradient by ΔnDCG so swaps that matter pull harder. LambdaMART: put those λ-gradients inside gradient-boosted trees — the classic LTR workhorse.', ru: 'RankNet: парная вероятность из разностей оценок. LambdaRank: вес градиента пары на ΔnDCG, чтобы важные обмены тянули сильнее. LambdaMART: эти λ-градиенты внутри градиентного бустинга деревьев — рабочая лошадка классического LTR.' } },

  // ───────────────────────── 🔗 Synthesis (cross-cutting) ─────────────────────────
  { id: 'syn-sparse-dense', lectures: ['03', '07', '08'], type: 'concept',
    q: { en: 'Trace “sparse vs dense, and why you need both” across the course: BM25 (L3) → dense isn’t free (L7) → hybrid (L8).', ru: 'Проследи «sparse vs dense, и почему нужны оба» сквозь курс: BM25 (L3) → dense isn’t free (L7) → hybrid (L8).' },
    a: { en: 'BM25 is a strong, robust lexical baseline (L3); dense retrievers win in-domain but degrade out-of-domain (L7); so production fuses both — hybrid + late interaction (L8) — to get lexical precision and semantic recall.', ru: 'BM25 — сильный устойчивый лексический базлайн (L3); dense выигрывает in-domain, но деградирует вне домена (L7); поэтому в проде сливают оба — hybrid + late interaction (L8) — ради лексической точности и семантического recall.' } },
  { id: 'syn-cosine', lectures: ['02', '05', '06', '07'], type: 'concept',
    q: { en: 'Cosine as the through-line “ruler”: where does it appear (L2, L5, L6, L7) and why direction-not-magnitude?', ru: 'Cosine как сквозная «линейка»: где встречается (L2, L5, L6, L7) и почему «направление, а не длина»?' },
    a: { en: 'Cosine measures angle in similarity (L2), reads word analogies (L5), lives inside the contrastive loss (L6), and scores bi-encoder pairs (L7). Direction encodes meaning; magnitude often just reflects length/frequency, which we don’t want to reward.', ru: 'Косинус мерит угол в similarity (L2), читает аналогии слов (L5), живёт внутри контрастивного лосса (L6) и скорит пары bi-encoder (L7). Направление кодирует смысл; длина часто лишь отражает объём/частоту, что награждать не нужно.' } },
  { id: 'syn-goodhart', lectures: ['01', '04'], type: 'concept',
    q: { en: 'Goodhart’s law across the course: how does metric-gaming show up in system design (L1) and in evaluation (L4)?', ru: 'Гудхарт сквозь курс: как гейминг метрики проявляется в system design (L1) и в оценке (L4)?' },
    a: { en: 'L1: optimizing a proxy (CTR) drives a feedback loop that amplifies clickbait/popularity. L4: a single offline number, once it becomes the target, invites overfitting and ignores significance — so use honest judgments, significance tests, and A/B.', ru: 'L1: оптимизация прокси (CTR) запускает feedback loop, усиливающий кликбейт/популярность. L4: одно оффлайн-число, став целью, провоцирует переобучение и игнор значимости — нужны честные оценки, тесты значимости и A/B.' } },
  { id: 'syn-recall-ceiling', lectures: ['04', '07', '08'], type: 'concept',
    q: { en: 'Why is recall@k the ceiling of any reranking pipeline, and how does that connect to rerank depth (L7) and metric choice (L4)?', ru: 'Почему recall@k — потолок любого реранкинг-пайплайна и как это связано с глубиной реранка (L7) и выбором метрики (L4)?' },
    a: { en: 'A reranker (cross-encoder, ColBERT, LTR) can only reorder the retrieved top-k, so recall@k bounds the achievable nDCG; choosing k trades latency vs recall, and you must measure with a recall-aware metric to see the ceiling.', ru: 'Реранкер (cross-encoder, ColBERT, LTR) лишь переставляет извлечённый top-k, поэтому recall@k ограничивает достижимый nDCG; выбор k — компромисс latency vs recall, и мерить надо метрикой, чувствительной к recall, чтобы увидеть потолок.' } },
];
