    {
      id: 'raptor', kind: 'prose',
      heading: { en: 'RAPTOR: a tree of summaries', ru: 'RAPTOR: дерево резюме', tt: 'RAPTOR: резюмеләр агачы' },
      img: 'L10/L10-10-raptor-tree.png', imgPos: 'float-right',
      imgAlt: {
        en: 'RAGdoll the Oracle stacks scraps into a pyramid — many leaf-scraps summarise up into fewer summary-scraps, then into one root — while Séréga points at the level his question lands on.',
        ru: 'Оракул RAGdoll складывает обрывки в пирамиду — много листовых обрывков обобщаются вверх в меньшее число резюме-обрывков, затем в один корень — а Серёга указывает на уровень, куда попадает его вопрос.',
        tt: 'RAGdoll Оракулы кисәкләрне пирамидага өя — күп яфрак-кисәк азрак резюме-кисәккә, аннары бер тамырга гомумиләшә — ә Серёга соравы төшкән дәрәҗәгә күрсәтә.',
      },
      body: {
        en: [
          "Summary indexing kept one summary per document. But questions arrive at different *altitudes*: \"what is the systolic phase?\" is a leaf-level detail, while \"summarise how the cardiovascular system works\" is a whole-corpus overview. A flat index of chunks answers the first well and the second badly — no single chunk *is* the overview. **RAPTOR** (Sarthi, Abdullah, Tuli, Khanna, Goldie & Manning, ICLR 2024, arXiv:2401.18059) builds an index that answers both.",
          "The construction is recursive. Start with the leaf chunks. **Cluster** semantically similar chunks together, **summarise** each cluster with the model into a higher-level node, and embed those summaries. Then recurse: cluster the summaries, summarise *them*, and climb again — until you reach a single root that summarises everything. The result is a tree where leaves are raw passages and every internal node is an abstractive summary of its subtree.",
          ":::calc In the toy illustration the tree has three levels: \\(8\\) leaf chunks cluster and summarise into \\(3\\) mid-level nodes, which summarise into \\(1\\) root — depth \\(3\\). Each level up is coarser and more abstract; each level down is finer and more literal. :::",
          "Retrieval is the payoff. Instead of searching only the leaves, you index **every node at every level** in one flat collection and retrieve across all of them. A broad question matches a high summary node and gets the synthesised overview; a narrow question matches a leaf and gets the precise passage. One index, one query path, but answers calibrated to the altitude of the question — no need to guess in advance whether the user wants the forest or a single tree.",
          "RAPTOR is multi-representation indexing taken vertical: where summary indexing gave you one proxy per document, RAPTOR gives you a *ladder* of proxies from literal to abstract, all searchable at once. It pairs naturally with everything in this lecture — chunk the leaves however you like, route altitude-sensitive queries toward the right level, and re-rank the mixed-altitude shortlist. The tree is just a richer thing to retrieve *from*.",
        ],
        ru: [
          "Индексирование по резюме держало одно резюме на документ. Но вопросы прибывают на разной *высоте*: «что такое систолическая фаза?» — деталь уровня листа, а «обобщи, как работает сердечно-сосудистая система» — обзор всего корпуса. Плоский индекс чанков отвечает на первый хорошо, на второй плохо — ни один чанк *не является* обзором. **RAPTOR** (Сарти, Абдулла, Тули, Кханна, Голди и Мэннинг, ICLR 2024, arXiv:2401.18059) строит индекс, что отвечает на оба.",
          "Построение рекурсивно. Начни с листовых чанков. **Кластеризуй** семантически близкие чанки вместе, **обобщи** каждый кластер моделью в узел уровнем выше и эмбеддь эти резюме. Затем рекурсия: кластеризуй резюме, обобщи *их* и поднимись снова — пока не дойдёшь до единого корня, обобщающего всё. Итог — дерево, где листья суть сырые отрывки, а каждый внутренний узел есть абстрактивное резюме своего поддерева.",
          ":::calc В игрушечной иллюстрации у дерева три уровня: \\(8\\) листовых чанков кластеризуются и обобщаются в \\(3\\) узла среднего уровня, которые обобщаются в \\(1\\) корень — глубина \\(3\\). Каждый уровень вверх грубее и абстрактнее; каждый вниз тоньше и буквальнее. :::",
          "Извлечение — это выигрыш. Вместо поиска только по листьям ты индексируешь **каждый узел на каждом уровне** в одну плоскую коллекцию и извлекаешь по всем сразу. Широкий вопрос матчится с высоким узлом-резюме и получает синтезированный обзор; узкий вопрос матчится с листом и получает точный отрывок. Один индекс, один путь запроса, но ответы откалиброваны под высоту вопроса — не нужно заранее гадать, хочет ли пользователь лес или одно дерево.",
          "RAPTOR — это многопредставленческое индексирование, развёрнутое вертикально: где индексирование по резюме давало один прокси на документ, RAPTOR даёт *лестницу* прокси от буквального до абстрактного, все искомые разом. Он естественно сочетается со всем в этой лекции — нарезай листья как хочешь, маршрутизируй чувствительные к высоте запросы к нужному уровню и переранжируй шортлист смешанной высоты. Дерево — это лишь более богатое то, *из чего* извлекать.",
        ],
        tt: [
          "Резюме буенча индекслау документка бер резюме тотты. Ләкин сораулар төрле *биеклектә* килә: «систолик фаза нәрсә?» — яфрак дәрәҗәсендәге деталь, ә «йөрәк-кан тамыр системасы ничек эшләвен гомумиләштер» — бөтен корпус күзәтүе. Чанкларның яссы индексы беренчесенә яхшы, икенчесенә начар җавап бирә — бер чанк та күзәтү *түгел*. **RAPTOR** (Сарти, Абдулла, Тули, Кханна, Голди һәм Мэннинг, ICLR 2024, arXiv:2401.18059) икесенә дә җавап бирә торган индекс төзи.",
          "Төзелеш рекурсив. Яфрак чанкларыннан башла. Семантик якын чанкларны бергә **кластерла**, һәр кластерны модель белән югарырак дәрәҗәдәге төенгә **гомумиләштер** һәм бу резюмеләрне эмбеддлә. Аннары рекурсия: резюмеләрне кластерла, *аларны* гомумиләштер һәм тагын күтәрел — барысын гомумиләштерүче бер тамырга җиткәнче. Нәтиҗә — яфраклары чи өзекләр, ә һәр эчке төене үз асагачының абстрактив резюмесе булган агач.",
          ":::calc Уенчык иллюстрациядә агачның өч дәрәҗәсе бар: \\(8\\) яфрак чанк кластерлана һәм \\(3\\) урта дәрәҗә төененә гомумиләшә, алар \\(1\\) тамырга гомумиләшә — тирәнлек \\(3\\). Һәр өскә дәрәҗә тупасрак һәм абстрактрак; һәр аска нечкәрәк һәм хәрефкәрәк. :::",
          "Алу — файда. Бары яфраклар буенча эзләү урынына син **һәр дәрәҗәдә һәр төенне** бер яссы җыелмага индекслыйсың һәм барысы буенча бер юлы аласың. Киң сорау биек резюме төененә туры килә һәм синтезланган күзәтү ала; тар сорау яфракка туры килә һәм төгәл өзек ала. Бер индекс, бер сорау юлы, ләкин җаваплар сорау биеклегенә көйләнгән — кулланучы урманны телиме яки бер агачны, алдан фаразларга кирәкми.",
          "RAPTOR — вертикаль җәелгән күп-тәкъдимле индекслау: резюме буенча индекслау документка бер прокси биргәндә, RAPTOR хәрефтән абстрактка кадәр прокси *баскычын* бирә, барысы бер юлы эзләнә. Ул бу лекциядәге һәр нәрсә белән табигый кушыла — яфракларны теләгәнчә кис, биеклеккә сизгер сорауларны дөрес дәрәҗәгә маршрутла һәм катнаш-биеклек шортлистын кабат ранжла. Агач — бары *нәрсәдән* алу өчен баерак нәрсә.",
        ],
      },
    },
