    {
      id: 'drop-in', kind: 'prose',
      heading: { en: "Same drawer, a better card", ru: "Тот же ящик — карточка лучше", tt: "Шул ук тартма — яхшырак карточка" },
      img: 'L16/L16-08-drop-in.png', imgPos: 'right',
      imgAlt: { en: "Séréga in his green tübetey at the library's binding-room bench, carefully re-writing one index card so it remembers its subject; at the front, that same-size card slides into the very same slot of a long HNSW/IVF drawer, while a reader at the query desk pulls it and is gone — drawer, desk, and shelves all unchanged, only the writing on the card is different.", ru: "Серёга в зелёной тюбетейке за верстаком в переплётной библиотеки бережно переписывает одну карточку, чтобы та помнила, о чём она; у фасада та же по размеру карточка ложится в тот же самый паз длинного ящика HNSW/IVF, а читатель у стола запросов берёт её и уходит — ящик, стол и полки те же, изменилась лишь надпись на карточке.", tt: "Séréga яшел түбәтәендә китапханәнең переплёт бүлмәсендәге верстак янында бер карточканы, ул кемгә кагылганын хәтерләсен өчен, җентекләп кабат яза; фасадта шул ук зурлыктагы карточка озын HNSW/IVF тартмасының нәкъ шул ук оясына керә, ә запрос өстәле яныдагы укучы аны ала да китә — тартма, өстәл һәм киштәләр шул ук, тик карточкадагы язу гына башка." },
      imgCaption: { en: "Same-size card, same **HNSW/IVF** drawer, same fast pull at the desk — I only changed how the card is *written*. **Late chunking is an indexing-side upgrade, not a rebuild.**", ru: "Та же по размеру карточка, тот же ящик **HNSW/IVF**, та же быстрая выдача у стола — я поменял лишь то, как карточка *написана*. **Late chunking — улучшение на стороне индексации, а не переделка.**", tt: "Шул ук зурлыктагы карточка, шул ук **HNSW/IVF** тартмасы, өстәлдә шул ук тиз бирелеш — мин тик карточканың ничек *язылганын* үзгәрттем. **Late chunking — индекс ягындагы яхшырту, яңадан төзү түгел.**" },
      body: {
        en: [
          "For weeks I braced for the bill. Surely a new way of *writing* the index cards means a new drawer to hold them, a new desk to read them from, a heavier reach at query time. So I re-embedded a whole corpus the late way, walked to the front of the library — and nothing downstream had moved. The card was the same size. It slid into the very same slot.",
          "That is the quiet gift of late chunking: it changes *nothing* past the binding room. Same **dimensionality** — the vector is exactly as wide as before, so it drops into your **HNSW or IVF** index untouched, no re-tuning, no reshaped schema. Same **query-time cost** — the reader at the desk pulls one tidy card per chunk and is gone, *free*, just as fast as with naive chunks. I didn't hand them a fistful of per-word sticky-notes to sort through; I handed them one card that simply *remembers* who it's about.",
          "So everything I fixed, I fixed *upstream* — offline, once, at index time. Re-embed the corpus the late way and the vector DB, the ANN index, the reranker, the whole query path never learn that anything changed. That is why this ships on a Tuesday and not next quarter: it's a pure **indexing-side** upgrade, not a rebuild.",
        ],
        ru: [
          "Неделями я готовился к счёту. Ведь новый способ *писать* карточки — это, казалось, новый ящик, чтобы их хранить, новый стол, чтобы читать, и тяжелее тянуться на запросе. Я переэмбеддил весь корпус по-позднему, вышел к фасаду библиотеки — и ниже по течению ничто не сдвинулось. Карточка того же размера. Легла в тот же самый паз.",
          "В этом тихий подарок late chunking: он не меняет *ничего* после переплётной. Та же **размерность** — вектор ровно той же ширины, что и был, и падает в твой **HNSW или IVF** индекс нетронутым: ни перенастройки, ни новой схемы. Та же **цена на запросе** — читатель у стола берёт одну аккуратную карточку на чанк и уходит, *бесплатно*, ровно так же быстро, как с наивными. Я не всучил ему горсть по-словных стикеров на разбор — я дал одну карточку, что просто *помнит*, о ком она.",
          "Так что всё, что я починил, я починил *выше по течению* — офлайн, один раз, на индексации. Переэмбеддь корпус по-позднему — и векторная БД, ANN-индекс, реранкер, весь путь запроса даже не узна́ют, что что-то изменилось. Оттого это катится во вторник, а не в следующем квартале: это чистое улучшение на **стороне индексации**, а не переделка.",
        ],
        tt: [
          "Атналар буе мин хисапка әзерләндем. Карточкаларны *язу* ысулы яңа булгач, аларны саклар өчен яңа тартма, укыр өчен яңа өстәл, ә запроста авыррак сузылу кирәктер, дип уйладым. Бөтен корпусны late ысул белән кабат embed иттем, китапханә фасадына чыктым — һәм аста бернәрсә дә кузгалмаган. Карточка шул ук зурлыкта. Нәкъ шул ук ояга керде.",
          "Менә шушы — late chunking'ның тыныч бүләге: ул переплёт бүлмәсеннән соң *берни* үзгәртми. Шул ук **dimensionality** — вектор нәкъ элеккечә киң, синең **HNSW яки IVF** index'ыңа тимичә төшә: көйләү дә, яңа схема да юк. Шул ук **query-time** бәясе — өстәл яныдагы укучы һәр chunk'ка бер пөхтә карточка ала да китә, *тиккә*, наив chunk'лар белән ничек тиз булса, шулай ук. Мин аңа сүзгә-сүз стикерлар уысын тоттырмадым — мин аңа кемгә кагылганын гади генә *хәтерли* торган бер карточка бирдем.",
          "Шулай итеп мин нәрсә төзәттем — барысын да *өстә*, аста түгел: офлайн, бер тапкыр, индексациядә төзәттем. Корпусны late ысул белән кабат embed ит — вектор DB, ANN index, reranker, бөтен запрос юлы берни үзгәргәнен белми дә кала. Шуңа күрә бу сишәмбедә үк чыга, киләсе кварталда түгел: бу чиста **индекс ягындагы** яхшырту, яңадан төзү түгел.",
        ],
      },
    },
