    {
      id: 'colpali', kind: 'prose',
      heading: { en: 'ColPali: retrieve over the page', ru: 'ColPali: поиск по странице', tt: 'ColPali: бит буйлап эзләү' },
      img: 'L12/L12-04-colpali.png', imgPos: 'float-right',
      imgAlt: {
        en: 'A scanned document page tiled into a grid of patches, a text query firing a beam to its best-matching patch — a table cell — while Séréga watches: late interaction over the page image, no OCR.',
        ru: 'Скан страницы документа, разбитый на сетку патчей; текстовый запрос пускает луч в наиболее подходящий патч — ячейку таблицы, — а Серёга наблюдает: позднее взаимодействие по изображению страницы, без OCR.',
        tt: 'Документ битенең сканы патчлар челтәренә бүленгән; текст соравы иң туры килгән патчка — таблица күзәнәгенә — нур җибәрә, ә Серёга күзәтә: бит рәсеме буйлап соңгы тәэсир итешү, OCR сыз.',
      },
      body: {
        en: [
          "The frontier idea pushes further: what if the *page itself* is the unit of retrieval? The classic document pipeline is OCR → layout parse → chunk → embed — and it is **brittle** on tables, figures, stamps and scans, where the meaning lives in the layout, not a clean text stream.",
          "**ColPali** (Faysse et al., 2024) skips all of it. Render each page as an **image**, embed it with a vision-language model into **patch-level** vectors, and retrieve with **late interaction** — a query token attends to its most similar image patch (MaxSim). A figure, a table cell, a stamp — all retrievable without ever transcribing them. And notice the lineage: this is **ColBERT's late interaction from L8** (Sir Cosine measuring per-patch), fused with **L12's shared image–text space**. The two frontiers we built meet in one model. The price comes from that same lineage: late interaction stores **one vector per patch** (hundreds-to-over-a-thousand per page), so the index is one-to-two orders of magnitude larger than a single CLIP page vector, and MaxSim must score every query-patch × page-patch pair per candidate — the **same multi-vector storage and latency tax as ColBERT in L8**, now charged *per page*. That is exactly why, on the menu, ColPali is the most faithful *and* the most expensive option.",
        ],
        ru: [
          "Фронтирная идея идёт дальше: что, если *сама страница* — единица поиска? Классический конвейер документа — OCR → разбор раскладки → чанк → эмбеддинг — и он **хрупок** на таблицах, рисунках, печатях и сканах, где смысл живёт в раскладке, а не в чистом потоке текста.",
          "**ColPali** (Faysse и др., 2024) пропускает всё это. Отрендерь каждую страницу как **изображение**, заэмбедь её визуально-языковой моделью в **попатчевые** векторы и извлекай **поздним взаимодействием**: токен запроса тянется к наиболее похожему патчу изображения (MaxSim). Рисунок, ячейка таблицы, печать — всё извлекаемо, ни разу не транскрибируясь. И заметь родословную: это **позднее взаимодействие ColBERT из L8** (Сэр Косинус, меряющий попатчево), сплавленное с **общим пространством изображение–текст из L12**. Два построенных нами фронтира встречаются в одной модели. Цена идёт из той же родословной: позднее взаимодействие хранит **по одному вектору на патч** (от сотен до более тысячи на страницу), так что индекс на один-два порядка больше одного CLIP-вектора страницы, а MaxSim обязан оценить каждую пару патч-запроса × патч-страницы для каждого кандидата — **тот же налог на хранение и задержку многовекторности, что у ColBERT в L8**, теперь взимаемый *за страницу*. Именно поэтому в меню ColPali — самый верный *и* самый дорогой вариант.",
        ],
        tt: [
          "Фронтир фикере тагын ераккарак китә: *бит үзе* эзләү берәмлеге булса? Классик документ конвейеры — OCR → макет тикшерү → чанк → эмбеддинг — һәм ул таблицаларда, рәсемнәрдә, мөһерләрдә һәм сканнарда **сынучан**, анда мәгънә макетта яши, чиста текст агымында түгел.",
          "**ColPali** (Faysse һ.б., 2024) боларның барысын калдыра. Һәр битне **рәсем** итеп ясый, аны күрү-тел моделе белән **патч дәрәҗәсендәге** векторларга эмбеддла һәм **соңгы тәэсир итешү** белән ала: сорау токены иң охшаш рәсем патчына омтыла (MaxSim). Рәсем, таблица күзәнәге, мөһер — барысы да, беркайчан күчереп язмыйча, алына. Һәм нәселне игътибар ит: бу — **L8 дагы ColBERT соңгы тәэсир итешүе** (патч буенча үлчәүче Сэр Косинус), **L12 дагы уртак рәсем-текст киңлеге** белән кушылган. Без төзегән ике фронтир бер модельдә очраша. Бәя шул ук нәселдән килә: соңгы тәэсир итешү **һәр патчка бер вектор** саклый (битенә йөзләрчәдән мең артыграк), шуңа индекс бер CLIP бит векторыннан бер-ике зурлык тәртибенә зуррак, ә MaxSim һәр кандидат өчен сорау-патч × бит-патч һәр парны бәяләргә тиеш — **L8 дагы ColBERT кебек үк күпвекторлы саклау һәм тоткарлык салымы**, хәзер *бит саен* алына. Нәкъ менә шуңа күрә менюда ColPali — иң тугрылыклы *һәм* иң кыйммәт вариант."
        ],
      },
    },
