import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFileSync, existsSync, statSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'docs'); const BASE='/deep-learning-for-search-summer-2026'; const PORT=8137;
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2','.webp':'image/webp','.jpg':'image/jpeg'};
const srv=createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.startsWith(BASE))p=p.slice(BASE.length);let f=join(DOCS,p);if(existsSync(f)&&statSync(f).isDirectory())f=join(f,'index.html');if(!existsSync(f)){res.statusCode=404;res.end('404');return;}res.setHeader('Content-Type',MIME[extname(f)]||'application/octet-stream');res.end(readFileSync(f));});
await new Promise(r=>srv.listen(PORT,r));
const b=await chromium.launch();const page=await b.newPage({viewport:{width:390,height:780},deviceScaleFactor:2});
await page.goto(`http://localhost:${PORT}${BASE}/en/book/05/`,{waitUntil:'networkidle'});await page.waitForTimeout(800);
const el=await page.$('[data-beat="climb-word2vec-net"] [data-step="3"]')||(await page.$$('[data-step]'))[3];
const h=await page.evaluateHandle(()=>{const sc=[...document.querySelectorAll('.scrolly')].find(s=>(s.querySelector('.scrolly-graphic')?.getAttribute('data-beat'))==='climb-word2vec-net');const marks=[...sc.querySelectorAll('[data-step]')];return marks[marks.length-1];});
await h.asElement().evaluate(n=>n.scrollIntoView({block:'center'}));await page.waitForTimeout(700);
const g=await h.asElement().evaluateHandle(n=>n.closest('.scrolly').querySelector('.scrolly-graphic'));
await g.asElement().screenshot({path:join(ROOT,'_internal/l56_reaudit2/book-wide/m390-skipgram-step3.png')});
console.log('mobile shot done');
await b.close();srv.close();
