import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFileSync, existsSync, statSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT,'docs'); const BASE='/deep-learning-for-search-summer-2026'; const PORT=8138;
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2','.webp':'image/webp','.jpg':'image/jpeg'};
const srv=createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.startsWith(BASE))p=p.slice(BASE.length);let f=join(DOCS,p);if(existsSync(f)&&statSync(f).isDirectory())f=join(f,'index.html');if(!existsSync(f)){res.statusCode=404;res.end('404');return;}res.setHeader('Content-Type',MIME[extname(f)]||'application/octet-stream');res.end(readFileSync(f));});
await new Promise(r=>srv.listen(PORT,r));
const b=await chromium.launch();const page=await b.newPage({viewport:{width:390,height:780},deviceScaleFactor:2});
await page.goto(`http://localhost:${PORT}${BASE}/en/book/05/`,{waitUntil:'networkidle'});await page.waitForTimeout(700);
// find the first skipgram svg and screenshot it directly
const svg=await page.$('svg.sg-svg, .scrolly svg');
const found=await page.evaluate(()=>{const s=[...document.querySelectorAll('.scrolly')].find(x=>(x.querySelector('.scrolly-graphic')?.getAttribute('data-beat'))==='climb-word2vec-net');if(!s)return 'no-scrolly';const g=s.querySelector('.scrolly-graphic');return g?('graphic h='+Math.round(g.getBoundingClientRect().height)+' display='+getComputedStyle(g).display):'no-graphic';});
console.log('mobile skipgram graphic:', found);
await page.evaluate(()=>{const s=[...document.querySelectorAll('.scrolly')].find(x=>(x.querySelector('.scrolly-graphic')?.getAttribute('data-beat'))==='climb-word2vec-net');s?.scrollIntoView({block:'start'});});
await page.waitForTimeout(600);
await page.screenshot({path:join(ROOT,'_internal/l56_reaudit2/book-wide/m390-skipgram-page.png')});
console.log('done');
await b.close();srv.close();
