import { chromium } from 'playwright';
const BASE='http://localhost:8099/Lecture%20Template.html';
const S=decodeURIComponent(new URL('./shots-fixed/',import.meta.url).pathname);
const b=await chromium.launch();const c=await b.newContext({viewport:{width:1920,height:1080}});const p=await c.newPage();
await p.goto(BASE,{waitUntil:'networkidle'});await p.waitForFunction(()=>window.Lecture&&window.Lecture.total>0);await p.waitForTimeout(1500);
await p.evaluate(()=>window.Lecture.goTo(0));await p.waitForTimeout(200);
await p.screenshot({path:S+'vendor-title-light.png',clip:{x:0,y:0,width:1920,height:1080}});
const ff=await p.evaluate(()=>getComputedStyle(document.querySelector('.slide.is-active h1')).fontFamily);
console.log('title h1 fontFamily:', ff);
await b.close();
