    {
      id: 'hubness', kind: 'prose',
      heading: { en: "All roads lead to Rome", ru: "Все дороги ведут в Рим", tt: "Бөтен юллар Римга илтә" },
      img: 'L18/L18-07-rome-hub.png', imgPos: 'right',
      imgAlt: { en: "Séréga in his green tübetey at his drafting table over a warped map: hundreds of thin roads from every small town all funnel into one swollen hub town at the centre, marked like a Rome, while three pale anti-hub towns stranded in the corners have no road reaching them at all.", ru: "Серёга в зелёной тюбетейке за чертёжным столом над покоробленной картой: сотни тонких дорог из каждого городка стекаются в один разбухший hub-город в центре, помеченный как Рим, а три бледных анти-хаба, застрявшие по углам, не имеют ни одной ведущей к ним дороги.", tt: "Яшел түбәтәйле Серёга сызым өстәле артында кыйшайган карта өстендә: һәр шәһәрчектән йөзләрчә нечкә юл үзәктәге бер шешенгән hub-шәһәргә агыла, ул Рим кебек билгеләнгән, ә почмакларда каткан өч төссез anti-hub'ка бер генә юл да килми." },
      imgCaption: { en: "**All roads lead to Rome** — a few **hub** towns are everyone's neighbour, while the **anti-hubs** in the margins are never visited.", ru: "**Все дороги ведут в Рим** — горстка **hub**-городов сосед всем, а **анти-хабы** на полях не навещает никто.", tt: "**Бөтен юллар Римга илтә** — бер уч **hub**-шәһәр һәркемгә күрше, ә читтәге **anti-hub**'ларга беркем дә килми." },
      body: {
        en: [
          "The wedge was one lie of the paper. Here is the second, and it hides in the roads, not the land. Pick a town \\(x\\) and ask a stranger's question: of all the *other* towns, how many list \\(x\\) among their \\(k\\) nearest? Count that — Radovanović called it \\(N_k(x)\\), the reverse-neighbour tally — and you have measured not how many friends a town keeps, but how many strangers keep *it*.",
          "On a small map the count is fair: everyone is somebody's neighbour a handful of times, no more. But as I add dimensions to the paper, the tally goes crooked. A few towns start turning up on *everyone's* shortlist — the **hubs** — while a long tail of towns appear on nobody's, ever — the **anti-hubs**, marooned in the margins. And the skew is not gentle: on plain uniform land it climbs from \\(0.121\\) at \\(d=3\\), to \\(1.541\\) at \\(d=20\\), to \\(5.445\\) at \\(d=100\\). All roads, it seems, lead to Rome.",
          "And Rome earns nothing to deserve it. In high dimensions every town is flung out onto a thin shell around the map's centroid — the mean of the whole crowd — all sitting at nearly the same radius. Whoever happens to fall closest to that centre is, by pure geometry, close to *all* of them at once; it becomes everyone's neighbour without meaning a thing to any of them. For retrieval this is poison: a handful of passages come back for every query I pose, while the anti-hubs sit unreachable, never surfaced — recall quietly bleeding out at the edges.",
        ],
        ru: [
          "Клин был первой ложью бумаги. Вот вторая — и прячется она в дорогах, а не в земле. Возьми город \\(x\\) и задай вопрос с изнанки: из всех *остальных* городов сколько держат \\(x\\) в числе своих \\(k\\) ближайших? Сосчитай это — Радованович назвал величину \\(N_k(x)\\), счётчиком обратных соседей, — и ты измеришь не сколько у города друзей, а сколько чужаков держат *его*.",
          "На маленькой карте счёт честный: каждый оказывается чьим-то соседом пару раз, не больше. Но стоит добавить бумаге измерений — и подсчёт кривится. Горстка городов начинает всплывать в списках *у всех* — это **hub'ы**, — а длинный хвост городов не всплывает ни у кого и никогда — **анти-хабы**, брошенные на полях. И перекос не мягкий: на простой однородной земле асимметрия растёт с \\(0.121\\) при \\(d=3\\) до \\(1.541\\) при \\(d=20\\) и до \\(5.445\\) при \\(d=100\\). Все дороги, выходит, ведут в Рим.",
          "А Рим ничем этого не заслужил. В больших размерностях каждый город выброшен на тонкую сферу вокруг центроида карты — среднего всей толпы — и все они почти на одном радиусе. Кто случайно оказался ближе к этому центру, тот по чистой геометрии близок сразу *ко всем*; он становится соседом каждому, не значив ничего ни для кого. Для поиска это яд: горстка пассажей возвращается на любой мой запрос, а анти-хабы сидят недостижимые, ни разу не всплыв, — и recall тихо утекает по краям.",
        ],
        tt: [
          "Чөй — кәгазьнең беренче ялганы иде. Менә икенчесе — һәм ул җирдә түгел, юлларда яшеренә. Бер шәһәр \\(x\\) ал да, әйләндереп сора: калган *бөтен* шәһәрләрнең ничәсе \\(x\\)-ны үзләренең \\(k\\) иң якыны арасында тота? Шуны сана — Радованович аны \\(N_k(x)\\), кире күршеләр санагычы, дип атаган, — һәм син шәһәрнең ничә дусты барын түгел, ә аны ничә чит-ят *үзенеке* итеп тотканын үлчисең.",
          "Кечкенә картада хисап гадел: һәркем кемгәдер берничә тапкыр күрше була, аннан артык түгел. Ләкин кәгазьгә үлчәмнәр өстәсәң — хисап кыйшая. Бер уч шәһәр *һәркемнең* исемлегендә калка башлый — болар **hub'лар**, — ә озын койрыктагы шәһәрләр беркемдә дә, беркайчан да калкмый — **anti-hub'лар**, читкә ташланганнар. Кыйшаю йомшак түгел: гади бертөрле җирдә skewness \\(d=3\\) вакытта \\(0.121\\)-дән \\(d=20\\) вакытта \\(1.541\\)-гә, \\(d=100\\) вакытта \\(5.445\\)-кә үрли. Бөтен юллар, күрәсең, Римга илтә.",
          "Ә Рим моны бернәрсә белән дә яуламаган. Зур үлчәмнәрдә һәр шәһәр картаның centroid'ы — бөтен төркемнең уртачасы — тирәли нечкә кабыкка ыргытыла, барысы да диярлек бер радиуста. Кем очраклы рәвештә шул үзәккә якынрак — ул саф геометрия буенча берьюлы *барысына* да якын; ул беркемгә бернәрсә аңлатмыйча һәркемгә күрше булып китә. Эзләү өчен бу — агу: бер уч passage минем һәр сорауга кайта, ә anti-hub'лар кулга кермичә утыра, бер тапкыр да калкмый, — һәм recall читләрдән тын гына агып бетә.",
        ],
      },
    },
