    {
      id: 'csls', kind: 'prose',
      heading: { en: "CSLS: a toll for crowded towns", ru: "CSLS: пошлина за тесноту", tt: "CSLS: тыгызлык өчен toll" },
      img: 'L18/L18-09-crowding-tax.png', imgPos: 'right',
      imgAlt: { en: "Séréga the cartographer leans over his warped map where every road converges on one swollen central hub-town labelled 'Rome'; at that town's gate he has bolted a brass toll booth with a heavy counterweight stamped r, so the roads leaving it sag under the charge while a thin, freed road at last reaches a lonely town stranded in the margin; the only green anywhere in the scene is his tübetey.", ru: "Серёга-картограф склонился над своей искажённой картой, где все дороги сходятся к одному раздутому центральному городу-хабу с табличкой «Рим»; у его ворот он привинтил латунную заставу с тяжёлым противовесом, помеченным r, так что уходящие дороги провисают под пошлиной, а тонкая освобождённая дорога наконец дотягивается до одинокого города, брошенного на краю; единственное зелёное во всей сцене — его тюбетейка.", tt: "Séréga-картограф үзенең бозылган картасы өстенә иелгән, анда барлык юллар «Рим» тактасы куелган бер шешенгән үзәк hub-шәһәргә җыела; шул шәһәр капкасына ул r дип тамгаланган авыр каршы-авырлыклы җиз застава беркеткән, шуңа чыгучы юллар пошлина астында бөгелә, ә нечкә, ирекле калган бер юл ниһаять кырыйда ялгыз калган шәһәргә барып җитә; сәхнәдә бердәнбер яшел төс — аның түбәтәе." },
      imgCaption: { en: "**Every road led to Rome — until I taxed it for being crowded.**", ru: "**Все дороги вели в Рим — пока я не обложил его пошлиной за тесноту.**", tt: "**Барлык юллар Римга илтә иде — мин аны тыгызлык өчен toll белән салганчы.**" },
      body: {
        en: [
          "I stand over the map and follow the roads. They all seem to lead to *Rome* — a handful of **hub** towns that every other town writes into its list of neighbours. But Rome is not truly near each of them; it is merely *crowded*, planted where the land is dense, so the naïve ruler keeps electing it. Raw cosine rewards popularity. So I bolt a toll booth to every town's gate, and I set the toll by how busy that town's own doorstep is.",
          "For each town \\(x\\) I first measure its local crowding: \\(r(x)\\), the mean cosine to its \\(K=10\\) nearest neighbours — large for a bustling hub, small for a quiet town in the margin. Then I re-price every road between \\(x\\) and \\(y\\) as \\( \\mathrm{CSLS}(x,y) = 2\\cos(x,y) - r_T(x) - r_S(y) \\): twice the road's plain closeness, minus each endpoint's toll. Conneau's *cross-domain local scaling*, 2018. A hub, whose \\(r\\) is large, now pays a heavy toll on every road it touches — it can no longer be close *just because it is crowded*. A genuinely near pair, both from quiet quarters, pays almost nothing and keeps its place.",
          "Same globe, same vectors — I only changed how I *read* the ruler, correcting each reading for how packed its two ends are. In word translation the score of a match climbed from \\(P@1 = 42.6\\) to \\(66.1\\) *(Conneau 2018)* — and the anti-hubs, once unreachable out in the margins, finally get visited. Note where this sits: whitening re-projected the *paper* to un-squash the cone; CSLS re-prices the *roads* to tame the neighbour graph. Two different repairs — one for the metric, one for the crowd — and I keep both in the satchel.",
        ],
        ru: [
          "Я стою над картой и веду взглядом по дорогам. Кажется, все они ведут в *Рим* — горстка городов-**хабов**, которых каждый другой город вписывает к себе в соседи. Но Рим не по-настоящему близок к каждому из них; он просто *тесен*, поставлен там, где земля густа, и наивная линейка снова и снова выбирает его. Голый косинус награждает популярность. Поэтому я привинчиваю к воротам каждого города заставу и назначаю пошлину по тому, как людно у его собственного порога.",
          "Для каждого города \\(x\\) я сперва измеряю его локальную тесноту: \\(r(x)\\) — средний косинус до его \\(K=10\\) ближайших соседей — большой у шумного хаба, малый у тихого города на окраине. Затем переоцениваю каждую дорогу между \\(x\\) и \\(y\\): \\( \\mathrm{CSLS}(x,y) = 2\\cos(x,y) - r_T(x) - r_S(y) \\) — удвоенная собственная близость дороги минус пошлина каждого конца. Это *cross-domain local scaling* Конно, 2018. Хаб, у которого \\(r\\) велик, теперь платит тяжёлую пошлину на каждой дороге, что его касается, — он больше не может быть близким *лишь потому, что тесен*. По-настоящему близкая пара, оба из тихих кварталов, платит почти ничего и остаётся на месте.",
          "Тот же глобус, те же векторы — я лишь изменил то, как *читаю* линейку, поправляя каждый отсчёт на тесноту его концов. В переводе слов оценка совпадения выросла с \\(P@1 = 42{,}6\\) до \\(66{,}1\\) *(Conneau 2018)* — и анти-хабы, прежде недостижимые на окраинах, наконец получают гостей. Заметь, где это стоит: отбеливание перепроецировало *бумагу*, чтобы разжать конус; CSLS переоценивает *дороги*, чтобы усмирить граф соседей. Две разные починки — одна для метрики, другая для толпы, — и обе я держу в котомке.",
        ],
        tt: [
          "Мин карта өстендә торам да юллар буйлап карашымны йөртәм. Барысы да *Римга* илтә кебек — берничә **hub**-шәһәр, аларны һәр башка шәһәр үзенә күрше итеп яза. Ләкин Рим һәрберсенә чынлап якын түгел; ул бары *тыгыз*, җир куе булган урында утыртылган, һәм беркатлы линейка аны кабат-кабат сайлый. Ялангач cosine популярлыкны бүләкли. Шуңа күрә мин һәр шәһәр капкасына застава беркетәм һәм пошлинаны аның үз бусагасы никадәр кеше белән тулы икәненә карап билгелим.",
          "Һәр шәһәр \\(x\\) өчен башта аның локаль тыгызлыгын үлчим: \\(r(x)\\) — аның \\(K=10\\) иң якын күршесенә кадәр уртача cosine — шаулы hub'та зур, кырыйдагы тыныч шәһәрдә кечкенә. Аннары \\(x\\) белән \\(y\\) арасындагы һәр юлны яңадан бәялим: \\( \\mathrm{CSLS}(x,y) = 2\\cos(x,y) - r_T(x) - r_S(y) \\) — юлның үз якынлыгы ике тапкыр, минус һәр очның пошлинасы. Бу Conneau'ның *cross-domain local scaling* ы, 2018. \\(r\\) зур булган hub хәзер үзе кагылган һәр юлда авыр пошлина түли — ул *бары тыгыз булганы өчен генә* якын була алмый. Чынлап якын пар, икесе дә тыныч кварталдан, диярлек бернәрсә түләми һәм урынында кала.",
          "Шул ук глобус, шул ук векторлар — мин бары линейканы ничек *укуымны* үзгәрттем, һәр укуны аның ике очының тыгызлыгына төзәтеп. Сүзләр тәрҗемәсендә туры килүнең бәясе \\(P@1 = 42{,}6\\) дан \\(66{,}1\\) гә күтәрелде *(Conneau 2018)* — һәм кырыйда элек ирешеп булмаган anti-hub'лар ниһаять кунак кабул итә. Кайда торганын күр: whitening *кәгазьне* конусны җәяр өчен яңадан проекцияләде; CSLS исә күршеләр графын тынычландыру өчен *юлларны* яңадан бәяли. Ике төрле ремонт — берсе метрика өчен, икенчесе халык өчен — һәм икесен дә мин капчыгымда саклыйм.",
        ],
      },
    },
