    {
      id: 'vs-llm', kind: 'prose',
      heading: { en: "The scribe you never had to hire", ru: "Писарь, которого можно и не нанимать", tt: "Син яллап тормаска мөмкин булган язучы" },
      img: 'L16/L16-07-vs-llm.png', imgPos: 'left',
      imgAlt: { en: "Two desks. On the left a costly robot-scribe stamps an extra CONTEXT paragraph onto each torn page, little coins raining out because it charges per stamp. On the right Séréga in his green tübetey simply reads the whole bound book first and gives a thumbs-up — no coins at all. Between their two finished cards sits a small equals sign: the same quality either way.", ru: "Два стола. Слева дорогой робот-писарь пришлёпывает к каждой вырванной странице лишний абзац-CONTEXT, и из-под штампа сыплются монетки — плата за каждый оттиск. Справа Серёга в зелёной тюбетейке просто читает всю переплетённую книгу целиком и показывает большой палец — ни монетки. Между их готовыми карточками стоит маленький знак равенства: качество одинаковое.", tt: "Ике өстәл. Сулда кыйммәтле робот-язучы һәр йолкынган биткә артык CONTEXT абзацын сугып куя, штамп астыннан тәңкәләр коела — һәр басым өчен түләү. Уңда яшел түбәтәйле Séréga бары бөтен төпләнгән китапны укып чыга да баш бармагын күрсәтә — бер тәңкә дә юк. Аларның ике әзер карточкасы арасында кечкенә тигезлек билгесе тора: сыйфат бертигез." },
      imgCaption: { en: "The LLM prepends a **paid** paragraph to every chunk. Late chunking matches it — **for free**: the encoder already knew the name.", ru: "LLM дописывает к каждому чанку **платный** абзац. Позднее чанкование даёт то же — **даром**: энкодер уже знал имя.", tt: "LLM һәр chunk'ка **түләүле** абзац өсти. Late chunking шуны ук бирә — **бушлай**: encoder исемне инде белә иде." },
      body: {
        en: [
          "There is another way to put the name back, and it comes from Anthropic: *Contextual Retrieval*. Before a torn page goes into the index, you hire a small, clever scribe — an LLM — to write one preface line at the top: *\"This passage is from ACME's quarterly report, about revenue.\"* Then you embed page-plus-preface. It works honestly — the referent is restored and the relevant chunk climbs to a reported cosine near \\(0.859\\), right where you want it.",
          "But look at the bill. That scribe writes a fresh preface for *every* chunk and charges an LLM call each time — once for every passage in the library, and again for every new document you ever add. It is a real fix with a meter that never stops ticking.",
          "Late chunking buys the *same* shelf for nothing. At my reading desk the very same ACME chunk lands at a reported \\(0.852\\) — a hair from the scribe's \\(0.859\\), the same answer for any practical purpose — while naïve chunking still buries it at \\(0.634\\), beneath a generic header sitting at \\(0.851\\). No preface, no coin: the long-context encoder had already written *ACME* into the word *it* while it read the whole book. Late chunking just harvests what attention already knew — the binding was free all along.",
        ],
        ru: [
          "Есть и другой способ вернуть имя на место — он из Anthropic и зовётся *Contextual Retrieval*. Прежде чем вырванная страница ляжет в индекс, ты нанимаешь маленького смышлёного писаря — LLM — и он выводит сверху одну строку-приписку: *«Этот фрагмент — из квартального отчёта ACME, про выручку»*. Дальше ты кодируешь страницу вместе с припиской. Работает честно — референт восстановлен, и нужный чанк поднимается до косинуса около \\(0{,}859\\), ровно туда, куда надо.",
          "Но взгляни на счёт. Писарь пишет свежую приписку к *каждому* чанку и за каждую берёт по вызову LLM — за каждый фрагмент в библиотеке и заново за каждый новый документ, который ты когда-либо добавишь. Это настоящее лечение, но со счётчиком, который всё тикает и тикает.",
          "Позднее чанкование берёт *ту же* полку даром. У меня за читальным столом тот самый чанк ACME оказывается на \\(0{,}852\\) — на волосок от писарёвых \\(0{,}859\\), для дела это тот же ответ, — тогда как наивный способ всё ещё хоронит его на \\(0{,}634\\), под общей шапкой в \\(0{,}851\\). Ни приписки, ни монеты: длинноконтекстный энкодер уже вписал *ACME* в слово *«оно»*, пока читал всю книгу. Позднее чанкование лишь снимает то, что внимание и так знало, — связка была бесплатной с самого начала.",
        ],
        tt: [
          "Исемне урынына кире кайтаруның тагын бер юлы бар — ул Anthropic'тан килә, *Contextual Retrieval* дип атала. Йолкып алынган бит index'ка керер алдыннан син кечкенә акыллы язучы — LLM — яллыйсың, ул өскә бер юллык өстәмә яза: *«Бу фрагмент — ACME'ның квартал отчётыннан, кереме турында»*. Аннары бит белән өстәмәне бергә embed итәсең. Намус белән эшли — референт торгызыла, кирәкле chunk cosine буенча якынча \\(0.859\\)га күтәрелә, нәкъ кирәк урынга.",
          "Ләкин счётка кара. Язучы *һәр* chunk'ка яңа өстәмә яза һәм һәрберсе өчен берәр LLM чакыруы ала — китапханәдәге һәр фрагмент өчен, һәм син өстәгән һәр яңа документ өчен яңадан. Бу — чын дәва, ләкин туктаусыз тик-тик иткән счётчик белән.",
          "Late chunking *шул ук* киштәне бушлай ала. Минем уку өстәлендә нәкъ шул ACME chunk'ы \\(0.852\\)дә тора — язучының \\(0.859\\)ыннан бер чәч кенә ерак, гамәли яктан шул ук җавап, — ә naive ысул аны һаман \\(0.634\\)тә, гомуми башлык астында \\(0.851\\)дә күмеп тота. Өстәмә дә юк, тәңкә дә юк: озын контекстлы encoder *ACME*ны *«ул»* сүзенә инде язган иде, бөтен китапны укыганда. Late chunking бары attention белгәнне җыеп ала — бәйләнеш башыннан ук бушлай иде.",
        ],
      },
    },
