/* cone-dial/logic.js — L18 "The Curved Map", act 01: the ONE knob behind anisotropy.

   The lecture quotes two numbers from Ethayarajh 2019 — random-pair cosine ≈0.6 in GPT-2's middle
   layers, ≈0.99 in its last — and leaves them as two facts. They are two points on ONE curve. Model
   a word as x = c·1_d + ε with ε ~ N(0, σ²I): the shared axis carries c, the word's own identity
   carries σ. Then

        E[cos] ≈ ‖μ‖² / (‖μ‖² + dσ²) = c² / (c² + σ²)

   and the DIMENSION CANCELS. Turning this knob is turning c/σ: 0.6 ⇒ c/σ ≈ 1.22 (the axis is barely
   louder than the noise), 0.99 ⇒ c/σ ≈ 9.95 (the axis is ten times louder than the meaning). Step 3
   sweeps d at a FIXED c/σ and the cosine does not move — which is the whole point: anisotropy is a
   signal-to-noise story, hubness (widgets/hub-toll) is a dimension story. Two different animals.

   DRIVER-AGNOSTIC: setStep(k)/maxStep, binds NO keyboard/scroll. EVERY number comes from
   data/l18-geometry.json → anisotropyDial (generated by _research/gen_l18.py, seeded, stdlib-only).

   Steps (maxStep = 4):
     0 → c/σ = 0: isotropy, a round cloud, cos ≈ 0, the average angle ≈ 90°.            s0
     1 → c/σ = 1.2247: a soft cone — this is GPT-2's middle layers.                     s1
     2 → c/σ = 9.9499: a razor wedge — this is GPT-2's last layer.                      s2
     3 → hold c/σ = 3 and sweep d = 2 → 768: the cosine does NOT move.                  s3
     4 → subtract μ at the same c/σ: the wedge springs open, cos → ≈0.                  s4 */
import { defineWidget } from '../_widget-base.js';

export const mountConeDial = defineWidget({
  id: 'cone-dial',
  rootClass: 'cd-root',
  exportName: 'mountConeDial',
  maxStep: 4,
  render({ host, data, labels, el }) {
    const D = (data && data.anisotropyDial) || {};
    const grid = D.snrGrid || [0];
    const dims = D.dims || [];
    const dim = D.canonicalDim != null ? D.canonicalDim : (dims[dims.length - 1] || 0);
    const cells = D.cells || [];
    const at = (snr, dd) => cells.find((c) => c.snr === snr && c.dim === dd) || {};
    // points are a LIST parallel to snrGrid (never keyed by a stringified float — "3" ≠ "3.0")
    const ptsFor = (snr, key) => {
      const row = (D.points || []).find((r) => r && r.snr === snr);
      return (row && row[key]) || [];
    };
    const f2 = (x) => (typeof x === 'number' && isFinite(x) ? x.toFixed(2) : '—');
    const f4 = (x) => (typeof x === 'number' && isFinite(x) ? x.toFixed(4) : '—');

    // the four stops the steps walk (index into snrGrid), then a d-sweep, then centering
    const SNR_ISO = grid[0];
    const SNR_SOFT = grid.reduce((b, s) => (Math.abs(s - 1.2247) < Math.abs(b - 1.2247) ? s : b), grid[0]);
    const SNR_HARD = grid.reduce((b, s) => (Math.abs(s - 9.9499) < Math.abs(b - 9.9499) ? s : b), grid[0]);
    const SNR_MID = grid.reduce((b, s) => (Math.abs(s - 3) < Math.abs(b - 3) ? s : b), grid[0]);
    const PLAN = [
      { snr: SNR_ISO, centered: false, sweep: false },
      { snr: SNR_SOFT, centered: false, sweep: false },
      { snr: SNR_HARD, centered: false, sweep: false },
      { snr: SNR_MID, centered: false, sweep: true },
      { snr: SNR_MID, centered: true, sweep: false },
    ];

    const W = 660, H = 372;
    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, class: 'wgt-svg cd-svg', role: 'img',
      'aria-label': labels.alt || '' }, host);

    // ── LEFT: the 2-D drawing twin. The ORIGIN is always in frame, because the whole trick is
    //    that the cloud drifts AWAY from it: seen from the origin, a distant cloud is a thin wedge.
    const box = { x: 24, y: 34, w: 290, h: 228 };
    el('text', { x: box.x + box.w / 2, y: box.y - 14, class: 'cd-lbl-strong', 'text-anchor': 'middle' }, svg)
      .textContent = labels.cloud || 'the cloud (d = 2, for the eye)';
    const wedge = el('path', { d: '', class: 'cd-wedge' }, svg);
    const axX = el('line', { x1: box.x, y1: box.y, x2: box.x, y2: box.y, class: 'cd-axis' }, svg);
    const axY = el('line', { x1: box.x, y1: box.y, x2: box.x, y2: box.y, class: 'cd-axis' }, svg);
    const originLbl = el('text', { x: box.x, y: box.y, class: 'cd-lbl' }, svg);
    originLbl.textContent = '0';
    const dots = [];
    for (let i = 0; i < 80; i += 1) dots.push(el('circle', { cx: box.x, cy: box.y, r: 3.0, class: 'cd-dot' }, svg));

    // ── RIGHT: the cosine gauge — a protractor from 0° to 90° with the mean-angle needle ───────
    const gx = 476, gy = 196, GR = 104;
    el('path', { d: `M ${gx} ${gy - GR} A ${GR} ${GR} 0 0 1 ${gx + GR} ${gy}`, class: 'cd-arc' }, svg);
    el('line', { x1: gx, y1: gy, x2: gx, y2: gy - GR - 8, class: 'cd-needle-ref' }, svg);
    el('text', { x: gx, y: gy - GR - 14, class: 'cd-lbl', 'text-anchor': 'middle' }, svg).textContent = '90°';
    el('text', { x: gx + GR + 14, y: gy + 4, class: 'cd-lbl', 'text-anchor': 'middle' }, svg).textContent = '0°';
    el('text', { x: gx, y: gy + 26, class: 'cd-lbl', 'text-anchor': 'middle' }, svg)
      .textContent = labels.gauge || 'mean angle, random pair';
    el('text', { x: gx, y: gy + 42, class: 'cd-lbl', 'text-anchor': 'middle' }, svg).textContent = `d = ${dim}`;
    const needle = el('line', { x1: gx, y1: gy, x2: gx, y2: gy - GR, class: 'cd-needle' }, svg);
    // the readouts sit to the LEFT of the pivot, where the needle never reaches (it sweeps 0°–90°)
    const cosLbl = el('text', { x: gx - 16, y: gy - 26, class: 'cd-cos', 'text-anchor': 'end' }, svg);
    const angLbl = el('text', { x: gx - 16, y: gy - 4, class: 'cd-ang', 'text-anchor': 'end' }, svg);

    // ── the knob track: c/σ from the smallest to the largest grid stop ─────────────────────────
    const tx0 = box.x, tx1 = box.x + box.w, ty = 306;
    const smax = grid[grid.length - 1] || 1;
    const tpos = (s) => tx0 + (s / smax) * (tx1 - tx0);
    el('line', { x1: tx0, y1: ty, x2: tx1, y2: ty, class: 'cd-track' }, svg);
    const trackOn = el('line', { x1: tx0, y1: ty, x2: tx0, y2: ty, class: 'cd-track-on' }, svg);
    const knob = el('circle', { cx: tx0, cy: ty, r: 8, class: 'cd-knob' }, svg);
    el('text', { x: tx0, y: ty + 24, class: 'cd-lbl' }, svg).textContent = 'c/σ = 0';
    el('text', { x: tx1, y: ty + 24, class: 'cd-lbl', 'text-anchor': 'end' }, svg).textContent = `c/σ = ${f2(smax)}`;
    const snrLbl = el('text', { x: (tx0 + tx1) / 2, y: ty - 14, class: 'cd-snr', 'text-anchor': 'middle' }, svg);

    // ── the d-sweep readout (step 3): one row per dimension, same c/σ ─────────────────────────
    const SWX = 352, SWY = 262;
    const dimRows = dims.map((dd, i) => el('text', { x: SWX, y: SWY + i * 20, class: 'cd-dimrow is-off' }, svg));
    const formula = el('text', { x: SWX, y: SWY + dims.length * 20 + 12, class: 'cd-formula' }, svg);

    return function update(k) {
      const plan = PLAN[Math.max(0, Math.min(PLAN.length - 1, k))];
      const cell = at(plan.snr, dim);
      const pts = ptsFor(plan.snr, plan.centered ? 'centered' : 'raw');

      // view: always keep the origin in frame — a square window spanning the cloud AND (0,0)
      let lo = -3.2, hi = 3.2;
      pts.forEach((p) => { lo = Math.min(lo, p[0], p[1]); hi = Math.max(hi, p[0], p[1]); });
      lo -= 1; hi += 1;
      const side = Math.min(box.w, box.h);
      const ox = box.x + (box.w - side) / 2, oy = box.y + (box.h - side) / 2;
      const sx2 = (v) => ox + ((v - lo) / (hi - lo)) * side;
      const sy2 = (v) => oy + side - ((v - lo) / (hi - lo)) * side;
      const zx = sx2(0), zy = sy2(0);
      axX.setAttribute('x1', ox); axX.setAttribute('y1', zy);
      axX.setAttribute('x2', ox + side); axX.setAttribute('y2', zy);
      axY.setAttribute('x1', zx); axY.setAttribute('y1', oy);
      axY.setAttribute('x2', zx); axY.setAttribute('y2', oy + side);
      originLbl.setAttribute('x', zx - 9); originLbl.setAttribute('y', zy + 13);
      dots.forEach((c, i) => {
        const p = pts[i] || [0, 0];
        c.setAttribute('cx', sx2(p[0]).toFixed(1));
        c.setAttribute('cy', sy2(p[1]).toFixed(1));
      });
      // The wedge the origin actually sees. Angles live on a circle, so the hull is the COMPLEMENT
      // of the widest empty gap — taking min/max of atan2 would tear the cloud apart at ±π.
      const angs = pts.map((p) => Math.atan2(p[1], p[0])).sort((a, b) => a - b);
      let span = Infinity, from = 0;
      if (angs.length > 1) {
        let gap = -1, gi = 0;
        for (let i = 0; i < angs.length; i += 1) {
          const nxt = i === angs.length - 1 ? angs[0] + 2 * Math.PI : angs[i + 1];
          if (nxt - angs[i] > gap) { gap = nxt - angs[i]; gi = i; }
        }
        from = angs[(gi + 1) % angs.length];
        span = 2 * Math.PI - gap;
      }
      if (span <= 2.6) {                                 // ≈150°: any wider and it is not a wedge
        const R2 = side * 0.7, to = from + span;
        wedge.setAttribute('d', `M ${zx} ${zy} L ${(zx + R2 * Math.cos(from)).toFixed(1)} ` +
          `${(zy - R2 * Math.sin(from)).toFixed(1)} A ${R2.toFixed(1)} ${R2.toFixed(1)} 0 0 0 ` +
          `${(zx + R2 * Math.cos(to)).toFixed(1)} ${(zy - R2 * Math.sin(to)).toFixed(1)} Z`);
      } else {
        wedge.setAttribute('d', '');
      }

      const cosv = plan.centered ? cell.centeredCos : cell.meanPairCos;
      const angv = plan.centered
        ? Math.acos(Math.max(-1, Math.min(1, cosv || 0))) * 180 / Math.PI
        : cell.angleDeg;
      const a = (angv || 0) * Math.PI / 180;
      needle.setAttribute('x2', (gx + GR * Math.cos(a)).toFixed(1));
      needle.setAttribute('y2', (gy - GR * Math.sin(a)).toFixed(1));
      cosLbl.textContent = `cos = ${f2(cosv)}`;
      angLbl.textContent = `${(angv || 0).toFixed(1)}°`;

      const sx = tpos(plan.snr);
      trackOn.setAttribute('x2', sx.toFixed(1));
      knob.setAttribute('cx', sx.toFixed(1));
      snrLbl.textContent = plan.centered
        ? `c/σ = ${f2(plan.snr)} − μ`
        : `c/σ = ${f2(plan.snr)}   ·   d = ${dim}`;

      dimRows.forEach((t, i) => {
        const dd = dims[i];
        const c2 = at(plan.snr, dd);
        t.textContent = plan.sweep ? `d = ${String(dd).padStart(3, ' ')}   cos = ${f4(c2.meanPairCos)}` : '';
        t.setAttribute('class', 'cd-dimrow');
      });
      formula.textContent = plan.sweep ? (labels.invariant || 'E[cos] = c²/(c²+σ²) — no d') : '';
    };
  },
});
