/* bpe-steps/logic.js — L2 'climb-bpe-steps' beat: WATCH the BPE training loop run.

   The sibling bpe-merge-ledger widget shows only the FINAL learned merges (a result). This one
   performs the loop the deck walks live: split words into chars + </w>, COUNT adjacent pairs
   weighted by word frequency, PICK the most frequent pair (ties flagged), MERGE it, RE-TOKENIZE,
   repeat — advancing one merge per scroll step. Numbers come from data/l2-bpe-steps.json (the
   source of truth, generated by _research/gen_bpe_steps.py; e s = 6+3 = 9, l o = 5+2 = 7, ...).

   DRIVER-AGNOSTIC (REFERENCE_IMPL_L2 a.6): exposes setStep(k)/maxStep, binds NO keyboard and NO
   scroll — the SLIDE driver (deck arrow keys) and the BOOK driver (Scrollama) both call setStep(k).
   All human text comes from i18n keys in `labels`.

   Built on the shared widgets/_widget-base.js factory (wgt-root/wgt-fade host, caption/counter
   scaffold, the setStep clamp + host.dataset.step, esc()). render() builds the panel scaffold and
   returns an update(k) that re-draws the three regions for step k:
     • corpus   — one row per word: word^freq  →  its current token chips,
     • tally    — the adjacent-pair frequency table, winner row highlighted, ties tagged,
     • merge    — the chosen rule  left + right → joined  (count), the working spelled out.

   PHASE MODEL (audit #0): each of the five merges is WATCHED in two sub-states so the algorithm
   reads as a running loop, not a sequence of finished results. step k → mergeIdx = ⌊k/2⌋, and
   phase = k % 2:
     • phase A (count)  — corpus still in tokensBefore, the pair tally drawn with NO winner
                          highlight + NO merge rule ("count the pairs"),
     • phase B (merge)  — the winner is flagged, the merge rule + working appear, and the corpus
                          swaps to tokensAfter ("merge → re-tokenize"). The pick visibly causes
                          the re-split.
   maxStep = 9 (five merges × two phases, steps 0..9). */
import { defineWidget, esc } from '../_widget-base.js';

export const mountBpeSteps = defineWidget({
  id: 'bpe-steps',
  rootClass: 'bps-root',
  exportName: 'mountBpeSteps',
  maxStep: 9,
  render({ host, data, labels }) {
    const steps = data.steps || [];
    const eow = data.eow || '</w>';

    const panel = document.createElement('div');
    panel.className = 'wgt-panel bps-panel';
    host.appendChild(panel);

    // ── region 1: corpus token rows ─────────────────────────────────────────
    const corpus = document.createElement('div');
    corpus.className = 'bps-region bps-corpus';
    const corpusHead = document.createElement('div');
    corpusHead.className = 'bps-head';
    corpusHead.textContent = labels.corpusHead || 'Corpus — current tokens';
    corpus.appendChild(corpusHead);
    const corpusBody = document.createElement('div');
    corpusBody.className = 'bps-corpus-body';
    corpus.appendChild(corpusBody);
    panel.appendChild(corpus);

    // ── region 2: pair-count tally ──────────────────────────────────────────
    const tally = document.createElement('div');
    tally.className = 'bps-region bps-tally';
    const tallyHead = document.createElement('div');
    tallyHead.className = 'bps-head';
    tallyHead.textContent = labels.tallyHead || 'Count adjacent pairs';
    tally.appendChild(tallyHead);
    const tallyBody = document.createElement('div');
    tallyBody.className = 'bps-tally-body';
    tally.appendChild(tallyBody);
    panel.appendChild(tally);

    // ── region 3: the merge rule applied ────────────────────────────────────
    const merge = document.createElement('div');
    merge.className = 'bps-region bps-merge';
    const mergeHead = document.createElement('div');
    mergeHead.className = 'bps-head';
    mergeHead.textContent = labels.mergeHead || 'Merge the winner';
    merge.appendChild(mergeHead);
    const mergeBody = document.createElement('div');
    mergeBody.className = 'bps-merge-body';
    merge.appendChild(mergeBody);
    panel.appendChild(merge);

    // a single token chip; `kind` adds an accent class (e.g. the just-merged piece)
    const chip = (text, kind) => {
      const c = document.createElement('span');
      c.className = 'bps-tok' + (kind ? ' bps-tok--' + kind : '');
      // render the end-of-word marker compactly but verbatim
      c.textContent = text;
      if (text === eow) c.classList.add('bps-tok--eow');
      return c;
    };

    // draw the corpus rows for one step. In the COUNT phase (before=true) the corpus is still in
    // its pre-merge tokenization with nothing highlighted; in the MERGE phase it swaps to the
    // re-tokenized state with the just-merged piece accented — so the pick visibly re-splits.
    function drawCorpus(st, before) {
      corpusBody.innerHTML = '';
      const rows = before
        ? (st.tokensBefore || st.tokensAfter || [])
        : (st.tokensAfter || st.tokensBefore || []);
      const winnerJoined = before ? null : (st.winner ? st.winner.joined : null);
      rows.forEach((entry) => {
        const row = document.createElement('div');
        row.className = 'bps-word-row';
        const lab = document.createElement('span');
        lab.className = 'bps-word-lab';
        lab.innerHTML = `<span class="bps-word">${esc(entry.word)}</span>` +
          `<span class="bps-freq">${esc(labels.freqMark || '×')}${esc(entry.freq)}</span>`;
        row.appendChild(lab);
        const toks = document.createElement('span');
        toks.className = 'bps-toks';
        (entry.tokens || []).forEach((t) => {
          // highlight the chip that is the piece we just merged this step
          toks.appendChild(chip(t, t === winnerJoined ? 'merged' : ''));
        });
        row.appendChild(toks);
        corpusBody.appendChild(row);
      });
    }

    // draw the pair-frequency table for one step. In the COUNT phase (showWinner=false) the bars
    // are shown with NO winner highlight and NO tags — the reader just reads the counts. In the
    // MERGE phase the max row lights up + tie rows are tagged, so the pick is a visible event.
    function drawTally(st, showWinner) {
      tallyBody.innerHTML = '';
      const tieSet = new Set(st.tie || []);
      (st.tally || []).forEach((p) => {
        const isWin = showWinner && p.isWinner;
        const r = document.createElement('div');
        r.className = 'bps-pair-row' + (isWin ? ' is-winner' : '');
        const isTie = showWinner && tieSet.has(p.joined) && !p.isWinner;
        if (isTie) r.classList.add('is-tie');
        const pairCell = document.createElement('span');
        pairCell.className = 'bps-pair';
        pairCell.innerHTML =
          `<span class="bps-tok bps-tok--mini">${esc(p.left)}</span>` +
          `<span class="bps-op">·</span>` +
          `<span class="bps-tok bps-tok--mini">${esc(p.right)}</span>`;
        r.appendChild(pairCell);
        const bar = document.createElement('span');
        bar.className = 'bps-bar';
        const fill = document.createElement('span');
        fill.className = 'bps-bar-fill';
        const top = (st.tally && st.tally[0] && st.tally[0].count) || p.count || 1;
        fill.style.width = Math.max(6, Math.round((p.count / top) * 100)) + '%';
        bar.appendChild(fill);
        r.appendChild(bar);
        const cnt = document.createElement('span');
        cnt.className = 'bps-count';
        cnt.textContent = String(p.count);
        r.appendChild(cnt);
        const tag = document.createElement('span');
        tag.className = 'bps-tag';
        if (isWin) {
          // Honest tie semantics (audit #2): if the winner is ITSELF part of the tie, say so —
          // it was not the lone maximum, it was one of several equal maxima broken by rule order.
          const winnerTied = tieSet.has(p.joined);
          tag.textContent = winnerTied
            ? (labels.winnerTieTag || 'max·tie-break')
            : (labels.winnerTag || 'max');
          tag.classList.add('bps-tag--win');
        } else if (isTie) {
          tag.textContent = labels.tieTag || 'tie';
          tag.classList.add('bps-tag--tie');
        }
        r.appendChild(tag);
        tallyBody.appendChild(r);
      });
    }

    // Apply the LEARNED merges to a word the corpus never contained — the payoff the caption
    // promises ("no [UNK]"). Nothing is hard-coded: the pieces are derived by running the merge
    // list from data/ in rank order, so the panel can never disagree with the trace above it.
    function encodeUnseen(word, merges) {
      let toks = word.split('').concat([eow]);
      merges.forEach((m) => {
        for (let i = 0; i < toks.length - 1; ) {
          if (toks[i] === m.left && toks[i + 1] === m.right) toks.splice(i, 2, m.joined);
          else i += 1;
        }
      });
      return toks;
    }

    // draw the merge rule + its weighted-count working for one step
    function drawMerge(st) {
      mergeBody.innerHTML = '';
      const w = st.winner;
      if (!w) return;
      const rule = document.createElement('div');
      rule.className = 'bps-rule';
      rule.innerHTML =
        `<span class="bps-rule-lab">${esc(labels.mergeRule || 'rule')}</span>` +
        `<span class="bps-tok">${esc(w.left)}</span>` +
        `<span class="bps-op">+</span>` +
        `<span class="bps-tok">${esc(w.right)}</span>` +
        `<span class="bps-op bps-arrow">→</span>` +
        `<span class="bps-tok bps-tok--merged">${esc(w.joined)}</span>`;
      mergeBody.appendChild(rule);
      // the working: "= newest 6 + widest 3 = 9"
      const bd = w.breakdown || [];
      if (bd.length) {
        const work = document.createElement('div');
        work.className = 'bps-work';
        const terms = bd.map((b) =>
          `<span class="bps-term"><span class="bps-word">${esc(b.word)}</span>` +
          `<span class="bps-freq">${esc(labels.freqMark || '×')}${esc(b.freq)}</span></span>`).join('<span class="bps-op">+</span>');
        work.innerHTML = `<span class="bps-op">=</span>${terms}` +
          `<span class="bps-op">=</span><span class="bps-sum">${esc(w.count)}</span>`;
        mergeBody.appendChild(work);
      }
    }

    // per-step update (factory clamps k to [0,maxStep] and owns the scrolly caption/counter).
    // Two phases per merge: even k = COUNT (read the tally), odd k = MERGE (pick + re-tokenize).
    return function update(k) {
      const mergeIdx = Math.min(steps.length - 1, Math.floor(k / 2));
      const isMergePhase = (k % 2) === 1;          // odd step → the merge half of this merge
      const st = steps[mergeIdx] || steps[steps.length - 1];
      if (!st) return;
      drawCorpus(st, !isMergePhase);               // count phase shows tokensBefore (no highlight)
      drawTally(st, isMergePhase);                 // winner/tie tags appear only in the merge phase
      if (isMergePhase) {
        drawMerge(st);
        // Last step only: the whole point of the loop — an unseen word falls apart into pieces
        // the loop just learned. Before this the merge list is incomplete and the split would lie.
        if (k === 9 && (data.merges || []).length) {
          const word = data.unseenWord || 'lowest';
          const pieces = encodeUnseen(word, data.merges);
          const row = document.createElement('div');
          row.className = 'bps-unseen';
          row.innerHTML =
            `<span class="bps-rule-lab">${esc(labels.unseenLab || 'unseen word')}</span>` +
            `<span class="bps-word">${esc(word)}</span>` +
            `<span class="bps-op bps-arrow">→</span>` +
            pieces.map((t) => `<span class="bps-tok bps-tok--merged">${esc(t)}</span>`).join('') +
            `<span class="bps-unseen-note">${esc(labels.noUnk || 'no [UNK]')}</span>`;
          mergeBody.appendChild(row);
        }
      } else {
        // COUNT phase: the merge region is not yet decided — show a one-line prompt so the region
        // never collapses to empty, and the "pick → merge" only happens on the next step.
        mergeBody.innerHTML = '';
        const hint = document.createElement('div');
        hint.className = 'bps-merge-hint';
        hint.textContent = labels.countHint || 'Pick the max next →';
        mergeBody.appendChild(hint);
      }
    };
  },
});
