/* bpe-steps/logic.js — L2 'climb-bpe-steps' beat: WATCH the BPE training loop run.

   The sibling bpe-merge-ledger widget shows only the FINAL learned merges (a result). This one
   performs the loop the deck walks live: split words into chars + </w>, COUNT adjacent pairs
   weighted by word frequency, PICK the most frequent pair (ties flagged), MERGE it, RE-TOKENIZE,
   repeat — advancing one merge per scroll step. Numbers come from data/l2-bpe-steps.json (the
   source of truth, generated by _research/gen_bpe_steps.py; e s = 6+3 = 9, l o = 5+2 = 7, ...).

   DRIVER-AGNOSTIC (REFERENCE_IMPL_L2 a.6): exposes setStep(k)/maxStep, binds NO keyboard and NO
   scroll — the SLIDE driver (deck arrow keys) and the BOOK driver (Scrollama) both call setStep(k).
   All human text comes from i18n keys in `labels`.

   Built on the shared widgets/_widget-base.js factory (wgt-root/wgt-fade host, caption/counter
   scaffold, the setStep clamp + host.dataset.step, esc()). render() builds the panel scaffold and
   returns an update(k) that re-draws the three regions for step k:
     • corpus   — one row per word: word^freq  →  its current token chips (after this merge),
     • tally    — the adjacent-pair frequency table, winner row highlighted, ties tagged,
     • merge    — the chosen rule  left + right → joined  (count), the working spelled out.
   maxStep = 4 (five merges, steps 0..4). */
import { defineWidget, esc } from '../_widget-base.js';

export const mountBpeSteps = defineWidget({
  id: 'bpe-steps',
  rootClass: 'bps-root',
  exportName: 'mountBpeSteps',
  maxStep: 4,
  render({ host, data, labels }) {
    const steps = data.steps || [];
    const eow = data.eow || '</w>';

    const panel = document.createElement('div');
    panel.className = 'wgt-panel bps-panel';
    host.appendChild(panel);

    // ── region 1: corpus token rows ─────────────────────────────────────────
    const corpus = document.createElement('div');
    corpus.className = 'bps-region bps-corpus';
    const corpusHead = document.createElement('div');
    corpusHead.className = 'bps-head';
    corpusHead.textContent = labels.corpusHead || 'Corpus — current tokens';
    corpus.appendChild(corpusHead);
    const corpusBody = document.createElement('div');
    corpusBody.className = 'bps-corpus-body';
    corpus.appendChild(corpusBody);
    panel.appendChild(corpus);

    // ── region 2: pair-count tally ──────────────────────────────────────────
    const tally = document.createElement('div');
    tally.className = 'bps-region bps-tally';
    const tallyHead = document.createElement('div');
    tallyHead.className = 'bps-head';
    tallyHead.textContent = labels.tallyHead || 'Count adjacent pairs';
    tally.appendChild(tallyHead);
    const tallyBody = document.createElement('div');
    tallyBody.className = 'bps-tally-body';
    tally.appendChild(tallyBody);
    panel.appendChild(tally);

    // ── region 3: the merge rule applied ────────────────────────────────────
    const merge = document.createElement('div');
    merge.className = 'bps-region bps-merge';
    const mergeHead = document.createElement('div');
    mergeHead.className = 'bps-head';
    mergeHead.textContent = labels.mergeHead || 'Merge the winner';
    merge.appendChild(mergeHead);
    const mergeBody = document.createElement('div');
    mergeBody.className = 'bps-merge-body';
    merge.appendChild(mergeBody);
    panel.appendChild(merge);

    // a single token chip; `kind` adds an accent class (e.g. the just-merged piece)
    const chip = (text, kind) => {
      const c = document.createElement('span');
      c.className = 'bps-tok' + (kind ? ' bps-tok--' + kind : '');
      // render the end-of-word marker compactly but verbatim
      c.textContent = text;
      if (text === eow) c.classList.add('bps-tok--eow');
      return c;
    };

    // draw the corpus rows for one step, marking which chips are the merged token
    function drawCorpus(st) {
      corpusBody.innerHTML = '';
      const rows = st.tokensAfter || st.tokensBefore || [];
      const winnerJoined = st.winner ? st.winner.joined : null;
      rows.forEach((entry) => {
        const row = document.createElement('div');
        row.className = 'bps-word-row';
        const lab = document.createElement('span');
        lab.className = 'bps-word-lab';
        lab.innerHTML = `<span class="bps-word">${esc(entry.word)}</span>` +
          `<span class="bps-freq">${esc(labels.freqMark || '×')}${esc(entry.freq)}</span>`;
        row.appendChild(lab);
        const toks = document.createElement('span');
        toks.className = 'bps-toks';
        (entry.tokens || []).forEach((t) => {
          // highlight the chip that is the piece we just merged this step
          toks.appendChild(chip(t, t === winnerJoined ? 'merged' : ''));
        });
        row.appendChild(toks);
        corpusBody.appendChild(row);
      });
    }

    // draw the pair-frequency table for one step, highlighting the winner + tie rows
    function drawTally(st) {
      tallyBody.innerHTML = '';
      const tieSet = new Set(st.tie || []);
      (st.tally || []).forEach((p) => {
        const r = document.createElement('div');
        r.className = 'bps-pair-row' + (p.isWinner ? ' is-winner' : '');
        const isTie = tieSet.has(p.joined) && !p.isWinner;
        if (isTie) r.classList.add('is-tie');
        const pairCell = document.createElement('span');
        pairCell.className = 'bps-pair';
        pairCell.innerHTML =
          `<span class="bps-tok bps-tok--mini">${esc(p.left)}</span>` +
          `<span class="bps-op">·</span>` +
          `<span class="bps-tok bps-tok--mini">${esc(p.right)}</span>`;
        r.appendChild(pairCell);
        const bar = document.createElement('span');
        bar.className = 'bps-bar';
        const fill = document.createElement('span');
        fill.className = 'bps-bar-fill';
        const top = (st.tally && st.tally[0] && st.tally[0].count) || p.count || 1;
        fill.style.width = Math.max(6, Math.round((p.count / top) * 100)) + '%';
        bar.appendChild(fill);
        r.appendChild(bar);
        const cnt = document.createElement('span');
        cnt.className = 'bps-count';
        cnt.textContent = String(p.count);
        r.appendChild(cnt);
        const tag = document.createElement('span');
        tag.className = 'bps-tag';
        if (p.isWinner) { tag.textContent = labels.winnerTag || 'max'; tag.classList.add('bps-tag--win'); }
        else if (isTie) { tag.textContent = labels.tieTag || 'tie'; tag.classList.add('bps-tag--tie'); }
        r.appendChild(tag);
        tallyBody.appendChild(r);
      });
    }

    // draw the merge rule + its weighted-count working for one step
    function drawMerge(st) {
      mergeBody.innerHTML = '';
      const w = st.winner;
      if (!w) return;
      const rule = document.createElement('div');
      rule.className = 'bps-rule';
      rule.innerHTML =
        `<span class="bps-rule-lab">${esc(labels.mergeRule || 'rule')}</span>` +
        `<span class="bps-tok">${esc(w.left)}</span>` +
        `<span class="bps-op">+</span>` +
        `<span class="bps-tok">${esc(w.right)}</span>` +
        `<span class="bps-op bps-arrow">→</span>` +
        `<span class="bps-tok bps-tok--merged">${esc(w.joined)}</span>`;
      mergeBody.appendChild(rule);
      // the working: "= newest 6 + widest 3 = 9"
      const bd = w.breakdown || [];
      if (bd.length) {
        const work = document.createElement('div');
        work.className = 'bps-work';
        const terms = bd.map((b) =>
          `<span class="bps-term"><span class="bps-word">${esc(b.word)}</span>` +
          `<span class="bps-freq">${esc(labels.freqMark || '×')}${esc(b.freq)}</span></span>`).join('<span class="bps-op">+</span>');
        work.innerHTML = `<span class="bps-op">=</span>${terms}` +
          `<span class="bps-op">=</span><span class="bps-sum">${esc(w.count)}</span>`;
        mergeBody.appendChild(work);
      }
    }

    // per-step update (factory clamps k to [0,maxStep] and owns the scrolly caption/counter)
    return function update(k) {
      const st = steps[k] || steps[steps.length - 1];
      if (!st) return;
      drawCorpus(st);
      drawTally(st);
      drawMerge(st);
    };
  },
});
