// content/book/l1.js — "The Lost Record" chapter (the L1 arc), per narrative/L1.md.
// Reuses the retrieve-rank-funnel and pos-bias-curve widgets. EN canonical + RU; TT falls back.
// NARRATIVE_METHOD: P1 hook, P2 creatures (Lexical Gremlin, Iceberg, Goodhart), P4 scale, P12 callback.

export default {
  id: '01',
  catchphrase: 'The Lost Record',
  beats: [
    {
      id: 'hook-lost-record', kind: 'prose',
      heading: { en: 'The Lost Record', ru: 'Потерянная запись' },
      img: 'L1/L1-06-needle.png', imgPos: 'hero',
      imgAlt: {
        en: 'Serega adrift on a raft in an ocean of bytes, reaching for the one document he needs',
        ru: 'Серёга на плоту в океане байтов тянется к единственному нужному ему документу',
      },
      imgCaption: {
        en: 'The search problem in one picture: not too few records — too many. You need exactly one.',
        ru: 'Задача поиска одной картинкой: записей не мало — их слишком много. Тебе нужна ровно одна.',
      },
      body: {
        en: [
          "I'm Serega, and somewhere in a sea of a billion documents there is exactly one record I need. No map, no index card, no helpful librarian. Just me, a query box, and an ocean of bytes. Back in 1982 — before the web even existed — John Naisbitt wrote that we are *drowning in information but starved for knowledge*. That is the whole problem in one line: the bottleneck was never storing the data, it was finding the one slice that answers the question I have *right now*. Storage is cheap. Attention is not.",
          "So here is what \"finding\" actually means, told honestly. In my head I have an **information need** — a rich, context-soaked want: I'm a second-year student, it's exam week, I want a *gentle* explanation of how vaccines train the immune system, in English, that I can read in five minutes. Then I squeeze all of that down into the two or three words I type into the box. The average web query is about 2.3–2.9 words long. Everything else — my level, my deadline, my language, my intent — gets thrown away at the door. The system never sees my need. It sees the two words. **Ranking is the attempt to reconstruct a rich need from a lossy signal** — like guessing the painting from a thumbnail the size of a postage stamp.",
          "And because the need is squeezed through that funnel, the answer can't be a simple yes/no filter. Relevance isn't binary; it's *graded*. Picture a five-point scale — Perfect, Excellent, Good, Fair, Bad — the same scale human judges use to label search results. A binary filter throws all of that structure away: it can only say \"matches / doesn't.\" A **ranking** keeps it: the best document goes to position 1, where almost all the attention lives, and the merely-okay ones sink. Users read top-down and rarely past the first few results, so the *order is the product*. That's the difference between search and a database. A database (SQL) answers \"which rows exactly match this predicate?\" — the result is a *set*, order doesn't matter, correctness is exact and verifiable. Search answers \"which document *best* satisfies a need I can only guess at?\" — the result is an ordered list, correctness is graded and subjective, and the failure mode is the scary one: it fails *silently*. A bad ranking still returns ten plausible-looking links. Nothing throws an exception. The user just quietly doesn't find what they came for.",
          "One more reframing before we set sail, because it pays off all term: search and recommendation are almost the same machine. Search is **PULL** — you have an explicit query, an active need, a loud signal of intent. Recommendation is **PUSH** — there's no query at all; TikTok's \"For You\" feed *guesses* the query you never typed, inferring intent from watch time, dwell, and history. They sit on one continuum, explicit → implicit, and architecturally they *converge*: both run a candidate-generation → ranking cascade. Recsys is just search where the query is implicit. So everything we learn about ranking transfers to half the internet.",
          "Two missions today, then. First: *find it* — that's **information retrieval (IR)**. Second, the harder one: build the machine that keeps finding it, for every user, every day, after I've gone to sleep — that's **ML system design**. Find the needle in the cosmos; then build the thing that keeps finding needles forever.",
        ],
        ru: [
          'Я Серёга, и где-то в море из миллиарда документов есть ровно одна запись, которая мне нужна. Ни карты, ни каталожной карточки, ни услужливого библиотекаря. Только я, строка запроса и океан байтов. Ещё в 1982-м — до того, как появился веб — Джон Нейсбитт написал, что мы *тонем в информации, но голодаем по знанию*. Вот вся задача в одной фразе: узким местом никогда не было *хранение* данных — им был *поиск* того единственного кусочка, который отвечает на вопрос, стоящий передо мной *прямо сейчас*. Хранилище дёшево. Внимание — нет.',
          'Так вот что на самом деле значит «найти», если честно. У меня в голове есть **информационная потребность** — богатое, пропитанное контекстом желание: я второкурсник, идёт сессия, я хочу *простое* объяснение того, как вакцины тренируют иммунитет, на английском, чтобы прочитать за пять минут. А потом я сжимаю всё это в два-три слова, которые набираю в строке. Средний веб-запрос — около 2.3–2.9 слова. Всё остальное — мой уровень, мой дедлайн, мой язык, моё намерение — выбрасывается на пороге. Система никогда не видит мою потребность. Она видит два слова. **Ранжирование — это попытка восстановить богатую потребность из сигнала с потерями** — как угадывать картину по миниатюре размером с почтовую марку.',
          'И поскольку потребность продавлена через эту воронку, ответ не может быть простым фильтром «да/нет». Релевантность не бинарна; она *градуирована*. Представь пятибалльную шкалу — Perfect, Excellent, Good, Fair, Bad — ту самую, которой люди-асессоры размечают результаты поиска. Бинарный фильтр выбрасывает всю эту структуру: он умеет только «подходит / не подходит». **Ранжирование** её сохраняет: лучший документ идёт на позицию 1, где живёт почти всё внимание, а средненькие тонут. Пользователи читают сверху вниз и редко заглядывают дальше первых результатов, так что *порядок и есть продукт*. В этом разница между поиском и базой данных. База (SQL) отвечает на «какие строки точно подходят под предикат?» — результат это *множество*, порядок неважен, корректность точна и проверяема. Поиск отвечает на «какой документ *лучше всего* удовлетворяет потребность, о которой я могу лишь догадываться?» — результат это упорядоченный список, корректность градуирована и субъективна, а режим отказа самый коварный: поиск ломается *молча*. Плохое ранжирование всё равно вернёт десять правдоподобных ссылок. Никакого исключения не выбросится. Пользователь просто тихо не находит того, за чем пришёл.',
          'Ещё одна переформулировка перед отплытием, потому что она окупится весь семестр: поиск и рекомендации — почти одна и та же машина. Поиск — это **PULL**: у тебя есть явный запрос, активная потребность, громкий сигнал намерения. Рекомендации — это **PUSH**: запроса нет вовсе; лента «Для тебя» в TikTok *угадывает* запрос, который ты не набирал, выводя намерение из времени просмотра, задержки на видео и истории. Они лежат на одном континууме, явное → неявное, и архитектурно *сходятся*: обе гоняют каскад «генерация кандидатов → ранжирование». Рекомендации — это просто поиск, где запрос неявный. Так что всё, что мы узнаём про ранжирование, переносится на половину интернета.',
          'Итак, сегодня две задачи. Первая: *найти её* — это **информационный поиск (IR)**. Вторая, посложнее: построить машину, которая продолжает находить её — для каждого пользователя, каждый день, после того как я ушёл спать — это **дизайн ML-систем**. Найти иголку в космосе; а потом построить то, что будет находить иголки вечно.',
        ],
      },
    },
    {
      id: 'stakes-products', kind: 'prose',
      heading: { en: 'Three products, one retrieval problem', ru: 'Три продукта, одна задача поиска' },
      body: {
        en: [
          "Before we set sail, look at where this machine already runs, because it's the same machine wearing three costumes. Put **Google**, **Ozon**, and **Yandex Neuro** side by side and the surfaces could not look more different — yet underneath each is *a query, a corpus, a ranker*, in that order.",
          "On **Google** (web search) the user wants a credible page, the corpus is web documents, and the answer is delivered as ten ordered blue links. On **Ozon** (e-commerce) the user wants an item to buy, the corpus is product listings, and the answer is a grid of products, ordered. On **Yandex Neuro** (a generative answer engine) the user wants a direct answer, the corpus is passages pulled from retrieved pages, and the answer is one fluent paragraph with citations. Three wants, three corpora, three presentation layers — but **the same pipeline underneath**: retrieve candidates, rank them, present the top few. Swap the corpus and the surface; the spine never moves.",
          "Notice the odd one out, because it foreshadows the very end of the course. Yandex Neuro bolts a large language model *on top of* retrieval. When the retrieval grounding is good, the paragraph is both fluent and correct. When the grounding fails, the model stays fluent and goes confidently wrong — the *confident horse with eight legs*. An LLM with no retrieval is an eloquent liar; retrieval is what keeps it honest. That coupling — retriever in front of generator — is **retrieval-augmented generation**, named by [Lewis et al. (2020)](https://arxiv.org/abs/2005.11401), and it's where this whole expedition lands twelve lectures from now. For today, just hold the shape: every product on this slide is a query, a corpus, and a ranker.",
        ],
        ru: [
          'Прежде чем отплыть, посмотри, где эта машина уже работает, потому что это одна и та же машина в трёх костюмах. Поставь рядом **Google**, **Ozon** и **Яндекс Нейро** — и поверхности окажутся совершенно разными, а под каждой — *запрос, корпус, ранкер*, именно в этом порядке.',
          'В **Google** (веб-поиск) пользователь хочет авторитетную страницу, корпус — это веб-документы, а ответ выдаётся как десять упорядоченных синих ссылок. В **Ozon** (электронная коммерция) пользователь хочет товар для покупки, корпус — это карточки товаров, а ответ — сетка продуктов, упорядоченная. В **Яндекс Нейро** (генеративный движок ответов) пользователь хочет прямой ответ, корпус — это пассажи, вытащенные из найденных страниц, а ответ — один связный абзац со ссылками. Три желания, три корпуса, три слоя подачи — но **один и тот же конвейер под ними**: извлечь кандидатов, отранжировать их, показать верхушку. Меняй корпус и поверхность; хребет остаётся на месте.',
          'Заметь белую ворону, потому что она предвещает самый конец курса. Яндекс Нейро прикручивает большую языковую модель *поверх* поиска. Когда заземление поиском хорошее, абзац и связный, и верный. Когда заземление подводит, модель остаётся связной и уверенно ошибается — *уверенная лошадь с восемью ногами*. LLM без поиска — красноречивый лжец; поиск — то, что держит её честной. Эта связка — ретривер перед генератором — называется **поиск-дополненная генерация (RAG)**, имя ей дали [Lewis et al. (2020)](https://arxiv.org/abs/2005.11401), и именно туда приходит вся эта экспедиция через двенадцать лекций. На сегодня просто держи форму: каждый продукт на этом слайде — это запрос, корпус и ранкер.',
        ],
      },
    },
    {
      id: 'problem-gremlin', kind: 'prose',
      heading: { en: 'The Lexical Gremlin', ru: 'Лексический Гремлин' },
      img: 'L1/L1-24-lexical-gremlin.png', imgPos: 'scene',
      imgAlt: {
        en: 'The Lexical Gremlin holds a BM25 brick wall between "couch" and "sofa"; the word "jaguar" splits into cat, car, laptop',
        ru: 'Лексический Гремлин держит кирпичную стену BM25 между «диваном» и «софой»; слово «jaguar» расщепляется на кошку, машину, ноутбук',
      },
      imgCaption: {
        en: 'Two people name the same thing the same word under 20% of the time (Furnas ’87). The Gremlin lives in that 80% gap.',
        ru: 'Два человека называют одну вещь одним словом меньше чем в 20% случаев (Furnas ’87). Гремлин живёт в этих 80%.',
      },
      body: {
        en: [
          "First obstacle, and he's grinning at me: the **Lexical Gremlin**. He's a small, smug creature whose entire job is to wedge a brick wall between words that mean the same thing. You search \"couch\"; the perfect document says \"sofa\"; the Gremlin makes sure the two never meet. Exact-match search — the kind that just checks whether the document literally contains your query words — loses to a synonym every single time.",
          "This isn't a rare edge case; it's the *number-one* reason search is hard, and it has a name and a number. [Furnas et al. (1987)](https://doi.org/10.1145/32206.32212) measured it (the *vocabulary problem*): ask two people to name the same thing and they pick the **same word less than 20% of the time**. \"Couch\" / \"sofa\" / \"settee.\" \"Soda\" / \"pop\" / \"fizzy drink.\" \"Joggers\" / \"sweatpants.\" The person who *wrote* the document and the person *searching* for it almost never agree on the words — so a system that only matches words is wrong by construction most of the time.",
          "The Gremlin attacks from two directions at once, and it helps to keep them straight. **Synonymy** is the first blade: a relevant document shares *zero* words with your query, so you never retrieve it — that's lost *recall*. Search \"comfortable couch,\" the best result reads \"plush sofa, sleeps two,\" overlap is exactly zero words, and yet it's plainly the right answer. **Polysemy** is the second blade: an *irrelevant* document shares your query word, so junk floods in — that's lost *precision*. Search \"jaguar\" and the word fans out into a cat, a car, and an operating system; search \"python\" and it's a language or a snake. One word, several meanings, and exact match can't tell them apart.",
          "Which kills a tempting belief students arrive with: *\"if a document contains all my query words it must be relevant, and if it's missing one it can't be.\"* Both halves are false. Term overlap is **neither necessary nor sufficient** for relevance. Not sufficient: a page that reads \"java java coffee java cup java\" contains the query \"java tutorial\" perfectly and is pure keyword-stuffed spam. Not necessary: the plush-sofa page answers \"comfortable couch\" with no shared words at all. Term overlap is a weak, biased *proxy* for relevance — useful, cheap, but leaky.",
          "And the damage is measurable in money, not just theory. On e-commerce sites, **10–20% of on-site searches return zero results** — and the usual culprit isn't empty shelves, it's the Gremlin: the shopper typed \"joggers\" and the catalogue only knows \"sweatpants.\" Run a store with 100k searches a month and a 10% zero-result rate, and that's 10,000 high-intent visitors hitting a wall every month. The fix is almost never more inventory; it's teaching the system that those two words mean the same thing. Hold onto the Gremlin — he's the villain who explains *why* we eventually have to give words real *meaning* instead of just matching letters. We'll come back to cage him.",
        ],
        ru: [
          'Первое препятствие, и он мне ухмыляется: **Лексический Гремлин**. Это мелкое самодовольное существо, чья единственная работа — вставлять кирпичную стену между словами, которые значат одно и то же. Ты ищешь «диван»; идеальный документ говорит «софа»; Гремлин следит, чтобы они никогда не встретились. Поиск по точному совпадению — тот, что просто проверяет, содержит ли документ буквально слова твоего запроса — проигрывает синониму каждый раз.',
          'Это не редкий частный случай; это *причина номер один*, почему поиск сложен, и у неё есть имя и число. [Furnas et al. (1987)](https://doi.org/10.1145/32206.32212) измерили это (*проблема словаря*): попроси двух людей назвать одну и ту же вещь — и они выберут **одно слово менее чем в 20% случаев**. «Couch» / «sofa» / «settee». «Soda» / «pop» / «fizzy drink». «Joggers» / «sweatpants». Тот, кто *написал* документ, и тот, кто его *ищет*, почти никогда не сходятся в словах — так что система, которая совпадает лишь по словам, ошибается по построению в большинстве случаев.',
          'Гремлин атакует сразу с двух сторон, и их полезно держать врозь. **Синонимия** — первое лезвие: релевантный документ делит с запросом *ноль* слов, и ты его никогда не извлекаешь — это потеря *полноты (recall)*. Ищешь «удобный диван», лучший результат гласит «мягкая софа, спальное место на двоих», пересечение — ровно ноль слов, и при этом это явно верный ответ. **Полисемия** — второе лезвие: *нерелевантный* документ делит с запросом слово, и валит мусор — это потеря *точности (precision)*. Ищешь «jaguar», и слово расходится на кошку, машину и операционную систему; ищешь «python» — это язык или змея. Одно слово, несколько смыслов, и точное совпадение не различает их.',
          'Что убивает соблазнительное убеждение, с которым студенты приходят: *«если документ содержит все слова моего запроса — он точно релевантен, а если хоть одного нет — точно нет»*. Обе половины ложны. Пересечение по словам **ни необходимо, ни достаточно** для релевантности. Недостаточно: страница «java java coffee java cup java» идеально содержит запрос «java tutorial» и при этом чистый спам с набивкой ключевых слов. Не необходимо: страница про мягкую софу отвечает на «удобный диван» вообще без общих слов. Пересечение по словам — слабый, смещённый *прокси* релевантности: полезный, дешёвый, но дырявый.',
          'И ущерб измеряется в деньгах, а не только в теории. На сайтах электронной коммерции **10–20% поисков на сайте возвращают ноль результатов** — и обычный виновник не пустые полки, а Гремлин: покупатель набрал «joggers», а каталог знает только «sweatpants». Возьми магазин со 100 тыс. поисков в месяц и долей нулевых результатов 10% — это 10 000 высокомотивированных посетителей, упирающихся в стену каждый месяц. Лекарство — почти никогда не больше товара; это научить систему, что эти два слова значат одно. Запомни Гремлина — это злодей, который объясняет, *почему* нам в итоге придётся дать словам настоящий *смысл*, а не просто совпадать по буквам. Мы ещё вернёмся, чтобы посадить его в клетку.',
        ],
      },
    },
    {
      id: 'stakes-scale', kind: 'prose',
      heading: { en: 'A galaxy too big to read', ru: 'Галактика, которую не прочесть' },
      img: 'L1/L1-25-zipf-beach.png', imgPos: 'scene',
      imgAlt: {
        en: 'Zipf long tail drawn as a beach: a few head sandcastles tower over an endless tail of never-seen-before queries',
        ru: 'Длинный хвост Ципфа в виде пляжа: несколько замков-голов возвышаются над бесконечным хвостом запросов, которых никто раньше не видел',
      },
      imgCaption: {
        en: 'Query frequency is Zipfian: a tiny head, an endless tail. You cannot memorise the tail — you must generalise.',
        ru: 'Частота запросов подчиняется Ципфу: крошечная голова, бесконечный хвост. Хвост не выучить — нужно обобщать.',
      },
      body: {
        en: [
          "And the scale is genuinely absurd. The web is on the order of \\(10^{12}\\) **pages** — a trillion. You cannot read everything at query time; a single brute-force scan of the corpus per query would melt any machine and blow every deadline. So the first instinct — \"just pre-compute the answer to every query\" — is dead on arrival, and here's the killer fact that kills it: every day, roughly **15% of the queries a big engine sees are ones it has *never seen before*.** (Google has said this for years — about 25% novel back in 2007, holding near 15% since.) At ~8.5 billion queries a day, 15% novel is on the order of **1.3 billion brand-new queries every single day.** You can't have a cached answer for a query that didn't exist this morning.",
          "Why doesn't the novelty ever run out? Because language is **Zipfian**. Draw query frequency as a beach: a few \"head\" queries — `youtube`, `weather`, `facebook login` — tower up like sandcastles and soak up enormous volume, while behind them stretches an *endless tail* of weird, specific, one-off queries that each get searched once and then maybe never again. `error code 0x80070643 windows 11 update fix`. `why does my sourdough smell like acetone`. The tail isn't a small leftover — most of the *distinct* queries, and a huge share of total intent, live out there. You cannot memorise a tail with no end. **You must generalise** — and that, in one sentence, is the statistical reason search needs machine learning rather than a giant lookup table.",
          "On top of sheer count, the *kind* of want changes from query to query, which is why one ranking can't be right for all of them. [Broder's (2002)](https://doi.org/10.1145/792550.792552) classic taxonomy (from AltaVista logs) splits intent three ways. **Navigational** (~25%): you want one specific place — `facebook login` — and \"good\" means the single right answer at position 1; anything else is failure. **Informational** (~40%): `how vaccines work` — you want to *learn*, so several good, diverse documents beat one; coverage matters more than a single winner. **Transactional** (~35%): `buy iphone 15` — you want to *do* something, and \"good\" means enabling the action. The exact ranking that nails a navigational query is wrong for an informational one. (And note: the percentages wobble between studies, because labelling intent is itself fuzzy — which is exactly why we eventually *learn* intent from behaviour instead of hand-labelling it.)",
          "So tally up what the system is actually up against: a trillion documents, a billion never-before-seen queries a day, a vocabulary where nobody agrees on words, and a user who told you almost nothing. You cannot pre-compute answers; you cannot read everything at query time; you cannot even rely on the words matching. Something has to give. The way out is not a bigger computer — it's a smarter *shape*.",
        ],
        ru: [
          'И масштаб по-настоящему абсурден. Веб — это порядка \\(10^{12}\\) **страниц** — триллион. Всё прочитать в момент запроса нельзя; один грубый перебор корпуса на каждый запрос расплавит любую машину и сорвёт все дедлайны. Так что первый порыв — «просто предвычислить ответ на каждый запрос» — мёртв на старте, и вот убийственный факт, который его добивает: каждый день примерно **15% запросов, которые видит большой движок, — те, что он *никогда раньше не видел*.** (Google говорит это годами — около 25% новых в 2007-м, держится у 15% с тех пор.) При ~8.5 млрд запросов в день 15% новых — это порядка **1.3 млрд совершенно новых запросов каждый день.** Нельзя иметь закэшированный ответ на запрос, которого утром не существовало.',
          'Почему новизна не заканчивается? Потому что язык **подчиняется Ципфу**. Нарисуй частоту запросов как пляж: несколько «головных» запросов — `youtube`, `погода`, `facebook login` — возвышаются как замки из песка и впитывают огромный объём, а позади них тянется *бесконечный хвост* странных, конкретных, разовых запросов, каждый из которых ищут один раз и, может, больше никогда. `error code 0x80070643 windows 11 update fix`. `почему моя закваска пахнет ацетоном`. Хвост — не маленький остаток: большинство *различных* запросов и огромная доля всего намерения живут именно там. Хвост без конца не выучить наизусть. **Нужно обобщать** — и это, в одном предложении, статистическая причина, почему поиску нужно машинное обучение, а не гигантская таблица соответствий.',
          'Помимо самого количества, *род* желания меняется от запроса к запросу — потому одно ранжирование не может быть верным для всех. Классическая таксономия [Broder (2002)](https://doi.org/10.1145/792550.792552) (по логам AltaVista) делит намерение натрое. **Навигационное** (~25%): тебе нужно одно конкретное место — `facebook login` — и «хорошо» значит единственный верный ответ на позиции 1; всё прочее — провал. **Информационное** (~40%): `как работают вакцины` — ты хочешь *узнать*, так что несколько хороших разнообразных документов лучше одного; покрытие важнее единственного победителя. **Транзакционное** (~35%): `купить iphone 15` — ты хочешь что-то *сделать*, и «хорошо» значит дать совершить действие. То самое ранжирование, что идеально для навигационного запроса, неверно для информационного. (И заметь: проценты гуляют от исследования к исследованию, потому что разметка намерения сама размыта — именно поэтому мы в итоге *учим* намерение из поведения, а не размечаем руками.)',
          'Итак, сложи всё, против чего на деле играет система: триллион документов, миллиард невиданных ранее запросов в день, словарь, где никто не сходится в словах, и пользователь, который сказал тебе почти ничего. Нельзя предвычислить ответы; нельзя прочитать всё в момент запроса; нельзя даже положиться на совпадение слов. Чем-то придётся пожертвовать. Выход не в более мощном компьютере — он в более умной *форме*.',
        ],
      },
    },
    {
      id: 'stakes-timeline', kind: 'prose',
      heading: { en: 'Sixty years of learning to match', ru: 'Шестьдесят лет учились совпадать' },
      body: {
        en: [
          "Here's the part that surprises people: none of what's coming *replaces* what came before. Search is an archaeology of good ideas stacked on top of each other, and a modern engine quietly runs almost all of them at once. Walk the timeline and you'll recognise every layer of the cascade we're about to build.",
          "It starts with counting. In 1958 Hans Peter Luhn proposed that a word's importance tracks how often it appears — term frequency, the first statistical signal. In 1972 [Spärck Jones](https://doi.org/10.1108/eb026526) added the twin idea that *rare* words carry more information — inverse document frequency — and \\(\\text{tf}\\cdot\\text{idf}\\) was born. In 1994 [Robertson & Walker](https://doi.org/10.1007/978-1-4471-2099-5_24) tuned that into **Okapi BM25**, the saturating, length-normalised scorer that — astonishingly — is *still* the first-stage retriever in most production systems thirty years on, and still the baseline every neural model is measured against.",
          "Then meaning arrived. In 2013 [Mikolov et al.](https://arxiv.org/abs/1301.3781) shipped **word2vec** and words became *vectors* — \"king − man + woman ≈ queen\" — the first real crack in the Lexical Gremlin's wall. In 2019, on the back of [BERT (Devlin et al., 2018)](https://arxiv.org/abs/1810.04805), dense retrieval grew up: [SBERT (Reimers & Gurevych)](https://arxiv.org/abs/1908.10084) and [DPR (Karpukhin et al., 2020)](https://arxiv.org/abs/2004.04906) learned to embed a query and a document so close in vector space that synonyms finally meet. Around 2020 the field stopped choosing sides and started *fusing* lexical and dense rankers together, and then [RAG (Lewis et al., 2020)](https://arxiv.org/abs/2005.11401) bolted a generator onto the retriever to close the loop.",
          "So the punchline is not \"neural beat classical.\" The punchline is that **production runs all of them, cascaded**: a 1994 BM25 retriever feeding a 2019 neural re-ranker feeding, sometimes, a 2020 generator — each layer doing the job it's cheapest and best at. The Lexical Gremlin was first measured in 1987 and isn't *defeated* until the dense-embedding layer of 2019; everything in between is the course you're taking. The timeline is the syllabus.",
        ],
        ru: [
          'Вот что удивляет людей: ничто из грядущего не *заменяет* того, что было раньше. Поиск — это археология хороших идей, наложенных друг на друга, и современный движок тихо гоняет почти все из них разом. Пройди по таймлайну — и узнаешь каждый слой каскада, который мы вот-вот построим.',
          'Всё начинается со счёта. В 1958-м Ханс Петер Лун предложил, что важность слова следует за тем, как часто оно встречается — частота терма, первый статистический сигнал. В 1972-м [Spärck Jones](https://doi.org/10.1108/eb026526) добавила парную идею, что *редкие* слова несут больше информации — обратная частота документа — и так родился \\(\\text{tf}\\cdot\\text{idf}\\). В 1994-м [Robertson & Walker](https://doi.org/10.1007/978-1-4471-2099-5_24) настроили это в **Okapi BM25**, насыщающийся, нормированный по длине скорер, который — поразительно — *по-прежнему* служит ретривером первой стадии в большинстве продакшн-систем тридцать лет спустя и до сих пор тот бейзлайн, с которым сравнивают каждую нейронную модель.',
          'Затем пришёл смысл. В 2013-м [Mikolov et al.](https://arxiv.org/abs/1301.3781) выпустили **word2vec**, и слова стали *векторами* — «king − man + woman ≈ queen» — первая настоящая трещина в стене Лексического Гремлина. В 2019-м на плечах [BERT (Devlin et al., 2018)](https://arxiv.org/abs/1810.04805) повзрослел плотный поиск: [SBERT (Reimers & Gurevych)](https://arxiv.org/abs/1908.10084) и [DPR (Karpukhin et al., 2020)](https://arxiv.org/abs/2004.04906) научились вкладывать запрос и документ так близко в векторном пространстве, что синонимы наконец встречаются. Около 2020-го поле перестало выбирать сторону и начало *сплавлять* лексические и плотные ранкеры вместе, а затем [RAG (Lewis et al., 2020)](https://arxiv.org/abs/2005.11401) прикрутил генератор к ретриверу, замкнув петлю.',
          'Так что вывод не «нейронное победило классическое». Вывод в том, что **продакшн гоняет их все, каскадом**: ретривер BM25 из 1994-го кормит нейронный переранкер из 2019-го, который кормит, иногда, генератор из 2020-го — каждый слой делает работу, в которой он дешевле и лучше всех. Лексического Гремлина впервые измерили в 1987-м, и он не *повержен* до слоя плотных эмбеддингов 2019-го; всё, что между, — это курс, который ты проходишь. Таймлайн — это и есть программа.',
        ],
      },
    },
    {
      id: 'turn-cascade', kind: 'prose',
      heading: { en: 'Narrow before you spend', ru: 'Сужай, прежде чем тратить' },
      body: {
        en: [
          "Here's the central trick of every search system, and once you see it you see it everywhere. You don't run your smartest, most expensive model on a billion documents — you'd melt, and you'd miss every deadline. Instead you build a **cascade**: a funnel of stages, cheap and broad at the top, expensive and precise at the bottom. Each stage looks at the survivors of the one before, spends about 10× more compute per document, and hands a 10×-shorter shortlist to the next. Watch the field narrow.",
          "Run the arithmetic and the funnel stops being a metaphor and becomes a budget. The good re-ranking model is a BERT cross-encoder — it reads the query and a document *together* and is wonderful at judging relevance, but it costs on the order of tens of milliseconds per query-document *pair*. Multiply that by \\(10^{9}\\) documents and you're roughly \\(10^{8}\\times\\) **over any reasonable latency budget**. It's simply not an option to score everything with the good model. So you don't. You let a *cheap* model — classic BM25 over an inverted index, or an approximate-nearest-neighbour vector lookup — sweep the whole corpus and keep maybe the top ~1000. Those two are fast *because* they're shallow. Then a mid-cost ranker (a gradient-boosted tree with hundreds of features) trims ~1000 down to ~100. Only *then*, on a shortlist small enough to afford it, does the heavy cross-encoder do its careful work and pick the final ~10.",
          "The reason the order matters — cheap first, dear last — is a hard, unforgiving rule: **the first stage sets a recall ceiling that nothing downstream can lift.** If retrieval drops a relevant document, it is gone for the rest of the pipeline; a perfect re-ranker can only reorder what it was handed. Picture the first stage as a leaky bucket: any star that falls through the floor is lost, and the re-ranker robot standing below simply cannot reach it. So if retrieval finds only 80% of the relevant documents, your *best possible* end-to-end result is 80% — full stop, no matter how brilliant the re-ranker. This is the single most common production mistake: teams pour months into a fancy re-ranker while 20% of the good documents are being silently dropped at stage 1. Recall is bought early and cheaply; precision is polished late and expensively. Invest in first-stage recall *before* you tune the re-ranker.",
          "Same shape, two readings. As an IR idea it's \"narrow billions down to a handful.\" As a *systems* idea it's a **latency budget**: you spend your milliseconds where they buy the most relevance per millisecond, and the heavy model only ever runs on the tiny set that earns it. Let's watch the cascade narrow, stage by stage, with the real numbers.",
        ],
        ru: [
          'Вот центральный трюк любой поисковой системы, и стоит его увидеть — видишь повсюду. Ты не запускаешь самую умную, самую дорогую модель на миллиарде документов — расплавишься и сорвёшь все сроки. Вместо этого строишь **каскад**: воронку стадий, дешёвую и широкую сверху, дорогую и точную снизу. Каждая стадия смотрит на выживших с предыдущей, тратит примерно в 10× больше вычислений на документ и передаёт следующему список в 10× короче. Смотри, как поле сужается.',
          'Просчитай арифметику — и воронка перестаёт быть метафорой и становится бюджетом. Хорошая модель переранжирования — это BERT-кросс-энкодер: он читает запрос и документ *вместе* и прекрасно судит о релевантности, но стоит порядка десятков миллисекунд на *пару* «запрос-документ». Умножь это на \\(10^{9}\\) документов — и ты примерно в \\(10^{8}\\times\\) **за пределами любого разумного бюджета задержки**. Скорить всё хорошей моделью — попросту не вариант. Поэтому ты так не делаешь. Ты даёшь *дешёвой* модели — классическому BM25 по инвертированному индексу или приближённому поиску ближайших соседей по векторам — пройтись по всему корпусу и оставить примерно топ-1000. Эти двое быстры *именно потому*, что неглубоки. Затем ранкер средней стоимости (градиентный бустинг над деревьями с сотнями признаков) обрезает ~1000 до ~100. И только *тогда*, на списке, достаточно коротком, чтобы это себе позволить, тяжёлый кросс-энкодер делает свою аккуратную работу и выбирает финальные ~10.',
          'Причина, почему порядок важен — дешёвое сначала, дорогое в конце — это жёсткое, неумолимое правило: **первая стадия задаёт потолок полноты, который ничто ниже по течению не поднимет.** Если извлечение уронило релевантный документ, он потерян для всего остального конвейера; идеальный переранкер может лишь переупорядочить то, что ему дали. Представь первую стадию как дырявое ведро: любая звезда, провалившаяся сквозь дно, потеряна, и робот-переранкер, стоящий внизу, попросту до неё не дотянется. Так что если извлечение находит лишь 80% релевантных документов, твой *лучший возможный* сквозной результат — 80%, и точка, как бы гениален ни был переранкер. Это самая частая ошибка в продакшене: команды месяцами вылизывают навороченный переранкер, пока 20% хороших документов молча отбрасываются на стадии 1. Полнота покупается рано и дёшево; точность шлифуется поздно и дорого. Вкладывайся в полноту первой стадии *прежде*, чем настраивать переранкер.',
          'Одна форма, два прочтения. Как идея IR это «сузить миллиарды до горстки». Как *системная* идея это **бюджет задержки**: ты тратишь свои миллисекунды там, где они покупают больше всего релевантности на миллисекунду, и тяжёлая модель работает только на крошечном наборе, который этого заслужил. Давай посмотрим, как каскад сужается, стадия за стадией, на реальных числах.',
        ],
      },
    },
    { id: 'climb-funnel', kind: 'scrolly', widget: 'retrieve-rank-funnel', data: 'l1-funnel' },
    {
      id: 'turn-system', kind: 'prose',
      heading: { en: 'A demo is not a system', ru: 'Демо — это не система' },
      img: 'L1/L1-32-not-a-system.png', imgPos: 'scene',
      imgAlt: {
        en: 'Serega proudly holds a laptop showing accuracy 0.92, dwarfed by a huge tangled production machine of pipes and gauges behind him',
        ru: 'Серёга гордо держит ноутбук с accuracy 0.92, а позади его затмевает огромная запутанная продакшн-машина из труб и датчиков',
      },
      imgCaption: {
        en: 'A model.fit() cell that scores 0.92 has solved maybe 5% of the problem. The other 95% is everything around it.',
        ru: 'Ячейка model.fit() с результатом 0.92 решила, может, 5% задачи. Остальные 95% — это всё, что вокруг неё.',
      },
      body: {
        en: [
          "Great — we can find the record once, in a notebook. The cascade works, the numbers look good, the demo lands. But a notebook isn't a product, and this is the moment the ground shifts under the whole lecture: *a model in a notebook is not a system.*",
          "Be concrete about how big the gap is. You wrote a `model.fit()` cell, it scored 0.92 on a held-out set, and it *feels* like you've solved the problem. You've solved maybe **5%** of it. The other 95% is everything the notebook quietly assumed away: where does the data come from, and who keeps it flowing? How is every feature computed *identically* at training time and at serving time? How do predictions come back in under 200 milliseconds, for thousands of users at once, when the cache is cold right after a deploy? Who notices when results slowly get worse — given that nothing ever throws an error? When and how do you retrain, and how do you roll back the night a release goes bad?",
          "The instant real users arrive, all of that surfaces, and it surfaces as the part of the iceberg below the waterline. The demo was the gleaming tip in the sun. The system is the vast, cold mass underneath that actually keeps search alive — and that's where production search lives or dies. So we pivot: from *what is search* to *how do you ship it and keep it breathing*. The second mission of the day starts here.",
        ],
        ru: [
          'Отлично — мы можем найти запись один раз, в ноутбуке. Каскад работает, числа выглядят хорошо, демо заходит. Но ноутбук — это не продукт, и именно сейчас почва уходит из-под всей лекции: *модель в ноутбуке — это не система.*',
          'Будем конкретны насчёт размера разрыва. Ты написал ячейку `model.fit()`, она дала 0.92 на отложенной выборке, и *кажется*, что задача решена. Решено, может, **5%** её. Остальные 95% — всё, что ноутбук тихо принял как данность: откуда берутся данные и кто поддерживает их поток? Как каждый признак вычисляется *одинаково* во время обучения и во время обслуживания? Как предсказания возвращаются меньше чем за 200 миллисекунд, для тысяч пользователей разом, когда кэш холодный сразу после деплоя? Кто замечает, что результаты медленно ухудшаются — учитывая, что никакой ошибки никогда не выбрасывается? Когда и как переобучать и как откатиться той ночью, когда релиз пошёл не так?',
          'В тот миг, когда приходят реальные пользователи, всё это всплывает — и всплывает как часть айсберга под водой. Демо было блестящей верхушкой на солнце. Система — это огромная холодная масса под ней, которая на самом деле держит поиск живым, и именно там продакшн-поиск живёт или умирает. Так что мы разворачиваемся: от *что такое поиск* к *как его выкатить и удержать дышащим*. Вторая миссия дня начинается здесь.',
        ],
      },
    },
    {
      id: 'climb-mlsd', kind: 'prose',
      heading: { en: 'The Iceberg', ru: 'Айсберг' },
      img: 'L1/L1-33-iceberg.png', imgPos: 'hero',
      imgAlt: {
        en: 'The ML iceberg: a tiny "ML code" tip above the waterline, a vast hidden mass of infrastructure below',
        ru: 'Айсберг ML: крошечная верхушка «ML-код» над водой, огромная скрытая масса инфраструктуры под ней',
      },
      imgCaption: {
        en: '"Only a small fraction of a real ML system is ML code" (Sculley 2015). The model is the tip; the iceberg is the job.',
        ru: '«Лишь малая доля реальной ML-системы — это ML-код» (Sculley 2015). Модель — верхушка; айсберг — это работа.',
      },
      body: {
        en: [
          "Meet the **Iceberg**. The model is the gleaming tip above the water — and it is *small*. Below the surface sits everything that actually keeps a search system alive: data collection and verification, feature extraction, configuration, the serving infrastructure, resource management, monitoring, and all the glue holding them together. [Sculley et al. (2015)](https://papers.nips.cc/paper/2015/hash/86df7dcfd896fcaf2674f757a2463eba-Abstract.html) drew exactly this picture at NeurIPS and gave it a memorable caption: *only a small fraction of a real-world ML system is ML code.* Your course so far has been about the tip. This part is about the iceberg — because every box below the waterline is a place a search system fails *silently*.",
          "Designing it means thinking in two loops at once. The **offline** loop runs on a schedule, off the request path: collect query and click logs → run a feature-and-index pipeline → train the ranker → register the model. It's latency-insensitive — you can take hours to crawl and index. The **online** loop runs per request, on a stopwatch: a query arrives → retrieve → rank → re-rank → serve, all inside a couple hundred milliseconds, then log what happened. Offline *builds* the index; online *walks* it. The two clocks could not be more different — hours versus milliseconds — and that asymmetry shapes every design choice that follows. The bridge between them is a single piece of plumbing called a **feature/index store**: offline writes features and the index there in batch; online reads them at low latency.",
          "That store isn't an architecture diagram flourish — it exists to kill the **#1 silent killer**, *training–serving skew*. Skew is when the features your model sees at serving time quietly differ from the ones it trained on — usually because two different code paths compute \"the same\" feature slightly differently, or because the data drifted between training and serving. The model trained on one distribution, serves on another, and degrades with *no error message at all*. The architectural fix is exactly the feature store: compute each feature **once**, write it where *both* training and serving read it, and parity is guaranteed by construction. (Google's Rules of ML say the same thing twice — \"train like you serve,\" \"reuse code between training and serving.\")",
          "Sculley's paper catalogues the rest of the debt, and each item has a search face. **CACE — Changing Anything Changes Everything:** ML systems have no clean module boundaries, so swap the tokenizer or nudge the BM25 floor and the input distribution to your re-ranker silently shifts. **Config debt:** one stale feature-version pin degrades ranking with no exception thrown — it just quietly rots. **Glue and pipeline jungles:** code testable only end-to-end, so a break anywhere can hide anywhere. The unifying property, the thing to tattoo on the back of your hand: **ML systems fail silently.** No stack trace — just slowly worse results. Which is why the last step of the design framework isn't \"deploy,\" it's *monitor*.",
          "So the whole framework is one disciplined loop, and it's worth memorising as six steps, each producing a concrete artifact. **(1) Frame** the problem: translate a business goal into an ML objective into a proxy metric — \"users find what they want\" → learn \\(P(\\text{relevant}\\mid q,d)\\) → optimise \\(\\text{nDCG}@10\\). (Google's Rule #1: don't be afraid to launch *without* ML first; a heuristic often beats a premature model and de-risks the plumbing.) **(2) Get the data:** logs plus graded 0–4 judgments, with splits chosen to avoid temporal leakage and known biases. **(3) Model and baselines:** simplest first — BM25 before the neural re-ranker (Rule #4: keep the first model simple, get the infrastructure right). **(4) Evaluate:** offline metrics that *predict* online, then the online test itself. **(5) Serve:** under a p99 latency budget, watching for train/serve skew. **(6) Monitor and close the loop:** track feature and score distributions, watch for drift, and feed the logs back into the next training cycle. Step 6 loops back to step 2 — the lifecycle is a *cycle*, not a line. Which brings us to the most dangerous part of that loop: the moment the system starts learning from its own behaviour.",
        ],
        ru: [
          'Знакомься: **Айсберг**. Модель — блестящая верхушка над водой, и она *мала*. Под поверхностью — всё, что на самом деле держит поисковую систему живой: сбор и проверка данных, извлечение признаков, конфигурация, инфраструктура обслуживания, управление ресурсами, мониторинг и весь клей, что их скрепляет. [Sculley et al. (2015)](https://papers.nips.cc/paper/2015/hash/86df7dcfd896fcaf2674f757a2463eba-Abstract.html) нарисовали ровно эту картину на NeurIPS и дали ей запоминающуюся подпись: *лишь малая доля реальной ML-системы — это ML-код.* Твой курс до сих пор был про верхушку. Эта часть — про айсберг, потому что каждый блок под водой — это место, где поисковая система ломается *молча*.',
          'Проектировать её — значит думать сразу в двух циклах. **Офлайн**-цикл работает по расписанию, в стороне от пути запроса: собрать логи запросов и кликов → прогнать конвейер признаков и индекса → обучить ранкер → зарегистрировать модель. Он нечувствителен к задержке — на обход и индексацию можно потратить часы. **Онлайн**-цикл работает на каждый запрос, с секундомером: приходит запрос → извлечь → ранжировать → переранжировать → выдать, всё за пару сотен миллисекунд, затем залогировать, что произошло. Офлайн *строит* индекс; онлайн *ходит* по нему. Двое часов не могут быть разнее — часы против миллисекунд — и эта асимметрия формирует каждое последующее проектное решение. Мост между ними — единственный кусок «сантехники» под названием **хранилище признаков/индекса**: офлайн пишет туда признаки и индекс пакетно; онлайн читает их с низкой задержкой.',
          'Это хранилище — не украшение на схеме архитектуры: оно существует, чтобы убить **убийцу номер один** — *перекос обучения и обслуживания (training–serving skew)*. Перекос — это когда признаки, которые модель видит при обслуживании, тихо отличаются от тех, на которых она обучалась — обычно потому, что два разных пути в коде вычисляют «один и тот же» признак чуть по-разному, или потому, что данные сдвинулись между обучением и обслуживанием. Модель обучилась на одном распределении, обслуживает на другом и деградирует *вообще без сообщения об ошибке*. Архитектурное лекарство — ровно хранилище признаков: вычисли каждый признак **один раз**, запиши туда, откуда читают *и* обучение, *и* обслуживание, и паритет гарантирован по построению. (Правила ML от Google говорят это дважды — «обучай как обслуживаешь», «переиспользуй код между обучением и обслуживанием».)',
          'Статья Скалли каталогизирует остальной долг, и у каждого пункта есть поисковое лицо. **CACE — Changing Anything Changes Everything, «меняя что угодно, меняешь всё»:** у ML-систем нет чистых границ модулей, так что поменяй токенизатор или подвинь порог BM25 — и распределение входов твоего переранкера тихо сдвинется. **Долг конфигурации:** один устаревший пин версии признака ухудшает ранжирование без всякого исключения — оно просто тихо гниёт. **Джунгли клея и конвейеров:** код, проверяемый только сквозным запуском, так что поломка где угодно может прятаться где угодно. Объединяющее свойство, которое стоит вытатуировать на тыльной стороне ладони: **ML-системы ломаются молча.** Никакого стек-трейса — лишь медленно ухудшающиеся результаты. Вот почему последний шаг проектного фреймворка не «выкатить», а *мониторить*.',
          'Итак, весь фреймворк — это один дисциплинированный цикл, и его стоит запомнить как шесть шагов, каждый из которых производит конкретный артефакт. **(1) Сформулировать** задачу: перевести бизнес-цель в ML-цель, а её — в прокси-метрику — «пользователи находят, что хотят» → выучить \\(P(\\text{релевантно}\\mid q,d)\\) → оптимизировать \\(\\text{nDCG}@10\\). (Правило №1 от Google: не бойся запуститься *без* ML сначала; эвристика часто бьёт преждевременную модель и снижает риск по «сантехнике».) **(2) Получить данные:** логи плюс градуированные оценки 0–4, со сплитами, выбранными так, чтобы избежать утечки по времени и известных смещений. **(3) Модель и бейзлайны:** сначала простейшее — BM25 до нейронного переранкера (Правило №4: держи первую модель простой, наладь инфраструктуру). **(4) Оценить:** офлайн-метрики, которые *предсказывают* онлайн, затем сам онлайн-тест. **(5) Обслуживать:** под бюджетом задержки p99, следя за перекосом обучения и обслуживания. **(6) Мониторить и замкнуть петлю:** отслеживать распределения признаков и скоров, ловить дрейф и возвращать логи в следующий цикл обучения. Шаг 6 возвращается к шагу 2 — жизненный цикл это *цикл*, а не прямая. Что приводит нас к самой опасной части этой петли: к моменту, когда система начинает учиться на собственном поведении.',
        ],
      },
    },
    {
      id: 'climb-drift', kind: 'prose',
      heading: { en: 'Five ways the data rots', ru: 'Пять способов, которыми данные гниют' },
      body: {
        en: [
          "Step 6 was *monitor*, and now we have to be honest about *what* you're monitoring for — because \"the system got worse\" is not a diagnosis, it's a symptom, and the cures are mutually exclusive. There are five distinct ways a production search system silently rots, and the whole skill is matching the fix to the failure. Apply a covariate-shift fix to a concept-drift problem and you've solved nothing.",
          "**Covariate shift** is when the *inputs* move but the rules don't: \\(P(x)\\) changes while \\(P(y \\mid x)\\) holds. Holiday traffic floods you with queries your model rarely trained on — the mapping from query to relevance is still valid, you're just seeing a different slice of it. You catch this by watching feature distributions, quantified with **KL divergence** or **PSI** (population stability index); when today's histogram drifts from training's, the alarm rings. **Concept drift** is the nastier twin: the *rules themselves* move, \\(P(y \\mid x)\\) changes. In 2019 the query \"corona\" meant a beer; in 2020 it meant a pandemic — same word, same features, totally different right answer. Concept drift is *invisible* in feature distributions — the inputs look fine — so you only catch it as rising error against *fresh* labels.",
          "**Data leakage** is the offline-metric inflator: information from the future sneaks into training, your offline number looks spectacular, and production face-plants. The fix is a discipline — split your data **by time, not at random** — because a random split on temporal data lets tomorrow teach yesterday. **Label delay** is subtler: conversions and other slow signals arrive late, so \"no conversion yet\" is not \"no conversion\" — treat a missing late label as unknown, not negative, or you'll train the model to distrust everything recent. And **Simpson's paradox**: an aggregate metric can move *up* while every single segment moves *down*, purely because the traffic mix shifted underneath you. The rule that saves you is to *always cut by segment* and never trust the aggregate alone.",
          "One more failure rides alongside these: **cold start** — a brand-new user, query, or document with no interaction history at all. You can't lean on behavioural features that don't exist yet, so you fall back on *content* features (what the document actually says), *popularity priors* (what's broadly good), and a little *exploration* to gather the first signals. Tattoo the meta-rule on the back of your hand: **the diagnosis determines the cure.** Naming the five — covariate shift, concept drift, leakage, label delay, Simpson's — is half the battle, because each one has a different tell and a different fix.",
        ],
        ru: [
          'Шаг 6 был *мониторить*, и теперь надо честно сказать, *за чем* именно ты следишь — потому что «система стала хуже» это не диагноз, а симптом, и лекарства взаимоисключающие. Есть пять разных способов, которыми продакшн-поиск молча гниёт, и весь навык — подобрать лекарство к болезни. Примени лекарство от ковариативного сдвига к дрейфу концепта — и ты не решил ничего.',
          '**Ковариативный сдвиг** — это когда *входы* двигаются, а правила нет: \\(P(x)\\) меняется, пока \\(P(y \\mid x)\\) держится. Праздничный трафик заваливает тебя запросами, на которых модель почти не училась — отображение «запрос → релевантность» всё ещё верно, ты просто видишь другой его срез. Ловишь это, следя за распределениями признаков, измеряя их **KL-дивергенцией** или **PSI** (индекс стабильности популяции); когда сегодняшняя гистограмма уходит от обучающей, звенит тревога. **Дрейф концепта** — более злой близнец: двигаются *сами правила*, меняется \\(P(y \\mid x)\\). В 2019-м запрос «corona» означал пиво; в 2020-м — пандемию: то же слово, те же признаки, совершенно другой верный ответ. Дрейф концепта *невидим* в распределениях признаков — входы выглядят нормально — так что ловишь ты его лишь как рост ошибки на *свежих* метках.',
          '**Утечка данных** — это раздуватель офлайн-метрики: информация из будущего просачивается в обучение, твоё офлайн-число выглядит блистательно, а продакшн падает лицом в пол. Лекарство — это дисциплина: дели данные **по времени, а не случайно** — потому что случайный сплит на временных данных позволяет завтра учить вчера. **Задержка меток** тоньше: конверсии и другие медленные сигналы приходят поздно, так что «конверсии пока нет» это не «конверсии нет» — считай отсутствующую позднюю метку неизвестной, а не отрицательной, иначе обучишь модель не доверять всему свежему. И **парадокс Симпсона**: агрегатная метрика может пойти *вверх*, пока каждый отдельный сегмент идёт *вниз*, чисто из-за того, что под тобой сдвинулась смесь трафика. Правило, которое спасает: *всегда режь по сегментам* и никогда не доверяй одному агрегату.',
          'Ещё один отказ едет рядом с этими: **холодный старт** — совсем новый пользователь, запрос или документ вообще без истории взаимодействий. Нельзя опереться на поведенческие признаки, которых ещё нет, так что откатываешься на *контентные* признаки (что документ на самом деле говорит), *приоры популярности* (что хорошо в целом) и немного *исследования*, чтобы собрать первые сигналы. Вытатуируй мета-правило на тыльной стороне ладони: **диагноз определяет лекарство.** Назвать пятёрку — ковариативный сдвиг, дрейф концепта, утечка, задержка меток, Симпсон — это половина дела, потому что у каждого свой признак и своё лекарство.',
        ],
      },
    },
    {
      id: 'climb-latency', kind: 'prose',
      heading: { en: 'Spending the millisecond budget', ru: 'Тратим бюджет миллисекунд' },
      body: {
        en: [
          "The online loop runs on a stopwatch, so let's actually read the stopwatch. A typical web-search service holds itself to a **\\(p_{99} \\lt 200\\) ms** service-level agreement — ninety-nine of every hundred requests must answer in under a fifth of a second. Walk one request through and watch the budget drain. The client's `GET /search` hits the API: **+3 ms**. The API asks the retriever for ~1000 candidates: **+35 ms**. It hands ~100 of them to the ranker: **+90 ms**. It writes the cache and logs asynchronously off the critical path: **+2 ms**. It serializes the top-\\(k\\) back to the client: **+4 ms**. Total: about **134 ms** — comfortably under the 200 ms ceiling, with headroom for a bad day.",
          "Read that ledger and one line screams: **ranking dominates** — 90 of the 134 ms. That is not an accident, it's the whole reason the cascade exists. You cannot afford the heavy model on the corpus, so retrieval cheaply narrows a billion documents to ~1000 in 35 ms, and the expensive ranker only ever touches the ~100 survivors. The cascade *is* a latency budget: spend your milliseconds where they buy the most relevance per millisecond, and never let the heavy model see more candidates than it has to.",
          "Two rules turn this from a diagram into an engineering discipline. First — and tattoo this one too — **alert on \\(p_{99}\\), not \\(p_{50}\\).** The median is a liar; it's the *tail* that users actually feel, and a system can have a beautiful 40 ms median while one request in fifty times out. A diagnostic tell: if \\(p_{99}\\) climbs while \\(p_{50}\\) *falls*, your request queue is backing up — some requests sail through while others rot in line. (For scale: YouTube's ranker serves in *tens of milliseconds*; the budget is real and tight everywhere.) Second, the cascade is a **tunable knob**, not a fixed shape. Adding a light distilled re-ranker (say MiniLM over the top ~100) costs ~60 ms and buys roughly **+5–15 \\(\\text{nDCG}@10\\)** — 70–90% of a heavy cross-encoder's gain at 30–50% of its cost. A heavy re-ranker on the top-20 adds ~200 ms to finalise the order. The two dials are **candidate-set size** and **per-stage model complexity**, and they trade almost linearly: *halving the candidate set roughly halves the cost* for a tiny relevance loss. That trade — latency spent versus \\(\\text{nDCG}\\) gained — is the knob you actually turn in production.",
        ],
        ru: [
          'Онлайн-цикл работает с секундомером, так что давай и правда прочитаем секундомер. Типичный веб-поисковый сервис держит себя в рамках соглашения об уровне обслуживания **\\(p_{99} \\lt 200\\) мс** — девяносто девять из каждых ста запросов обязаны ответить менее чем за пятую долю секунды. Проведём один запрос насквозь и посмотрим, как тает бюджет. Клиентский `GET /search` бьёт в API: **+3 мс**. API просит у ретривера ~1000 кандидатов: **+35 мс**. Передаёт ~100 из них ранкеру: **+90 мс**. Пишет кэш и логи асинхронно, в стороне от критического пути: **+2 мс**. Сериализует топ-\\(k\\) обратно клиенту: **+4 мс**. Итого: около **134 мс** — комфортно под потолком в 200 мс, с запасом на плохой день.',
          'Прочитай эту ведомость, и одна строка кричит: **ранжирование доминирует** — 90 из 134 мс. Это не случайность, это вся причина существования каскада. Тяжёлую модель на корпусе ты позволить не можешь, так что извлечение дёшево сужает миллиард документов до ~1000 за 35 мс, а дорогой ранкер касается лишь ~100 выживших. Каскад *и есть* бюджет задержки: трать миллисекунды там, где они покупают больше всего релевантности на миллисекунду, и никогда не давай тяжёлой модели видеть больше кандидатов, чем необходимо.',
          'Два правила превращают это из схемы в инженерную дисциплину. Первое — и его тоже вытатуируй — **алертить по \\(p_{99}\\), а не по \\(p_{50}\\).** Медиана лжёт; пользователи чувствуют *хвост*, и у системы может быть прекрасная медиана в 40 мс, пока один запрос из пятидесяти отваливается по таймауту. Диагностический признак: если \\(p_{99}\\) лезет вверх, пока \\(p_{50}\\) *падает*, у тебя забивается очередь запросов — часть проскакивает, а часть гниёт в очереди. (Для масштаба: ранкер YouTube отдаёт ответ за *десятки миллисекунд*; бюджет реален и тесен везде.) Второе, каскад — это **настраиваемая ручка**, а не фиксированная форма. Добавить лёгкий дистиллированный переранкер (скажем, MiniLM поверх топ-~100) стоит ~60 мс и покупает примерно **+5–15 \\(\\text{nDCG}@10\\)** — 70–90% выигрыша тяжёлого кросс-энкодера за 30–50% его стоимости. Тяжёлый переранкер на топ-20 добавляет ~200 мс, чтобы финализировать порядок. Две ручки — **размер набора кандидатов** и **сложность модели на стадию** — и они меняются почти линейно: *вдвое урезать набор кандидатов почти вдвое режет стоимость* при крошечной потере релевантности. Этот размен — потраченная задержка против выигранного \\(\\text{nDCG}\\) — и есть та ручка, которую ты на деле крутишь в продакшене.',
        ],
      },
    },
    {
      id: 'climb-case-371m', kind: 'prose',
      heading: { en: 'Measured pain, engineered fix', ru: 'Измеренная боль, инженерное лекарство' },
      body: {
        en: [
          "Let's ground all of this in one real ledger, because techniques you adopt as defaults are techniques you don't understand. The task: **371 million** short multilingual strings, two languages, return the top-100 matches with a score, under a **1-second SLA**, and — the catch — *no GPU available* for inference. Watch the naive design hit the wall, then watch each fix enter as the answer to a *measured* pain point, never as a hammer looking for a nail.",
          "**Before (naive).** Embed all 371M documents with a multilingual model at `float64`, dimension **784**. Now stare at the resource ledger: the vector store has shape \\((371\\text{M}, 784)\\) at 8 bytes each — that's on the order of **2.3 terabytes** of raw vectors, which won't sit in memory; there's no GPU to accelerate the math; and a brute-force similarity scan over 371M rows per query blows clean through the 1-second SLA. Three red annotations: *huge memory*, *no GPU*, *too slow*. The design is simply unservable.",
          "**After (engineered).** Three changes, each targeting one red mark. *One:* run a **cascade** with an **ANN index** (the approximate-nearest-neighbour structures of L9) so you never brute-force — the index jumps to the right neighbourhood instead of scanning everyone, which retires *too slow*. *Two:* shrink the embedding from dimension **784 to 24** — via PCA or simply a smaller model — and the store becomes \\((371\\text{M}, 24)\\), roughly a **30× memory cut** that retires *huge memory* and quietly removes the need for the GPU you didn't have. *Three:* **cache** the hot queries, since query frequency is Zipfian (remember the beach) and a small head of repeated queries soaks up enormous volume — answer those from cache for free. The result: *same model quality, a tiny fraction of the resources, top-100 in well under a second.* Every red annotation flips to \"(no problem).\"",
          "The pattern here is the one to carry all term, and it's worth stating bluntly: **introduce each technique as the fix to a measured bottleneck, never as a default.** Nobody reached for ANN, dimensionality reduction, or caching because they're fashionable; each one entered because a specific number — terabytes, no-GPU, seconds — said it had to. That discipline is the difference between engineering a system and cargo-culting one.",
        ],
        ru: [
          'Заземлим всё это в одной реальной ведомости, потому что приёмы, которые ты берёшь по умолчанию, — это приёмы, которых ты не понимаешь. Задача: **371 миллион** коротких многоязычных строк, два языка, вернуть топ-100 совпадений со скором, под **SLA в 1 секунду**, и — подвох — *GPU для инференса нет*. Смотри, как наивный дизайн врезается в стену, а затем как каждое лекарство входит ответом на *измеренную* болевую точку, а не молотком в поисках гвоздя.',
          '**До (наивно).** Вложить все 371M документов многоязычной моделью в `float64`, размерность **784**. Теперь вглядись в ресурсную ведомость: векторное хранилище имеет форму \\((371\\text{M}, 784)\\) по 8 байт каждое — это порядка **2.3 терабайта** сырых векторов, которые в память не влезут; GPU для ускорения математики нет; а грубый перебор сходства по 371M строк на каждый запрос пробивает SLA в 1 секунду насквозь. Три красные пометки: *огромная память*, *нет GPU*, *слишком медленно*. Дизайн попросту необслуживаем.',
          '**После (инженерно).** Три изменения, каждое бьёт по одной красной метке. *Раз:* запусти **каскад** с **ANN-индексом** (приближённые структуры поиска ближайших соседей из L9), чтобы никогда не перебирать в лоб — индекс прыгает в нужную окрестность вместо перебора всех, что снимает *слишком медленно*. *Два:* ужми эмбеддинг с размерности **784 до 24** — через PCA или просто меньшей моделью — и хранилище становится \\((371\\text{M}, 24)\\), примерно **30-кратное** сокращение памяти, что снимает *огромную память* и тихо убирает нужду в GPU, которого у тебя не было. *Три:* **кэшируй** горячие запросы, ведь частота запросов подчиняется Ципфу (вспомни пляж) и небольшая голова повторяющихся запросов впитывает огромный объём — отвечай на них из кэша бесплатно. Итог: *то же качество модели, крошечная доля ресурсов, топ-100 заметно меньше чем за секунду.* Каждая красная пометка переворачивается в «(не проблема)».',
          'Паттерн здесь — тот, что нужно нести весь семестр, и его стоит сказать прямо: **вводи каждый приём как лекарство от измеренного узкого места, а не по умолчанию.** Никто не хватался за ANN, понижение размерности или кэш потому, что они модны; каждый вошёл, потому что конкретное число — терабайты, нет-GPU, секунды — сказало, что он необходим. Эта дисциплина и есть разница между тем, чтобы инженерить систему, и тем, чтобы слепо ей подражать.',
        ],
      },
    },
    { id: 'catch-goodhart', kind: 'scrolly', widget: 'pos-bias-curve', data: 'l1-click-model' },
    {
      id: 'payoff-forever', kind: 'prose',
      heading: { en: 'The machine that keeps finding', ru: 'Машина, что продолжает находить' },
      img: 'L1/L1-56-found.png', imgPos: 'hero',
      imgAlt: {
        en: 'Serega holds the one document overhead in triumph, the ocean of bytes finally calm around him',
        ru: 'Серёга торжествующе держит тот самый документ над головой, океан байтов наконец спокоен вокруг него',
      },
      imgCaption: {
        en: 'Found it — and built the machine that keeps finding it. The Lost Record closes.',
        ru: 'Нашёл — и построил машину, что продолжает находить. «Потерянная запись» закрывается.',
      },
      body: {
        en: [
          "You just saw the most dangerous trap in the whole system, so let's name the creature who springs it: **Goodhart the Trickster**. His law, in the crisp phrasing [Strathern (1997)](https://doi.org/10.1002/(SICI)1234-981X(199707)5:3<305::AID-EURO184>3.0.CO;2-4) gave [Goodhart's (1975)](https://en.wikipedia.org/wiki/Goodhart%27s_law) original: *when a measure becomes a target, it ceases to be a good measure.* Train your ranker to maximise click-through rate and Goodhart grins and yanks the CTR line up — with clickbait, outrage, ambiguous thumbnails, and accidental taps. The proxy rises while the thing you actually wanted — a satisfied user — quietly sinks.",
          "It bites so hard because the feedback you collect is *contaminated by the very ranking that produced it*. Position bias means result #1 earns ~32% of clicks largely **because it is #1**, not because it is best — the cascade click model of [Craswell et al. (2008)](https://doi.org/10.1145/1341531.1341545) makes this precise, and [Joachims (2002)](https://doi.org/10.1145/775047.775067) first warned that raw clickthrough is implicit, biased feedback rather than ground-truth relevance. Train naively on those raw clicks and the model learns \"predict what was already on top,\" freezing the incumbents and burying the long tail — the same data flywheel that should compound *quality* instead compounds *bias*, rich-get-richer, every lap. The fixes are real: pair every proxy with a guardrail (dwell time, quick-back rate); reweight clicks by how likely each result was to be *examined* — [inverse-propensity weighting (Joachims et al., 2017)](https://doi.org/10.1145/3018661.3018699); explore a little so unshown items can earn feedback too. The meta-lesson: you must actively fight the loop your own system creates, or it slowly poisons its own training data.",
          "And there's a quieter, equally costly trap right next door — believing your offline number. *\"Our new model wins on \\(\\text{nDCG}@10\\) offline, so it'll win with real users.\"* It often won't. Offline metrics are computed on *historical, biased* logs and miss freshness, diversity, trust, presentation, and session dynamics. Per [Kohavi, Tang & Xu (2020)](https://doi.org/10.1017/9781108653985), at Microsoft's Bing only about **one in three** ideas that look promising offline actually produce a positive online A/B effect; the other two-thirds are flat or worse, and comparable rates show up at Netflix and Booking. So offline is a *hypothesis*, not a verdict: use it to iterate fast, then confirm online — and the most expensive bug of all isn't a wrong architecture, it's a wrong *frame*. A technically perfect CTR-maximiser that quietly tanks retention is worse than no model, because it fails silently while the proxy looks fantastic. [Covington et al. (2016)](https://doi.org/10.1145/2959100.2959190) is the canonical fix: YouTube trains its ranker not on \\(P(\\text{click})\\) but on a watch-time-weighted logistic whose odds approximate \\(E[\\text{watch time}]\\) — *same architecture, same logs*, but now it prefers videos people finish over videos they merely start. You can always swap the model; you rarely notice you optimised the wrong thing until the business metric has already moved against you.",
          "So that's the shape of the whole thing, and it's worth holding as one triad: **IR gives you the problem and the metrics; deep learning fills the pipeline; ML system design keeps it alive.** A cascade to find the record fast, wrapped in a system that learns from its own behaviour without being fooled by it, watched closely enough to catch the silent failures. We can find the Lost Record — and *keep* finding it, for every user, every day, after I've gone to sleep. The needle in the cosmos, found; the machine that keeps finding needles, sketched.",
          "But the Gremlin is still out there, smirking. For all our systems machinery, exact match *still* can't tell \"couch\" from \"sofa\" — every box in that beautiful blueprint sits on a retrieval stage that's blind to meaning. To beat him for good we have to stop matching letters and start giving words *meaning*: coordinates in a space where synonyms sit close together and \"couch\" and \"sofa\" are practically neighbours. How do we even *represent* a record as something a machine can compare? That's where we sail next — and it's where we finally start building the weapon that cages the Lexical Gremlin.",
        ],
        ru: [
          'Ты только что увидел самую опасную ловушку во всей системе, так что назовём существо, которое её захлопывает: **Гудхарт-Трикстер**. Его закон, в чёткой формулировке, которую [Strathern (1997)](https://doi.org/10.1002/(SICI)1234-981X(199707)5:3<305::AID-EURO184>3.0.CO;2-4) дала оригиналу [Goodhart (1975)](https://en.wikipedia.org/wiki/Goodhart%27s_law): *когда мера становится целью, она перестаёт быть хорошей мерой.* Обучи свой ранкер максимизировать кликабельность (CTR) — и Гудхарт ухмыляется и тянет линию CTR вверх: кликбейтом, возмущением, двусмысленными превью и случайными тапами. Прокси растёт, пока то, что тебе на самом деле было нужно — довольный пользователь — тихо тонет.',
          'Кусается это так больно потому, что собранная тобой обратная связь *заражена тем самым ранжированием, что её породило*. Позиционное смещение означает, что результат №1 собирает ~32% кликов во многом **потому, что он №1**, а не потому, что он лучший — каскадная click-модель [Craswell et al. (2008)](https://doi.org/10.1145/1341531.1341545) описывает это точно, а [Joachims (2002)](https://doi.org/10.1145/775047.775067) первым предупредил, что сырой клик — это неявная смещённая обратная связь, а не эталонная релевантность. Обучи наивно на этих сырых кликах — и модель выучит «предсказывай то, что уже было сверху», заморозив фаворитов и закопав длинный хвост — тот же маховик данных, что должен наращивать *качество*, вместо этого наращивает *смещение*, богатые богатеют, с каждым кругом. Лекарства реальны: к каждому прокси добавляй guardrail (время на странице, доля быстрых возвратов); перевзвешивай клики по тому, насколько вероятно результат вообще *рассмотрели* — [inverse-propensity weighting (Joachims et al., 2017)](https://doi.org/10.1145/3018661.3018699); немного исследуй, чтобы непоказанные элементы тоже могли заработать обратную связь. Мета-урок: ты обязан активно бороться с петлёй, которую создаёт твоя же система, иначе она медленно отравит собственные обучающие данные.',
          'И рядом есть тихая, столь же дорогая ловушка — верить своему офлайн-числу. *«Наша новая модель выигрывает по \\(\\text{nDCG}@10\\) офлайн, значит, выиграет и у реальных пользователей.»* Часто не выиграет. Офлайн-метрики считаются на *исторических, смещённых* логах и упускают свежесть, разнообразие, доверие, подачу и динамику сессии. По [Kohavi, Tang & Xu (2020)](https://doi.org/10.1017/9781108653985), в Bing у Microsoft лишь примерно **одна из трёх** идей, выглядящих многообещающе офлайн, на деле даёт положительный онлайн-эффект в A/B; остальные две трети — без изменений или хуже, и схожие доли встречаются в Netflix и Booking. Так что офлайн — это *гипотеза*, а не вердикт: используй его для быстрых итераций, затем подтверждай онлайн — и самый дорогой баг из всех не неверная архитектура, а неверная *постановка*. Технически идеальный максимизатор CTR, тихо обваливающий удержание, хуже отсутствия модели, потому что он ломается молча, пока прокси выглядит великолепно. [Covington et al. (2016)](https://doi.org/10.1145/2959100.2959190) — каноническое лекарство: YouTube обучает ранкер не на \\(P(\\text{клик})\\), а на взвешенной по времени просмотра логистике, чьи шансы аппроксимируют \\(E[\\text{время просмотра}]\\) — *та же архитектура, те же логи*, но теперь он предпочитает видео, которые досматривают, видео, которые лишь начинают. Модель всегда можно заменить; то, что ты оптимизировал не то, обычно замечаешь, только когда бизнес-метрика уже пошла против тебя.',
          'Вот и форма всего целого, и её стоит держать как одну триаду: **IR даёт тебе задачу и метрики; глубокое обучение наполняет конвейер; дизайн ML-систем держит всё живым.** Каскад, чтобы быстро найти запись, обёрнутый в систему, которая учится на собственном поведении, не давая себя обмануть, и за которой следят достаточно пристально, чтобы поймать молчаливые отказы. Мы можем найти Потерянную запись — и *продолжать* находить её, для каждого пользователя, каждый день, после того как я ушёл спать. Иголка в космосе найдена; машина, что продолжает находить иголки, набросана.',
          'Но Гремлин всё ещё там, ухмыляется. При всей нашей системной машинерии точное совпадение *по-прежнему* не отличит «диван» от «софы» — каждый блок в этом прекрасном чертеже стоит на стадии извлечения, слепой к смыслу. Чтобы победить его окончательно, надо перестать совпадать по буквам и начать давать словам *смысл*: координаты в пространстве, где синонимы стоят рядом, а «диван» и «софа» — практически соседи. Как вообще *представить* запись как нечто, что машина может сравнивать? Туда мы и направляемся дальше — и именно там мы наконец начинаем ковать оружие, которое посадит Лексического Гремлина в клетку.',
        ],
      },
    },
  ],
};
