// content/book/l2.js — "First Contact" chapter (the full L2 arc), per narrative/L2.md.
// The single source for this chapter's NARRATIVE prose. SCROLLY beats pull their per-step prose
// from the widget's own i18n.json (the figure narrates itself). EN canonical + RU; TT falls back.
// Built per NARRATIVE_METHOD.md (P1 hook, P2 creatures, P3 metaphor, P9 humor off precision, P12 callback).
// Prose beats may carry an illustration: img:'L2/<file>.png' (+ imgAlt/imgCaption {en,ru}, optional imgPos).

export default {
  id: '02',
  catchphrase: 'First Contact',
  beats: [
    {
      id: 'hook-first-contact', kind: 'prose',
      heading: { en: 'First Contact', ru: 'Первый контакт' },
      img: 'L2/L2-06-first-contact.png',
      imgAlt: {
        en: 'Serega and an alien face each other across a cloud of question marks — no shared symbols.',
        ru: 'Серёга и инопланетянин стоят друг против друга в облаке вопросительных знаков — нет общих символов.',
      },
      imgCaption: {
        en: 'An alien, and not one shared letter. Step one: agree on an alphabet. Step two: learn when two phrases mean the same thing.',
        ru: 'Инопланетянин — и ни одной общей буквы. Шаг один: договориться об алфавите. Шаг два: научиться понимать, когда две фразы об одном.',
      },
      body: {
        en: [
          "I'm Serega, and I've got a problem. There's an alien on my screen, and it won't stop talking. The translator spits out symbols. Are two of its phrases saying the same thing, or completely different things? I genuinely cannot tell.",
          "Here's the thing about meaning: a machine never gets to touch it directly. It only ever sees *strings* — sequences of characters with no built-in sense of which are alike. And strings are stubborn. A grey pixel halfway between black and white is a perfectly real, meaningful colour; you can interpolate it. But there is no word halfway between *cat* and *dog*. Symbols are **discrete** — they share no inherent ruler. \"Cat\" and \"car\" differ by one letter and mean wildly different things; \"couch\" and \"sofa\" share no letters and mean the same thing. You cannot read closeness off the spelling.",
          "So the mission splits into two jobs, and they have to happen in that order. First, **turn the alien's text into something countable** — numbers a machine can hold. Then, on top of those numbers, **manufacture a notion of distance** so the machine can finally judge: are these two meanings close, or far? Get Data, then Measure. Buckle up — we're going to build both halves from scratch.",
        ],
        ru: [
          'Я Серёга, и у меня проблема. На экране — инопланетянин, и он не замолкает. Переводчик выдаёт символы. Две его фразы говорят об одном и том же или о совершенно разном? Честно — не могу понять.',
          'Вот в чём штука со смыслом: машина никогда не касается его напрямую. Она видит только *строки* — последовательности символов без всякого встроенного чувства, какие из них похожи. А строки упрямы. Серый пиксель посередине между чёрным и белым — вполне реальный, осмысленный цвет; его можно интерполировать. Но слова посередине между *cat* и *dog* не существует. Символы **дискретны** — у них нет общей линейки. «Cat» и «car» отличаются одной буквой и значат совершенно разное; «couch» и «sofa» не имеют общих букв и значат одно и то же. По написанию близость не прочитать.',
          'Поэтому миссия распадается на две задачи, и порядок важен. Сначала — **превратить текст инопланетянина в нечто счётное**, в числа, которые машина может удержать. Потом, поверх этих чисел, — **изготовить понятие расстояния**, чтобы машина наконец могла судить: эти два смысла близки или далеки? Сперва Get Data, потом Measure. Пристегнись — обе половины мы построим с нуля.',
        ],
      },
    },
    {
      id: 'problem-raw-text', kind: 'prose',
      heading: { en: 'Raw text is not computable', ru: 'Сырой текст не вычисляем' },
      img: 'L2/L2-08-discreteness.png',
      imgAlt: {
        en: 'A continuous grey gradient on the left; on the right, "cat" and "dog" with no word in between.',
        ru: 'Слева непрерывный серый градиент; справа «cat» и «dog», и никакого слова между ними.',
      },
      imgCaption: {
        en: 'Pixels interpolate; symbols do not. There is no valid point between two strings — so we have to invent the coordinates ourselves.',
        ru: 'Пиксели интерполируются; символы — нет. Между двумя строками нет допустимой точки — координаты придётся придумать самим.',
      },
      body: {
        en: [
          "First snag: a computer can't do anything with raw letters. It needs numbers. The lazy fix is to build a dictionary — give every whole word its own integer ID — and feed those IDs to the model. It works right up until the alien says a word we never logged. One unseen word and the whole pipeline shrugs: *out of vocabulary*. The model has no slot for it, so it collapses everything it hasn't memorised into a single useless `[UNK]` token. Names, typos, hashtags, code identifiers, the alien's whole language — all flattened to the same blank.",
          "You might hope: just make the dictionary bigger. Read more text, keep adding words, surely it saturates? It does not. Two empirical laws say so, and we'll meet them as a figure in a moment. **Zipf's law** says word frequency falls off as roughly one-over-rank: on a real 3.7-million-token corpus, the top 10 words alone cover 20.6% of everything, the top 100 cover 47.3%, the top 1000 cover 71.4% — and then a colossal tail of words seen exactly once. **Heaps' law** says the number of distinct word-types keeps growing as you read, like \\(V \\approx K\\,N^{\\beta}\\) with \\(\\beta \\approx 0.59\\) — sublinear but *unbounded*. After 3.66 million tokens we'd already counted 94,287 distinct types and the curve was still climbing.",
          "Put those two facts together and the verdict is non-negotiable: **no fixed list of whole words can ever cover real language.** New words arrive forever. So we stop trying to enumerate words — and start breaking them into pieces small enough to never run out.",
        ],
        ru: [
          'Первая загвоздка: компьютер ничего не может сделать с сырыми буквами. Ему нужны числа. Ленивое решение — построить словарь, выдать каждому целому слову свой целочисленный ID и скормить эти ID модели. Работает ровно до того мига, когда инопланетянин произносит слово, которого мы не записали. Одно невиданное слово — и весь конвейер разводит руками: *слова нет в словаре*. У модели нет под него ячейки, и она схлопывает всё незаученное в один бесполезный токен `[UNK]`. Имена, опечатки, хэштеги, идентификаторы из кода, весь язык инопланетянина — всё сплющено в один пустой знак.',
          'Можно понадеяться: просто сделаем словарь больше. Прочитаем больше текста, будем добавлять слова — наверняка он насытится? Нет. Об этом говорят два эмпирических закона, и сейчас мы встретим их в виде фигуры. **Закон Ципфа**: частота слова падает примерно как один-на-ранг — на реальном корпусе в 3,7 млн токенов одни только топ-10 слов покрывают 20,6% всего, топ-100 — 47,3%, топ-1000 — 71,4%, а дальше колоссальный хвост слов, встреченных ровно один раз. **Закон Хипса**: число различных типов слов растёт по мере чтения как \\(V \\approx K\\,N^{\\beta}\\) при \\(\\beta \\approx 0{,}59\\) — сублинейно, но *неограниченно*. После 3,66 млн токенов мы уже насчитали 94 287 различных типов, и кривая всё ещё лезла вверх.',
          'Сложи эти два факта — и приговор не подлежит обжалованию: **никакой конечный список целых слов не покроет настоящий язык.** Новые слова приходят вечно. Поэтому мы перестаём перечислять слова — и начинаем дробить их на куски, достаточно мелкие, чтобы они никогда не кончались.',
        ],
      },
    },
    {
      id: 'problem-morphology-scripts', kind: 'prose',
      heading: { en: '"Split on spaces" is parochial', ru: '«Резать по пробелам» — местечковая привычка' },
      body: {
        en: [
          "There's a quieter reason whole-word lists fail, and it has nothing to do with running out of vocabulary — it's that *the unit \"a word\" barely exists* once you leave English. Take Turkish, an **agglutinative** language that glues meaning together: `evlerinizden` is a single written word — `ev` + `ler` + `iniz` + `den`, \"from your houses\". One word, four morphemes. A whole-word vocabulary would need a *separate entry for every such combination* — and Turkish, Finnish, and Hungarian generate them by the millions. The same blow-up [Furnas et al. (1987)](https://doi.org/10.1145/32206.32212) warned about, now multiplied by morphology.",
          "And the very assumption that words are *delimited by spaces* is an English-centric one. There are roughly 7000 languages and many scripts: Arabic and Hebrew run right-to-left; Chinese writes `今天我很高兴` (\"I am happy today\") with **no spaces at all**, so where one word ends and the next begins is itself a learned, ambiguous decision; Thai has no spaces either; Japanese mixes kanji, hiragana and katakana in one breath. Even English leaks — \"New York\" is two tokens for one place, \"can't\" is one token for two words, and URLs and #hashtags obey no rule a space could catch.",
          "So \"tokenize = split on whitespace\" is a rule that only ever worked for a slice of one language family. We want a method that **learns its units from the data itself** and works on any script — no hand-written boundary rules, no per-language exception list. That is exactly what the sub-word tokenizers in this chapter do (and why SentencePiece, which we'll meet, treats the space as just another symbol).",
        ],
        ru: [
          'Есть и более тихая причина, по которой списки целых слов проваливаются, и она не про исчерпание словаря — она про то, что *сама единица «слово» едва существует*, стоит выйти за пределы английского. Возьми турецкий, **агглютинативный** язык, склеивающий смысл: `evlerinizden` — одно написанное слово, `ev` + `ler` + `iniz` + `den`, «из ваших домов». Одно слово, четыре морфемы. Словарю целых слов понадобилась бы *отдельная запись на каждую такую комбинацию* — а турецкий, финский и венгерский плодят их миллионами. Тот самый взрыв, о котором предупреждали [Furnas et al. (1987)](https://doi.org/10.1145/32206.32212), теперь домножен на морфологию.',
          'И само допущение, что слова *разделены пробелами*, — английско-центричное. Языков около 7000, письменностей много: арабский и иврит идут справа налево; китайский пишет `今天我很高兴` («сегодня я очень рад») **вообще без пробелов**, так что где кончается одно слово и начинается следующее — уже выученное, неоднозначное решение; в тайском пробелов тоже нет; японский мешает кандзи, хирагану и катакану в одном дыхании. Даже английский течёт: «New York» — два токена на одно место, «can\'t» — один токен на два слова, а URL и #хэштеги не подчиняются ни одному правилу, которое поймал бы пробел.',
          'Значит, «токенизация = резать по пробелам» — правило, работавшее лишь для куска одной языковой семьи. Нам нужен метод, который **учит свои единицы из самих данных** и работает на любой письменности — без рукописных правил границ, без списка исключений на каждый язык. Именно это делают под-словные токенизаторы из этой главы (и потому SentencePiece, с которым мы встретимся, считает пробел просто ещё одним символом).',
        ],
      },
    },
    {
      id: 'turn-normalize-stem', kind: 'prose',
      heading: { en: 'Before you cut, you clean', ru: 'Прежде чем резать — чистят' },
      body: {
        en: [
          "Raw text doesn't go straight to the tokenizer. The real pipeline is **normalize → pre-tokenize → tokenize → ids**, and each box earns its place. \"This is an example.\" eventually becomes a list of integer ids like `[40134, 2052, 133, 389, 12]` — but only after the first box quietly fixes problems you can't even *see*.",
          "**Normalization** handles invisible differences that silently break matching. The character \"é\" has *two* legal Unicode encodings: NFC stores it as one code point `U+00E9`, while NFD stores it as plain `e` plus a combining accent `U+0301`. They render identically and compare *unequal* byte-for-byte — so \"café\" typed two ways fails to match itself. The Unicode normal forms (NFC/NFD compose-or-decompose; NFKC/NFKD also fold look-alikes, `ﬁ`→`fi`, full-width `Ａ`→`A`, `²`→`2`) exist to collapse these. But normalization is a double-edged knife: lowercasing merges \"US\" the country with \"us\" the pronoun, and aggressive NFKC rewrites `x²`→`x2`, destroying the very signal a chemistry or math search needs. The rule of thumb: NFC plus minimal folding for a generation model (modern byte-level tokenizers like GPT-2/4's do *almost no* normalization), heavier NFKC + casefold only for a lexical search index, where recall on surface form beats precision.",
          "Then there's the older trick of collapsing *word forms* to a root, and it comes in two flavours. **Stemming** is a crude, rule-based chopping of suffixes — the Porter stemmer turns `studies → studi`, `caring → car` — fast and language-light, but the output is a stem, not always a real word, and it over-merges (`universe`, `university` → `univers`). **Lemmatization** maps a word to its dictionary *lemma* using a vocabulary and morphology, often with the part of speech: `studies → study`, `drove → drive`, `better → good`, and `saw → see` (verb) or `saw` (noun). Both shrink `open / opened / opens / opening` to one form so a query matches every variant — the classic fix for the **lexical gap** the Gremlin guarded in the last chapter. Crucially: sparse retrieval like BM25 still *leans* on stemming and lemmatization, while neural and sub-word models usually skip them and let the tokenizer plus learned embeddings absorb morphology. So this whole preprocessing pipeline lives mostly on the classical-IR side — but you have to know it's there, because it shapes recall.",
        ],
        ru: [
          'Сырой текст не идёт прямо в токенизатор. Настоящий конвейер — **нормализация → пред-токенизация → токенизация → id**, и каждая коробка заслуживает место. «This is an example.» в итоге становится списком целочисленных id вроде `[40134, 2052, 133, 389, 12]` — но лишь после того, как первая коробка тихо чинит проблемы, которых ты даже *не видишь*.',
          '**Нормализация** разбирается с невидимыми различиями, которые молча ломают совпадение. У символа «é» *два* легальных юникод-кодирования: NFC хранит его как один кодовый пункт `U+00E9`, а NFD — как обычное `e` плюс комбинируемый акцент `U+0301`. Выглядят одинаково, а побайтово *не равны* — так что «café», набранное двумя способами, не совпадает само с собой. Нормальные формы Юникода (NFC/NFD — компонуют или разлагают; NFKC/NFKD ещё и складывают похожие глифы, `ﬁ`→`fi`, полноширинное `Ａ`→`A`, `²`→`2`) существуют, чтобы их схлопнуть. Но нормализация — нож о двух лезвиях: понижение регистра сливает «US» (страну) с «us» (местоимением), а агрессивный NFKC переписывает `x²`→`x2`, уничтожая именно тот сигнал, что нужен химическому или математическому поиску. Правило большого пальца: NFC плюс минимальная складка для генеративной модели (современные байтовые токенизаторы вроде GPT-2/4 почти *не* нормализуют), тяжёлый NFKC + casefold — только для лексического индекса, где полнота по поверхностной форме важнее точности.',
          'Дальше — старый приём свести *словоформы* к корню, и он бывает двух сортов. **Стемминг** — грубое правило-основанное обрубание суффиксов: стеммер Портера превращает `studies → studi`, `caring → car` — быстро и язык-легко, но на выходе стем, не всегда настоящее слово, и он пере-сливает (`universe`, `university` → `univers`). **Лемматизация** отображает слово в его словарную *лемму* по словарю и морфологии, часто с частью речи: `studies → study`, `drove → drive`, `better → good`, а `saw → see` (глагол) или `saw` (существительное). Оба сжимают `open / opened / opens / opening` к одной форме, чтобы запрос совпал с любым вариантом — классическое лекарство от **лексического разрыва**, который сторожил Гремлин в прошлой главе. Важно: разреженный поиск вроде BM25 всё ещё *опирается* на стемминг и лемматизацию, а нейронные и под-словные модели обычно их пропускают и дают токенизатору плюс выученным эмбеддингам впитать морфологию. Так что весь этот пред-обработочный конвейер живёт в основном на стороне классического IR — но знать о нём надо, потому что он формирует полноту.',
        ],
      },
    },
    {
      id: 'turn-tokenize', kind: 'prose',
      heading: { en: 'Enter the Tokenosaurus', ru: 'Появляется Токенозавр' },
      img: 'L2/L2-23-tokenosaurus.png', imgPos: 'mascot',
      imgAlt: {
        en: 'The Tokenosaurus, a friendly dinosaur, snipping a word into sub-word chunks with its teeth.',
        ru: 'Токенозавр — дружелюбный динозавр — зубами нарезает слово на под-словные куски.',
      },
      imgCaption: {
        en: "The dino's one job: there's no such thing as an unknown word — only a word he hasn't finished chewing into familiar bites.",
        ru: 'Единственная работа динозавра: неизвестных слов не бывает — есть слово, которое он ещё не дожевал до знакомых кусочков.',
      },
      body: {
        en: [
          "So we stop chasing whole words and chop them into *sub-words*. Meet the **Tokenosaurus** — a friendly beast that snips text into reusable chunks. Never seen the word *internationalization*? Fine — it still splits into pieces we *have* seen: `inter` + `national` + `ization`. The vocabulary stays finite, every input is representable, and `[UNK]` simply stops happening.",
          "But how big should the chunks be? That's a genuine three-way tug-of-war — a trade-off triangle between **vocabulary size**, **sequence length**, and **out-of-vocabulary risk**, and you can only ever keep two corners happy. Go to the extreme of single characters (or raw bytes) and the vocabulary shrinks to about 256 symbols and OOV vanishes entirely — but a sentence balloons to four or five times as many tokens, which is brutal when attention costs grow with the square of the length. Go to the extreme of whole words and sequences are short — but the vocabulary is unbounded (that's Heaps again) and OOV is everywhere. **Sub-words sit in the sweet interior:** a bounded vocabulary of roughly 30k–200k pieces, moderate sequence length, near-zero OOV. That's why every modern tokenizer — GPT-2's 50,257, GPT-4's ~100k, BERT's 30,522, LLaMA's 32k — lives there.",
          "The real magic is that we don't hand-pick the chunks. We let the *data* decide which pieces are worth keeping, by a beautifully simple loop. That loop is the next figure — watch the merges happen.",
        ],
        ru: [
          'Поэтому мы перестаём гоняться за целыми словами и режем их на *подслова*. Знакомьтесь — **Токенозавр**, дружелюбный зверь, который кромсает текст на переиспользуемые куски. Не видел слова *internationalization*? Не беда — оно всё равно распадётся на куски, которые мы *видели*: `inter` + `national` + `ization`. Словарь остаётся конечным, любой вход представим, а `[UNK]` просто перестаёт случаться.',
          'Но насколько крупными должны быть куски? Это настоящее перетягивание каната на три стороны — треугольник компромисса между **размером словаря**, **длиной последовательности** и **риском OOV**, и довольными можно держать лишь два угла из трёх. Уйди в крайность одиночных символов (или сырых байтов) — словарь сожмётся до примерно 256 знаков, а OOV исчезнет совсем, но предложение раздуется в четыре-пять раз по числу токенов, что жестоко, ведь стоимость внимания растёт как квадрат длины. Уйди в крайность целых слов — последовательности короткие, но словарь безграничен (это снова Хипс), а OOV повсюду. **Подслова сидят в сладкой середине:** ограниченный словарь примерно в 30k–200k кусков, умеренная длина, почти нулевой OOV. Поэтому каждый современный токенизатор — 50 257 у GPT-2, ~100k у GPT-4, 30 522 у BERT, 32k у LLaMA — живёт именно там.',
          'Настоящая магия в том, что куски мы не выбираем руками. Мы даём *данным* решать, какие куски стоит хранить, по на удивление простому циклу. Этот цикл — следующая фигура: следи, как происходят слияния.',
        ],
      },
    },
    { id: 'climb-bpe', kind: 'scrolly', widget: 'bpe-merge-ledger', data: 'l2-bpe' },
    { id: 'stats-zipf-heaps', kind: 'scrolly', widget: 'zipf-heaps', data: 'l2-corpus-stats' },
    {
      id: 'turn-bpe-nonunique', kind: 'prose',
      heading: { en: 'A word has no "correct" split', ru: 'У слова нет «правильного» разреза' },
      body: {
        en: [
          "Before we leave BPE, kill a myth that trips up everyone: *a word does not have one correct tokenization.* In principle a string can be cut many ways — `linear` could be `li + near` or `li + n + ea + r`; `algebra` could be `al + ge + bra` or `al + g + e + bra`. There is no fact of the matter inside the word. BPE makes the cut **deterministic only by fixing the order of its learned merges** and applying them greedily, top of the list first.",
          "So the segmentation is a property of the *trained merge table*, not of the word. Watch two tokenizers disagree on `singer`. Merge table A learned `{e+r→er, sin+g→sing}` and produces `[sing, er]` — 2 tokens. Merge table B learned `{s+i→si, n+g→ng}` and produces `[si, ng, e, r]` — 4 tokens. Same word, two trained tokenizers, **different segmentation, different token count, different model inputs.** This is one concrete reason you can never mix a tokenizer from one model with the weights of another — the ids simply don't mean the same thing.",
          "One last upgrade that makes BPE bullet-proof: run it on **raw bytes** instead of characters. There are only 256 possible bytes, so the base alphabet is tiny and fixed, every possible input — every emoji, every script, every corrupted blob — is representable, and `[UNK]` becomes literally *impossible*. That byte-level move (GPT-2, Radford et al. 2019, and every frontier model since) is why modern tokenizers also fold whitespace into tokens: a leading space is part of the byte stream, so `the` and `Ġthe` (\"space-the\") are simply different tokens. Hold that thought — it comes back to bite us in the consequences beat.",
        ],
        ru: [
          'Прежде чем уйти от BPE, убьём миф, на котором спотыкаются все: *у слова нет одной правильной токенизации.* В принципе строку можно резать многими способами — `linear` это `li + near` или `li + n + ea + r`; `algebra` это `al + ge + bra` или `al + g + e + bra`. Внутри слова нет истины на этот счёт. BPE делает разрез **детерминированным лишь тем, что фиксирует порядок выученных слияний** и применяет их жадно, сверху списка.',
          'Значит, сегментация — свойство *обученной таблицы слияний*, а не слова. Смотри, как два токенизатора расходятся на `singer`. Таблица A выучила `{e+r→er, sin+g→sing}` и даёт `[sing, er]` — 2 токена. Таблица B выучила `{s+i→si, n+g→ng}` и даёт `[si, ng, e, r]` — 4 токена. Одно слово, два обученных токенизатора, **разная сегментация, разное число токенов, разный вход модели.** Это одна конкретная причина, почему нельзя смешивать токенизатор одной модели с весами другой — id просто значат не то же самое.',
          'Последний апгрейд, делающий BPE пуленепробиваемым: гоняй его по **сырым байтам**, а не символам. Возможных байтов всего 256, так что базовый алфавит крошечный и фиксированный, любой возможный вход — любой эмодзи, любая письменность, любой битый блоб — представим, а `[UNK]` становится буквально *невозможным*. Этот байтовый ход (GPT-2, Radford et al. 2019, и каждая фронтир-модель с тех пор) — причина, по которой современные токенизаторы вшивают и пробелы в токены: ведущий пробел — часть байтового потока, так что `the` и `Ġthe` («пробел-the») — просто разные токены. Запомни это — оно ещё укусит нас в бите про последствия.',
        ],
      },
    },
    {
      id: 'turn-wordpiece', kind: 'prose',
      heading: { en: 'WordPiece: merge by surprise, not by count', ru: 'WordPiece: слияние по неожиданности, а не по счёту' },
      body: {
        en: [
          "BPE has a cousin that powers **BERT**: **WordPiece**, from [Schuster & Nakajima (2012)](https://doi.org/10.1109/ICASSP.2012.6289079) (originally for Japanese/Korean voice search). The single conceptual difference is *which pair it merges*. BPE merges the most **frequent** adjacent pair. WordPiece instead merges the pair with the highest **likelihood score** $$\\mathrm{score}(A,B) = \\frac{\\mathrm{freq}(AB)}{\\mathrm{freq}(A)\\cdot\\mathrm{freq}(B)}.$$ Read that as pointwise mutual information without the log: dividing by the two marginal counts favours pairs that co-occur *more than chance*. A pair of two very common pieces (`th` + `e`) has a big numerator but an even bigger denominator, so it scores modestly; a rare piece that almost always follows one specific neighbour scores high. That's why WordPiece tends to keep meaningful morphemes together.",
          "It also **marks word-internal pieces** with a `##` continuation prefix: `playing → play + ##ing`, `tokenization → token + ##ization`. The bare first piece starts a word; every `##` piece glues onto the previous one — which preserves word boundaries for tasks like named-entity recognition. Worked on a tiny corpus where `q`, `u`, `i`, `c` each appear once, the first three merges score `(q,##u)=29`, then `(qu,##i)=30`, then `(qui,##c)=31` (the vocabulary-size factor grows by one each step), assembling `quick` one piece at a time.",
          "Encoding at run time is different from training: it's **greedy longest-match, left to right**. An unseen `quickness` becomes `qu ##ick ##ness` by reusing learned pieces. But here's the catch that separates WordPiece from byte-level BPE — its base alphabet is the *characters of the training data*, not all 256 bytes, so if no sub-word matches at all, the whole word still collapses to `[UNK]`. WordPiece reduces unknowns dramatically; byte-level BPE eliminates them.",
        ],
        ru: [
          'У BPE есть кузен, питающий **BERT**: **WordPiece**, из [Schuster & Nakajima (2012)](https://doi.org/10.1109/ICASSP.2012.6289079) (изначально для японского/корейского голосового поиска). Единственное концептуальное отличие — *какую пару он сливает*. BPE сливает самую **частую** соседнюю пару. WordPiece вместо этого сливает пару с наибольшей оценкой **правдоподобия** $$\\mathrm{score}(A,B) = \\frac{\\mathrm{freq}(AB)}{\\mathrm{freq}(A)\\cdot\\mathrm{freq}(B)}.$$ Читай это как поточечную взаимную информацию без логарифма: деление на два маргинальных счётчика поощряет пары, встречающиеся *чаще случайного*. Пара из двух очень частых кусков (`th` + `e`) имеет большой числитель, но ещё больший знаменатель, и оценка скромна; редкий кусок, почти всегда идущий за одним конкретным соседом, набирает много. Поэтому WordPiece склонен держать осмысленные морфемы вместе.',
          'Он также **помечает внутрисловные куски** префиксом-продолжением `##`: `playing → play + ##ing`, `tokenization → token + ##ization`. Голый первый кусок начинает слово; каждый `##`-кусок приклеивается к предыдущему — что сохраняет границы слов для задач вроде распознавания именованных сущностей. На крошечном корпусе, где `q`, `u`, `i`, `c` встречаются по разу, первые три слияния дают `(q,##u)=29`, затем `(qu,##i)=30`, затем `(qui,##c)=31` (множитель размера словаря растёт на единицу за шаг), собирая `quick` по кусочку.',
          'Кодирование во время работы отличается от обучения: это **жадное самое-длинное-совпадение, слева направо**. Невиданное `quickness` становится `qu ##ick ##ness`, переиспользуя выученные куски. Но вот загвоздка, отделяющая WordPiece от байтового BPE — его базовый алфавит это *символы обучающих данных*, а не все 256 байтов, так что если не совпал ни один под-кусок, всё слово всё равно схлопывается в `[UNK]`. WordPiece резко сокращает неизвестные; байтовый BPE их устраняет.',
        ],
      },
    },
    {
      id: 'turn-unigram-sentencepiece', kind: 'prose',
      heading: { en: 'Unigram & SentencePiece: prune, don\'t merge', ru: 'Unigram и SentencePiece: не сливай — отсекай' },
      body: {
        en: [
          "The third family runs the loop *backwards*. **Unigram LM**, from [Kudo (2018)](https://arxiv.org/abs/1804.10959), starts from a deliberately **large** seed vocabulary, fits a unigram language model over it, and then iteratively **prunes** the tokens whose removal *least* hurts the corpus likelihood — trimming down to the target size. Where BPE and WordPiece build *up* (merge), Unigram builds *down* (prune). The probabilistic view buys something neither merge-based scheme has: **sub-word regularization** — at training time you can *sample* among alternative segmentations of the same word, a free data-augmentation that makes the downstream model robust to exactly the non-uniqueness we just saw.",
          "**SentencePiece**, from [Kudo & Richardson (2018)](https://arxiv.org/abs/1808.06226), is often conflated with Unigram but is a *different thing*: it's a **toolkit** that can run either BPE or Unigram, and its real contribution is treating **whitespace as an ordinary character**, rendered `▁` (U+2581): \"Hello world\" → `▁Hello ▁world`. That one decision makes it fully **reversible** (you can detokenize back to the exact original) and **language-agnostic** — no pre-tokenizer, no \"split on spaces\" assumption, so it works on Chinese and Thai out of the box. That's precisely the parochial assumption we flagged earlier, now dissolved. It's why SentencePiece dominates multilingual models — T5, ALBERT, XLNet, LLaMA, Mistral all ride it.",
        ],
        ru: [
          'Третье семейство гоняет цикл *задом наперёд*. **Unigram LM**, из [Kudo (2018)](https://arxiv.org/abs/1804.10959), стартует с нарочно **большого** затравочного словаря, подгоняет над ним униграммную языковую модель и затем итеративно **отсекает** токены, удаление которых *меньше всего* вредит правдоподобию корпуса — обрезая до целевого размера. Там, где BPE и WordPiece строят *вверх* (слияние), Unigram строит *вниз* (отсечение). Вероятностный взгляд даёт то, чего нет у слияний: **subword-регуляризацию** — на обучении можно *сэмплировать* среди альтернативных сегментаций одного слова, бесплатная аугментация, делающая модель устойчивой ровно к той неоднозначности, что мы только что видели.',
          '**SentencePiece**, из [Kudo & Richardson (2018)](https://arxiv.org/abs/1808.06226), часто путают с Unigram, но это *другое*: это **инструмент**, умеющий гонять и BPE, и Unigram, а его настоящий вклад — трактовать **пробел как обычный символ**, рисуемый `▁` (U+2581): «Hello world» → `▁Hello ▁world`. Одно это решение делает его полностью **обратимым** (можно детокенизировать обратно ровно в оригинал) и **языконезависимым** — нет пред-токенизатора, нет допущения «резать по пробелам», так что он работает на китайском и тайском из коробки. Это и есть та местечковая привычка, которую мы отметили раньше, теперь растворённая. Поэтому SentencePiece царит в многоязычных моделях — T5, ALBERT, XLNet, LLaMA, Mistral все на нём.',
        ],
      },
    },
    {
      id: 'stats-tokenizer-family', kind: 'prose',
      heading: { en: 'Three cutters, one table', ru: 'Три резака, одна таблица' },
      body: {
        en: [
          "Step back and the whole tokenizer zoo fits in one line. **BPE merges by frequency**; **WordPiece merges by likelihood gain**; **Unigram prunes by likelihood loss.** All three end with a *bounded* sub-word vocabulary — they differ only in how they choose the inventory and how they mark continuations. BPE is bottom-up, marks nothing (or works on bytes), and powers GPT-2/4 and RoBERTa. WordPiece is bottom-up, marks word-internal pieces with `##`, and powers BERT ([Devlin et al. 2019](https://arxiv.org/abs/1810.04805)). Unigram is top-down, marks word starts with `▁` via SentencePiece, and powers T5, LLaMA and Mistral. The lineage is a tidy arc — word → sub-word → byte: rule-based word splits (Penn Treebank, 1993), BPE born as a *compression* trick ([Gage 1994](http://www.pennelynn.com/Documents/CUJ/HTML/94HTML/19940045.HTM)), WordPiece (2012), BPE finally entering NLP for rare words ([Sennrich et al. 2016](https://arxiv.org/abs/1508.07909)), Unigram + SentencePiece (2018), and byte-level BPE killing OOV for good (GPT-2, 2019). The algorithm waited *twenty-two years* for the right problem.",
          "One more category that **BPE never learns**: **special tokens** — reserved ids the framework inserts around your text. The classic BERT set: `[CLS]` (a sequence-summary slot for classification), `[SEP]` (separates two segments — e.g. `query | document` in a reranker), `[PAD]` (batch filler, masked out of the loss), `[MASK]` (the hidden position a masked-language-model must predict, ~15% of tokens), plus `[UNK]` and the begin/end markers `<s>`/`</s>` (BOS/EOS). The `[SEP]` case is your bridge to next chapter: a BERT cross-encoder reranker scores `[CLS] query [SEP] document [SEP]` for relevance. Chat models add their own: ChatML uses `<|im_start|>`/`<|im_end|>`, LLaMA-3 uses `<|begin_of_text|>` and friends, all injected by `tokenizer.apply_chat_template()`. A real foot-gun lurks here — apply a chat template *and* pass `add_special_tokens=True` and you insert BOS **twice**, quietly degrading quality. Pick one.",
        ],
        ru: [
          'Сделай шаг назад — и весь зоопарк токенизаторов умещается в одну строку. **BPE сливает по частоте**; **WordPiece сливает по приросту правдоподобия**; **Unigram отсекает по потере правдоподобия.** Все трое заканчивают *ограниченным* под-словным словарём — различаются лишь в том, как выбирают инвентарь и как метят продолжения. BPE — снизу вверх, не метит ничего (или работает на байтах), питает GPT-2/4 и RoBERTa. WordPiece — снизу вверх, метит внутрисловные куски через `##`, питает BERT ([Devlin et al. 2019](https://arxiv.org/abs/1810.04805)). Unigram — сверху вниз, метит начала слов через `▁` посредством SentencePiece, питает T5, LLaMA и Mistral. Родословная — аккуратная дуга, слово → под-слово → байт: правило-основанные разрезы слов (Penn Treebank, 1993), BPE, рождённый как трюк *сжатия* ([Gage 1994](http://www.pennelynn.com/Documents/CUJ/HTML/94HTML/19940045.HTM)), WordPiece (2012), BPE, наконец вошедший в NLP для редких слов ([Sennrich et al. 2016](https://arxiv.org/abs/1508.07909)), Unigram + SentencePiece (2018) и байтовый BPE, насмерть убивший OOV (GPT-2, 2019). Алгоритм ждал *двадцать два года* подходящей задачи.',
          'Ещё одна категория, которой **BPE никогда не учится**: **специальные токены** — зарезервированные id, которые фреймворк вставляет вокруг твоего текста. Классический набор BERT: `[CLS]` (слот-сводка последовательности для классификации), `[SEP]` (разделяет два сегмента — например, `запрос | документ` в реранкере), `[PAD]` (наполнитель батча, маскируемый из функции потерь), `[MASK]` (скрытая позиция, которую модель маскированного языка должна предсказать, ~15% токенов), плюс `[UNK]` и маркеры начала/конца `<s>`/`</s>` (BOS/EOS). Случай `[SEP]` — твой мост в следующую главу: BERT-кросс-энкодер-реранкер оценивает `[CLS] запрос [SEP] документ [SEP]` на релевантность. Чат-модели добавляют свои: ChatML использует `<|im_start|>`/`<|im_end|>`, LLaMA-3 — `<|begin_of_text|>` и компанию, всё вставляется через `tokenizer.apply_chat_template()`. Тут таится настоящая мина: примени чат-шаблон *и* передай `add_special_tokens=True` — и вставишь BOS **дважды**, тихо ухудшив качество. Выбери одно.',
        ],
      },
    },
    {
      id: 'catch-tokenization-consequences', kind: 'prose',
      heading: { en: 'Where the cutter leaves scars', ru: 'Где резак оставляет шрамы' },
      body: {
        en: [
          "The tokenizer isn't a neutral pre-processing step — its arbitrary cuts leave fingerprints all over model behaviour. Start with **numbers**. Train a byte-level BPE on real text and the split of `327` *shifts with vocabulary size*: at a 1k vocab it's `3 | 2 | 7` (three tokens), at 4k and 16k it's `32 | 7` (two tokens). The model never sees place value line up consistently — which is a big reason LLMs are quietly bad at arithmetic. (LLaMA and PaLM force single-digit number tokens precisely to fix this.) **Code** has the same disease: in Python, indentation *is* the block structure, yet early tokenizers spent one token per space, fragmenting nested code and burning context — GPT-3.5/4 added single tokens for runs of 4/8/16 spaces, a concrete reason they got better at code. And format choice is token cost: YAML usually needs *fewer* tokens than JSON for the same data (no braces, fewer quotes and commas), a real prompt-engineering lever.",
          "**One glyph is not one token.** A \"family\" emoji `👨‍👩‍👧` is really man + ZWJ + woman + ZWJ + girl — several byte tokens glued by zero-width joiners — and under UTF-8 a single Chinese character like `高` is three bytes, so byte-level BPE spends 2–3 tokens on it. The *visual* atom and the *token* atom are simply not the same thing. **Morphology** stress-tests the cutter too: German concatenates freely (`Donaudampfschifffahrtsgesellschaftskapitän` → six morpheme-pieces), which sub-words handle gracefully, whereas Arabic is *non-concatenative* — the triliteral root `k-t-b` (\"write\") weaves *through* the vowels and patterns of `kataba` / `kattaba` / `iktataba`, so a contiguous left-to-right merger can't capture the shared piece cleanly. A known weak spot for BPE/WordPiece on Semitic languages.",
          "Two more quirks that come straight from \"the model's atoms are tokens, not letters.\" **Trailing-space sensitivity**: `\" the\"` and `\"the\"` are *different tokens* (remember byte-level BPE folds the leading space in), so a prompt ending in a stray space lands off-distribution and degrades the completion — trim it. And the famous \"how many R's in *strawberry*?\" failure: the model sees `straw` + `berry`, never `s-t-r-a-w-...`, so any character-level operation requires it to have *memorized* each token's spelling. It isn't looking at letters at run time. None of these is a reasoning bug; every one is a tokenization scar.",
        ],
        ru: [
          'Токенизатор — не нейтральный шаг пред-обработки: его произвольные разрезы оставляют отпечатки по всему поведению модели. Начни с **чисел**. Обучи байтовый BPE на настоящем тексте — и разрез `327` *сдвигается с размером словаря*: при словаре 1k это `3 | 2 | 7` (три токена), при 4k и 16k это `32 | 7` (два токена). Модель никогда не видит, чтобы разряды стабильно выстраивались — большая причина, почему LLM тихо плохи в арифметике. (LLaMA и PaLM принудительно делают однозначные числовые токены именно чтобы это починить.) У **кода** та же болезнь: в Python отступ *и есть* блочная структура, а ранние токенизаторы тратили по токену на пробел, дробя вложенный код и сжигая контекст — GPT-3.5/4 добавили одиночные токены на серии из 4/8/16 пробелов, конкретная причина, почему они стали лучше в коде. И выбор формата — это стоимость в токенах: YAML обычно требует *меньше* токенов, чем JSON, на те же данные (нет фигурных скобок, меньше кавычек и запятых), реальный рычаг промпт-инжиниринга.',
          '**Один глиф — не один токен.** Эмодзи «семья» `👨‍👩‍👧` на деле это мужчина + ZWJ + женщина + ZWJ + девочка — несколько байтовых токенов, склеенных нулевой-ширины соединителями, — а в UTF-8 один китайский иероглиф вроде `高` это три байта, так что байтовый BPE тратит на него 2–3 токена. *Визуальный* атом и *токенный* атом — просто не одно и то же. **Морфология** тоже устраивает резаку стресс-тест: немецкий свободно конкатенирует (`Donaudampfschifffahrtsgesellschaftskapitän` → шесть морфемных кусков), что под-слова обрабатывают изящно, тогда как арабский *не-конкатенативен* — трёхбуквенный корень `k-t-b` («писать») вплетается *сквозь* гласные и шаблоны `kataba` / `kattaba` / `iktataba`, так что непрерывное слияние слева направо не схватывает общий кусок чисто. Известное слабое место BPE/WordPiece на семитских языках.',
          'Ещё две причуды прямо из «атомы модели — токены, а не буквы». **Чувствительность к хвостовому пробелу**: `« the»` и `«the»` — *разные токены* (помни, байтовый BPE вшивает ведущий пробел), так что промпт, кончающийся лишним пробелом, попадает вне распределения и портит продолжение — обрежь его. И знаменитый провал «сколько R в *strawberry*?»: модель видит `straw` + `berry`, никогда `s-t-r-a-w-...`, так что любая операция уровня символов требует, чтобы она *заучила* написание каждого токена. Во время работы она на буквы не смотрит. Ни одно из этого не баг рассуждения; каждое — шрам токенизации.',
        ],
      },
    },
    {
      id: 'payoff-token-tax-search', kind: 'prose',
      heading: { en: 'The token tax — and why search pays it', ru: 'Токен-налог — и почему поиск его платит' },
      body: {
        en: [
          "All those scars converge on one number with real-world teeth: **fertility**, the average tokens-per-word a tokenizer spends. Train a 16k-vocab byte-level BPE on a mostly-English corpus and English `tokenization` costs **3** tokens — but the Russian word «привет» (\"hello\") costs **12 byte-level tokens**. That gap is the **multilingual token tax**, and it isn't just inefficiency, it's a *fairness* problem. Because attention is \\(O(n^2)\\), 2× fertility is roughly **4× the training compute**; at inference it's about **2× the API bill, 2× the latency**, and a smaller effective context window. A speaker of a low-resource language literally pays more, waits longer, and gets a smaller usable prompt — for the *same information*.",
          "And this lands squarely on **search**, which is why the whole tokenization half wasn't a detour. Sparse retrieval like BM25 matches *surface terms*, so it is acutely sensitive to tokenization, stemming and stop-words: under exact BM25 a query for `ensembling` simply won't match a document that says `ensemble` — plurals and tenses miss, which is the lexical gap from the previous chapter wearing a new coat. Worse, sparse and dense systems often tokenize *differently*: `euthanasia` is one BM25 term, but a multilingual model like XLM-R splits it into several sub-words, so when you try to **fuse** a sparse ranker with a neural one, the units don't line up. And fertility means non-English queries are more likely to be **truncated and under-retrieved** — uneven recall across languages, a search-fairness bug baked into the cutter. Tokenization is not a preprocessing footnote; it shapes recall.",
          "So Part one of the mission is complete: we turned the alien's raw stream into bounded, computable units — sub-words learned by BPE, WordPiece or Unigram, normalized and cleaned, robust against Heaps' endless tail and the world's 7000 scripts. Every phrase is now a vector of numbers. Which raises the question the second half exists to answer: *given two of these vectors, how do we measure that they mean the same thing?* On to the Instruments.",
        ],
        ru: [
          'Все эти шрамы сходятся в одно число с реальными зубами: **фертильность**, среднее число токенов-на-слово, которое тратит токенизатор. Обучи 16k-словарный байтовый BPE на преимущественно английском корпусе — и английское `tokenization` стоит **3** токена, а русское слово «привет» — **12 байтовых токенов**. Этот разрыв и есть **многоязычный токен-налог**, и это не просто неэффективность, это проблема *справедливости*. Поскольку внимание это \\(O(n^2)\\), двойная фертильность — это примерно **4× обучающих вычислений**; на инференсе это около **2× счёта за API, 2× задержки** и меньшее эффективное окно контекста. Носитель малоресурсного языка буквально платит больше, ждёт дольше и получает меньший полезный промпт — за *ту же информацию*.',
          'И это бьёт ровно по **поиску**, поэтому вся токенизационная половина не была отступлением. Разреженный поиск вроде BM25 совпадает по *поверхностным термам*, поэтому остро чувствителен к токенизации, стеммингу и стоп-словам: под точным BM25 запрос `ensembling` просто не совпадёт с документом, где написано `ensemble` — множественные числа и времена промахиваются, и это лексический разрыв из прошлой главы в новом пальто. Хуже того, разреженные и плотные системы часто токенизируют *по-разному*: `euthanasia` — один терм BM25, но многоязычная модель вроде XLM-R режет его на несколько под-слов, так что при попытке **слить** разреженный ранкер с нейронным единицы не сходятся. А фертильность означает, что неанглийские запросы вероятнее **обрезаются и недополучаются** — неравная полнота по языкам, баг справедливости поиска, запечённый в резак. Токенизация — не сноска пред-обработки; она формирует полноту.',
          'Итак, первая часть миссии завершена: мы превратили сырой поток инопланетянина в ограниченные, вычислимые единицы — под-слова, выученные BPE, WordPiece или Unigram, нормализованные и очищенные, устойчивые против бесконечного хвоста Хипса и 7000 письменностей мира. Каждая фраза теперь вектор чисел. Что поднимает вопрос, ради которого существует вторая половина: *даны два таких вектора — как измерить, что они значат одно и то же?* Переходим к Инструментам.',
        ],
      },
    },
    {
      id: 'problem-length-lies', kind: 'prose',
      heading: { en: 'Length lies', ru: 'Длина врёт' },
      img: 'L2/L2-56-cosine-vs-euclid.png',
      imgAlt: {
        en: 'Two arrows (1,1) and (10,10) pointing the same way; Euclidean calls them far, cosine calls them identical.',
        ru: 'Две стрелки (1,1) и (10,10) смотрят в одну сторону; евклид считает их далёкими, косинус — одинаковыми.',
      },
      imgCaption: {
        en: '\\((1,1)\\) and \\((10,10)\\) point the same way. Euclidean distance \\(\\sqrt{162} \\approx 12.73\\) screams "different" — yet the direction is identical.',
        ru: '\\((1,1)\\) и \\((10,10)\\) смотрят в одну сторону. Евклидово расстояние \\(\\sqrt{162} \\approx 12{,}73\\) вопит «разные» — а направление при этом одинаково.',
      },
      body: {
        en: [
          "Tokenization done, every phrase is now a vector of numbers — a point in space, where each coordinate counts (roughly) how much of some feature the phrase carries. To compare two phrases, the obvious move is to measure the straight-line distance between their points: \\(\\lVert a - b\\rVert\\), the Euclidean distance you learned in school. Obvious… and wrong.",
          "Here's the trap, with exact numbers. Take the phrase whose vector is \\(a = (1, 1)\\) and the same phrase said twice as emphatically, \\(b = (10, 10)\\). They carry the *same* meaning — both point in exactly the same direction, up-and-to-the-right at 45°. But the Euclidean distance between them is $$\\lVert a - b\\rVert = \\sqrt{9^2 + 9^2} = \\sqrt{162} \\approx 12.73.$$ Raw distance screams \"these are totally different!\" — when in fact one is just a louder version of the other.",
          "That's the bug in one line: **length lies.** Euclidean distance conflates *how much* a vector says with *what* it says. A long document and a short document on the identical topic land far apart simply because the long one has bigger counts. We don't want loudness. We want a measure that throws away magnitude entirely and listens only to *direction* — to where the vector points.",
        ],
        ru: [
          'Токенизация позади — теперь каждая фраза это вектор чисел, точка в пространстве, где каждая координата считает (грубо), сколько в фразе того или иного признака. Чтобы сравнить две фразы, очевидный ход — измерить расстояние по прямой между их точками: \\(\\lVert a - b\\rVert\\), евклидово расстояние из школы. Очевидно… и неверно.',
          'Вот ловушка, с точными числами. Возьми фразу с вектором \\(a = (1, 1)\\) и ту же фразу, сказанную вдвое напористее, \\(b = (10, 10)\\). Смысл у них *один и тот же* — обе смотрят ровно в одну сторону, вправо-вверх под 45°. Но евклидово расстояние между ними $$\\lVert a - b\\rVert = \\sqrt{9^2 + 9^2} = \\sqrt{162} \\approx 12{,}73.$$ Сырое расстояние вопит: «они совершенно разные!» — хотя на деле одна просто громче другой.',
          'Вот баг в одну строку: **длина врёт.** Евклидово расстояние смешивает *сколько* вектор говорит с тем, *что* он говорит. Длинный документ и короткий на одну и ту же тему оказываются далеко друг от друга просто потому, что у длинного счётчики больше. Нам не нужна громкость. Нам нужна мера, которая полностью выбрасывает величину и слушает только *направление* — куда вектор смотрит.',
        ],
      },
    },
    {
      id: 'turn-measure-angle', kind: 'prose',
      heading: { en: 'Measure the angle, not the length', ru: 'Измеряй угол, а не длину' },
      img: 'L2/L2-48-sir-cosine.png', imgPos: 'mascot',
      imgAlt: {
        en: 'Sir Cosine, a knight of the unit sphere, measuring the angle between two vector-lances with a protractor.',
        ru: 'Сэр Косинус, рыцарь единичной сферы, измеряет транспортиром угол между двумя векторами-копьями.',
      },
      imgCaption: {
        en: "Sir Cosine's creed: relevance is a small angle. Throw away both lengths and only the meaning's direction is left standing.",
        ru: 'Кредо Сэра Косинуса: релевантность — это малый угол. Отбрось обе длины — и устоит только направление смысла.',
      },
      body: {
        en: [
          "Enter **Sir Cosine and the Knights of the Unit Sphere**. Their whole creed: forget distance, measure the *angle* between two vectors. The instrument is **cosine similarity** — the cosine of that angle, $$\\cos\\theta = \\frac{a\\cdot b}{\\lVert a\\rVert\\,\\lVert b\\rVert} = \\frac{\\sum_i a_i b_i}{\\sqrt{\\sum_i a_i^2}\\,\\sqrt{\\sum_i b_i^2}}.$$ The numerator is the dot product, \\(\\sum_i a_i b_i\\); the denominator divides out *both* lengths, so the magnitude cancels and only direction is left. Point the same way → angle \\(0\\) → \\(\\cos\\theta = 1\\) (as similar as it gets). At right angles → \\(\\cos\\theta = 0\\) (nothing in common). Opposite → \\(\\cos\\theta = -1\\). For ordinary word-count vectors, which can't go negative, the score lives in \\([0, 1]\\).",
          "Run it on our trap from the last beat: \\(a = (1, 1)\\), \\(b = (10, 10)\\). Dot product \\(= 1\\cdot 10 + 1\\cdot 10 = 20\\); \\(\\lVert a\\rVert = \\sqrt{2}\\), \\(\\lVert b\\rVert = \\sqrt{200}\\); so $$\\cos\\theta = \\frac{20}{\\sqrt{2}\\cdot\\sqrt{200}} = \\frac{20}{\\sqrt{400}} = \\frac{20}{20} = 1.0.$$ Where Euclidean said \\(12.73\\) (\"miles apart\"), Sir Cosine says \\(1.0\\) (\"identical\"). He saw through the loudness to the meaning.",
          "And here's the elegant payoff that makes vector search practical. Expand the squared distance: \\(\\lVert x - y\\rVert^2 = \\lVert x\\rVert^2 + \\lVert y\\rVert^2 - 2\\,(x\\cdot y)\\). If you first **normalize** every vector to unit length — push every point onto the surface of the unit sphere — that collapses to $$\\lVert x - y\\rVert^2 = 2\\,(1 - \\cos\\theta).$$ On the sphere, cosine, dot product, and (negative) Euclidean distance all rank neighbours in the *exact same order*. That's why real systems L2-normalize their embeddings and then run a blazing-fast dot-product index: they get cosine's meaning at a dot product's speed. The next figure is the worked example on the sphere — watch the numbers, no jokes.",
        ],
        ru: [
          'На сцену выходят **Сэр Косинус и Рыцари Единичной Сферы**. Весь их девиз: забудь про расстояние, измеряй *угол* между двумя векторами. Инструмент — **косинусная близость**, косинус этого угла: $$\\cos\\theta = \\frac{a\\cdot b}{\\lVert a\\rVert\\,\\lVert b\\rVert} = \\frac{\\sum_i a_i b_i}{\\sqrt{\\sum_i a_i^2}\\,\\sqrt{\\sum_i b_i^2}}.$$ В числителе скалярное произведение, \\(\\sum_i a_i b_i\\); знаменатель делит на *обе* длины, так что величина сокращается и остаётся только направление. Смотрят в одну сторону → угол \\(0\\) → \\(\\cos\\theta = 1\\) (максимально похожи). Под прямым углом → \\(\\cos\\theta = 0\\) (ничего общего). Противоположно → \\(\\cos\\theta = -1\\). Для обычных векторов счётчиков слов, которые не уходят в минус, оценка живёт в \\([0, 1]\\).',
          'Прогоним на нашей ловушке из прошлого бита: \\(a = (1, 1)\\), \\(b = (10, 10)\\). Скалярное произведение \\(= 1\\cdot 10 + 1\\cdot 10 = 20\\); \\(\\lVert a\\rVert = \\sqrt{2}\\), \\(\\lVert b\\rVert = \\sqrt{200}\\); значит $$\\cos\\theta = \\frac{20}{\\sqrt{2}\\cdot\\sqrt{200}} = \\frac{20}{\\sqrt{400}} = \\frac{20}{20} = 1{,}0.$$ Там, где евклид сказал \\(12{,}73\\) («за тридевять земель»), Сэр Косинус говорит \\(1{,}0\\) («одно и то же»). Он разглядел за громкостью смысл.',
          'И вот изящная расплата, которая делает векторный поиск практичным. Разверни квадрат расстояния: \\(\\lVert x - y\\rVert^2 = \\lVert x\\rVert^2 + \\lVert y\\rVert^2 - 2\\,(x\\cdot y)\\). Если сперва **нормировать** каждый вектор к единичной длине — вытолкнуть каждую точку на поверхность единичной сферы — это схлопывается в $$\\lVert x - y\\rVert^2 = 2\\,(1 - \\cos\\theta).$$ На сфере косинус, скалярное произведение и (отрицательное) евклидово расстояние ранжируют соседей в *точно том же порядке*. Поэтому реальные системы L2-нормируют свои эмбеддинги, а потом гоняют молниеносный индекс по скалярному произведению: они получают смысл косинуса на скорости скалярного произведения. Следующая фигура — разобранный пример на сфере; следи за числами, без шуток.',
        ],
      },
    },
    { id: 'climb-cosine', kind: 'scrolly', widget: 'cosine-sphere', data: 'l2-cosine' },
    {
      id: 'turn-dot-mips', kind: 'prose',
      heading: { en: 'The dot product: when magnitude is signal', ru: 'Скалярное произведение: когда величина — сигнал' },
      body: {
        en: [
          "Cosine threw magnitude away on purpose. But sometimes magnitude *is* the signal — and that's the **dot product** standing on its own, not buried inside the cosine formula. It's just $$a\\cdot b = \\sum_i a_i b_i = \\lVert a\\rVert\\,\\lVert b\\rVert\\cos\\theta,$$ which is cosine *without* the normalization, so it rewards both alignment **and** length. Quick worked example: \\(u = 2i - 3j\\), \\(v = 4i + 2j\\) give \\(a\\cdot b = 2\\cdot 4 + (-3)\\cdot 2 = 8 - 6 = 2\\). Unlike cosine, its range is the whole line \\((-\\infty, \\infty)\\), and — careful — it is **not a metric**: it can be negative, and it doesn't satisfy the distance axioms.",
          "So why ever prefer it? Because of **MIPS — maximum inner product search**, \\(\\arg\\max_b\\, a\\cdot b\\). Trained **dual encoders** (the two-tower retrievers behind dense search, like [DPR, Karpukhin et al. 2020](https://arxiv.org/abs/2004.04906)) deliberately *learn meaningful norms* — they push a confident, information-rich passage to a larger magnitude so it wins on dot product, something cosine would flatten away. When the model was trained to put signal in the length, you must score with the dot product or you throw that signal out.",
          "And the flip side, the rule of thumb: **don't** use raw dot product when length is an *artifact* rather than signal — e.g. raw TF-IDF, where a long document scores high just for being long. There, magnitude is noise: normalize it away and use cosine. The choice isn't aesthetic; it follows directly from whether your representation earned its lengths.",
        ],
        ru: [
          'Косинус нарочно выбросил величину. Но иногда величина *и есть* сигнал — и тогда на сцену выходит **скалярное произведение** само по себе, а не спрятанное внутри формулы косинуса. Это просто $$a\\cdot b = \\sum_i a_i b_i = \\lVert a\\rVert\\,\\lVert b\\rVert\\cos\\theta,$$ то есть косинус *без* нормировки, поэтому оно вознаграждает и выравнивание, **и** длину. Быстрый разбор: \\(u = 2i - 3j\\), \\(v = 4i + 2j\\) дают \\(a\\cdot b = 2\\cdot 4 + (-3)\\cdot 2 = 8 - 6 = 2\\). В отличие от косинуса, его диапазон — вся прямая \\((-\\infty, \\infty)\\), и — осторожно — это **не метрика**: оно бывает отрицательным и не удовлетворяет аксиомам расстояния.',
          'Так зачем его вообще предпочитать? Из-за **MIPS — поиска максимального скалярного произведения**, \\(\\arg\\max_b\\, a\\cdot b\\). Обученные **двойные энкодеры** (две-башни-ретриверы за плотным поиском, как [DPR, Karpukhin et al. 2020](https://arxiv.org/abs/2004.04906)) нарочно *учат осмысленные нормы* — они выталкивают уверенный, информативный пассаж к большей величине, чтобы он выигрывал по скалярному произведению, что косинус бы сплющил. Когда модель обучена класть сигнал в длину, надо скорить скалярным произведением, иначе ты этот сигнал выбрасываешь.',
          'И обратная сторона, правило большого пальца: **не** используй сырое скалярное произведение, когда длина — *артефакт*, а не сигнал, например сырой TF-IDF, где длинный документ набирает много просто за длину. Там величина — шум: убери её нормировкой и используй косинус. Выбор не эстетический; он прямо следует из того, заслужило ли твоё представление свои длины.',
        ],
      },
    },
    {
      id: 'turn-minkowski-family', kind: 'prose',
      heading: { en: 'The whole Lp family', ru: 'Всё семейство Lp' },
      body: {
        en: [
          "Euclidean distance — the \\(\\sqrt{\\sum(\\Delta)^2}\\) that *length lies* taught us to distrust — is just one member of a whole family, the **Minkowski \\(L_p\\)** distances: $$\\lVert x\\rVert_p = \\Big(\\sum_i |x_i|^{p}\\Big)^{1/p},\\qquad d_p(x,y) = \\Big(\\sum_i |x_i - y_i|^{p}\\Big)^{1/p}.$$ Turn the single dial \\(p\\) and you get the whole zoo. **\\(p = 2\\)** is **Euclidean** (straight-line): for \\(P(3,2), Q(4,1)\\), \\(d_2 = \\sqrt{1^2 + (-1)^2} = \\sqrt 2 \\approx 1.414\\). **\\(p = 1\\)** is **Manhattan** (city-block, the taxicab sum of absolute differences): for \\(P(2,9), Q(3,5)\\), \\(d_1 = |3-2| + |5-9| = 1 + 4 = 5\\). And **\\(p \\to \\infty\\)** is **Chebyshev**, which collapses to the single largest coordinate gap, \\(L_\\infty = \\max_i |x_i - y_i|\\) — on that same \\(P,Q\\) it's \\(\\max(1, 4) = 4\\).",
          "Two warnings on the dial. Push \\(p\\) below 1 — a *fractional* \\(0 \\lt p \\lt 1\\) — and you get a **quasi-norm**: it still measures something, but it **violates the triangle inequality**, so it is no longer a true metric. And the reason anyone reaches for low \\(p\\) at all is the punchline of this chapter's second half: in **high dimensions, \\(L_1\\) keeps contrast better than \\(L_2\\)** — [Aggarwal, Hinneburg & Keim (2001)](https://doi.org/10.1007/3-540-44503-X_27) showed that lower \\(p\\) resists the distance concentration the Wraith is about to unleash. So when scales differ or outliers bite, prefer \\(L_1\\)'s linear penalty over \\(L_2\\)'s quadratic one.",
          "And here is the elegant bridge back to Sir Cosine, the single most important identity in vector search. Expand the squared Euclidean distance: \\(\\lVert x - y\\rVert^2 = \\lVert x\\rVert^2 + \\lVert y\\rVert^2 - 2\\,(x\\cdot y)\\). **L2-normalize** every vector — push it onto the unit sphere, \\(\\lVert x\\rVert = \\lVert y\\rVert = 1\\) — and it collapses to $$\\lVert x - y\\rVert^2 = 2\\,(1 - \\cos\\theta).$$ On the sphere, ranking by cosine \\(\\uparrow\\), by dot product \\(\\uparrow\\), and by squared-Euclidean \\(\\downarrow\\) give the **identical** nearest-neighbour order. *Off* the sphere they part ways — that's our `(1,1)` vs `(10,10)` trap, \\(\\cos = 1\\) yet \\(\\lVert a - b\\rVert = \\sqrt{162} \\approx 12.73\\). Magnitude is exactly where the three measures agree or diverge.",
        ],
        ru: [
          'Евклидово расстояние — то самое \\(\\sqrt{\\sum(\\Delta)^2}\\), которому «длина врёт» научила не доверять, — лишь один член целого семейства, **минковских \\(L_p\\)**-расстояний: $$\\lVert x\\rVert_p = \\Big(\\sum_i |x_i|^{p}\\Big)^{1/p},\\qquad d_p(x,y) = \\Big(\\sum_i |x_i - y_i|^{p}\\Big)^{1/p}.$$ Покрути единственную ручку \\(p\\) — и получишь весь зоопарк. **\\(p = 2\\)** — **евклидово** (по прямой): для \\(P(3,2), Q(4,1)\\), \\(d_2 = \\sqrt{1^2 + (-1)^2} = \\sqrt 2 \\approx 1{,}414\\). **\\(p = 1\\)** — **манхэттенское** (квартальное, такси-сумма модулей разностей): для \\(P(2,9), Q(3,5)\\), \\(d_1 = |3-2| + |5-9| = 1 + 4 = 5\\). А **\\(p \\to \\infty\\)** — **чебышёвское**, схлопывающееся к единственному наибольшему разрыву по координате, \\(L_\\infty = \\max_i |x_i - y_i|\\) — на тех же \\(P,Q\\) это \\(\\max(1, 4) = 4\\).',
          'Два предупреждения по ручке. Опусти \\(p\\) ниже 1 — *дробное* \\(0 \\lt p \\lt 1\\) — и получишь **квази-норму**: она всё ещё что-то мерит, но **нарушает неравенство треугольника**, так что уже не настоящая метрика. А причина, по которой за малым \\(p\\) вообще тянутся, — это пуант второй половины главы: в **больших размерностях \\(L_1\\) держит контраст лучше \\(L_2\\)** — [Aggarwal, Hinneburg & Keim (2001)](https://doi.org/10.1007/3-540-44503-X_27) показали, что меньшее \\(p\\) сопротивляется концентрации расстояний, которую вот-вот выпустит Призрак. Так что когда шкалы различаются или кусают выбросы, предпочитай линейный штраф \\(L_1\\) квадратичному \\(L_2\\).',
          'И вот изящный мост обратно к Сэру Косинусу, самое важное тождество векторного поиска. Разверни квадрат евклидова расстояния: \\(\\lVert x - y\\rVert^2 = \\lVert x\\rVert^2 + \\lVert y\\rVert^2 - 2\\,(x\\cdot y)\\). **L2-нормируй** каждый вектор — вытолкни на единичную сферу, \\(\\lVert x\\rVert = \\lVert y\\rVert = 1\\) — и оно схлопывается в $$\\lVert x - y\\rVert^2 = 2\\,(1 - \\cos\\theta).$$ На сфере ранжирование по косинусу \\(\\uparrow\\), по скалярному произведению \\(\\uparrow\\) и по квадрату евклида \\(\\downarrow\\) дают **тот же** порядок ближайших соседей. *Вне* сферы они расходятся — это наша ловушка `(1,1)` против `(10,10)`, \\(\\cos = 1\\), а \\(\\lVert a - b\\rVert = \\sqrt{162} \\approx 12{,}73\\). Величина — ровно то, где три меры сходятся или расходятся.',
        ],
      },
    },
    {
      id: 'turn-set-string-measures', kind: 'prose',
      heading: { en: 'Sets and strings need their own rulers', ru: 'Множествам и строкам нужны свои линейки' },
      body: {
        en: [
          "Cosine, dot and \\(L_p\\) all assume dense vectors of real numbers. But a lot of data isn't that — it's **sets** (the words shingled out of a document, the items a user clicked, categorical features) — and sets want their own ruler. The natural one is **Jaccard**: $$J(A, B) = \\frac{|A \\cap B|}{|A \\cup B|} \\in [0, 1],$$ the fraction of the *union* that the two sets share. Its complement, the Jaccard *distance* \\(1 - J\\), is a genuine metric. The beautiful part is how you scale it. **MinHash** (Broder, used at AltaVista) builds tiny signatures with a magic property: the probability that two sketches collide *equals* their Jaccard — so you estimate set similarity in sub-linear time, the trick still used to **deduplicate web-scale LLM training data**. Its dense cousin **SimHash** (Charikar) does the same for *cosine* via random hyperplanes. The rhyme to memorize: MinHash ↔ Jaccard (sets); SimHash ↔ cosine (dense). Pair either with **LSH** banding and you get sublinear near-duplicate search.",
          "And when the unit of comparison is a *string itself* — spell-check, fuzzy matching, fixing a typo'd query — you want **edit (Levenshtein) distance**: the minimum number of single-character **insertions, deletions, or substitutions** to turn one string into another. It's computed by a small dynamic program over a grid, $$D[i,j] = \\min\\begin{cases} D[i\\!-\\!1, j] + 1 & \\text{(delete)}\\\\ D[i, j\\!-\\!1] + 1 & \\text{(insert)}\\\\ D[i\\!-\\!1, j\\!-\\!1] + \\mathbb{1}[s_i \\neq t_j] & \\text{(substitute, free if equal)} \\end{cases}$$ Worked example: `HONDA` → `HYUNDAI`. They share the `H` and the run `N D A`; the cheapest alignment inserts `Y`, `U`, and `I`, so the bottom-right cell of the grid reads **3 edits**. Levenshtein is a true metric on strings, but the DP costs \\(O(nm)\\) — fine for short strings, hopeless for long documents, which is exactly why for documents you *shingle and MinHash* instead.",
        ],
        ru: [
          'Косинус, скалярное произведение и \\(L_p\\) все предполагают плотные векторы вещественных чисел. Но многие данные не такие — это **множества** (слова, нашинкованные из документа, товары, кликнутые пользователем, категориальные признаки) — и множествам нужна своя линейка. Естественная — **Жаккар**: $$J(A, B) = \\frac{|A \\cap B|}{|A \\cup B|} \\in [0, 1],$$ доля *объединения*, которую два множества делят. Его дополнение, *расстояние* Жаккара \\(1 - J\\), — настоящая метрика. Прекрасно то, как его масштабируют. **MinHash** (Broder, применялся в AltaVista) строит крошечные сигнатуры с волшебным свойством: вероятность столкновения двух скетчей *равна* их Жаккару — так оценивают сходство множеств за сублинейное время, трюк, до сих пор используемый для **дедупликации обучающих данных LLM веб-масштаба**. Его плотный кузен **SimHash** (Charikar) делает то же для *косинуса* через случайные гиперплоскости. Рифма для запоминания: MinHash ↔ Жаккар (множества); SimHash ↔ косинус (плотные). Соедини любой с бэндингом **LSH** — и получишь сублинейный поиск почти-дубликатов.',
          'А когда единица сравнения — *сама строка* — проверка орфографии, нечёткое совпадение, починка опечатанного запроса — нужно **редакционное расстояние (Левенштейна)**: минимальное число одно-символьных **вставок, удалений или замен**, чтобы превратить одну строку в другую. Считается маленьким динамическим программированием по сетке, $$D[i,j] = \\min\\begin{cases} D[i\\!-\\!1, j] + 1 & \\text{(удаление)}\\\\ D[i, j\\!-\\!1] + 1 & \\text{(вставка)}\\\\ D[i\\!-\\!1, j\\!-\\!1] + \\mathbb{1}[s_i \\neq t_j] & \\text{(замена, бесплатно если равны)} \\end{cases}$$ Разбор: `HONDA` → `HYUNDAI`. Они делят `H` и серию `N D A`; самое дешёвое выравнивание вставляет `Y`, `U` и `I`, так что правая-нижняя клетка сетки показывает **3 правки**. Левенштейн — настоящая метрика на строках, но ДП стоит \\(O(nm)\\) — годно для коротких строк, безнадёжно для длинных документов, и именно поэтому для документов *шинкуют и MinHash-ят*.',
        ],
      },
    },
    {
      id: 'stats-measure-family', kind: 'prose',
      heading: { en: 'Which measure, when', ru: 'Какая мера и когда' },
      body: {
        en: [
          "Time to lay the whole toolbox on the bench. The **similarity family**, by what each captures, its range, whether it's a true metric, and its pitfall: **Cosine** — angle, \\([-1, 1]\\), *not* a metric (the angular distance \\(\\arccos(\\cos)/\\pi\\) is), pitfall: the zero vector and anisotropy. **Dot** — angle + magnitude, \\((-\\infty, \\infty)\\), not a metric, pitfall: length artifacts (its strength in MIPS). **Euclidean** — straight-line gap, \\([0, \\infty)\\), a true metric, pitfall: scale and high-d concentration. **Jaccard** — set overlap, \\([0, 1]\\), distance is a metric, pitfall: set-size disparity. **Edit / Levenshtein** — string ops, a metric, pitfall: \\(O(nm)\\), short strings only. **KL / JS** — distribution gap, KL is \\([0, \\infty)\\) and *not* a metric (it's asymmetric; \\(\\sqrt{\\mathrm{JS}}\\) is a metric), pitfall: zero bins need smoothing. **Pearson** — centered correlation, \\([-1, 1]\\), not a metric — and the lovely fact students miss: **Pearson is literally cosine after mean-centering**, which is why it removes per-user rating bias in recommendation.",
          "From the family falls a rough **decision guide** (heuristic, not law — the real answer depends on how your embeddings were *trained*): text / embeddings where direction matters but length shouldn't → **cosine**; continuous features on the *same* scale → **Euclidean \\(L_2\\)**; continuous features on *different* scales or with outliers → **Manhattan \\(L_1\\)**; categorical / sets by member overlap → **Jaccard**; ordinal ranks by monotonic agreement → **Spearman**; correlated, mean-centred multivariate → **Pearson**. The deeper fork underneath it is **sparse-sets vs dense-embeddings**: sparse, mostly-zero set representations (shingled docs, user–item pairs) want Jaccard + MinHash + LSH; dense learned vectors in \\(\\mathbb{R}^d\\) want cosine or dot plus an ANN index ([HNSW, Malkov & Yashunin 2018](https://arxiv.org/abs/1603.09320), or IVF-PQ). Pick the wrong family — cosine on raw sparse counts, or Jaccard on dense floats — and the ranking is meaningless.",
          "And tied to actual *jobs*: semantic search / RAG → cosine (normalized) or dot for trained dual encoders; near-duplicate / dedup → Jaccard via MinHash; plagiarism → shingle containment then edit-distance alignment; clustering → squared-Euclidean (k-means) or cosine (spherical k-means); recommendation / collaborative filtering → Pearson or a learned dot; drift monitoring → KL / JS / Wasserstein over distributions. Measure choice is *task-driven and tied to the representation* — never a default you reach for out of habit.",
        ],
        ru: [
          'Пора выложить весь инструментарий на верстак. **Семейство мер** — по тому, что каждая ловит, её диапазону, является ли она настоящей метрикой и её ловушке: **Косинус** — угол, \\([-1, 1]\\), *не* метрика (угловое расстояние \\(\\arccos(\\cos)/\\pi\\) — да), ловушка: нулевой вектор и анизотропия. **Скалярное** — угол + величина, \\((-\\infty, \\infty)\\), не метрика, ловушка: артефакты длины (его сила в MIPS). **Евклидово** — разрыв по прямой, \\([0, \\infty)\\), настоящая метрика, ловушка: шкала и концентрация в больших размерностях. **Жаккар** — пересечение множеств, \\([0, 1]\\), расстояние — метрика, ловушка: разница в размере множеств. **Редакционное / Левенштейна** — операции над строками, метрика, ловушка: \\(O(nm)\\), только короткие строки. **KL / JS** — разрыв распределений, KL это \\([0, \\infty)\\) и *не* метрика (асимметрична; \\(\\sqrt{\\mathrm{JS}}\\) — метрика), ловушка: нулевые корзины требуют сглаживания. **Пирсон** — центрированная корреляция, \\([-1, 1]\\), не метрика — и милый факт, который упускают: **Пирсон — буквально косинус после центрирования по среднему**, поэтому он убирает по-пользовательское смещение оценок в рекомендациях.',
          'Из семейства выпадает грубый **гид по выбору** (эвристика, не закон — настоящий ответ зависит от того, как *обучали* эмбеддинги): текст / эмбеддинги, где важно направление, а не длина → **косинус**; непрерывные признаки на *той же* шкале → **евклидово \\(L_2\\)**; непрерывные признаки на *разных* шкалах или с выбросами → **манхэттенское \\(L_1\\)**; категориальные / множества по пересечению членов → **Жаккар**; порядковые ранги по монотонному согласию → **Спирмен**; коррелированное, центрированное многомерное → **Пирсон**. Глубже под этим — развилка **разреженные-множества против плотных-эмбеддингов**: разреженные, почти-нулевые представления множеств (нашинкованные документы, пары пользователь–товар) хотят Жаккар + MinHash + LSH; плотные выученные векторы в \\(\\mathbb{R}^d\\) хотят косинус или скалярное плюс ANN-индекс ([HNSW, Malkov & Yashunin 2018](https://arxiv.org/abs/1603.09320), или IVF-PQ). Выбери не то семейство — косинус на сырых разреженных счётчиках или Жаккар на плотных флоатах — и ранжирование бессмысленно.',
          'И привязка к реальным *задачам*: семантический поиск / RAG → косинус (нормированный) или скалярное для обученных двойных энкодеров; почти-дубликаты / дедуп → Жаккар через MinHash; плагиат → вложенность шинглов, затем выравнивание редакционным расстоянием; кластеризация → квадрат евклида (k-means) или косинус (сферический k-means); рекомендации / коллаборативная фильтрация → Пирсон или выученное скалярное; мониторинг дрейфа → KL / JS / Вассерштейн над распределениями. Выбор меры *задаче-зависим и привязан к представлению* — никогда не дефолт, к которому тянешься по привычке.',
        ],
      },
    },
    { id: 'catch-curse-highd', kind: 'scrolly', widget: 'highd-histogram', data: 'l2-highd' },
    {
      id: 'catch-hubness-anisotropy', kind: 'prose',
      heading: { en: 'The Wraith has two more tricks', ru: 'У Призрака есть ещё два трюка' },
      img: 'L2/L2-61-wraith.png', imgPos: 'mascot',
      imgAlt: {
        en: 'The Curse-of-Dimensionality Wraith crushing a wide distance histogram down into a single thin spike.',
        ru: 'Призрак Проклятия Размерности сминает широкую гистограмму расстояний в один тонкий пик.',
      },
      imgCaption: {
        en: "Distance loses its contrast in high dimensions — and that's just the Wraith warming up. Hubness and anisotropy are his other two knives.",
        ru: 'В больших размерностях расстояние теряет контраст — и это лишь разминка Призрака. Хабность и анизотропия — два других его ножа.',
      },
      body: {
        en: [
          "The histogram you just watched is the Wraith's first trick: **distance concentration.** As the number of dimensions climbs from 2 to 1000, the spread of pairwise distances collapses toward a single spike — the nearest point becomes barely closer than the farthest, so \"nearest neighbour\" almost stops meaning anything, and a tiny perturbation flips which point wins. Real embeddings live in hundreds to thousands of dimensions, exactly where this bites. But the Wraith has two subtler tricks, and a working engineer has to recognise both.",
          "**Hubness.** In high dimensions the geometry quietly elects a few **hub** points that show up in almost *everyone's* nearest-neighbour list — not because they're truly relevant, but because of where they happen to sit — while other points (the anti-hubs) appear in nobody's. The symptom is unmistakable in a real system: the same handful of documents keep getting returned for unrelated queries. The fixes rescale the local geometry — mutual proximity, local/global scaling, mutual-kNN graphs — so a point can't be a universal neighbour by accident.",
          "**Anisotropy.** This one is about the embeddings themselves, not the dimension count. Raw representations out of a model like BERT or GPT-2 don't fill space evenly — they cram into a narrow **cone**, so even two unrelated tokens already sit at a small angle, and raw cosine reports everything as \"pretty similar.\" Your beautiful angle-measure gets inflated and loses its bite. The remedy is to push the cloud back toward isotropy — whitening, standardization, or, best of all, contrastive training that deliberately pulls synonyms together and shoves impostors apart. So take it from someone the Wraith has fooled before: never trust raw cosine on out-of-the-box hidden states until you've calibrated them.",
        ],
        ru: [
          'Гистограмма, которую ты только что смотрел, — первый трюк Призрака: **концентрация расстояний.** Когда число размерностей лезет с 2 до 1000, разброс попарных расстояний схлопывается к одному пику — ближайшая точка оказывается едва ли ближе самой дальней, так что «ближайший сосед» почти перестаёт что-либо значить, а крошечное возмущение меняет победителя. Реальные эмбеддинги живут в сотнях и тысячах размерностей — ровно там, где это и кусает. Но у Призрака есть два более тонких трюка, и работающий инженер обязан узнавать оба.',
          '**Хабность.** В высоких размерностях геометрия тихо избирает несколько точек-**хабов**, которые попадают в списки ближайших соседей почти у *всех* — не потому что они и правда релевантны, а из-за того, где они случайно сидят, — тогда как другие точки (анти-хабы) не попадают ни к кому. Симптом в реальной системе ни с чем не спутать: одна и та же горстка документов возвращается на не связанные между собой запросы. Лечат это пересчётом локальной геометрии — взаимная близость, локальное/глобальное масштабирование, графы взаимных kNN — чтобы точка не становилась универсальным соседом по случайности.',
          '**Анизотропия.** Этот трюк уже про сами эмбеддинги, а не про число размерностей. Сырые представления из модели вроде BERT или GPT-2 не заполняют пространство равномерно — они жмутся в узкий **конус**, так что даже два не связанных токена уже стоят под малым углом, и сырой косинус докладывает обо всём как о «довольно похожем». Твоя прекрасная мера угла раздувается и теряет хватку. Лекарство — толкнуть облако обратно к изотропии: отбеливание, стандартизация или, лучше всего, контрастивное обучение, которое нарочно стягивает синонимы и расталкивает самозванцев. И поверь тому, кого Призрак уже однажды провёл: никогда не доверяй сырому косинусу на «из коробки» скрытых состояниях, пока их не откалибруешь.',
        ],
      },
    },
    {
      id: 'catch-faiss-numerics', kind: 'prose',
      heading: { en: 'In practice: match the metric to the training', ru: 'На практике: метрику — под обучение' },
      body: {
        en: [
          "One last thing before the Knights take their bow, because it's the bug that bites real systems hardest. The library everyone reaches for is **FAISS** ([Johnson, Douze & Jégou 2019](https://arxiv.org/abs/1702.08734)) — and FAISS **has no native cosine metric.** It offers `METRIC_L2`, which returns *squared* \\(L_2\\) (no square root — cheaper, and the ordering is identical anyway), and `METRIC_INNER_PRODUCT` for the dot product. To get cosine you **L2-normalize your vectors first**, then use an inner-product index (`IndexFlatIP`). Forget to normalize, and your \"cosine\" search silently becomes a dot-product search that rewards long vectors — the single most common production retrieval bug, and it fails *quietly*, returning plausible-looking nonsense.",
          "The governing rule is one line: **match the index metric to how the embedding model was trained.** Most sentence models are trained against cosine, so normalize and use inner product; some retrievers (the dual encoders from the dot-product beat) are trained against dot, so feed them raw. A cosine-trained model scored under raw dot — or vice versa — behaves oddly for no obvious reason. And two numerical guards, because the edge cases will find you: cosine is **undefined for a zero vector** (the norm is zero, so you divide by zero — add a tiny \\(\\varepsilon\\), or store unit vectors and skip empties), and **KL divergence blows up on empty bins** (a zero in the denominator) so it needs smoothing before you compare two distributions. Normalize once, store unit vectors, guard the zero — and the geometry stays honest at serving time.",
        ],
        ru: [
          'Последнее, прежде чем Рыцари откланяются, потому что это баг, кусающий реальные системы сильнее всего. Библиотека, к которой все тянутся, — **FAISS** ([Johnson, Douze & Jégou 2019](https://arxiv.org/abs/1702.08734)) — и у FAISS **нет родной метрики косинуса.** Она предлагает `METRIC_L2`, возвращающую *квадрат* \\(L_2\\) (без корня — дешевле, а порядок всё равно тот же), и `METRIC_INNER_PRODUCT` для скалярного произведения. Чтобы получить косинус, **сначала L2-нормируй векторы**, потом используй индекс по скалярному произведению (`IndexFlatIP`). Забудешь нормировать — и твой «косинусный» поиск тихо станет поиском по скалярному произведению, награждающим длинные векторы; самый частый продакшн-баг поиска, и он отказывает *тихо*, возвращая правдоподобную чушь.',
          'Управляющее правило — одна строка: **подгоняй метрику индекса под то, как обучали модель эмбеддингов.** Большинство модельных предложений обучены против косинуса — нормируй и используй скалярное; некоторые ретриверы (двойные энкодеры из бита про скалярное) обучены против скалярного — корми их сырыми. Косинус-обученная модель, оцениваемая сырым скалярным — или наоборот — ведёт себя странно без видимой причины. И две численные предосторожности, ведь крайние случаи тебя найдут: косинус **не определён для нулевого вектора** (норма ноль, деление на ноль — добавь крошечный \\(\\varepsilon\\) или храни единичные векторы и пропускай пустые), а **KL-дивергенция взрывается на пустых корзинах** (ноль в знаменателе), так что ей нужно сглаживание перед сравнением двух распределений. Нормируй один раз, храни единичные векторы, стереги ноль — и геометрия останется честной во время выдачи.',
        ],
      },
    },
    {
      id: 'payoff-knights-win', kind: 'prose',
      heading: { en: 'The Knights hold the sphere', ru: 'Рыцари удерживают сферу' },
      img: 'L2/L2-70-first-contact-callback.png',
      imgAlt: {
        en: 'Serega and the alien shake hands; the cloud of question marks is replaced by one shared vector arrow.',
        ru: 'Серёга и инопланетянин жмут руки; облако вопросительных знаков заменено одной общей стрелкой-вектором.',
      },
      imgCaption: {
        en: 'Contact. The machine can finally tell when two meanings are close — First Contact resolved.',
        ru: 'Контакт. Машина наконец может сказать, когда два смысла близки — Первый контакт установлен.',
      },
      body: {
        en: [
          "So tally the mission. We turned the alien's raw text into countable units — the Tokenosaurus' sub-words, learned by BPE merges, bounded against Heaps' endless tail. Then we built the first Instrument: cosine, which measures meaning by *direction*, immune to the loudness that fooled Euclidean. And when the Curse-of-Dimensionality Wraith tried to melt every distance into mush, the trick held — because on the unit sphere, where only direction survives, the Wraith's concentration loses its grip and Sir Cosine still stands. The machine can finally judge when two meanings are close. **First Contact established.**",
          "But a question is already glowing on the console. Those vectors — where do their *directions* actually come from? So far the coordinates were just word counts, and counts don't know that *couch* and *sofa* mean the same thing; the Knights can compare directions beautifully, but only if something first points the words the right way. That's the next chapter. We're going to learn where meaning gets its coordinates — where *couch* and *sofa* finally land next to each other on the map: **embeddings.**",
        ],
        ru: [
          'Подведём итог миссии. Мы превратили сырой текст инопланетянина в счётные единицы — подслова Токенозавра, выученные слияниями BPE, ограниченные против бесконечного хвоста Хипса. Потом построили первый Инструмент: косинус, который меряет смысл по *направлению* и невосприимчив к громкости, обманувшей евклид. А когда Призрак Проклятия Размерности попытался расплавить всякое расстояние в кашу, фокус устоял — потому что на единичной сфере, где выживает только направление, концентрация Призрака теряет хватку, а Сэр Косинус по-прежнему стоит. Машина наконец может судить, когда два смысла близки. **Первый контакт установлен.**',
          'Но на консоли уже мигает вопрос. Эти векторы — откуда вообще берутся их *направления*? Пока что координатами были просто счётчики слов, а счётчики не знают, что *couch* и *sofa* значат одно и то же; Рыцари прекрасно сравнивают направления, но лишь если что-то сперва развернёт слова в правильную сторону. Это следующая глава. Мы узнаем, где смысл получает свои координаты — где *couch* и *sofa* наконец оказываются рядом на карте: **эмбеддинги.**',
        ],
      },
    },
  ],
};
