// content/book/l3.js — "The Star Catalog" (L3): Classical IR + Full-text Ranking + Rank Fusion.
// Beats match narrative/L3.md. Widgets: inverted-index, bm25-calc, rrf-fusion (built by gen_l3.py
// on a real 20 Newsgroups sub-corpus). EN canonical + RU; TT falls back. NARRATIVE_METHOD applies.

export default {
  id: '03',
  catchphrase: 'The Star Catalog',
  beats: [
    {
      id: 'hook-catalog', kind: 'prose',
      heading: { en: 'The Star Catalog', ru: 'Звёздный каталог' },
      img: 'L3/L3-00-star-catalog.png', imgPos: 'hero',
      imgAlt: {
        en: 'Serega the star-cartographer floating before a billion-point sky, plotting it onto a catalogue of constellation cards.',
        ru: 'Серёга-звёздный картограф висит перед небом из миллиарда точек, перенося его в каталог из созвездных карточек.',
      },
      imgCaption: {
        en: 'A billion documents, one of them yours. Don’t search the sky — search the catalogue of it.',
        ru: 'Миллиард документов, и один из них — твой. Не ищи в небе — ищи в его каталоге.',
      },
      body: {
        en: [
          "I'm Serega, and I'm staring at a sky of a billion documents. One of them answers the question on the screen. Just one. The other 999,999,999 are noise, and from where I'm floating they all look exactly the same — tiny points of light, indistinguishable, infinite.",
          "I can't fly past each star and check. Do the arithmetic and it's almost funny: even at a microsecond per document, a billion of them is seventeen minutes of pure looking, per query — and a user gives me about one second before they leave. So I won't search the sky at all. I'll do what every astronomer figured out centuries ago, and what every search engine quietly reinvented: don't search the sky. Search a *catalog* of it.",
          "That's the whole job today. Build the catalog, then learn to rank what it returns — because finding the right stars and putting the *best* one first are two different problems, and the second one is sneakier than it looks.",
        ],
        ru: [
          'Я Серёга, и я смотрю на небо из миллиарда документов. Один из них отвечает на вопрос на экране. Ровно один. Остальные 999 999 999 — шум, и отсюда, где я вишу, все они выглядят одинаково — крошечные точки света, неразличимые, бесконечные.',
          'Я не могу облететь каждую звезду и проверить. Прикинь арифметику — даже смешно: пусть микросекунда на документ, но миллиард документов — это семнадцать минут чистого разглядывания на один запрос, а пользователь даёт мне около секунды, прежде чем уйти. Поэтому я вообще не буду искать по небу. Я сделаю то, что астрономы поняли века назад, а каждый поисковик тихо переоткрыл: не ищи по небу — ищи по его *каталогу*.',
          'В этом и вся задача на сегодня. Построить каталог, а потом научиться ранжировать то, что он вернёт, — потому что найти нужные звёзды и поставить *лучшую* первой — это две разные задачи, и вторая коварнее, чем кажется.',
        ],
      },
    },
    {
      id: 'problem-linear-scan', kind: 'prose',
      img: 'L3/L3-01-linear-scan-doom.png', imgPos: 'scene',
      imgAlt: {
        en: 'A lone explorer who has checked 12 of 1,000,000,000 stars one by one — the brute-force scan is hopeless.',
        ru: 'Одинокий исследователь проверил 12 из 1 000 000 000 звёзд по одной — перебор безнадёжен.',
      },
      imgCaption: {
        en: 'Twelve stars checked, 999,999,988 to go, and the user already left. Brute force isn’t slow — it’s hopeless.',
        ru: 'Проверено двенадцать звёзд, осталось 999 999 988, а пользователь уже ушёл. Перебор не медленный — он безнадёжный.',
      },
      body: {
        en: [
          "Let's name the naive plan first, so we can watch it die. Read every document at query time and check whether it matches. That's called a **linear scan**, and it is a complete non-starter. Ten milliseconds to open and read a single document, times a billion documents, is months of wall-clock time for *one* search. Multiply by the thousands of queries arriving every second and you haven't built a search engine, you've built a space heater.",
          "And the budget you're up against is brutal. A user perceives anything under about **100 milliseconds** as instant, gives you maybe a second before they feel the lag, and is gone by two or three. That 100 ms isn't even all yours — the network round-trip, the page render, and the other services in the request each take a slice, so the actual time the ranker gets to *think* is a fraction of it. A scan that needs minutes to touch a billion documents has overspent the budget by seven orders of magnitude before it has ranked a single result.",
          "And don't fix it by buying more machines. You can shard the scan across a thousand servers and you've still turned months into hours — for a budget that's supposed to be one second. The problem isn't horsepower. The problem is that you're reading the whole library to answer every question, and the library keeps growing.",
          "We need the answer before we've touched even a thousandth of the sky. That means doing the expensive work *once*, ahead of time, and turning each query into a cheap lookup against what we precomputed. Hold that thought — precompute once, look up forever — because it's the spine of everything that follows.",
        ],
        ru: [
          'Сначала назовём наивный план, чтобы посмотреть, как он умрёт. Прочитать каждый документ в момент запроса и проверить совпадение. Это называется **линейное сканирование**, и это полный тупик. Десять миллисекунд, чтобы открыть и прочитать один документ, умножить на миллиард документов — это месяцы реального времени на *один* поиск. Умножь на тысячи запросов, приходящих каждую секунду, — и ты построил не поисковик, а обогреватель.',
          'А бюджет, против которого ты бьёшься, беспощаден. Всё, что меньше примерно **100 миллисекунд**, пользователь воспринимает как мгновенное, секунду ещё терпит до ощущения тормоза, а через две-три уходит. И эти 100 мс даже не все твои — сетевой круг, отрисовка страницы и другие сервисы в запросе откусывают по куску, так что времени, чтобы ранкер *подумал*, остаётся доля от них. Скан, которому нужны минуты, чтобы тронуть миллиард документов, перерасходовал бюджет на семь порядков ещё до того, как отранжировал хоть один результат.',
          'И не чини это покупкой машин. Размажь скан по тысяче серверов — и месяцы превратятся в часы, при бюджете, который должен быть в одну секунду. Дело не в мощности. Дело в том, что ты перечитываешь всю библиотеку, чтобы ответить на каждый вопрос, а библиотека всё растёт.',
          'Нам нужен ответ ещё до того, как мы тронули хотя бы тысячную долю неба. А значит — сделать дорогую работу *один раз*, заранее, и превратить каждый запрос в дешёвый поиск по тому, что мы предвычислили. Запомни эту мысль — предвычислить однажды, искать вечно, — потому что это хребет всего дальнейшего.',
        ],
      },
    },
    {
      id: 'turn-inverted-index', kind: 'prose',
      heading: { en: 'Build the catalog', ru: 'Строим каталог' },
      img: 'L3/L3-11-inverted-index-cards.png', imgPos: 'scene',
      imgAlt: {
        en: 'A card catalogue where each card holds one term and points at the list of star-charts (documents) containing it.',
        ru: 'Картотека, где каждая карточка хранит один терм и указывает на список звёздных карт (документов), содержащих его.',
      },
      imgCaption: {
        en: 'Stop asking each document “do you have this word?” Keep one card per word that already knows the answer.',
        ru: 'Хватит спрашивать каждый документ «есть у тебя это слово?» Заведи на каждое слово карточку, которая уже знает ответ.',
      },
      body: {
        en: [
          "Here's the trick, and it's almost embarrassingly simple once you see it. Stop asking each document \"do you contain this word?\" — that's the question that forces you to visit every document. Flip it around. Keep a list, *for every word*, of which documents contain it. Ask the question once, store the answer, reuse it forever.",
          "That flipped table is the **inverted index**. \"Inverted\" because the natural direction is document → words (a document is just a list of the words inside it), and we've turned it inside out into word → documents. Picture a card catalogue: one card per word, and on each card a column of document IDs — a constellation card pointing straight at its stars. A query stops being a journey across the sky and becomes a single reach for the right card.",
        ],
        ru: [
          'Вот трюк — и он почти неловко прост, как только ты его увидишь. Перестань спрашивать каждый документ «содержишь ли ты это слово?» — это и есть вопрос, который заставляет обойти каждый документ. Переверни его. Храни список, *для каждого слова*, какие документы его содержат. Задай вопрос один раз, сохрани ответ, переиспользуй вечно.',
          'Эта перевёрнутая таблица и есть **инвертированный индекс**. «Инвертированный» — потому что естественное направление это документ → слова (документ — это просто список слов внутри него), а мы вывернули его наизнанку в слово → документы. Представь картотеку: по карточке на слово, а на каждой карточке — столбик ID документов, созвездная карточка, указывающая прямо на свои звёзды. Запрос перестаёт быть путешествием по небу и становится одним движением к нужной карточке.',
        ],
      },
    },
    { id: 'climb-index', kind: 'scrolly', widget: 'inverted-index', data: 'l3-index' },
    {
      id: 'turn-index-internals', kind: 'prose',
      heading: { en: "What's inside a catalog card", ru: 'Что внутри каталожной карточки' },
      img: 'L3/L3-12-postings-compression.png', imgPos: 'scene',
      imgAlt: {
        en: 'A postings list compressed by storing the gaps between sorted doc IDs instead of the IDs themselves.',
        ru: 'Список постингов сжат хранением разностей между отсортированными ID документов вместо самих ID.',
      },
      imgCaption: {
        en: 'Store the gaps, not the stars: a sorted postings list shrinks by keeping the differences between doc IDs.',
        ru: 'Храни разрывы, а не звёзды: отсортированный список постингов усыхает, сохраняя разницу между ID документов.',
      },
      body: {
        en: [
          "A card with a list of document IDs is the cartoon version. The real thing has more on it, and the extras are what make search *fast* rather than merely possible. The card splits into two halves: a **dictionary** that maps each term to where its list lives (and stores its document frequency, df — how many documents contain it, which we'll need for ranking in a minute), and the **postings list** itself. Each entry in that list — a **posting** — usually carries not just the document ID but the count of how many times the word appears there (its term frequency, tf), and often the exact positions, so we can later tell that \"new york\" the city is different from a document that happens to mention \"new\" and \"york\" a paragraph apart.",
          "Then there's how the catalog gets *built* in the first place. You can't sort a trillion postings in memory, so indexers stream the corpus in blocks, sort each block to disk, and merge the sorted runs together — the same merge-sort idea your data-structures course beat into you, just at planetary scale. The two classic recipes have names, both laid out in [Manning, Raghavan & Schütze (2008)](https://nlp.stanford.edu/IR-book/): **BSBI** (block sort-based indexing) sorts blocks of term-IDs; **SPIMI** (single-pass in-memory indexing) skips the global sort entirely and grows per-term lists on the fly. Either way the output is the same shape, and that's why production engines like Lucene store the index as immutable *segments* that get merged in the background: building and serving never stop fighting for the same machine.",
          "And the lists get *compressed*, hard, with a one-two punch. First, the document IDs on a card are sorted, so you store the first ID and then the **gaps** — for a list `3, 8, 12, 30` you keep `3, +5, +4, +18`, tiny numbers instead of full IDs. Second, **variable-byte** coding packs each small gap into as few bytes as it needs: one byte carries seven data bits plus a continuation bit, so any gap below 128 fits in a single byte. Run the arithmetic on that list — four 32-bit IDs is 16 bytes naively; four gaps, each under 128, is 4 bytes. That's a clean **\\(4\\times\\) compression**, and on a popular word's list the ratio is far higher. More of the list fits in cache, so the lookup the user is waiting on touches memory instead of disk. None of this is glamorous. All of it is the difference between a demo and an engine.",
          "Last piece: matching documents to a multi-word query is a **merge** of sorted lists, and you can make it skip. To find documents containing *both* \"space\" and \"team\", walk the two sorted lists together like a zipper; with skip pointers you can leap over chunks of one list that can't possibly match. Start from the rarest word — its list is shortest, so it does the least work. That instinct, *rarest first*, is going to come back the moment we start ranking.",
        ],
        ru: [
          'Карточка со списком ID документов — это мультяшная версия. У настоящей внутри больше, и именно добавки делают поиск *быстрым*, а не просто возможным. Карточка делится надвое: **словарь**, что отображает каждый терм в то, где лежит его список (и хранит его документную частоту, df — в скольких документах он есть, что понадобится нам для ранжирования через минуту), и сам **список постингов**. Каждая запись в этом списке — **постинг** — обычно несёт не только ID документа, но и счётчик, сколько раз слово там встречается (его частоту термина, tf), а часто и точные позиции, чтобы потом отличить «нью-йорк» как город от документа, где «нью» и «йорк» просто стоят через абзац.',
          'Дальше — как каталог вообще *строится*. Триллион постингов в памяти не отсортируешь, поэтому индексаторы гонят корпус блоками, сортируют каждый блок на диск и сливают отсортированные пробеги вместе — та самая идея слияния-сортировки, которую вбивали в тебя на структурах данных, только в планетарном масштабе. У двух классических рецептов есть имена, оба расписаны в [Manning, Raghavan & Schütze (2008)](https://nlp.stanford.edu/IR-book/): **BSBI** (блочная сортирующая индексация) сортирует блоки ID-термов; **SPIMI** (однопроходная индексация в памяти) вообще пропускает глобальную сортировку и наращивает списки по термам на лету. В любом случае результат одной формы, и поэтому продакшн-движки вроде Lucene хранят индекс как неизменяемые *сегменты*, которые сливаются в фоне: построение и обслуживание всё время дерутся за одну машину.',
          'И списки *сжимаются*, жёстко, двойным ударом. Во-первых, ID документов на карточке отсортированы, поэтому ты хранишь первый ID, а дальше — **разности**: для списка `3, 8, 12, 30` держишь `3, +5, +4, +18`, крошечные числа вместо полных ID. Во-вторых, **переменно-байтовое** кодирование пакует каждую малую разность в столько байт, сколько нужно: один байт несёт семь бит данных плюс бит продолжения, так что любая разность меньше 128 влезает в один байт. Прокрути арифметику на этом списке — четыре 32-битных ID это наивно 16 байт; четыре разности, каждая меньше 128, это 4 байта. Это честное **сжатие в \\(4\\times\\)**, а на списке популярного слова отношение куда выше. Больше списка помещается в кэш, поэтому поиск, которого ждёт пользователь, трогает память, а не диск. Ничего гламурного. И при этом — вся разница между демо и движком.',
          'Последнее: сопоставить документы многословному запросу — это **слияние** отсортированных списков, и его можно ускорить пропусками. Чтобы найти документы сразу со «space» и «team», иди по двум отсортированным спискам вместе, как застёжка-молния; со skip-указателями ты перепрыгиваешь куски одного списка, которые заведомо не совпадут. Начинай с самого редкого слова — его список короче, значит, и работы меньше. Этот инстинкт, *сначала редкое*, вернётся в тот же миг, как мы начнём ранжировать.',
        ],
      },
    },
    { id: 'climb-compression', kind: 'scrolly', widget: 'postings-compression', data: 'l3-compression' },
    {
      id: 'turn-boolean-phrase', kind: 'prose',
      heading: { en: 'Boolean queries and phrases', ru: 'Булевы запросы и фразы' },
      body: {
        en: [
          "Before we rank anything, let's see how far the catalog gets us on *matching* alone — because the merge we just built is more flexible than \"both words must appear\". The **boolean model**, the oldest retrieval model there is, maps the three logical operators straight onto set operations over postings lists. **AND is intersection**: for postings `cat → [D1, D2, D3]` and `dog → [D1, D2]`, the query `cat AND dog` returns \\([D1,D2,D3]\\cap[D1,D2] = [D1, D2]\\) — and notice it's *non-empty*, unlike the disjoint `space AND team` from a moment ago, because here the words genuinely co-occur. **OR is union**: `dog OR mouse` = \\([D1,D2]\\cup[D2,D3] = [D1, D2, D3]\\), which broadens recall when you'd rather over-return than miss. **NOT is set difference**: `cat AND NOT mouse` = \\([D1,D2,D3]\\setminus[D2,D3] = [D1]\\), keeping the cat documents that *don't* also mention mouse. Three operators, three set operations, all of them a single linear pass over sorted lists.",
          "There's one optimization a real query planner never skips, and it's the same instinct from the skip-merge: for a multi-term AND, **intersect the rarest term first** — the one with the smallest df. The running intersection can only *shrink* as you fold in more lists, so starting from the shortest list means every later merge runs against an already-tiny result. Rarest first, again. This is the standard machinery in [Manning, Raghavan & Schütze (2008)](https://nlp.stanford.edu/IR-book/), the inverted-index textbook this whole section follows.",
          "Boolean matching has one blind spot the card-of-doc-IDs can't fix on its own: it can tell you *both* \"new\" and \"york\" appear in a document, but not that they appear *next to each other* as the phrase \"new york\". For that you need the positions we tucked into each posting — the **positional index**. Each posting now carries, per term, the list of token offsets where it occurs: say `new → D5:[3, 11]` and `york → D5:[4, 27]`. A **phrase query** is then a two-stage merge. First the ordinary doc-level AND: both \"new\" and \"york\" land in D5, so D5 is a *candidate* — necessary, but not yet sufficient. Then the positional check: is there an offset \\(p\\) of \"new\" and an offset \\(q\\) of \"york\" with \\(q - p = 1\\)? Test \\(p = 3\\): \"york\" sits at \\(q = 4\\), and \\(4 - 3 = 1\\) — a hit, the phrase \"new york\" really occurs. Test \\(p = 11\\): the nearest \"york\" is at 27, a gap of 16 — not adjacent, a false co-occurrence rejected. Two appearances of both words, but only *one* genuine phrase.",
          "Generalize that gap and you get **proximity search** for free: a phrase is the special case \\(\\text{gap} = 1\\); \"within \\(k\\) words\" is just \\(\\text{gap} \\le k\\). The cost is real — storing every position bloats the index well beyond a plain doc-ID list — but it's the price of telling \"new york\" the city from a document that merely scatters \"new\" and \"york\" across different paragraphs, and exact phrase matching is non-negotiable for names, quotations, and code. Matching, though, is still binary: present or absent, phrase or no phrase. The catalog can tell you *which* documents qualify. It still says nothing about which are *best*.",
        ],
        ru: [
          'Прежде чем что-то ранжировать, посмотрим, как далеко каталог уводит нас на одном *совпадении*, — ведь слияние, что мы построили, гибче, чем «оба слова обязаны быть». **Булева модель**, старейшая модель поиска, отображает три логических оператора прямо на операции над множествами постингов. **AND — это пересечение**: для постингов `cat → [D1, D2, D3]` и `dog → [D1, D2]` запрос `cat AND dog` даёт \\([D1,D2,D3]\\cap[D1,D2] = [D1, D2]\\) — и заметь, оно *непусто*, в отличие от непересекающегося `space AND team` минуту назад, потому что здесь слова по-настоящему встречаются вместе. **OR — это объединение**: `dog OR mouse` = \\([D1,D2]\\cup[D2,D3] = [D1, D2, D3]\\), что расширяет полноту, когда лучше вернуть лишнее, чем упустить. **NOT — это разность множеств**: `cat AND NOT mouse` = \\([D1,D2,D3]\\setminus[D2,D3] = [D1]\\), оставляя документы про кота, которые *не* упоминают ещё и мышь. Три оператора, три операции над множествами, и все — один линейный проход по отсортированным спискам.',
          'Есть одна оптимизация, которую настоящий планировщик запросов не пропускает никогда, и это тот же инстинкт, что в skip-слиянии: для многословного AND **пересекай сначала самый редкий терм** — с наименьшей df. Бегущее пересечение может только *сжиматься* по мере добавления списков, поэтому, начав с самого короткого, ты гонишь каждое следующее слияние против уже крошечного результата. Снова — сначала редкое. Это стандартная механика из [Manning, Raghavan & Schütze (2008)](https://nlp.stanford.edu/IR-book/), учебника по инвертированному индексу, которому следует весь этот раздел.',
          'У булева совпадения есть слепое пятно, которое карточка из ID документов сама не закроет: она скажет, что *оба* слова «new» и «york» есть в документе, но не то, что они стоят *рядом* как фраза «new york». Для этого нужны позиции, которые мы вложили в каждый постинг, — **позиционный индекс**. Каждый постинг теперь несёт, по терму, список смещений токенов, где он встречается: скажем, `new → D5:[3, 11]` и `york → D5:[4, 27]`. **Фразовый запрос** тогда — двухэтапное слияние. Сперва обычный AND на уровне документа: и «new», и «york» попадают в D5, значит D5 — *кандидат*: необходимо, но ещё не достаточно. Затем позиционная проверка: есть ли смещение \\(p\\) у «new» и смещение \\(q\\) у «york» с \\(q - p = 1\\)? Проверь \\(p = 3\\): «york» стоит на \\(q = 4\\), и \\(4 - 3 = 1\\) — попадание, фраза «new york» и вправду встречается. Проверь \\(p = 11\\): ближайший «york» на 27, разрыв 16 — не рядом, ложная совстречаемость отвергнута. Два появления обоих слов, но настоящая фраза лишь *одна*.',
          'Обобщи этот разрыв — и **поиск по близости** достаётся бесплатно: фраза — частный случай \\(\\text{разрыв} = 1\\); «в пределах \\(k\\) слов» — это просто \\(\\text{разрыв} \\le k\\). Цена реальна — хранение каждой позиции раздувает индекс далеко за пределы простого списка ID, — но это плата за умение отличить «new york» как город от документа, где «new» и «york» просто разбросаны по разным абзацам, а точное совпадение фраз обязательно для имён, цитат и кода. Совпадение, впрочем, всё ещё бинарно: есть или нет, фраза или не фраза. Каталог скажет, *какие* документы подходят. Он по-прежнему молчит о том, какие *лучшие*.',
        ],
      },
    },
    {
      id: 'turn-scoring', kind: 'prose',
      heading: { en: 'Matching isn’t ranking', ru: 'Совпадение — это не ранжирование' },
      body: {
        en: [
          "Now watch a quieter failure. Ask the catalog for documents that contain *both* of two query words and sometimes you get back… nothing. A strict boolean AND is brittle: one missing word and a genuinely great document is exiled. Loosen it to OR and you get the opposite disaster — hundreds of documents, all technically matching, none of them ordered. The index tells you *which* documents qualify. It says nothing about which are *best*.",
          "Matching is binary; relevance is a spectrum. A document that uses your rare keyword five times in two sentences is almost certainly more on-topic than one that mentions it once in a footnote — and a word that appears in *every* document tells you nothing at all about which to prefer. So the classic recipe has two instincts baked in: reward rare words more than common ones, and don't let a single word repeated a hundred times drown out everything else. Hold those two instincts. We're about to make them arithmetic.",
        ],
        ru: [
          'Теперь смотри на провал потише. Спроси каталог о документах, содержащих сразу *оба* слова запроса, — и иногда получишь… ничего. Строгое булево AND хрупко: одно недостающее слово, и по-настоящему отличный документ отправлен в изгнание. Ослабь до OR — и получишь обратную катастрофу: сотни документов, все формально совпадают, ни один не упорядочен. Индекс говорит, *какие* документы подходят. Он молчит о том, какие *лучшие*.',
          'Совпадение бинарно; релевантность — спектр. Документ, где твоё редкое слово стоит пять раз в двух предложениях, почти наверняка ближе к теме, чем тот, где оно мелькнуло раз в сноске, — а слово, которое есть в *каждом* документе, вообще ничего не говорит о выборе. Поэтому в классическом рецепте зашиты два инстинкта: награждать редкие слова сильнее частых и не давать одному слову, повторённому сто раз, заглушить всё остальное. Запомни эти два инстинкта. Сейчас мы сделаем их арифметикой.',
        ],
      },
    },
    {
      id: 'turn-bow', kind: 'prose',
      heading: { en: 'Bag-of-Words', ru: 'Мешок слов' },
      img: 'L3/L3-16-bag-of-words.png', imgPos: 'scene',
      imgAlt: {
        en: 'A document tipped into a bag; word order spills out and only the word counts remain.',
        ru: 'Документ вытряхивают в мешок; порядок слов теряется, остаются только счётчики слов.',
      },
      imgCaption: {
        en: '“Dog bites man” and “man bites dog” land in the same bag. Comically wrong — and it works anyway.',
        ru: '«Собака укусила человека» и «человек укусил собаку» падают в один мешок. Смешно неправильно — и всё равно работает.',
      },
      body: {
        en: [
          "Before we can weigh words, we need to agree on what a document *is* to the math. Here's the move that quietly underlies all of classical IR, and it has a name worth saying out loud: **Bag-of-Words**. Take a document, dump every word into a bag, shake it, throw away the order. All you keep is *which* words appeared and *how many times*. \"Dog bites man\" and \"man bites dog\" become the same bag — which is obviously, comically wrong, and somehow works anyway for an astonishing range of tasks.",
          "Why it works: lay every document's bag out as a row of counts over a fixed vocabulary and you've built a **document-term matrix** — every document is now a vector, a point in a space with one axis per word. Make it concrete with three tiny sentences — \"the cat sat on the mat\", \"the dog sat on the log\", \"cats and dogs play\". The shared vocabulary has eleven words (`and, cat, cats, dog, dogs, log, mat, on, play, sat, the`), so each sentence becomes an eleven-number row: the first is `[0,1,0,0,0,0,1,1,0,1,2]` — one \"cat\", one \"mat\", one \"on\", one \"sat\", and \"the\" twice. Geometry arrives for free. Documents that share many words sit near each other; a query is just another short vector you can compare against all of them. This is the **vector space model** — [Salton, Wong & Yang (1975)](https://doi.org/10.1145/361219.361220) — and it's the bridge from \"a pile of text\" to \"something a computer can rank.\"",
          "And it's immediately, concretely useful. A spam filter is mostly Bag-of-Words: it doesn't parse your email's grammar, it counts words — \"free\", \"winner\", \"viagra\" push the score toward spam; the words in your actual correspondence pull it back — and a naïve probability model on those counts catches the junk with embarrassing reliability. The catch is the one we just admitted: throwing away order means \"the movie was good, not bad\" and \"the movie was bad, not good\" look nearly identical to the bag. Order carries meaning, and we just shredded it. We'll spend a whole later chapter buying it back. For now, the bag is enough — because the real signal isn't *whether* a word appears, it's *how much it should count*.",
        ],
        ru: [
          'Прежде чем взвешивать слова, нужно договориться, чем документ *является* для математики. Вот ход, который тихо лежит в основе всего классического IR, и у него есть имя, которое стоит произнести вслух: **мешок слов** (Bag-of-Words). Берём документ, ссыпаем все слова в мешок, трясём, выбрасываем порядок. Остаётся только то, *какие* слова встретились и *сколько раз*. «Собака кусает человека» и «человек кусает собаку» становятся одним мешком — что очевидно и комично неверно, и почему-то всё равно работает для поразительного спектра задач.',
          'Почему работает: разложи мешок каждого документа строкой счётчиков по фиксированному словарю — и ты построил **матрицу документ–термин**: каждый документ теперь вектор, точка в пространстве с осью на каждое слово. Сделай это конкретным на трёх крошечных предложениях — «the cat sat on the mat», «the dog sat on the log», «cats and dogs play». Общий словарь — одиннадцать слов (`and, cat, cats, dog, dogs, log, mat, on, play, sat, the`), поэтому каждое предложение становится строкой из одиннадцати чисел: первое — `[0,1,0,0,0,0,1,1,0,1,2]` — одна «cat», одна «mat», одна «on», одна «sat» и «the» дважды. Геометрия приходит бесплатно. Документы, делящие много слов, стоят рядом; запрос — это просто ещё один короткий вектор, который можно сравнить со всеми. Это **векторная модель** — [Salton, Wong & Yang (1975)](https://doi.org/10.1145/361219.361220) — мост от «кучи текста» к «тому, что компьютер умеет ранжировать».',
          'И польза мгновенная, конкретная. Спам-фильтр — это в основном мешок слов: он не разбирает грамматику письма, он считает слова — «бесплатно», «победитель», «viagra» толкают оценку к спаму; слова твоей реальной переписки тянут назад — и наивная вероятностная модель на этих счётчиках ловит мусор с неприличной надёжностью. Подвох тот, что мы только что признали: выбросив порядок, «фильм хороший, а не плохой» и «фильм плохой, а не хороший» для мешка почти неотличимы. Порядок несёт смысл, а мы его только что измельчили. Целую будущую главу мы потратим, чтобы выкупить его обратно. Пока мешка хватит — потому что настоящий сигнал не в том, *встречается* ли слово, а в том, *насколько оно должно считаться*.',
        ],
      },
    },
    {
      id: 'climb-tfidf', kind: 'prose',
      heading: { en: 'TF-IDF: rare words carry the signal', ru: 'TF-IDF: сигнал несут редкие слова' },
      img: 'L3/L3-17-reweight.png', imgPos: 'scene',
      imgAlt: {
        en: 'A balance scale where common words shrink light and rare words grow heavy — TF-IDF re-weighting.',
        ru: 'Весы, где частые слова легчают, а редкие тяжелеют — перевзвешивание TF-IDF.',
      },
      imgCaption: {
        en: '“The” is in everything, so it tells you nothing. The rarer the word, the louder it should count.',
        ru: '«The» есть везде — значит, не говорит ни о чём. Чем реже слово, тем громче оно должно звучать.',
      },
      body: {
        en: [
          "So we weight the counts in the bag with two ideas that fight in opposite directions. The first is **term frequency** \\(tf\\): a word that appears more often in a document is, all else equal, more *about* that document. The second is **inverse document frequency** \\(idf\\) — [Spärck Jones (1972)](https://doi.org/10.1108/eb026526) — and it's the clever one. A word that shows up in *every* document — \"the\", or \"space\" inside a corpus that's all about space — is useless for telling documents apart, no matter how often it appears. A word that shows up in only a handful of documents is gold: when it matches, it really means something.",
          "Multiply them — \\(tf \\cdot idf\\) — and you get a weight that rewards documents rich in the query's *rare* words while shrugging off the common ones. Watch it bite on two documents: A = \"The car is driven on the road\", B = \"The truck is driven on the highway\". With $$idf = \\log\\frac{2}{df}$$ the words they *share* — \"the\", \"is\", \"driven\", \"on\" — all have \\(df = 2\\), so \\(idf = \\log(2/2) = 0\\), and they contribute *nothing* to either score even though they're most of the text. Only the distinguishing words survive: \"car\" and \"road\" (\\(df = 1\\), idf = **0.6931**) carry document A; \"truck\" and \"highway\" carry document B; each lands a \\(tf \\cdot idf\\) of about **0.099**. The math is doing exactly what your intuition wanted — it's learning which words are worth listening to, from the corpus alone, with nobody labelling anything.",
          "TF-IDF is a genuinely great first instrument, and for years it *was* search. But it has two flaws you can feel if you push on it. First, \\(tf\\) is **linear**: a word that appears ten times scores ten times as high as a word that appears once — but the tenth mention almost never adds ten times the evidence. Second, it has a weak sense of **length**: a long document accumulates raw counts just by being long, so it can outscore a short, perfectly-on-point one for no good reason. Two flaws, both fixable. Fixing them is the most interesting story in this whole chapter.",
        ],
        ru: [
          'Итак, мы взвешиваем счётчики в мешке двумя идеями, тянущими в разные стороны. Первая — **частота термина** \\(tf\\): слово, что встречается в документе чаще, при прочих равных сильнее *о* нём говорит. Вторая — **обратная частота документа** \\(idf\\) — [Spärck Jones (1972)](https://doi.org/10.1108/eb026526) — и она хитрая. Слово, которое есть в *каждом* документе — «the» или «space» в корпусе, целиком про космос, — бесполезно для различения документов, как часто бы оно ни встречалось. Слово, которое есть лишь в горстке документов, — золото: когда оно совпадает, это действительно что-то значит.',
          'Перемножь их — \\(tf \\cdot idf\\) — и получишь вес, награждающий документы, богатые *редкими* словами запроса, и отмахивающийся от частых. Смотри, как он кусается на двух документах: A = «The car is driven on the road», B = «The truck is driven on the highway». При $$idf = \\log\\frac{2}{df}$$ слова, что у них *общие* — «the», «is», «driven», «on», — все имеют \\(df = 2\\), поэтому \\(idf = \\log(2/2) = 0\\), и они дают *ноль* вклада в любую из оценок, хотя ими занят почти весь текст. Выживают только различающие: «car» и «road» (\\(df = 1\\), idf = **0,6931**) несут документ A; «truck» и «highway» несут документ B; каждое набирает \\(tf \\cdot idf\\) около **0,099**. Математика делает ровно то, чего хотела интуиция: она учится, какие слова стоит слушать, из одного корпуса, без единой разметки.',
          'TF-IDF — по-настоящему отличный первый инструмент, и годами он *и был* поиском. Но у него два изъяна, которые ощущаешь, если нажать. Первый: \\(tf\\) **линеен**: слово, встретившееся десять раз, набирает в десять раз больше, чем встретившееся раз, — но десятое упоминание почти никогда не добавляет десятикратной улики. Второй: у него слабое чувство **длины**: длинный документ копит сырые счётчики просто потому, что он длинный, и может обойти короткий, идеально по теме, без всякой причины. Два изъяна, оба чинятся. Их починка — самая интересная история во всей этой главе.',
        ],
      },
    },
    { id: 'climb-bm25', kind: 'scrolly', widget: 'bm25-calc', data: 'l3-bm25' },
    {
      id: 'climb-bm25-numbers', kind: 'prose',
      heading: { en: 'BM25, by the numbers', ru: 'BM25 в числах' },
      img: 'L3/L3-02-bm25-sextant.png', imgPos: 'scene',
      imgAlt: {
        en: 'BM25 drawn as a trusty brass sextant — the classic instrument for taking a bearing on relevance.',
        ru: 'BM25 изображён как надёжный латунный секстант — классический прибор, чтобы взять пеленг на релевантность.',
      },
      imgCaption: {
        en: 'BM25 is the trusty old sextant: two well-tuned dials, \\(k_1\\) and \\(b\\), and it takes an accurate bearing on relevance.',
        ru: 'BM25 — надёжный старый секстант: два хорошо настроенных диска, \\(k_1\\) и \\(b\\), и он берёт точный пеленг на релевантность.',
      },
      body: {
        en: [
          "Let me make the figure you just stepped through reproducible with pen and paper, because the whole point of BM25 is that the numbers *move* the way your intuition wanted — and you should watch them move. Take a toy collection of three tiny documents: D1 = \"cat cat dog\", D2 = \"cat dog dog mouse\", D3 = \"mouse cat\". The query is *cat dog*. Three docs of length 3, 4, and 2, so the average document length is \\(avgdl = (3 + 4 + 2)/3 = 3.0\\) — and BM25 uses \\(k_1 = 1.5\\), \\(b = 0.75\\).",
          "Start with idf, the rare-word reward, smoothed so it never blows up. \"cat\" appears in all three documents (\\(df = 3\\)), so its \\(idf = \\ln\\!\\big(1 + \\frac{3 - 3 + 0.5}{3 + 0.5}\\big) = \\ln(1.1429) = 0.1335\\) — tiny, because a word in every document barely distinguishes them. \"dog\" appears in only two (\\(df = 2\\)), so \\(idf = \\ln\\!\\big(1 + \\frac{3 - 2 + 0.5}{2 + 0.5}\\big) = \\ln(1.6) = 0.4700\\) — three and a half times heavier. The rarer word already carries most of the signal before we count a single occurrence.",
          "Now the saturating part, the piece that fixes TF-IDF's linearity. Each term contributes \\(idf \\cdot B\\), where the saturating, length-aware factor is $$B=\\frac{tf\\,(k_1+1)}{tf + k_1\\big[(1-b)+b\\,\\frac{len}{avgdl}\\big]}$$ a fraction that rises fast for the first occurrence and then flattens, with the bracket gently penalising long documents. Take it slowly and work one term fully: \"dog\" in D2, which has \\(tf = 2\\) and length 4. The bracket is \\((1-0.75) + 0.75\\cdot(4/3) = 1.25\\), the numerator is \\(2\\cdot(1.5+1) = 5\\), the denominator is \\(2 + 1.5\\cdot1.25 = 3.875\\), so \\(B = 5/3.875 = 1.2903\\), and the term's weight is \\(1.2903 \\cdot 0.4700 = 0.6065\\). That single number is two-thirds of why D2 wins.",
          "That was the hardest term; the rest is just bookkeeping. Sum the two terms per document and the ranking falls out. D2 = 0.1161 (cat) + 0.6065 (dog) = **0.7226**. D1 = 0.1908 (cat, \\(tf = 2\\)) + 0.4700 (dog) = **0.6608**. D3 = 0.1571 (cat) + 0 (no dog) = **0.1571**. So **D2 > D1 > D3** — and notice *why*: D1 says \"cat\" twice, but saturation means that second \"cat\" adds almost nothing (0.1908 vs a single-mention 0.1335), while D2's two \"dog\"s land on the heavier idf and on the saturating curve's steep part. The short, on-point D2 beats the longer-but-repetitive D1, and the barely-relevant D3 trails far behind. That is the sextant working, one number at a time.",
          "One more query nails down the idf instinct, because in cat/dog the two words were close in rarity. Run *nasa shuttle* over a small real sub-corpus where the terms are genuinely far apart: \"nasa\" is in three documents (idf = **0.9445**), \"shuttle\" in only two (idf = **1.2809**), so the rarer word is the heavier one before any counting. The document that says \"shuttle\" three times and \"nasa\" once scores **2.8151** and wins outright; a document with \"nasa\" twice and \"shuttle\" once trails at 2.4733; and a document with a lone \"nasa\" and no \"shuttle\" sits at 0.9249. The rare term dominates — exactly as idf promised — and saturation keeps the triple-\"shuttle\" from running away with a tenfold score it didn't earn.",
        ],
        ru: [
          'Дай я сделаю фигуру, по которой ты только что шагал, воспроизводимой с карандашом и бумагой, — ведь весь смысл BM25 в том, что числа *движутся* так, как хотела твоя интуиция, и на это стоит посмотреть. Возьми игрушечную коллекцию из трёх крошечных документов: D1 = «cat cat dog», D2 = «cat dog dog mouse», D3 = «mouse cat». Запрос — *cat dog*. Три документа длиной 3, 4 и 2, значит средняя длина \\(avgdl = (3 + 4 + 2)/3 = 3{,}0\\) — а BM25 берёт \\(k_1 = 1{,}5\\), \\(b = 0{,}75\\).',
          'Начни с idf, награды за редкость, сглаженной так, чтобы она не взрывалась. «cat» есть во всех трёх документах (\\(df = 3\\)), поэтому его \\(idf = \\ln\\!\\big(1 + \\frac{3 - 3 + 0{,}5}{3 + 0{,}5}\\big) = \\ln(1{,}1429) = 0{,}1335\\) — крошечная, ведь слово в каждом документе их почти не различает. «dog» есть лишь в двух (\\(df = 2\\)), поэтому \\(idf = \\ln\\!\\big(1 + \\frac{3 - 2 + 0{,}5}{2 + 0{,}5}\\big) = \\ln(1{,}6) = 0{,}4700\\) — в три с половиной раза тяжелее. Более редкое слово уже несёт почти весь сигнал, ещё до того как мы сосчитали хоть одно вхождение.',
          'Теперь насыщающаяся часть, та, что чинит линейность TF-IDF. Каждый термин даёт \\(idf \\cdot B\\), где насыщающийся и учитывающий длину множитель — это $$B=\\frac{tf\\,(k_1+1)}{tf + k_1\\big[(1-b)+b\\,\\frac{len}{avgdl}\\big]}$$ дробь, что круто растёт на первом вхождении и потом выполаживается, а скобка мягко наказывает длинные документы. Не спеша прокрути один термин полностью: «dog» в D2, у которого \\(tf = 2\\) и длина 4. Скобка — \\((1-0{,}75) + 0{,}75\\cdot(4/3) = 1{,}25\\), числитель — \\(2\\cdot(1{,}5+1) = 5\\), знаменатель — \\(2 + 1{,}5\\cdot1{,}25 = 3{,}875\\), поэтому \\(B = 5/3{,}875 = 1{,}2903\\), а вес термина — \\(1{,}2903 \\cdot 0{,}4700 = 0{,}6065\\). Это одно число — две трети причины, почему D2 побеждает.',
          'Это был самый тяжёлый термин; дальше — лишь арифметика. Просуммируй два термина по документу — и ранжирование выпадает само. D2 = 0,1161 (cat) + 0,6065 (dog) = **0,7226**. D1 = 0,1908 (cat, \\(tf = 2\\)) + 0,4700 (dog) = **0,6608**. D3 = 0,1571 (cat) + 0 (нет dog) = **0,1571**. Итак, **D2 > D1 > D3** — и заметь *почему*: D1 говорит «cat» дважды, но из-за насыщения второй «cat» добавляет почти ничего (0,1908 против 0,1335 за одно упоминание), тогда как два «dog» в D2 ложатся на более тяжёлую idf и на крутую часть насыщающейся кривой. Короткий, по теме D2 обходит длинный-но-повторяющийся D1, а едва релевантный D3 плетётся далеко позади. Вот так секстант и работает — по одному числу за раз.',
          'Ещё один запрос закрепляет инстинкт idf, ведь в cat/dog оба слова были близки по редкости. Прогони *nasa shuttle* по маленькому реальному подкорпусу, где термины по-настоящему разнесены: «nasa» в трёх документах (idf = **0,9445**), «shuttle» лишь в двух (idf = **1,2809**), так что более редкое слово тяжелее ещё до всякого счёта. Документ, где «shuttle» трижды и «nasa» раз, набирает **2,8151** и побеждает начисто; документ с «nasa» дважды и «shuttle» раз отстаёт с 2,4733; а документ с одиноким «nasa» и без «shuttle» сидит на 0,9249. Редкий термин доминирует — ровно как обещала idf, — а насыщение не даёт тройному «shuttle» убежать с десятикратной оценкой, которую он не заработал.',
        ],
      },
    },
    {
      id: 'climb-bm25-history', kind: 'prose',
      heading: { en: 'The BM25 saga', ru: 'Сага о BM25' },
      img: 'L3/L3-13-bm25-saga.png', imgPos: 'scene',
      imgAlt: {
        en: 'A timeline of ranking instruments refined over generations: knotted rope → TF·IDF → sextant (BM25) → tuned BM25 with k₁ and b dials.',
        ru: 'Линия времени инструментов ранжирования, оттачиваемых поколениями: узловая верёвка → TF·IDF → секстант (BM25) → настроенный BM25 с дисками k₁ и b.',
      },
      imgCaption: {
        en: 'Each instrument was earned by the last one drowning at sea. “25” isn’t a version — it’s the 25th try that finally held.',
        ru: 'Каждый прибор заработан тем, что предыдущий утонул в море. «25» — не версия, а 25-я попытка, которая наконец устояла.',
      },
      body: {
        en: [
          "That formula you just watched — BM25 — didn't spring out of anyone's head. It's a sextant, tuned over thirty years, each notch filed off only after the previous instrument failed at sea. The \"BM\" stands for *Best Match*, and the number 25 is not a version label some marketer chose; it is literally the twenty-fifth variant the team worked through. The story of how they got there is the best engineering parable I know, so let me actually tell it.",
          "It starts in the 1970s with a question that sounds academic and turns out to be the whole game: given a query, which documents are most *probably* relevant? Stephen Robertson and Karen Spärck Jones formalised it as the **Probabilistic Ranking Principle** — rank documents by their odds of being relevant — and from it fell out the **RSJ weight** ([Robertson & Spärck Jones, 1976](https://doi.org/10.1002/asi.4630270302)), essentially the idf we just used, born from probability rather than guessed. That first ranker, **BM1**, only asked *is the word present or not*. It completely ignored how many times the word appeared. You already know why that's not enough.",
          "So they added term frequency — and immediately hit the linearity flaw, the same one we just found in TF-IDF. Their fix came from a piece of theory called the **2-Poisson model** ([Robertson, 1981](https://doi.org/10.1108/eb026690)): imagine a word is \"elite\" to a document when the document is genuinely about that word's topic, and model the counts as a mixture of two Poisson distributions, elite and not. Work through the math and the optimal weight isn't linear in tf at all — it's a *saturating* curve that rises fast for the first few occurrences and then flattens. That is the deep \"why\" behind the shape: the second mention of a word is strong evidence, the fiftieth barely moves you. They didn't bolt saturation on for taste; the probability told them to.",
          "Then length. A long document racks up term counts just by going on, so they normalised by document length — and now they had a fork. Normalise fully and you get **BM11**; don't normalise at all and you get **BM15**; and out in the field, neither extreme won everywhere. BM15 over-rewarded long documents, BM11 over-punished them. They even tried a separate length-correction term and a query-frequency factor, measured the lot on real collections, and — this is the engineer's move — *threw the correction away* when the data said it earned nothing. Tried it, measured it, deleted it. That's the whole discipline in one gesture.",
          "The twenty-fifth variant was the one that stopped the search. Instead of choosing between BM11 and BM15, **put a dial between them** — a single knob *b* that slides from \"ignore length\" to \"fully normalise\" — and let whoever runs the engine tune it to their corpus. Set \\(b \\approx 0.75\\), let \\(k_1 \\approx 1.5\\) control how fast \\(tf\\) saturates, and you have BM25: the RSJ idf, a saturating tf, and a tunable length penalty, all in one line. This all came together at City University London on a system called **Okapi** ([Robertson & Walker, 1994](https://doi.org/10.1007/978-1-4471-2099-5_24)), which is why you'll still hear it called Okapi BM25; it then went and *won* the early **TREC** competitions in the early 1990s, the bake-off that turned IR from opinion into measurement.",
          "Here's the part that should keep you humble. That worked example you just stepped through ranks D2 above D1 above D3 — a short, on-point document beating a longer one that merely mentions the words — and it does it with arithmetic from the 1990s. On the modern **BEIR** benchmark ([Thakur et al., 2021](https://arxiv.org/abs/2104.08663)), averaged across eighteen datasets, BM25 still scores around 0.43 nDCG@10 *zero-shot* — and plenty of expensive neural models, trained on GPUs that didn't exist when BM25 was finalised, fail to beat it. Thirty years of careful filing produced a baseline so good it's a little embarrassing. Respect the sextant.",
        ],
        ru: [
          'Та формула, которую ты только что разглядывал, — BM25 — не выпрыгнула из чьей-то головы. Это секстант, который настраивали тридцать лет, и каждую засечку стачивали, только когда прежний прибор подводил в открытом море. «BM» — это *Best Match*, «лучшее совпадение», а число 25 — не версия, выбранная маркетологом; это буквально двадцать пятый вариант, который проработала команда. История того, как они до него дошли, — лучшая инженерная притча, что я знаю, так что дай я её и вправду расскажу.',
          'Всё начинается в 1970-х с вопроса, который звучит академично, а оказывается всей игрой: дан запрос — какие документы *вероятнее всего* релевантны? Стивен Робертсон и Карен Спарк Джонс формализовали это как **принцип вероятностного ранжирования** — ранжируй документы по шансам быть релевантными — и из него выпал **вес RSJ** ([Robertson & Spärck Jones, 1976](https://doi.org/10.1002/asi.4630270302)), по сути та самая idf, что мы только что брали, но рождённая из вероятности, а не угаданная. Тот первый ранкер, **BM1**, спрашивал лишь *есть слово или нет*. Он полностью игнорировал, сколько раз слово встретилось. Ты уже знаешь, почему этого мало.',
          'Тогда добавили частоту термина — и сразу упёрлись в изъян линейности, тот самый, что мы нашли в TF-IDF. Починка пришла из теории под названием **модель 2-Пуассона** ([Robertson, 1981](https://doi.org/10.1108/eb026690)): представь, что слово «элитно» документу, когда документ по-настоящему о теме этого слова, и смоделируй счётчики как смесь двух пуассоновских распределений, элитного и нет. Прокрути математику — и оптимальный вес вовсе не линеен по tf, это *насыщающаяся* кривая, что круто растёт на первых вхождениях и потом выполаживается. Вот глубокое «почему» этой формы: второе упоминание слова — сильная улика, пятидесятое едва двигает. Они не прикрутили насыщение для вкуса; так велела вероятность.',
          'Затем длина. Длинный документ копит счётчики просто потому, что тянется, поэтому его нормировали на длину — и тут возникла развилка. Нормируй полностью — получишь **BM11**; не нормируй вовсе — получишь **BM15**; и в поле ни одна крайность не побеждала везде. BM15 переоценивал длинные документы, BM11 их перенаказывал. Они даже пробовали отдельный поправочный член на длину и фактор частоты в запросе, измерили всё это на реальных коллекциях и — вот ход инженера — *выбросили поправку*, когда данные сказали, что она ничего не даёт. Попробовали, измерили, удалили. Вся дисциплина в одном жесте.',
          'Двадцать пятый вариант и оказался тем, на котором поиск остановился. Вместо выбора между BM11 и BM15 — **поставь между ними диск**: одну ручку *b*, что скользит от «игнорируй длину» до «нормируй полностью», — и дай тому, кто крутит движок, настроить её под свой корпус. Поставь \\(b \\approx 0{,}75\\), пусть \\(k_1 \\approx 1{,}5\\) управляет скоростью насыщения \\(tf\\) — и вот BM25: idf от RSJ, насыщающийся tf и настраиваемый штраф за длину, всё в одной строке. Всё это сложилось в Городском университете Лондона на системе **Okapi** ([Robertson & Walker, 1994](https://doi.org/10.1007/978-1-4471-2099-5_24)), поэтому до сих пор слышишь «Okapi BM25»; затем оно пошло и *выиграло* ранние соревнования **TREC** в начале 1990-х — тот самый смотр, что превратил IR из мнения в измерение.',
          'А вот часть, что должна держать тебя в смирении. Тот разобранный пример, по которому ты шагал, ставит D2 выше D1 и выше D3 — короткий документ по теме обходит длинный, что просто упоминает слова, — и делает это арифметикой из 1990-х. На современном бенчмарке **BEIR** ([Thakur et al., 2021](https://arxiv.org/abs/2104.08663)), усреднённый по восемнадцати наборам, BM25 всё ещё даёт около 0,43 nDCG@10 *zero-shot* — и куча дорогих нейронных моделей, обученных на GPU, которых не было, когда BM25 доделывали, не может его обойти. Тридцать лет аккуратной заточки дали базовую планку, настолько хорошую, что слегка неловко. Уважай секстант.',
        ],
      },
    },
    {
      id: 'turn-wand', kind: 'prose',
      heading: { en: 'How BM25 serves fast', ru: 'Как BM25 успевает быстро' },
      body: {
        en: [
          "There's a debt I've been quietly running up, and it's time to pay it. Back at the start I promised the index lets us answer before touching even a thousandth of the sky — but BM25 still scores documents, and a popular two-word query can touch postings lists with *millions* of entries each. If we computed the full BM25 sum for every one of them, we'd be back inside a slow scan, just with arithmetic. So how does BM25 over a billion documents actually come back in under a hundred milliseconds? The answer is that **you never need every score — only the top \\(k\\)**, and there's a beautiful trick for skipping the rest.",
          "The trick is called **WAND** (*Weak AND*), and it rides on one observation: each query term has a **maximum score** it could ever contribute — its idf times the largest saturating factor any document achieves, a number you can precompute and store on the term's card. So for any document, you can sum the max-scores of the query terms it contains and get an **upper bound** on its possible BM25 score, *before* doing the real arithmetic. Now keep a running **threshold**: the score of the \\(k\\)-th best document found so far. The move is ruthless — if a document's optimistic upper bound can't even beat that threshold, it *cannot* land in the top \\(k\\), so you skip it without ever computing its true score. Most documents fail this cheap test and are never fully evaluated. As the threshold climbs through the search, the bar rises and more documents get skipped, faster.",
          "**BlockMax-WAND** sharpens the same blade. Instead of one max-score per whole postings list, it stores a max-score per *block* of postings — a few hundred entries each — so when a block's local maximum can't clear the threshold, the algorithm leaps over the *entire block* in one jump, the same skip-pointer instinct we built for boolean merges, now driven by scores instead of doc IDs. The effect is that top-\\(k\\) retrieval becomes **effectively sublinear** in practice: you read a small, score-promising slice of each list and confidently ignore the rest. This is the missing half of the latency story from the very first beat. The inverted index lets you find the *candidate* documents without a scan; WAND and BlockMax-WAND let you *rank* them without scoring all of them — and together they're why BM25 over [Robertson & Walker's (1994)](https://doi.org/10.1007/978-1-4471-2099-5_24) formula meets a hundred-millisecond budget on a web-scale corpus. The classical engine isn't just clever about *what* it scores; it's clever about *how few* documents it ever has to.",
          "One footnote on the family, because the production world has a few dialects of BM25 worth knowing by name. **BM25F** scores documents with multiple *fields* — a title, a body, anchor text — each with its own length normalization, so a term in the title can be made to count for more than the same term buried in the body. **BM25+** adds a small floor \\(\\delta\\) so that very long documents can't have a matching term's contribution decay all the way to nothing. Both are tiny edits to the one formula, both catalogued in [Robertson & Zaragoza's (2009)](https://doi.org/10.1561/1500000019) survey *BM25 and Beyond* — and the fact that thirty-year-old arithmetic still earns careful, named variants in modern engines tells you how stubbornly good the baseline is.",
        ],
        ru: [
          'Есть долг, который я тихо набирал, и пора по нему расплатиться. В самом начале я обещал, что индекс даёт ответ ещё до того, как мы тронули хотя бы тысячную долю неба, — но BM25 всё-таки оценивает документы, а популярный двухсловный запрос может тронуть списки постингов по *миллиону* записей в каждом. Считай мы полную сумму BM25 для каждого из них — и мы снова внутри медленного скана, только с арифметикой. Так как же BM25 по миллиарду документов реально возвращается меньше чем за сто миллисекунд? Ответ в том, что **тебе никогда не нужны все оценки — только топ-\\(k\\)**, и есть красивый трюк, чтобы пропустить остальное.',
          'Трюк называется **WAND** (*Weak AND*, «слабое И»), и он держится на одном наблюдении: у каждого терма запроса есть **максимальная оценка**, которую он вообще может дать, — его idf, умноженная на наибольший насыщающийся множитель, что достигает любой документ, число, которое можно предвычислить и хранить на карточке терма. Поэтому для любого документа ты можешь сложить макс-оценки термов запроса, что в нём есть, и получить **верхнюю границу** возможной оценки BM25, *до* настоящей арифметики. Теперь держи бегущий **порог**: оценку \\(k\\)-го лучшего документа, найденного к этому моменту. Ход беспощаден — если оптимистичная верхняя граница документа не может даже превзойти этот порог, он *не способен* попасть в топ-\\(k\\), так что ты пропускаешь его, ни разу не посчитав настоящую оценку. Большинство документов проваливают эту дешёвую проверку и никогда не оцениваются полностью. По мере того как порог растёт по ходу поиска, планка поднимается, и документов пропускается всё больше и быстрее.',
          '**BlockMax-WAND** точит то же лезвие. Вместо одной макс-оценки на весь список постингов он хранит макс-оценку на *блок* постингов — по несколько сотен записей в каждом, — так что, когда локальный максимум блока не дотягивает до порога, алгоритм перепрыгивает *весь блок* одним прыжком, тот же инстинкт skip-указателей, что мы построили для булевых слияний, только ведомый теперь оценками, а не ID документов. В итоге извлечение топ-\\(k\\) становится на практике **по сути сублинейным**: ты читаешь маленький, перспективный по оценке кусочек каждого списка и уверенно игноришь остальное. Это недостающая половина истории про задержку из самого первого бита. Инвертированный индекс даёт найти *документы-кандидаты* без скана; WAND и BlockMax-WAND дают *ранжировать* их, не оценивая всех, — и вместе они объясняют, почему BM25 по формуле [Robertson & Walker (1994)](https://doi.org/10.1007/978-1-4471-2099-5_24) укладывается в сто миллисекунд на корпусе веб-масштаба. Классический движок умён не только в том, *что* он оценивает; он умён в том, *как мало* документов ему вообще приходится трогать.',
          'Одна сноска про семейство, ведь в продакшне есть пара диалектов BM25, которые стоит знать по имени. **BM25F** оценивает документы с несколькими *полями* — заголовок, тело, текст ссылок — у каждого своя нормировка длины, так что терм в заголовке можно заставить весить больше, чем тот же терм, зарытый в теле. **BM25+** добавляет небольшой пол \\(\\delta\\), чтобы у очень длинных документов вклад совпавшего терма не угасал до полного нуля. Оба — крошечные правки к той самой формуле, оба занесены в обзор [Robertson & Zaragoza (2009)](https://doi.org/10.1561/1500000019) *BM25 and Beyond*, — а то, что тридцатилетняя арифметика до сих пор зарабатывает аккуратные именованные варианты в современных движках, говорит, насколько упрямо хороша эта планка.',
        ],
      },
    },
    {
      id: 'turn-fusion', kind: 'prose',
      heading: { en: 'One ranker is never enough', ru: 'Одного ранкера всегда мало' },
      body: {
        en: [
          "BM25 is a workhorse, but it's still one opinion. It scores documents by exact-word overlap, weighted cleverly — that's its lens, and like any lens it has blind spots. A second ranker sees the same documents through a different lens. Take cosine similarity over the TF-IDF vectors we built a moment ago: it cares about the *angle* between a document and the query, the overall shape of their word usage, not the same things BM25 leans on. Two competent rankers, looking at the same shelf, will hand you two different top-tens.",
          "When two good rankers disagree, the rookie move is to crown a favourite and ignore the other. The smart move is to *fuse* their votes — to trust a document that *both* rankers liked more than one that only impressed a single judge. But there's an obstacle, and it's the same one that bit us with the inverted index's score scales: BM25 might hand out numbers like 12.4 while cosine lives between 0 and 1. You cannot just add them; the bigger scale would silently win every time. We need a way to combine rankings that doesn't care how loud each ranker shouts.",
        ],
        ru: [
          'BM25 — рабочая лошадка, но это всё ещё одно мнение. Он оценивает документы по точному пересечению слов, хитро взвешенному, — это его линза, и, как у любой линзы, у неё есть слепые зоны. Второй ранкер смотрит на те же документы через другую линзу. Возьми косинусную близость по TF-IDF векторам, что мы построили минуту назад: его волнует *угол* между документом и запросом, общая форма их словоупотребления, а не то, на что опирается BM25. Два толковых ранкера, глядя на одну полку, выдадут тебе две разные десятки.',
          'Когда два хороших ранкера расходятся, новичок коронует любимчика и игнорирует второго. Умный ход — *слить* их голоса: довериться документу, который понравился *обоим* ранкерам, сильнее, чем тому, что впечатлил лишь одного судью. Но есть препятствие, и оно то же, что укусило нас со шкалами индекса: BM25 может выдавать числа вроде 12,4, а косинус живёт между 0 и 1. Просто сложить нельзя; большая шкала молча победит каждый раз. Нужен способ объединять ранжирования, которому всё равно, как громко кричит каждый ранкер.',
        ],
      },
    },
    {
      id: 'turn-fusion-family', kind: 'prose',
      heading: { en: 'A council of navigators', ru: 'Совет навигаторов' },
      img: 'L3/L3-15-fusion-navigators-council.png', imgPos: 'scene',
      imgAlt: {
        en: 'A council of navigators with disagreeing star-charts merging them into one ranked master-chart.',
        ru: 'Совет навигаторов с расходящимися звёздными картами сводит их в одну ранжированную мастер-карту.',
      },
      imgCaption: {
        en: 'Two rankers, two stubborn star-charts. RRF doesn’t crown a winner — it makes them vote, and trusts what they agree on.',
        ru: 'Два ранкера, две упрямые звёздные карты. RRF не выбирает фаворита — он заставляет их голосовать и верит тому, в чём они сошлись.',
      },
      body: {
        en: [
          "There's a whole family of ways to merge ranked lists, and walking the family tree tells you why the winner won. The first instinct is to *fix the scales*: normalise every ranker's scores to a common range — min-max them into [0,1], or z-score them — and then add. That's **CombSUM**; its cousin **CombMNZ** multiplies in a bonus for documents that more than one ranker surfaced at all. It works, but it's fragile: a single ranker with a weird score distribution, one outlier blowing out the min-max range, and your careful normalisation curdles.",
          "So a second school says: throw the scores away entirely and keep only the *ranks*. **Borda count**, borrowed from voting theory, gives a document \\(m\\) points for first place, \\(m-1\\) for second, and so on down each list, then sums — exactly how some elections tally preferences. More elaborate schemes like **CPMF** model each rank as carrying a probability mass and combine those. The appeal is obvious: a rank is a rank, immune to whatever bizarre scale a ranker reports. The drawback of plain Borda is that it treats the gap between rank 1 and rank 2 the same as the gap between rank 50 and rank 51 — which is wrong, because nobody scrolls to 51.",
          "Which sets up the punchline, and the figure after this beat is it. **Reciprocal Rank Fusion** ([Cormack, Clarke & Büttcher, 2009](https://doi.org/10.1145/1571941.1572114)) keeps the rank-only robustness but discounts gently: a document at rank \\(r\\) in a list contributes $$\\mathrm{RRF}(d)=\\sum_r \\frac{1}{k+r},\\qquad k=60$$ summed across every ranker, with a single tiny constant \\(k = 60\\). Because the contribution shrinks as you go down — \\(1/61\\) at rank 1, \\(1/62\\) at rank 2, and so on — being near the top counts for a lot and being deep counts for almost nothing, yet the 60 keeps any single rank-1 from dominating outright. It needs no score normalisation and no per-corpus tuning, and it folds any number of rankers together. Watch the council of navigators take their two disagreeing charts and agree on a course: a document both rankers place first earns \\(1/61 + 1/61 \\approx 0.0328\\) and tops the fused list.",
        ],
        ru: [
          'Есть целое семейство способов слить ранжированные списки, и прогулка по родословной показывает, почему победитель победил. Первый инстинкт — *починить шкалы*: нормировать оценки каждого ранкера в общий диапазон — min-max в [0,1] или z-оценка — и сложить. Это **CombSUM**; его родич **CombMNZ** домножает бонус документам, которые всплыли больше чем у одного ранкера. Работает, но хрупко: один ранкер со странным распределением оценок, один выброс, разносящий min-max диапазон, — и аккуратная нормировка сворачивается.',
          'Поэтому вторая школа говорит: выброси оценки совсем и оставь только *ранги*. **Подсчёт Борда**, заимствованный из теории голосования, даёт документу \\(m\\) очков за первое место, \\(m-1\\) за второе и так вниз по каждому списку, потом суммирует — ровно так некоторые выборы считают предпочтения. Более затейливые схемы вроде **CPMF** моделируют каждый ранг как несущий вероятностную массу и комбинируют их. Притяжение очевидно: ранг есть ранг, ему плевать на любую дикую шкалу ранкера. Минус простого Борда в том, что он считает разрыв между рангом 1 и 2 таким же, как между 50 и 51, — что неверно, ведь до 51-го никто не доскролливает.',
          'Что и подводит к развязке, а фигура после этого бита — она и есть. **Реципрокное слияние рангов** ([Cormack, Clarke & Büttcher, 2009](https://doi.org/10.1145/1571941.1572114)) сохраняет устойчивость «только по рангам», но мягко дисконтирует: документ на ранге \\(r\\) в списке даёт вклад $$\\mathrm{RRF}(d)=\\sum_r \\frac{1}{k+r},\\qquad k=60$$ просуммированный по всем ранкерам, с одной крошечной константой \\(k = 60\\). Поскольку вклад убывает по мере спуска — \\(1/61\\) на ранге 1, \\(1/62\\) на ранге 2 и так далее — быть у верха стоит много, а быть глубоко — почти ничего, и при этом 60 не даёт ни одному рангу-1 доминировать начисто. Ему не нужна ни нормировка оценок, ни покорпусная настройка, и он складывает любое число ранкеров. Смотри, как совет навигаторов берёт две несогласные карты и сходится на курсе: документ, которого оба ранкера ставят первым, набирает \\(1/61 + 1/61 \\approx 0{,}0328\\) и возглавляет слитый список.',
        ],
      },
    },
    { id: 'climb-rrf', kind: 'scrolly', widget: 'rrf-fusion', data: 'l3-rrf' },
    {
      id: 'turn-pagerank', kind: 'prose',
      heading: { en: 'Let the links vote', ru: 'Пусть голосуют ссылки' },
      img: 'L3/L3-14-pagerank-stars-voting.png', imgPos: 'scene',
      imgAlt: {
        en: 'Stars pointing arrows at each other; authority flows to the star that the most arrows pile onto, which glows brightest.',
        ru: 'Звёзды указывают стрелками друг на друга; авторитет течёт к звезде, на которую падает больше всего стрелок, и она светит ярче всех.',
      },
      imgCaption: {
        en: 'Every link is a vote — but a vote from an important page outweighs a vote from a nobody. Authority that defines itself.',
        ru: 'Каждая ссылка — голос, но голос важной страницы весит больше голоса никому не известной. Авторитет, определяющий сам себя.',
      },
      body: {
        en: [
          "Everything so far scores a document by what's *inside* it. But on the web there's a second signal sitting in plain sight, and it's not in any document's text — it's in the *links between them*. Treat every link as a vote: a page that many others point to is probably worth something. That's the seed of **PageRank** ([Page, Brin, Motwani & Winograd, 1998](http://ilpubs.stanford.edu:8090/422/)), the idea that put a particular search engine on the map in the late 1990s. The twist that made it work is recursive — a vote from an important page should count for more than a vote from a nobody. Importance is defined in terms of itself.",
          "That sounds circular, and it is, in the productive way. Picture a bored web surfer clicking links at random forever; the fraction of time they spend on each page, in the long run, *is* that page's PageRank. Written out, each page's score is $$PR(i) = \\frac{1-d}{n} + d\\sum_{j\\to i}\\frac{PR(j)}{\\mathrm{outdeg}(j)}$$ where every page \\(j\\) that links to \\(i\\) hands over a share of its own score, split evenly across its out-links, and \\(d = 0.85\\) is the chance the surfer follows a link rather than teleporting. You solve it by **power iteration**: start everyone equal at \\(1/3 \\approx 0.333\\), apply that update, repeat, and the numbers settle. Run it on a tiny three-page web — A points to B, B to C, C to both A and B — and watch the votes flow. B is the only page with *two* in-links (from A and from C), so it accumulates the most: after the first pass it already jumps to about 0.475, and as the iterations settle it converges to **≈0.40** (0.397 to be exact). A and C split the remainder — A lands near 0.215, C near 0.388 — and B holds the largest share precisely because two pages, not one, vote for it. One catch worth a footnote: a page with no outgoing links would be a black hole that hoards everyone's score, so the surfer is allowed to randomly teleport (the \\(1-d \\approx 0.15\\) term) to keep the whole thing from collapsing.",
          "The point for us isn't the algorithm; it's the category. PageRank is a **query-independent** signal — it's about the document, computed once, before anyone searches anything. BM25 is query-*dependent*; it only means something relative to your words. A real engine wants both, plus a dozen more signals, and that raises an obvious question: how do you combine a lexical score, an angle, and an authority number that live on completely different scales? We just built the answer to that. Let's use it.",
        ],
        ru: [
          'Всё до сих пор оценивало документ по тому, что *внутри* него. Но в вебе есть второй сигнал, лежащий на виду, и он не в тексте ни одного документа — он в *ссылках между ними*. Считай каждую ссылку голосом: страница, на которую указывают многие, вероятно, чего-то стоит. Это зерно **PageRank** ([Page, Brin, Motwani & Winograd, 1998](http://ilpubs.stanford.edu:8090/422/)), идеи, что вывела один конкретный поисковик в люди в конце 1990-х. Поворот, который заставил её работать, рекурсивен: голос важной страницы должен весить больше, чем голос пустого места. Важность определяется через саму себя.',
          'Звучит как круг — и это круг, в продуктивном смысле. Представь скучающего сёрфера, вечно кликающего по случайным ссылкам; доля времени, что он проводит на каждой странице, в пределе *и есть* её PageRank. Если выписать, оценка каждой страницы — это $$PR(i) = \\frac{1-d}{n} + d\\sum_{j\\to i}\\frac{PR(j)}{\\mathrm{outdeg}(j)}$$ где каждая страница \\(j\\), ссылающаяся на \\(i\\), отдаёт долю своей оценки, поделённую поровну между её исходящими ссылками, а \\(d = 0{,}85\\) — вероятность, что сёрфер пойдёт по ссылке, а не телепортируется. Решают это **степенным методом**: начни со всех равными по \\(1/3 \\approx 0{,}333\\), примени это обновление, повтори — и числа устаканятся. Прогони на крошечном вебе из трёх страниц — A указывает на B, B на C, C сразу на A и B — и смотри, как текут голоса. B — единственная страница с *двумя* входящими ссылками (от A и от C), поэтому она копит больше всех: уже после первого прохода подскакивает примерно до 0,475, а по мере сходимости итераций приходит к **≈0,40** (точнее, 0,397). A и C делят остаток — A оседает около 0,215, C около 0,388 — и B держит наибольшую долю именно потому, что за неё голосуют две страницы, а не одна. Один подвох на сноску: страница без исходящих ссылок была бы чёрной дырой, копящей чужие оценки, поэтому сёрферу разрешено случайно телепортироваться (член \\(1-d \\approx 0{,}15\\)), чтобы вся конструкция не схлопнулась.',
          'Суть для нас не в алгоритме, а в категории. PageRank — это **независимый от запроса** сигнал: он о документе, вычислен один раз, до того как кто-то что-то искал. BM25 *зависит* от запроса; он что-то значит лишь относительно твоих слов. Настоящему движку нужны оба, плюс десяток других сигналов, и тут встаёт очевидный вопрос: как объединить лексическую оценку, угол и число авторитетности, живущие на совершенно разных шкалах? Мы только что построили ответ на это. Давай им и воспользуемся.',
        ],
      },
    },
    { id: 'turn-pagerank-power', kind: 'scrolly', widget: 'pagerank-power', data: 'l3-pagerank' },
    {
      id: 'catch-gremlin', kind: 'prose',
      heading: { en: 'The Lexical Gremlin laughs', ru: 'Лексический Гремлин смеётся' },
      img: 'L3/L3-04-lexical-gremlin-wall.png', imgPos: 'scene',
      imgAlt: {
        en: 'The Lexical Gremlin wedging a brick wall between "couch" and "sofa" — exact-term matching is blind to meaning.',
        ru: 'Лексический Гремлин вставляет кирпичную стену между «диваном» и «софой» — точное совпадение по словам слепо к смыслу.',
      },
      imgCaption: {
        en: 'Search “couch,” miss the perfect “sofa,” score it exactly zero. Every clever weight we built still can’t climb his wall.',
        ru: 'Ищешь «диван», промахиваешься мимо идеальной «софы» — и ставишь ровно ноль. Никакой умный вес не лезет через его стену.',
      },
      body: {
        en: [
          "There's a catch, and he's grinning at me from behind the catalog. BM25, RRF, PageRank, the whole classical apparatus — every last piece of it matches on *exact words*. The index is a card per literal token; the scores reward literal overlap. So search \"couch\" and a perfect document that happens to say \"sofa\" scores exactly zero. Not low. Zero. As far as the catalog is concerned, those two words are as unrelated as \"couch\" and \"crocodile.\"",
          "This is the **Lexical Gremlin**, back from chapter one, and he is *thrilled* with everything we just built — because no amount of clever weighting climbs over his wall. You can patch a few cases: stemming so \"running\" and \"runs\" collapse together, query expansion to bolt synonyms on by hand. But those are buckets bailing a boat. The Gremlin wedges a brick wall between every pair of words that mean the same thing and were spelled differently, and our entire toolkit is built on spelling. To beat him for real we'll have to stop matching words and start matching *meaning* — give every word a position in a space where \"couch\" and \"sofa\" sit as neighbours. That's a later chapter, and it's the one he's afraid of.",
        ],
        ru: [
          'Есть подвох, и он ухмыляется мне из-за каталога. BM25, RRF, PageRank, весь классический аппарат — каждая его деталь совпадает по *точным словам*. Индекс — это карточка на буквальный токен; оценки награждают буквальное пересечение. Поэтому ищешь «диван», а идеальный документ, где написано «кушетка», получает ровно ноль. Не мало. Ноль. С точки зрения каталога эти два слова так же не связаны, как «диван» и «крокодил».',
          'Это **Лексический Гремлин**, вернувшийся из первой главы, и он *в восторге* от всего, что мы только что построили, — потому что никакое хитрое взвешивание не перелезет его стену. Можно залатать пару случаев: стемминг, чтобы «бегущий» и «бежит» схлопнулись, расширение запроса, чтобы вручную прицепить синонимы. Но это вёдра, вычерпывающие лодку. Гремлин вставляет кирпичную стену между каждой парой слов, что значат одно, но написаны иначе, а весь наш инструментарий построен на написании. Чтобы победить его по-настоящему, придётся перестать совпадать по словам и начать совпадать по *смыслу* — дать каждому слову позицию в пространстве, где «диван» и «кушетка» стоят соседями. Это следующая глава, и именно её он боится.',
        ],
      },
    },
    {
      id: 'payoff-catalog', kind: 'prose',
      heading: { en: 'The catalog is built', ru: 'Каталог построен' },
      img: 'L3/L3-10-scan-vs-catalog.png', imgPos: 'hero',
      imgAlt: {
        en: 'The same billion-star sky two ways: "scan everything?" hopeless, versus "look it up" — the card catalogue beams straight to the three wanted stars.',
        ru: 'То же небо из миллиарда звёзд двумя путями: «сканировать всё?» — безнадёжно, против «посмотреть в каталоге» — картотека ведёт прямо к трём нужным звёздам.',
      },
      imgCaption: {
        en: 'Scan the whole sky, or reach for the right card? The catalogue beams you to the three stars you wanted. The Ship finds fast.',
        ru: 'Сканировать всё небо — или потянуться за нужной карточкой? Каталог ведёт прямо к трём нужным звёздам. Корабль ищет быстро.',
      },
      body: {
        en: [
          "So here's the Ship we built, and it finds *fast*. An inverted index — gaps-compressed, skip-merged, segment-merged — for instant lookup instead of a doomed scan. Bag-of-Words to turn documents into vectors. TF-IDF to weight the words, then thirty years of BM25 to weight them *right*. PageRank for authority that needs no query. And reciprocal rank fusion, the council of navigators, to combine all those disagreeing voices into one honest order. It is the baseline every fancy neural method in this course will have to beat — and you'd be genuinely surprised how often it just wins.",
          "Two questions trail us out of here, and each owns a chapter. First, the uncomfortable one: I keep saying \"better\" and \"wins\" — but how would we even *know*? Eyeballing ten results is not a measurement, and BM25's ranking might be quietly worse than I think. That's the next chapter, The Proving Grounds, where we put an honest number on a ranking. Second, the Gremlin is still out there behind his wall, and caging him for good is the chapter after — when words finally get coordinates. The catalog is built. Now we learn whether it's any good, and then we learn to read between the words.",
        ],
        ru: [
          'Итак, вот Корабль, что мы построили, и он ищет *быстро*. Инвертированный индекс — сжатый разностями, со skip-слиянием, со слиянием сегментов — для мгновенного поиска вместо обречённого скана. Мешок слов, чтобы превратить документы в векторы. TF-IDF, чтобы взвесить слова, а потом тридцать лет BM25, чтобы взвесить их *правильно*. PageRank для авторитетности, которой не нужен запрос. И реципрокное слияние рангов, совет навигаторов, чтобы свести все эти несогласные голоса в один честный порядок. Это базовая планка, которую придётся брать каждому модному нейронному методу в этом курсе, — и ты искренне удивишься, как часто она просто побеждает.',
          'Два вопроса тянутся за нами отсюда, и у каждого своя глава. Первый, неудобный: я всё твержу «лучше» и «побеждает» — но как нам вообще это *узнать*? Оценить десять результатов на глаз — не измерение, и ранжирование BM25 может быть тихо хуже, чем я думаю. Это следующая глава, «Полигон», где мы ставим ранжированию честное число. Второй: Гремлин всё ещё там, за своей стеной, и посадить его в клетку навсегда — глава за ней, когда слова наконец получат координаты. Каталог построен. Теперь узнаем, хорош ли он, а потом научимся читать между слов.',
        ],
      },
    },
  ],
};
