// content/book/l5.js — "The Map of Meaning" (L5): word embeddings + dimensionality reduction.
// Beats match narrative/L5.md (15, in order). Widgets: embedding-space (the analogy story) and
// dimred-projection (PCA → variance → t-SNE). Every displayed NUMBER comes from
// data/l5-embeddings.json + data/l5-dimred.json (facts-gate). EN canonical + RU + TT (all written).

export default {
  id: '05',
  catchphrase: 'The Map of Meaning',
  beats: [
    {
      id: 'hook-map', kind: 'prose',
      heading: { en: 'The Map of Meaning', ru: 'Карта смысла', tt: 'Мәгънә картасы' },
      img: 'L5/L5-00-map-of-meaning.png', imgPos: 'hero',
      imgAlt: {
        en: 'Serega the cartographer standing before a vast star-map where words hang as points of light, charting meaning as terrain.',
        ru: 'Серёга-картограф стоит перед огромной звёздной картой, где слова висят точками света, нанося смысл как местность.',
        tt: 'Серёга-картограф зур йолдыз картасы алдында тора, анда сүзләр яктылык ноктасы булып эленеп тора, мәгънәне җир-су итеп сызып бара.',
      },
      imgCaption: {
        en: 'Three lectures ago an alien said a word we’d never logged. Today that word finally gets a place on the map.',
        ru: 'Три лекции назад инопланетянин сказал слово, которого у нас не было в журнале. Сегодня это слово наконец получит место на карте.',
        tt: 'Өч лекция элек чит планеталы без язмаган сүзне әйтте. Бүген ул сүз ниһаять картада урын ала.',
      },
      body: {
        en: [
          "I'm Serega, and I want to take you back to **First Contact** — the alien on the screen, the translator spitting out symbols, the moment we couldn't tell whether two of its phrases meant the same thing. We solved half of it: we turned the alien's text into countable units and we built cosine, a way to measure when two *vectors* point the same way. But there was a crack we papered over, and it has been widening ever since.",
          "Here's the crack. The whole classical machine — the inverted index, BM25, the bag-of-words vectors — treats a word as a *symbol*: a unique ID, a card in a catalog, a slot in a vector. And symbols have no sense of *nearness in meaning*. To that machine \"couch\" and \"sofa\" are as unrelated as \"couch\" and \"crocodile\" — different IDs, full stop. The alien could hand us a perfect synonym for a word in our index and we'd score it exactly zero.",
          "So today we do the thing the alien needed all along: we give every word **coordinates**. Not an arbitrary ID, but a position in a space where the geometry *means* something — where \"couch\" and \"sofa\" land as neighbours, where the direction from \"king\" to \"queen\" is the same arrow as from \"man\" to \"woman\", and where *near* finally means *related*. We're going to draw the Map of Meaning. Then, because that map lives in three hundred dimensions and you have two eyes, we'll learn to fold it small enough to see.",
        ],
        ru: [
          'Я Серёга, и я хочу вернуть тебя в **Первый контакт** — инопланетянин на экране, переводчик, выплёвывающий символы, миг, когда мы не могли понять, значат ли две его фразы одно и то же. Половину мы решили: превратили текст инопланетянина в счётные единицы и построили косинус — способ мерить, когда два *вектора* смотрят в одну сторону. Но мы заклеили трещину, и с тех пор она только росла.',
          'Вот эта трещина. Вся классическая машина — инвертированный индекс, BM25, векторы мешка слов — обращается со словом как с *символом*: уникальный ID, карточка в каталоге, ячейка в векторе. А у символов нет чувства *близости по смыслу*. Для этой машины «диван» и «софа» так же не связаны, как «диван» и «крокодил» — разные ID, и точка. Инопланетянин мог бы вручить нам идеальный синоним к слову из нашего индекса, а мы поставили бы ему ровно ноль.',
          'Поэтому сегодня мы делаем то, что инопланетянину было нужно с самого начала: даём каждому слову **координаты**. Не произвольный ID, а позицию в пространстве, где геометрия *что-то значит* — где «диван» и «софа» оказываются соседями, где направление от «king» к «queen» — та же стрелка, что от «man» к «woman», и где *близко* наконец значит *связано*. Мы нарисуем Карту смысла. А потом, поскольку эта карта живёт в трёхстах измерениях, а глаз у тебя два, научимся складывать её так, чтобы её можно было увидеть.',
        ],
        tt: [
          'Мин — Серёга, һәм мин сине **Беренче контакт**ка кире кайтарырга телим — экрандагы чит планеталы, символлар чыгарып торган тәрҗемәче, без аның ике фразасы бер үк нәрсә аңлатамы икәнен аера алмаган мизгел. Яртысын чиштек: чит планеталының текстын санала торган берәмлекләргә әйләндердек һәм косинус төзедек — ике *вектор* бер якка караганын үлчәү ысулы. Әмма без бер ярыкны ябыштырган идек, һәм ул шуннан бирле киңәя барды.',
          'Менә шул ярык. Бөтен классик машина — инвертацияләнгән индекс, BM25, сүзләр капчыгы векторлары — сүзне *символ* итеп карый: уникаль ID, каталогтагы карточка, вектордагы оя. Ә символларда *мәгънә буенча якынлык* тойгысы юк. Бу машина өчен «диван» белән «софа» «диван» белән «крокодил» кебек үк бәйләнешсез — төрле ID, шул гына. Чит планеталы безнең индекстагы сүзгә идеаль синоним бирә алыр иде, ә без аңа нәкъ ноль куяр идек.',
          'Шуңа күрә бүген без чит планеталыга башта ук кирәк булганны эшлибез: һәр сүзгә **координаталар** бирәбез. Ирекле ID түгел, ә геометриясе *нәрсәдер аңлаткан* киңлектә позиция — анда «диван» белән «софа» күршеләр булып төшә, анда «king»’тан «queen»’гә юнәлеш «man»’нан «woman»’га булган шул ук ук, һәм анда *якын* ниһаять *бәйле* дигән сүз. Без Мәгънә картасын сызачакбыз. Аннары, бу карта өч йөз үлчәмдә яшәгәнгә, ә синең күзең икәү, аны күреп булырлык итеп бөкләргә өйрәнәчәкбез.',
        ],
      },
    },
    {
      id: 'problem-no-nearness', kind: 'prose',
      heading: { en: 'Symbols have no “near”', ru: 'У символов нет «близко»', tt: 'Символларда «якын» юк' },
      img: 'L5/L5-02-words-to-coordinates.png', imgPos: 'scene',
      imgAlt: {
        en: 'Words being lifted off a flat list of one-hot symbols and dropped as points onto a 2-D coordinate grid.',
        ru: 'Слова поднимают с плоского списка one-hot символов и роняют точками на 2-D координатную сетку.',
        tt: 'Сүзләрне one-hot символлар яссы исемлегеннән күтәреп, 2-D координат челтәренә нокта итеп төшерәләр.',
      },
      imgCaption: {
        en: 'One-hot gives every word its own lonely axis — all pairs the same distance apart. Coordinates make distance mean something.',
        ru: 'One-hot даёт каждому слову свою одинокую ось — все пары на одинаковом расстоянии. Координаты делают расстояние осмысленным.',
        tt: 'One-hot һәр сүзгә үз ялгыз күчәрен бирә — бар парлар бертигез ераклыкта. Координаталар ераклыкны мәгънәле итә.',
      },
      body: {
        en: [
          "Let's make the failure concrete, because it's worse than \"a bit blind\" — it's *total*. The classical way to hand a word to math is **one-hot encoding**: pick a vocabulary of, say, 50,000 words, and represent word number 7 as a vector of 50,000 zeros with a single 1 in slot 7. \"cat\" might be slot 312, \"dog\" slot 6,201, \"airplane\" slot 18,540. Three vectors, each a lone spike on its own axis.",
          "Now measure how *near* any two of them are. The dot product of two different one-hot vectors is always zero — their 1s never line up — so the cosine between any two distinct words is exactly $$\\cos(\\text{cat},\\text{dog}) = 0 = \\cos(\\text{cat},\\text{airplane}).$$ Read that again. \"cat\" and \"dog\" are *exactly as similar* as \"cat\" and \"airplane\": not similar at all, identically not-similar. Every pair of distinct words sits the same fixed distance apart, the corners of a giant simplex, equidistant and meaningless. This is the **Lexical Gremlin's** home turf — the brick wall he wedges between \"couch\" and \"sofa\" is built into the representation itself.",
          "And it's not just one-hot. BM25 and the bag-of-words document vectors inherit the same disease, because they're sums of one-hot word axes: a document about *felines* and a document about *cats* share no terms, so they share no coordinates, so they're orthogonal — zero overlap — even though they're about the same thing. Stemming and synonym lists are buckets bailing the boat, hand-patched, brittle, never enough. The real fix has to change the *representation*: stop giving each word a private axis, and start giving it a position that other words can be *near*.",
        ],
        ru: [
          'Сделаем провал конкретным, потому что он хуже, чем «немного слепой», — он *тотальный*. Классический способ передать слово в математику — **one-hot кодирование**: возьми словарь, скажем, на 50 000 слов и представь слово номер 7 как вектор из 50 000 нулей с единственной 1 в позиции 7. «cat» — пусть позиция 312, «dog» — 6 201, «airplane» — 18 540. Три вектора, каждый — одинокий всплеск на своей оси.',
          'Теперь измерь, насколько *близки* любые два из них. Скалярное произведение двух разных one-hot векторов всегда ноль — их единицы никогда не совпадают, — поэтому косинус между любыми двумя разными словами ровно $$\\cos(\\text{cat},\\text{dog}) = 0 = \\cos(\\text{cat},\\text{airplane}).$$ Перечитай. «cat» и «dog» *ровно так же похожи*, как «cat» и «airplane»: не похожи вовсе, одинаково непохожи. Каждая пара разных слов стоит на одном фиксированном расстоянии, вершины гигантского симплекса, равноудалённые и бессмысленные. Это родная земля **Лексического Гремлина** — кирпичная стена, которую он вставляет между «диваном» и «софой», вшита в само представление.',
          'И дело не только в one-hot. BM25 и векторы мешка слов наследуют ту же болезнь, ведь они — суммы one-hot осей слов: документ про *кошачьих* и документ про *кошек* не делят ни одного терма, значит, не делят координат, значит, ортогональны — нулевое пересечение, — хотя они про одно и то же. Стемминг и списки синонимов — вёдра, вычерпывающие лодку: ручные, хрупкие, всегда недостаточные. Настоящее лечение должно сменить *представление*: перестать давать каждому слову личную ось и начать давать ему позицию, к которой другие слова могут быть *близки*.',
        ],
        tt: [
          'Уңышсызлыкны конкрет итик, чөнки ул «бераз сукыр»дан да начаррак — ул *тулы*. Сүзне математикага тапшыруның классик ысулы — **one-hot кодлау**: әйтик, 50 000 сүзле сүзлек ал һәм 7 нче сүзне 50 000 нульдан, 7 нче оядагы бер генә 1 белән, вектор итеп күрсәт. «cat» — әйтик 312 нче оя, «dog» — 6 201, «airplane» — 18 540. Өч вектор, һәркайсы — үз күчәрендә ялгыз чөй.',
          'Хәзер аларның теләсә кайсы икесе ничек *якын* икәнен үлч. Ике төрле one-hot векторның скаляр тапкырчыгышы һәрвакыт нуль — аларның берәмлекләре беркайчан туры килми, — шуңа теләсә кайсы ике төрле сүз арасындагы косинус нәкъ $$\\cos(\\text{cat},\\text{dog}) = 0 = \\cos(\\text{cat},\\text{airplane}).$$ Тагын укы. «cat» белән «dog» «cat» белән «airplane» кебек *нәкъ шулай ук охшаш*: бөтенләй охшаш түгел, бертигез охшамаган. Һәр төрле сүз пары бер үк беркетелгән ераклыкта тора, гигант симплексның почмаклары, бертигез ерак һәм мәгънәсез. Бу — **Лексик Гремлин**ның туган җире — ул «диван» белән «софа» арасына кыстырган кирпеч стена күрсәтмәнең үзенә салынган.',
          'Һәм бу бары one-hot та гына түгел. BM25 һәм сүзләр капчыгы документ векторлары шул ук авыруны мирас итеп ала, чөнки алар — one-hot сүз күчәрләре суммасы: *мәчеләр* турындагы документ һәм *песиләр* турындагы документ бер генә терминны да уртаклашмый, димәк координаталарны да уртаклашмый, димәк ортогональ — нуль кисешү, — гәрчә алар бер үк нәрсә турында булса да. Стемминг һәм синоним исемлекләре — көймәне суыртучы чиләкләр: кул белән ясалган, сынучан, һәрвакыт җитми. Чын дәвалау *күрсәтмәне* үзгәртергә тиеш: һәр сүзгә шәхси күчәр бирүне туктатып, аңа башка сүзләр *якын* була алырлык позиция бирә башларга.',
        ],
      },
    },
    {
      id: 'turn-distributional', kind: 'prose',
      heading: { en: 'The company a word keeps', ru: 'Компания, что слово держит', tt: 'Сүз тоткан иптәшләр' },
      body: {
        en: [
          "So where do the coordinates come from? Not from a dictionary, not from hand-labelling — from a single, deep observation made by the linguist J. R. Firth in 1957, and it's worth quoting straight: *\"You shall know a word by the company it keeps.\"* This is the **distributional hypothesis**, and once you see it you can't unsee it: a word's meaning is the distribution of *contexts* it appears in.",
          "Run the thought experiment Firth was pointing at. Suppose you've never met the word \"wug\", but you keep reading sentences like \"the wug purred and curled up on the warm windowsill\", \"she fed the wug and scratched behind its ears\", \"the wug knocked a cup off the table, naturally\". You don't need a definition. The *company* — purred, fed, windowsill, knocked the cup off the table — has already told you a wug is a cat, or close enough to live next to one. Meaning leaked out of the contexts and into the word.",
          "Here's the leap that makes it computable. If two words appear in the *same contexts* — \"couch\" and \"sofa\" both sit near \"cushion\", \"living room\", \"sit down\", \"comfortable\" — then their context distributions are nearly identical, and we'll *define* them to be near in our space. Flip it around: we'll search for a set of word coordinates such that words sharing contexts end up close together. The contexts are the gravity; the coordinates are what settles under it. Every embedding method in this chapter is some clever way of doing exactly that — turning \"the company a word keeps\" into a vector.",
        ],
        ru: [
          'Так откуда же берутся координаты? Не из словаря, не из ручной разметки — из одного глубокого наблюдения лингвиста Дж. Р. Фёрта в 1957 году, и его стоит привести дословно: *«Слово узнаётся по компании, которую оно водит»*. Это **дистрибутивная гипотеза**, и, увидев её однажды, развидеть нельзя: смысл слова — это распределение *контекстов*, в которых оно встречается.',
          'Прокрути мысленный эксперимент, на который указывал Фёрт. Допустим, ты никогда не встречал слово «wug», но всё читаешь предложения вроде «wug замурлыкал и свернулся на тёплом подоконнике», «она покормила wug и почесала ему за ухом», «wug, разумеется, скинул чашку со стола». Определение тебе не нужно. *Компания* — замурлыкал, покормила, подоконник, скинул чашку со стола — уже сказала, что wug это кот или кто-то достаточно близкий, чтобы жить рядом. Смысл просочился из контекстов в слово.',
          'Вот скачок, что делает это вычислимым. Если два слова появляются в *одних и тех же контекстах* — «диван» и «софа» оба стоят рядом с «подушкой», «гостиной», «присядь», «удобный», — то их распределения контекстов почти одинаковы, и мы *по определению* сделаем их близкими в нашем пространстве. Переверни: мы будем искать набор координат слов такой, что слова с общими контекстами окажутся рядом. Контексты — это гравитация; координаты — то, что под ней оседает. Каждый метод эмбеддинга в этой главе — какой-нибудь хитрый способ сделать ровно это: превратить «компанию, что слово водит» в вектор.',
        ],
        tt: [
          'Соң, координаталар каян килә? Сүзлектән түгел, кул белән билгеләүдән түгел — телче Дж. Р. Фёртның 1957 елда ясаган бер тирән күзәтүеннән, һәм аны сүзгә-сүз китерергә кирәк: *«Сүзне ул йөргән иптәшләре буенча белерсең»*. Бу — **дистрибутив гипотеза**, һәм аны бер күргәч, күрмәгәнгә салынып булмый: сүзнең мәгънәсе — ул очраган *контекстлар* таралышы.',
          'Фёрт күрсәткән уй экспериментын әйләндереп чык. Әйтик, син «wug» сүзен беркайчан очратмагансың, ләкин «wug мырлады һәм җылы тәрәзә төбенә бөгәрләнде», «ул wug’ны ашатты һәм колак артын кашыды», «wug, әлбәттә, өстәлдән чынаякны төшерде» кебек җөмләләрне укып торасың. Сиңа билгеләмә кирәкми. *Иптәшләре* — мырлады, ашатты, тәрәзә төбе, чынаякны төшерде — wug’ның мәче икәнен, яки янәшә яшәрлек дәрәҗәдә якын икәнен инде әйтте. Мәгънә контекстлардан сүзгә сеңде.',
          'Менә моны исәпләп була торган итә торган сикереш. Әгәр ике сүз *бер үк контекстларда* очраса — «диван» белән «софа» икесе дә «мендәр», «кунак бүлмәсе», «утыр», «уңайлы» янында тора, — аларның контекст таралышлары диярлек бертөрле, һәм без аларны үз киңлегебездә *билгеләмә буенча* якын итәчәкбез. Әйләндер: без уртак контекстлы сүзләр янәшә төшә торган сүз координаталары җыелмасын эзләячәкбез. Контекстлар — тартылыш; координаталар — аның астында утырганы. Бу бүлектәге һәр эмбеддинг методы — нәкъ шуны эшләүнең берәр хәйләкәр ысулы: «сүз йөргән иптәшләрне» векторга әйләндерү.',
        ],
      },
    },
    {
      id: 'climb-word2vec', kind: 'prose',
      heading: { en: 'word2vec: learning the coordinates', ru: 'word2vec: учим координаты', tt: 'word2vec: координаталарны өйрәнү' },
      body: {
        en: [
          "In 2013 [Mikolov and colleagues at Google](https://arxiv.org/abs/1301.3781) turned the distributional hypothesis into a fast, trainable recipe — **word2vec** — and it's the one worth working through in full. The variant we'll follow is **skip-gram**: a tiny prediction game whose *by-product* is the map. Slide a window over the text; for each centre word, try to predict the words around it. Centre \"cat\" in \"the lazy cat sat on the\", and the model must raise the probability of its neighbours — \"lazy\", \"sat\", \"on\" — within a window of, say, two words each side.",
          "Mechanically, every word gets *two* vectors: one as a centre word ($v_w$) and one as a context word ($u_w$), both the coordinates we're trying to learn. The model scores how well a context word $o$ fits a centre word $c$ by their dot product $u_o^\\top v_c$, and turns the scores over the whole vocabulary into probabilities with a softmax: $$P(o \\mid c) = \\frac{\\exp(u_o^\\top v_c)}{\\sum_{w \\in V} \\exp(u_w^\\top v_c)}.$$ Train by maximizing the probability of the *true* neighbours across the whole corpus. The pressure is exactly the distributional hypothesis made numerical: to predict \"cat\"'s neighbours well, \"cat\"'s vector must come to resemble the vectors of words that share its company — so \"cat\" and \"dog\", which keep nearly the same company, drift together.",
          "But look at that denominator. The softmax sums over *every* word in the vocabulary — 50,000, a million — for *every* training step. That's hopeless at scale; you'd spend all your compute normalizing. word2vec's decisive trick is **negative sampling**: don't ask \"which of all million words comes next?\", ask a far cheaper yes/no question. For each real (centre, context) pair, draw a handful — typically $k = 5$ to $20$ — of *random* words as fake \"negative\" contexts, and train a logistic classifier to say *yes* to the real pair and *no* to the fakes: $$\\log \\sigma(u_o^\\top v_c) + \\sum_{i=1}^{k} \\mathbb{E}_{w_i \\sim P_n}\\big[\\log \\sigma(-u_{w_i}^\\top v_c)\\big].$$ Here $\\sigma$ is the logistic sigmoid. Each step now touches $k+1$ words instead of a million — and that single change is what turned a beautiful idea into something you can train on billions of words over a weekend.",
          "Two details that matter in practice and are pure distributional-hypothesis wisdom. The negatives are drawn not uniformly but from the *unigram distribution raised to the 3/4 power* — a tuning that samples frequent words a bit less and rare words a bit more, so common junk like \"the\" doesn't dominate the negatives. And frequent words get **subsampled** — randomly dropped in proportion to their frequency — because the ten-thousandth time \"the\" appears next to \"cat\" it teaches nothing new. The result, after a pass over enough text: a few hundred numbers per word, and a space where the company each word keeps has hardened into a position.",
        ],
        ru: [
          'В 2013 году [Миколов с коллегами в Google](https://arxiv.org/abs/1301.3781) превратили дистрибутивную гипотезу в быстрый, обучаемый рецепт — **word2vec**, — и его стоит разобрать целиком. Вариант, которому мы последуем, — **skip-gram**: крошечная игра в предсказание, *побочный продукт* которой и есть карта. Веди окно по тексту; для каждого центрального слова пытайся предсказать слова вокруг. Центр «cat» в «the lazy cat sat on the» — и модель должна поднять вероятность его соседей «lazy», «sat», «on» в окне, скажем, по два слова с каждой стороны.',
          'Механически каждое слово получает *два* вектора: один как центральное слово ($v_w$) и один как контекстное ($u_w$) — обе те координаты, что мы учим. Модель оценивает, насколько контекстное слово $o$ подходит центральному $c$, их скалярным произведением $u_o^\\top v_c$ и превращает оценки по всему словарю в вероятности через softmax: $$P(o \\mid c) = \\frac{\\exp(u_o^\\top v_c)}{\\sum_{w \\in V} \\exp(u_w^\\top v_c)}.$$ Обучай, максимизируя вероятность *настоящих* соседей по всему корпусу. Давление — это ровно дистрибутивная гипотеза, ставшая числом: чтобы хорошо предсказывать соседей «cat», вектор «cat» должен стать похож на векторы слов с той же компанией, — поэтому «cat» и «dog», водящие почти одну компанию, сближаются.',
          'Но взгляни на знаменатель. Softmax суммирует по *каждому* слову словаря — 50 000, миллион — на *каждом* шаге обучения. На масштабе это безнадёжно; всё железо уйдёт на нормировку. Решающий трюк word2vec — **негативное сэмплирование**: не спрашивай «какое из миллиона слов идёт следующим?», задай куда более дешёвый вопрос «да/нет». Для каждой настоящей пары (центр, контекст) вытяни горсть — обычно $k = 5$–$20$ — *случайных* слов как фальшивые «негативные» контексты и обучи логистический классификатор говорить *да* настоящей паре и *нет* фальшивым: $$\\log \\sigma(u_o^\\top v_c) + \\sum_{i=1}^{k} \\mathbb{E}_{w_i \\sim P_n}\\big[\\log \\sigma(-u_{w_i}^\\top v_c)\\big].$$ Здесь $\\sigma$ — логистическая сигмоида. Каждый шаг теперь трогает $k+1$ слов вместо миллиона — и именно эта замена превратила красивую идею в нечто, что обучается на миллиардах слов за выходные.',
          'Две детали, важные на практике и чистая мудрость дистрибутивной гипотезы. Негативы тянут не равномерно, а из *униграммного распределения в степени 3/4* — настройка, что сэмплит частые слова чуть реже, а редкие чуть чаще, чтобы хлам вроде «the» не доминировал в негативах. А частые слова **сабсэмплят** — случайно выбрасывают пропорционально частоте, — потому что в десятитысячный раз «the» рядом с «cat» не учит ничему новому. Итог, после прохода по достаточному тексту: несколько сотен чисел на слово и пространство, где компания, что водит каждое слово, затвердела в позицию.',
        ],
        tt: [
          '2013 елда [Миколов һәм Google’дагы хезмәттәшләре](https://arxiv.org/abs/1301.3781) дистрибутив гипотезаны тиз, өйрәтелә торган рецептка — **word2vec**’ка — әйләндерделәр, һәм аны тулысынча карап чыгарга кирәк. Без иярә торган вариант — **skip-gram**: кечкенә алдан әйтү уены, аның *янәмә продукты* карта да була. Текст буенча тәрәзәне шудыр; һәр үзәк сүз өчен аның тирәсендәге сүзләрне алдан әйтергә тырыш. «the lazy cat sat on the»’дагы үзәк «cat» — һәм модель аның күршеләре «lazy», «sat», «on» ихтималлыгын күтәрергә тиеш, әйтик, һәр якта ике сүзле тәрәзәдә.',
          'Механик яктан һәр сүз *ике* вектор ала: берсе үзәк сүз буларак ($v_w$) һәм берсе контекст сүз буларак ($u_w$) — без өйрәнә торган координаталарның икесе дә. Модель контекст сүзе $o$ үзәк сүз $c$’га ничек туры килгәнен аларның скаляр тапкырчыгышы $u_o^\\top v_c$ белән бәяли һәм бөтен сүзлек буенча бәяләрне softmax аша ихтималлыкларга әйләндерә: $$P(o \\mid c) = \\frac{\\exp(u_o^\\top v_c)}{\\sum_{w \\in V} \\exp(u_w^\\top v_c)}.$$ Бөтен корпус буенча *чын* күршеләрнең ихтималлыгын максимумлаштырып өйрәт. Басым — нәкъ санга әйләнгән дистрибутив гипотеза: «cat» күршеләрен яхшы алдан әйтер өчен, «cat» векторы шул ук иптәшле сүзләрнең векторларына охшарга тиеш, — шуңа диярлек бер үк иптәш йөрткән «cat» белән «dog» якынлаша.',
          'Әмма ваклагычка кара. Softmax *һәр* өйрәтү адымында сүзлекнең *һәр* сүзе буенча — 50 000, миллион — суммалый. Масштабта бу өметсез; бөтен куәт нормалаштыруга китәр. word2vec’ның хәлиткеч хәйләсе — **негатив сэмплинг**: «миллион сүзнең кайсысы киләсе?» дип сорама, күпкә арзанрак «әйе/юк» соравын бир. Һәр чын (үзәк, контекст) пары өчен бер уч — гадәттә $k = 5$–$20$ — *очраклы* сүзне ялган «негатив» контекст итеп тарт һәм логистик классификаторны чын парга *әйе*, ялганнарга *юк* дип әйтергә өйрәт: $$\\log \\sigma(u_o^\\top v_c) + \\sum_{i=1}^{k} \\mathbb{E}_{w_i \\sim P_n}\\big[\\log \\sigma(-u_{w_i}^\\top v_c)\\big].$$ Монда $\\sigma$ — логистик сигмоида. Һәр адым хәзер миллион урынына $k+1$ сүзгә кагыла — һәм нәкъ менә бу алыштыру матур идеяне ял көннәрендә миллиард сүздә өйрәтеп була торган нәрсәгә әйләндерде.',
          'Практикада мөһим һәм саф дистрибутив-гипотеза зирәклеге булган ике деталь. Негативлар бертигез түгел, ә *униграмма таралышының 3/4 дәрәҗәсеннән* тартыла — еш сүзләрне бераз сирәгрәк, сирәкләрне бераз ешрак сэмпллый торган көйләү, «the» кебек чүп негативларда өстенлек итмәсен өчен. Ә еш сүзләр **сабсэмпллана** — ешлыкка пропорциональ очраклы рәвештә ташлана, — чөнки «the»’ның «cat» янында ун меңенче тапкыр килүе яңа бернәрсә дә өйрәтми. Җитәрлек текст буенча үткәннән соң нәтиҗә: сүзгә берничә йөз сан һәм һәр сүз йөрткән иптәш позициягә каткан киңлек.',
        ],
      },
    },
    {
      id: 'turn-analogy', kind: 'prose',
      heading: { en: 'Meaning becomes arithmetic', ru: 'Смысл становится арифметикой', tt: 'Мәгънә арифметикага әйләнә' },
      img: 'L5/L5-05-analogy-arrows.png', imgPos: 'scene',
      imgAlt: {
        en: 'A parallelogram of arrows on the meaning map: the king→queen arrow drawn parallel to the man→woman arrow.',
        ru: 'Параллелограмм стрелок на карте смысла: стрелка king→queen параллельна стрелке man→woman.',
        tt: 'Мәгънә картасында уклар параллелограммы: king→queen угы man→woman угына параллель.',
      },
      imgCaption: {
        en: 'The relation “king→queen” turns out to be a direction — the very same arrow as “man→woman”. Relations live in the map’s geometry.',
        ru: 'Отношение «king→queen» оказывается направлением — той же стрелкой, что «man→woman». Отношения живут в геометрии карты.',
        tt: '«king→queen» мөнәсәбәте юнәлеш булып чыга — нәкъ «man→woman» белән бер үк ук. Мөнәсәбәтләр картаның геометриясендә яши.',
      },
      body: {
        en: [
          "Now comes the moment that made the whole field sit up — the thing nobody put in the training objective, that fell out anyway. We trained the space only to predict neighbours. We never told it about gender, or royalty, or plurals, or capital cities. And yet, when you go looking, the space has quietly *organized itself by relation*.",
          "Watch what that means geometrically. Take the vectors for \"man\" and \"woman\" and subtract them: $\\text{woman} - \\text{man}$ is an arrow, a direction in the space. Now take \"king\" and \"queen\" and subtract: $\\text{queen} - \\text{king}$ is *another* arrow — and it points the same way. The relationship \"…and its female counterpart\" became a single, consistent **direction** you can travel along. The same is true for \"capital of\" (\"paris\" → \"france\"), for tense, for plural. Meaning didn't just become a *place*; the relations *between* meanings became *vectors*. Which means we can do arithmetic on them — and the next page does exactly that, with the real numbers.",
        ],
        ru: [
          'Теперь — момент, от которого встрепенулось всё поле: то, чего никто не закладывал в цель обучения, а оно всё равно выпало. Мы учили пространство лишь предсказывать соседей. Мы ни словом не обмолвились про пол, про сан, про множественное число, про столицы. И всё же, стоит приглядеться, пространство тихо *организовало себя по отношениям*.',
          'Смотри, что это значит геометрически. Возьми векторы «man» и «woman» и вычти: $\\text{woman} - \\text{man}$ — это стрелка, направление в пространстве. Теперь возьми «king» и «queen» и вычти: $\\text{queen} - \\text{king}$ — это *другая* стрелка, и она смотрит туда же. Отношение «…и его женский аналог» стало единым, согласованным **направлением**, вдоль которого можно идти. То же верно для «столица чего» («paris» → «france»), для времени, для множественного числа. Смысл стал не просто *местом* — отношения *между* смыслами стали *векторами*. А значит, над ними можно делать арифметику — что следующая страница и проделает, с настоящими числами.',
        ],
        tt: [
          'Хәзер бөтен өлкәне сискәндергән мизгел — өйрәтү максатына беркем салмаган, ә барыбер килеп чыккан нәрсә. Без киңлекне бары күршеләрне алдан әйтергә генә өйрәттек. Без аңа җенес турында да, дәрәҗә турында да, күплек турында да, башкалалар турында да бер сүз әйтмәдек. Шулай да, карап торсаң, киңлек тын гына *үзен мөнәсәбәтләр буенча оештырган*.',
          'Бу геометрик яктан нәрсә аңлатканын кара. «man» белән «woman» векторларын ал һәм тартып ал: $\\text{woman} - \\text{man}$ — ул ук, киңлектә юнәлеш. Хәзер «king» белән «queen»’не ал һәм тартып ал: $\\text{queen} - \\text{king}$ — ул *башка* ук, һәм ул шул якка карый. «…һәм аның хатын-кыз парасы» мөнәсәбәте буйлап барып була торган бердәм, килешле **юнәлешкә** әйләнде. Шул ук «нәрсәнең башкаласы» («paris» → «france») өчен, заман өчен, күплек өчен дөрес. Мәгънә бары *урын* гына булмады — мәгънәләр *арасындагы* мөнәсәбәтләр *векторларга* әйләнде. Димәк, алар өстендә арифметика эшләп була — киләсе бит нәкъ шуны эшли, чын саннар белән.',
        ],
      },
    },
    { id: 'climb-analogy', kind: 'scrolly', widget: 'embedding-space', data: 'l5-embeddings' },
    {
      id: 'turn-glove', kind: 'prose',
      heading: { en: 'A second road: GloVe', ru: 'Вторая дорога: GloVe', tt: 'Икенче юл: GloVe' },
      body: {
        en: [
          "word2vec earns its map by *prediction* — slide a window, guess the neighbours, let the gradients sculpt the space. A year later, [Pennington, Socher and Manning at Stanford](https://aclanthology.org/D14-1162/) arrived at *the same kind of map* from the opposite direction, by *counting*. Their method is **GloVe** — Global Vectors — and the contrast between the two is the whole story of how embeddings work.",
          "Start by building the **co-occurrence matrix** $X$: go over the entire corpus once and tally $X_{ij}$ = how many times word $j$ appears in the context of word $i$. This is a giant, global table of who-keeps-company-with-whom — the distributional hypothesis written out in full as counts. word2vec never builds this table; it streams the corpus and learns locally, window by window. GloVe stares at the whole thing at once.",
          "GloVe's insight is that the *ratios* of co-occurrence probabilities carry the meaning. For \"ice\" versus \"steam\": the word \"solid\" co-occurs much more with \"ice\", \"gas\" much more with \"steam\", while \"water\" co-occurs with both and \"fashion\" with neither — and it's those ratios, not the raw counts, that pin down the relationship. So GloVe learns vectors whose dot products match the *log* of the co-occurrence counts, minimizing $$J = \\sum_{i,j} f(X_{ij})\\,\\big(w_i^\\top \\tilde{w}_j + b_i + \\tilde{b}_j - \\log X_{ij}\\big)^2,$$ where the weighting $f(X_{ij})$ damps down the most frequent pairs so \"the\" doesn't swamp everything — the same instinct as word2vec's subsampling, in a different coat. It's a weighted matrix factorization, and you can read it as factoring that global count table into word vectors.",
          "Two roads, one destination. **Predictive** (word2vec) learns the map by repeatedly guessing local context; **count-based** (GloVe) learns it by factoring a global co-occurrence table. They land in remarkably similar places — the same neighbourhoods, the same analogy directions — which is the deepest hint that the *map itself*, not the algorithm, is the real object. The numbers you're about to see come from GloVe vectors; they'd look much the same from word2vec. The company a word keeps determines where it lives, however you do the bookkeeping.",
        ],
        ru: [
          'word2vec зарабатывает карту *предсказанием* — веди окно, угадывай соседей, дай градиентам лепить пространство. Год спустя [Пеннингтон, Сошер и Мэннинг в Стэнфорде](https://aclanthology.org/D14-1162/) пришли к *такой же карте* с противоположной стороны — *подсчётом*. Их метод — **GloVe**, Global Vectors, — и контраст между двумя и есть вся история того, как работают эмбеддинги.',
          'Начни с построения **матрицы совстречаемости** $X$: пройди по всему корпусу один раз и подсчитай $X_{ij}$ = сколько раз слово $j$ встречается в контексте слова $i$. Это гигантская глобальная таблица того, кто-с-кем-водит-компанию — дистрибутивная гипотеза, выписанная целиком в виде счётчиков. word2vec эту таблицу никогда не строит; он гонит корпус потоком и учится локально, окно за окном. GloVe же смотрит на всё разом.',
          'Прозрение GloVe в том, что смысл несут *отношения* вероятностей совстречаемости. Для «ice» против «steam»: слово «solid» куда чаще встречается с «ice», «gas» — с «steam», тогда как «water» встречается с обоими, а «fashion» — ни с одним, — и именно эти отношения, а не сырые счётчики, фиксируют связь. Поэтому GloVe учит векторы, чьи скалярные произведения совпадают с *логарифмом* счётчиков совстречаемости, минимизируя $$J = \\sum_{i,j} f(X_{ij})\\,\\big(w_i^\\top \\tilde{w}_j + b_i + \\tilde{b}_j - \\log X_{ij}\\big)^2,$$ где вес $f(X_{ij})$ глушит самые частые пары, чтобы «the» не затопило всё, — тот же инстинкт, что сабсэмплинг word2vec, в другом пальто. Это взвешенная факторизация матрицы, и её можно читать как разложение той глобальной таблицы счётчиков на векторы слов.',
          'Две дороги, один пункт назначения. **Предсказательная** (word2vec) учит карту, раз за разом угадывая локальный контекст; **счётная** (GloVe) — факторизуя глобальную таблицу совстречаемости. Они приходят в поразительно похожие места — те же окрестности, те же направления аналогий, — и это глубочайший намёк, что настоящий объект — *сама карта*, а не алгоритм. Числа, что ты сейчас увидишь, взяты с GloVe-векторов; с word2vec они выглядели бы почти так же. Компания, что водит слово, определяет, где оно живёт, как ни веди бухгалтерию.',
        ],
        tt: [
          'word2vec картаны *алдан әйтү* белән казана — тәрәзәне шудыр, күршеләрне чамала, градиентларга киңлекне сыкларга бир. Бер елдан соң [Стэнфордта Пеннингтон, Сошер һәм Мэннинг](https://aclanthology.org/D14-1162/) *шундый ук картага* капма-каршы яктан — *санау* белән килделәр. Аларның методы — **GloVe**, Global Vectors, — һәм икесе арасындагы контраст эмбеддинглар ничек эшләвенең бөтен тарихы.',
          '**Бергә-очрашу матрицасы** $X$ төзүдән башла: бөтен корпус буенча бер тапкыр үтеп, $X_{ij}$ = $j$ сүзе $i$ сүзе контекстында ничә тапкыр очравын санап чык. Бу — кем-кем-белән-иптәш-йөргәненең гигант глобаль таблицасы — санаулар итеп тулысынча язылган дистрибутив гипотеза. word2vec бу таблицаны беркайчан төземи; ул корпусны агым итеп куа һәм локаль, тәрәзәдән-тәрәзәгә, өйрәнә. GloVe исә барысына бердән карый.',
          'GloVe’ның зирәклеге шунда: мәгънәне бергә-очрашу ихтималлыкларының *нисбәтләре* йөртә. «ice»’ка каршы «steam» өчен: «solid» сүзе «ice» белән күпкә ешрак очрый, «gas» — «steam» белән, ә «water» икесе белән дә, «fashion» берсе белән дә очрамый, — һәм нәкъ менә шул нисбәтләр, чи санаулар түгел, бәйләнешне беркетә. Шуңа GloVe скаляр тапкырчыгышлары бергә-очрашу санауларының *логарифмына* туры килгән векторларны өйрәнә, $$J = \\sum_{i,j} f(X_{ij})\\,\\big(w_i^\\top \\tilde{w}_j + b_i + \\tilde{b}_j - \\log X_{ij}\\big)^2$$ минимумлаштырып, монда $f(X_{ij})$ авырлыгы иң еш парларны тонык итә, «the» барысын басмасын өчен, — нәкъ word2vec сабсэмплингы инстинкты, башка пальтода. Бу — авырлыклы матрица факторизациясе, һәм аны шул глобаль санаулар таблицасын сүз векторларына таркату итеп укып була.',
          'Ике юл, бер барачак урын. **Алдан әйтүле** (word2vec) картаны локаль контекстны кат-кат чамалап өйрәнә; **санаулы** (GloVe) — глобаль бергә-очрашу таблицасын факторлаштырып. Алар таң калырлык охшаш урыннарга килә — шул ук тирәләр, шул ук аналогия юнәлешләре, — һәм бу — чын объект *карта үзе*, алгоритм түгел дигән иң тирән ишарә. Хәзер күрәчәк саннар GloVe векторларыннан алынган; word2vec’тан алар диярлек шулай ук күренер иде. Сүз йөрткән иптәш ул кайда яшәгәнен билгели, хисапны ничек алып барсаң да.',
        ],
      },
    },
    {
      id: 'stakes-too-many-dims', kind: 'prose',
      heading: { en: 'Three hundred numbers you can’t see', ru: 'Триста чисел, которых не видно', tt: 'Күреп булмый торган өч йөз сан' },
      body: {
        en: [
          "Time for the catch, and it's a big one. The maps people actually ship aren't the six-number sketch we've been drawing — production embeddings live in **300 dimensions** (GloVe's standard size; word2vec and friends use 100–1000). Three hundred numbers per word. And that's the *good* news: 300-D is exactly what gives the space enough room to encode gender *and* royalty *and* tense *and* topic *and* register all as separate, simultaneous directions. The richness is the dimensionality.",
          "Here's the problem the richness creates. *You cannot see 300 dimensions.* Your visual system maxes out at three, and you really only reason comfortably in two. Every picture in this chapter — the parallelogram, the islands of meaning — has been a *lie of convenience*, a 2-D shadow I drew so the idea would fit on a page. The real space is a 300-dimensional cloud of forty-thousand points, and no eye will ever look at it directly.",
          "This matters beyond the pretty pictures. You debug what you can see. When an embedding model misbehaves — synonyms drifting apart, two senses of a word tangled together, a cluster that shouldn't exist — you need to *look*. And you can't look at 300-D. So we need a way to take that vast, high-dimensional map and **fold it down** to two or three dimensions you can actually plot, while keeping as much of the real shape as possible. Enter a new character, whose entire job is exactly that fold.",
        ],
        ru: [
          'Пора к подвоху, и он крупный. Карты, которые люди реально выкатывают, — не шестичисленный набросок, что мы рисовали: продакшн-эмбеддинги живут в **300 измерениях** (стандартный размер GloVe; word2vec и компания берут 100–1000). Триста чисел на слово. И это *хорошая* новость: именно 300-D даёт пространству достаточно места, чтобы закодировать пол *и* сан *и* время *и* тему *и* регистр — все как отдельные, одновременные направления. Богатство и есть размерность.',
          'Вот проблема, которую это богатство создаёт. *Триста измерений увидеть нельзя.* Зрение упирается в три, а удобно рассуждаешь вообще в двух. Каждая картинка в этой главе — параллелограмм, острова смысла — была *ложью ради удобства*, 2-D тенью, что я рисовал, чтобы идея влезла на страницу. Настоящее пространство — 300-мерное облако из сорока тысяч точек, и ни один глаз никогда не посмотрит на него прямо.',
          'Это важно не только ради красивых картинок. Ты чинишь то, что видишь. Когда модель эмбеддингов чудит — синонимы расходятся, два смысла слова спутаны, есть кластер, которого быть не должно, — нужно *посмотреть*. А на 300-D не посмотришь. Значит, нужен способ взять эту огромную многомерную карту и **свернуть её** до двух-трёх измерений, которые реально можно нарисовать, сохранив как можно больше настоящей формы. На сцену выходит новый персонаж, чья вся работа — ровно этот сгиб.',
        ],
        tt: [
          'Подвох вакыты, һәм ул зур. Кешеләр чынлап чыгарган карталар — без сызган алты санлы эскиз түгел: продакшн эмбеддинглары **300 үлчәмдә** яши (GloVe’ның стандарт зурлыгы; word2vec һәм иптәшләре 100–1000 ала). Сүзгә өч йөз сан. Һәм бу *яхшы* хәбәр: нәкъ 300-D киңлеккә җенесне *дә*, дәрәҗәне *дә*, заманны *дә*, теманы *дә*, регистрны *дә* — барысын аерым, бер үк вакытлы юнәлешләр итеп кодларга җитәрлек урын бирә. Байлык — ул үлчәмлелек.',
          'Менә бу байлык тудырган проблема. *Өч йөз үлчәмне күреп булмый.* Күрү өчтә туктала, ә уңайлы фикерләү гомумән икедә. Бу бүлектәге һәр рәсем — параллелограмм, мәгънә утраулары — *уңайлык өчен ялган* иде, идея биткә сыйсын өчен мин сызган 2-D күләгә. Чын киңлек — кырык мең нокталы 300-үлчәмле болыт, һәм беркайчан бер күз дә аңа турыдан карамаячак.',
          'Бу матур рәсемнәр өчен генә мөһим түгел. Син күргәнеңне төзәтәсең. Эмбеддинг моделе тилерсә — синонимнар аерылса, сүзнең ике мәгънәсе бутала, булмаска тиешле кластер бар, — *карарга* кирәк. Ә 300-D’га карап булмый. Димәк, бу зур, күп үлчәмле картаны алып, аны чынлап сызып була торган ике-өч үлчәмгә **бөкли** торган ысул кирәк, чын форманы мөмкин кадәр күбрәк саклап. Сәхнәгә яңа персонаж чыга, аның бөтен эше — нәкъ менә шул бөкләү.',
        ],
      },
    },
    {
      id: 'turn-dimred', kind: 'prose',
      heading: { en: 'Enter the Cartographer', ru: 'Выходит Картограф', tt: 'Картограф чыга' },
      img: 'L5/L5-08-cartographer.png', imgPos: 'scene',
      imgAlt: {
        en: 'The Cartographer, a robed figure creasing a vast star-map along careful folds to make it small enough to carry.',
        ru: 'Картограф, фигура в плаще, заминает огромную звёздную карту по аккуратным складкам, чтобы её можно было унести.',
        tt: 'Картограф, плащлы фигура, зур йолдыз картасын җентекле бөкләрдән сыга, аны күтәреп йөрерлек итеп.',
      },
      imgCaption: {
        en: 'The Cartographer’s one job: fold a map too big to hold down to a size you can carry — without losing the shape of the land.',
        ru: 'Единственная работа Картографа: сложить карту, которую не удержать, до размера, что унесёшь, — не потеряв форму земли.',
        tt: 'Картографның бер генә эше: тотып булмый торган картаны күтәреп йөрерлек зурлыкка бөкләү — җирнең формасын югалтмыйча.',
      },
      body: {
        en: [
          "Meet the **Cartographer**. Her one job, the only thing she does, is **dimensionality reduction**: take a map that lives in 300 dimensions and crease it down to 2 or 3, so a human can finally hold it. Like every good map-folder, she faces a trade-off — the folded map can't be the territory, something is always lost in the creases — and the whole craft is in *choosing what to keep*.",
          "Frame the task precisely. We have forty thousand points in 300-D. We want a new set of forty thousand points in 2-D such that the *structure that matters* — which words are near which, which clusters hang together — survives the projection. \"Structure that matters\" is doing a lot of work in that sentence, and it splits the field in two. One school says: keep the directions of greatest *variance*, the axes along which the data is most spread out — that's **PCA**, and it's linear, fast, and honest about how much it threw away. The other says: forget global geometry, just keep each point's *local neighbours* close — that's **t-SNE** and **UMAP**, non-linear and gorgeous and treacherous. We'll walk through both, with the real numbers, in the climb that follows.",
        ],
        ru: [
          'Знакомься — **Картограф**. Её единственная работа, всё, что она делает, — **снижение размерности**: взять карту, что живёт в 300 измерениях, и заломить её до 2 или 3, чтобы человек наконец смог её удержать. Как у всякого хорошего складывателя карт, у неё компромисс — сложенная карта не может быть территорией, в складках всегда что-то теряется, — и всё мастерство в том, *что выбрать сохранить*.',
          'Сформулируем задачу точно. У нас сорок тысяч точек в 300-D. Нужен новый набор из сорока тысяч точек в 2-D такой, что *важная структура* — какие слова рядом с какими, какие кластеры держатся вместе — переживёт проекцию. «Важная структура» тащит в этой фразе много веса, и она раскалывает поле надвое. Одна школа говорит: сохрани направления наибольшей *дисперсии*, оси, вдоль которых данные разбросаны сильнее всего, — это **PCA**, линейный, быстрый и честный в том, сколько он выбросил. Другая говорит: забудь глобальную геометрию, просто держи *локальных соседей* каждой точки рядом — это **t-SNE** и **UMAP**, нелинейные, роскошные и коварные. Пройдём оба, с настоящими числами, в следующем восхождении.',
        ],
        tt: [
          'Таныш бул — **Картограф**. Аның бер генә эше, ул эшләгән бөтен нәрсә — **үлчәмлелекне киметү**: 300 үлчәмдә яшәгән картаны алып, аны 2 яки 3’кә сыгу, кеше ниһаять аны тотып торсын өчен. Һәр яхшы карта бөклүче кебек, аның килешүе бар — бөкләнгән карта җир-су була алмый, бөкләрдә һәрвакыт нәрсәдер югала, — һәм бөтен осталык *нәрсә сакларга икәнен сайлауда*.',
          'Бурычны төгәл әйтик. Бездә 300-D’да кырык мең нокта бар. Безгә 2-D’да кырык мең ноктаның яңа җыелмасы кирәк, *мөһим төзелеш* — кайсы сүзләр кайсыларга якын, кайсы кластерлар бергә тора — проекциядә исән калырлык. «Мөһим төзелеш» бу җөмләдә күп авырлык күтәрә, һәм ул өлкәне икегә яра. Бер мәктәп әйтә: иң зур *дисперсия* юнәлешләрен, мәгълүмат иң нык таралган күчәрләрне сакла, — бу **PCA**, ул линеар, тиз һәм нәрсә ташлаганын ачык әйтә. Икенчесе: глобаль геометрияне оныт, бары һәр ноктаның *локаль күршеләрен* янәшә тот, — бу **t-SNE** һәм **UMAP**, линеар түгел, искиткеч һәм мәкерле. Икесен дә, чын саннар белән, киләсе менүдә үтәрбез.',
        ],
      },
    },
    { id: 'climb-pca', kind: 'scrolly', widget: 'dimred-projection', data: 'l5-dimred' },
    {
      id: 'turn-manifold', kind: 'prose',
      heading: { en: 'When the map is curved', ru: 'Когда карта искривлена', tt: 'Карта бөгелгәндә' },
      img: 'L5/L5-10-folded-map-manifold.png', imgPos: 'scene',
      imgAlt: {
        en: 'A flat sheet trying to capture a curved, rolled-up surface (a Swiss-roll manifold) — a straight projection cuts across the curl.',
        ru: 'Плоский лист пытается схватить искривлённую свёрнутую поверхность (рулет-многообразие) — прямая проекция режет поперёк завитка.',
        tt: 'Яссы кәгазь бөгелгән, төрелгән өслекне (рулет-күпьяклык) тотарга тырыша — туры проекция бөтерелешне аркылы кисә.',
      },
      imgCaption: {
        en: 'PCA flattens with a single straight cut. But meaning curls — and a straight cut through a rolled-up sheet glues far-apart points together.',
        ru: 'PCA сплющивает одним прямым разрезом. Но смысл сворачивается — а прямой разрез сквозь свёрнутый лист склеивает далёкие точки.',
        tt: 'PCA бер туры кисем белән яссылый. Әмма мәгънә бөтерелә — ә төрелгән кәгазьне аркылы туры кисү ерак нокталарны бер-берсенә ябыштыра.',
      },
      body: {
        en: [
          "PCA is honest, fast, and *linear* — and that last word is its ceiling. PCA can only rotate the space and flatten it with a single straight cut; it assumes the structure worth keeping lies along straight axes. Often the structure doesn't. Picture data shaped like a Swiss roll — a 2-D sheet rolled up in 3-D. Two points on opposite ends of the *rolled-up* sheet sit physically close in 3-D, but along the surface, the path that actually matters, they're far apart. Slice that roll flat with one straight PCA cut and you glue the far ends together: a catastrophe of false neighbours.",
          "The fix is to stop preserving *global* distances and preserve *neighbourhoods* instead. The idea, called **manifold learning**, assumes the data — though embedded in 300-D — actually lies on a lower-dimensional curved surface, a *manifold*, like that 2-D sheet curled through 3-D space. We don't care about the straight-line distance between two far-apart words; we care that each word keeps the *same close neighbours* after the fold. Get the local relationships right, let the global layout bend however it must, and unroll the curl instead of slicing through it.",
          "That's the philosophy behind **t-SNE** ([van der Maaten & Hinton, 2008](https://www.jmlr.org/papers/v9/vandermaaten08a.html)) and its faster cousin **UMAP** ([McInnes, Healy & Melville, 2018](https://arxiv.org/abs/1802.03426)). Both turn distances into neighbour *probabilities* in the high-D space, then arrange points in 2-D so those neighbour relationships match as closely as possible. The picture they produce is the iconic one — tight, well-separated islands of meaning, the plot that launched a thousand papers. We already met it on the last step. It's beautiful. It is also, in a very specific way, a liar — which is the next beat.",
        ],
        ru: [
          'PCA честен, быстр и *линеен* — и последнее слово его потолок. PCA умеет лишь повернуть пространство и сплющить одним прямым разрезом; он предполагает, что структура, которую стоит сохранить, лежит вдоль прямых осей. Часто структура там не лежит. Представь данные в форме рулета — 2-D лист, свёрнутый в 3-D. Две точки на противоположных концах *свёрнутого* листа физически близки в 3-D, но вдоль поверхности — по пути, который реально важен, — они далеки. Сплющь этот рулет одним прямым разрезом PCA — и склеишь дальние концы: катастрофа ложных соседей.',
          'Лечение — перестать сохранять *глобальные* расстояния и сохранять вместо них *окрестности*. Идея, называемая **обучением многообразий**, предполагает, что данные — хоть и вложены в 300-D — на деле лежат на искривлённой поверхности меньшей размерности, *многообразии*, как тот 2-D лист, свёрнутый в 3-D. Нам не важно расстояние по прямой между двумя далёкими словами; нам важно, чтобы каждое слово сохранило *тех же близких соседей* после сгиба. Возьми локальные связи верно, дай глобальной раскладке гнуться как придётся — и разверни завиток, а не режь сквозь него.',
          'Это философия за **t-SNE** ([ван дер Маатен и Хинтон, 2008](https://www.jmlr.org/papers/v9/vandermaaten08a.html)) и его более быстрым родичем **UMAP** ([Макиннес, Хили и Мелвилл, 2018](https://arxiv.org/abs/1802.03426)). Оба превращают расстояния в *вероятности* соседства в высокой размерности, а затем расставляют точки в 2-D так, чтобы эти соседства совпали как можно точнее. Картинка, что они выдают, — та самая знаменитая: плотные, чётко разделённые острова смысла, график, запустивший тысячу статей. Мы уже встретили его на прошлом шаге. Он прекрасен. И ещё он, очень определённым образом, лжец — о чём следующий бит.',
        ],
        tt: [
          'PCA намуслы, тиз һәм *линеар* — һәм соңгы сүз аның түшәме. PCA бары киңлекне борып, аны бер туры кисем белән яссылый ала; ул сакларга кирәкле төзелеш туры күчәрләр буенча ята дип фараз итә. Еш кына төзелеш анда ятмый. Рулет формасындагы мәгълүматны күз алдыңа китер — 3-D’да төрелгән 2-D кәгазь. *Төрелгән* кәгазьнең капма-каршы очларындагы ике нокта 3-D’да физик яктан якын, әмма өслек буенча — чынлап мөһим юл буенча — алар ерак. Бу рулетны бер туры PCA кисеме белән яссыла — һәм ерак очларны ябыштырасың: ялган күршеләр фаҗигасе.',
          'Дәвалау — *глобаль* ераклыкларны саклауны туктатып, аның урынына *тирәләрне* саклау. **Күпьяклык өйрәнү** дип аталган идея, мәгълүмат — 300-D’га салынса да — чынлыкта кечерәк үлчәмле бөгелгән өслектә, *күпьяклыкта*, ята дип фараз итә, шул 3-D аша төрелгән 2-D кәгазь кебек. Безгә ике ерак сүз арасындагы туры сызык ераклыгы кирәкми; безгә һәр сүз бөкләнгәч *шул ук якын күршеләрен* саклавы кирәк. Локаль бәйләнешләрне дөрес ал, глобаль урнашуга ничек туры килсә шулай бөгелергә бир — һәм бөтерелешне аркылы кисмичә җәеп сал.',
          'Бу — **t-SNE** ([ван дер Маатен һәм Хинтон, 2008](https://www.jmlr.org/papers/v9/vandermaaten08a.html)) һәм аның тизрәк туганы **UMAP** ([Макиннес, Хили һәм Мелвилл, 2018](https://arxiv.org/abs/1802.03426)) артындагы фәлсәфә. Икесе дә ераклыкларны югары үлчәмдә күршелек *ихтималлыкларына* әйләндерә, аннары нокталарны 2-D’да шул күршелекләр мөмкин кадәр төгәл туры килерлек итеп урнаштыра. Алар чыгарган рәсем — шул мәшһүре: тыгыз, ачык аерылган мәгънә утраулары, мең мәкаләне җибәргән график. Без аны узган адымда инде очраттык. Ул искиткеч. Һәм ул, бик билгеле бер ысул белән, ялганчы да — бу хакта киләсе бит.',
        ],
      },
    },
    {
      id: 'climb-tsne', kind: 'prose',
      heading: { en: 'The readable picture', ru: 'Читаемая картинка', tt: 'Укылышлы рәсем' },
      body: {
        en: [
          "Let's read the actual t-SNE plot we just built — 44 real words, 50-D GloVe vectors, projected down with perplexity 14. The mechanics, briefly: t-SNE measures, for each word, how probable every other word is as a neighbour under a Gaussian in the high-D space; **perplexity** is the knob that sets roughly *how many* neighbours each point pays attention to — about 14 here. Then in 2-D it uses a heavy-tailed (Student-t) distribution for the same probabilities and shuffles the points until the two sets of neighbour-probabilities agree. The heavy tail is the secret sauce: it gives crowded points room to spread, so the clusters don't collapse into one blob.",
          "And the payoff is plain in the result. The seven groups we planted — **royalty, family, animals, countries, capitals, tech, transport** — pull into seven tight, cleanly separated islands. \"king\", \"queen\", \"prince\", \"throne\", \"crown\" huddle in one corner; \"cat\", \"dog\", \"puppy\", \"kitten\", \"tiger\", \"lion\" in another; \"computer\", \"software\", \"data\", \"algorithm\", \"internet\" off in the tech quarter. The Lexical Gremlin's nightmare made visible: words that *mean* similar things now *sit* together, with no synonym list, no stemming, nothing hand-coded — just the company they keep, learned from raw text and folded onto a page you can read at a glance.",
          "Compare it to the PCA plot from the same data and the difference is instructive. PCA's islands are real but loose and overlapping, because a single linear cut keeping 37.7% of the variance can't pull them fully apart. t-SNE's are crisp and well-spaced, because it bent the layout to honour local neighbourhoods. This is exactly why t-SNE and UMAP are the default tools whenever someone wants to *show* you an embedding space. Which is precisely where the danger lives — because that crisp, convincing picture invites you to read things into it that simply aren't there.",
        ],
        ru: [
          'Прочитаем настоящий t-SNE график, что мы только что построили: 44 реальных слова, 50-мерные GloVe-векторы, спроецированные с перплексией 14. Механика коротко: t-SNE мерит для каждого слова, насколько вероятно каждое другое как сосед под гауссианой в высокой размерности; **перплексия** — ручка, что задаёт примерно *сколько* соседей учитывает каждая точка, около 14 здесь. Затем в 2-D он использует тяжелохвостое (стьюдентово-t) распределение для тех же вероятностей и тасует точки, пока два набора вероятностей соседства не сойдутся. Тяжёлый хвост — секретный ингредиент: он даёт тесным точкам место разойтись, чтобы кластеры не схлопнулись в одно пятно.',
          'И выигрыш виден в результате. Семь групп, что мы заложили, — **сан, семья, животные, страны, столицы, техника, транспорт** — стягиваются в семь плотных, чисто разделённых островов. «king», «queen», «prince», «throne», «crown» жмутся в одном углу; «cat», «dog», «puppy», «kitten», «tiger», «lion» в другом; «computer», «software», «data», «algorithm», «internet» в техническом квартале. Кошмар Лексического Гремлина, ставший видимым: слова, что *значат* похожее, теперь *сидят* вместе — без списка синонимов, без стемминга, без единой ручной строчки, — лишь компания, что они водят, выученная из сырого текста и сложенная на страницу, читаемую с одного взгляда.',
          'Сравни с PCA-графиком по тем же данным — разница поучительна. Острова PCA реальны, но рыхлы и налегают друг на друга, ведь один линейный разрез, хранящий 37.7% дисперсии, не растащит их до конца. У t-SNE они чёткие и хорошо разнесены, ведь он погнул раскладку, чтобы почтить локальные окрестности. Именно поэтому t-SNE и UMAP — инструменты по умолчанию, когда кто-то хочет *показать* тебе пространство эмбеддингов. И ровно здесь живёт опасность — ведь эта чёткая, убедительная картинка приглашает вычитать из неё то, чего там попросту нет.',
        ],
        tt: [
          'Без хәзер генә төзегән чын t-SNE графигын укыйк: 44 чын сүз, 50-үлчәмле GloVe векторлары, перплекслылык 14 белән проекцияләнгән. Механикасы кыскача: t-SNE һәр сүз өчен башка һәр сүзнең күрше булу ихтималлыгын югары үлчәмдә Гаусс буенча үлчи; **перплекслылык** — һәр нокта якынча *ничә* күршене искә алганын куючы тоткыч, монда якынча 14. Аннары 2-D’да ул шул ук ихтималлыклар өчен авыр койрыклы (Стьюдент-t) таралышны куллана һәм ике күршелек ихтималлыклары җыелмасы килешкәнче нокталарны болгата. Авыр койрык — яшерен состав: ул тыгыз нокталарга таралырга урын бирә, кластерлар бер тапка йомылмасын өчен.',
          'Һәм отыш нәтиҗәдә күренеп тора. Без салган җиде төркем — **дәрәҗә, гаилә, хайваннар, илләр, башкалалар, техника, транспорт** — җиде тыгыз, чиста аерылган утрауга җыела. «king», «queen», «prince», «throne», «crown» бер почмакта кысыла; «cat», «dog», «puppy», «kitten», «tiger», «lion» икенчесендә; «computer», «software», «data», «algorithm», «internet» техник кварталда. Лексик Гремлин төше күренгә әйләнде: охшаш нәрсә *аңлаткан* сүзләр хәзер бергә *утыра* — синоним исемлексез, стеммингсыз, бер генә кул язган юлсыз, — бары алар йөрткән иптәш, чи тексттан өйрәнелгән һәм бер карашта укыла торган биткә бөкләнгән.',
          'Шул ук мәгълүматтан PCA графигы белән чагыштыр — аерма гыйбрәтле. PCA утраулары чын, әмма йомшак һәм бер-берсенә керешә, чөнки дисперсиянең 37.7%’ын саклаган бер линеар кисем аларны ахырга кадәр тарта алмый. t-SNE’ныкы ачык һәм яхшы аерылган, чөнки ул урнашуны локаль тирәләрне хөрмәтләр өчен бөкте. Нәкъ шуңа күрә t-SNE һәм UMAP — кемдер сиңа эмбеддинг киңлеген *күрсәтергә* теләгәндә килешү буенча кораллар. Һәм нәкъ менә монда куркыныч яши — чөнки бу ачык, ышандыргыч рәсем синнән анда бөтенләй булмаган нәрсәне укып чыгарырга чакыра.',
        ],
      },
    },
    {
      id: 'catch-tsne-lies', kind: 'prose',
      heading: { en: 'How to misread a t-SNE plot', ru: 'Как неверно прочитать t-SNE', tt: 't-SNE’ны ничек ялгыш уку' },
      img: 'L5/L5-12-tsne-mirage.png', imgPos: 'scene',
      imgAlt: {
        en: 'A t-SNE plot drawn as a mirage: tempting cluster gaps and sizes shimmer like real distances but dissolve on closer look.',
        ru: 't-SNE график как мираж: заманчивые промежутки и размеры кластеров мерцают как настоящие расстояния, но рассеиваются при ближайшем взгляде.',
        tt: 't-SNE графигы сараб булып сызылган: кызыктыргыч кластер бушлыклары һәм зурлыклары чын ераклыклар кебек җемелди, әмма якынрак карагач юкка чыга.',
      },
      imgCaption: {
        en: 'The plot looks like a map with real distances. It isn’t. Gaps, cluster sizes, and positions are a mirage — only “who’s near whom” survives.',
        ru: 'График выглядит как карта с настоящими расстояниями. Это не так. Промежутки, размеры и позиции — мираж; выживает лишь «кто рядом с кем».',
        tt: 'График чын ераклыклы карта кебек күренә. Алай түгел. Бушлыклар, зурлыклар һәм урыннар — сараб; бары «кем кемгә якын» исән кала.',
      },
      body: {
        en: [
          "Here's the trap, and it's the single most important caveat in this whole chapter — call it the Cartographer's warning. A t-SNE plot **is not a map you can measure**. It preserves who's-near-whom and almost nothing else, and three things on it that look meaningful are mirages.",
          "**One: the distances between clusters mean nothing.** If the royalty island sits far from the animals island while countries sits close to capitals, you cannot conclude royalty is \"more different\" from animals than countries is from capitals. t-SNE optimizes *local* neighbourhoods; it makes no promise about the spacing *between* well-separated clusters, and that spacing is largely an accident of the optimization. **Two: cluster sizes mean nothing.** A tight little knot and a big loose blob can hold the same number of equally-similar points — t-SNE inflates sparse regions and shrinks dense ones to keep everything legible. The *area* a cluster takes up is not how spread-out it really is.",
          "**Three: it's not even stable.** Change the **perplexity** — the neighbour-count knob — and the picture reorganizes. Low perplexity shatters the data into many tiny islands; high perplexity merges them into continents; the [Wattenberg, Viégas & Johnson (2016) \"How to Use t-SNE Effectively\"](https://distill.pub/2016/misread-tsne/) interactive shows the *same* data producing wildly different plots as you turn that one dial. Re-run with a new random seed and clusters rotate and drift. So the discipline is strict: read a t-SNE plot for *which points group together*, full stop. Never read distances, never read cluster sizes, never read a single run as ground truth. The picture is a lossy projection presented with the confidence of a photograph — and that confidence is exactly what makes it dangerous.",
        ],
        ru: [
          'Вот ловушка, и это самая важная оговорка во всей главе — назовём её предостережением Картографа. t-SNE график **не карта, которую можно мерить**. Он сохраняет кто-рядом-с-кем и почти ничего больше, а три вещи на нём, что выглядят осмысленными, — миражи.',
          '**Раз: расстояния между кластерами ничего не значат.** Если остров сана далеко от острова животных, а страны близко к столицам, нельзя заключить, что сан «больше отличается» от животных, чем страны от столиц. t-SNE оптимизирует *локальные* окрестности; он ничего не обещает про промежутки *между* хорошо разделёнными кластерами, и эти промежутки во многом случайность оптимизации. **Два: размеры кластеров ничего не значат.** Тугой узелок и большое рыхлое пятно могут держать одинаковое число одинаково-похожих точек — t-SNE раздувает разреженные области и сжимает плотные, чтобы всё осталось читаемым. *Площадь*, что занимает кластер, — не то, насколько он реально разбросан.',
          '**Три: он даже не стабилен.** Смени **перплексию** — ручку числа соседей — и картинка перестроится. Низкая перплексия дробит данные на множество крошечных островов; высокая сливает их в континенты; интерактив [Wattenberg, Viégas & Johnson (2016) «How to Use t-SNE Effectively»](https://distill.pub/2016/misread-tsne/) показывает, как *одни и те же* данные дают дико разные графики, стоит крутнуть этот один регулятор. Перезапусти с новым случайным зерном — и кластеры повернутся и сдвинутся. Поэтому дисциплина строга: читай t-SNE график на предмет *какие точки группируются вместе*, и точка. Никогда не читай расстояния, никогда не читай размеры кластеров, никогда не принимай один запуск за истину. Картинка — это проекция с потерями, поданная с уверенностью фотографии, — и именно эта уверенность делает её опасной.',
        ],
        tt: [
          'Менә тозак, һәм бу — бөтен бүлектәге иң мөһим кисәтү — аны Картограф кисәтүе дип атыйк. t-SNE графигы **үлчәп була торган карта түгел**. Ул кем-кемгә-якын икәнен һәм башка диярлек бернәрсәне саклый, ә анда мәгънәле кебек күренгән өч нәрсә — сараб.',
          '**Беренче: кластерлар арасындагы ераклыклар бернәрсә аңлатмый.** Әгәр дәрәҗә утравы хайваннар утравыннан ерак, ә илләр башкалаларга якын торса, дәрәҗә хайваннардан илләр башкалалардан «күбрәк аерыла» дип нәтиҗә ясап булмый. t-SNE *локаль* тирәләрне оптимизацияли; ул яхшы аерылган кластерлар *арасындагы* бушлык турында бернәрсә вәгъдә итми, һәм бу бушлык күбесенчә оптимизация очраклыгы. **Икенче: кластер зурлыклары бернәрсә аңлатмый.** Тыгыз төенчек һәм зур йомшак тап бертигез санда бертигез охшаш нокта тота ала — t-SNE сирәк өлкәләрне киертә һәм тыгызларны кыса, барысы укылышлы калсын өчен. Кластер алган *мәйдан* — ул чынлыкта күпме таралганы түгел.',
          '**Өченче: ул хәтта тотрыклы да түгел.** **Перплекслылыкны** — күрше санын тоткычны — үзгәрт, һәм рәсем яңадан төзелә. Түбән перплекслылык мәгълүматны күп кенә кечкенә утрауларга вата; югарысы аларны континентларга кушА; [Wattenberg, Viégas & Johnson (2016) «How to Use t-SNE Effectively»](https://distill.pub/2016/misread-tsne/) интерактивы *шул ук* мәгълүматның бу бер тоткычны борсаң бик төрле графиклар бирүен күрсәтә. Яңа очраклы орлык белән кабат җибәр — кластерлар борыла һәм шуыша. Шуңа дисциплина каты: t-SNE графигын *кайсы нокталар бергә төркемләнә* дип укы, шул гына. Беркайчан ераклыкларны укыма, беркайчан кластер зурлыкларын укыма, беркайчан бер җибәрүне хакыйкать итеп алма. Рәсем — фотография ышанычы белән бирелгән югалтулы проекция, — һәм нәкъ менә шул ышаныч аны куркынычлы итә.',
        ],
      },
    },
    {
      id: 'catch-gremlin-cornered', kind: 'prose',
      heading: { en: 'The Gremlin, cornered', ru: 'Гремлин, загнанный в угол', tt: 'Почмакка кысылган Гремлин' },
      body: {
        en: [
          "Step back and look at what we've done to the **Lexical Gremlin**. For three chapters he wedged a brick wall between every pair of words that meant the same thing and were spelled differently — \"couch\" and \"sofa\" scored a flat zero, as far apart as \"couch\" and \"crocodile\". The map breaks his wall. \"couch\" and \"sofa\" now land as neighbours, \"cat\" and \"dog\" sit at cosine 0.922, synonyms cluster, and exact spelling stopped being destiny. He's cornered. For the first time, he's losing.",
          "But — and read this carefully, because it sets up the next chapter — he is **not yet caged**. There's one move he has left, and it's a good one. Our map gives each word *exactly one* vector. One point, one position, forever. Now think about the word \"bank\". It means the side of a river *and* a place that holds money — two genuinely different senses — and our embedding is forced to cram both into a single location. So \"bank\" lands at the hopeless average of \"river\" and \"money\", a smear between two meanings, fully near to neither. \"Apple\" the fruit and \"Apple\" the company; \"python\" the snake and \"python\" the language; \"spring\" the season, the coil, the water source — every one of them collapsed to a single dot.",
          "This is **polysemy**, and it's the Gremlin's last redoubt. A static embedding — word2vec, GloVe, every method in this chapter — assigns one vector per word *type*, blind to the fact that the same string means different things in different sentences. \"I sat on the river bank\" and \"I deposited cash at the bank\" hand the model the identical vector for \"bank\", and it cannot tell them apart. To finish the Gremlin off we'll need a vector that *changes with its context* — a representation where \"bank\" near \"river\" and \"bank\" near \"money\" become different points. That's a contextual embedding, and it's the whole project of the next chapter. The Gremlin is cornered. Caging him is L6.",
        ],
        ru: [
          'Отступи и посмотри, что мы сделали с **Лексическим Гремлином**. Три главы он вставлял кирпичную стену между каждой парой слов, что значат одно, но написаны иначе, — «диван» и «софа» получали ровный ноль, так же далеко, как «диван» и «крокодил». Карта ломает его стену. «диван» и «софа» теперь соседи, «cat» и «dog» сидят на косинусе 0.922, синонимы кластеризуются, и точное написание перестало быть судьбой. Он загнан в угол. Впервые он проигрывает.',
          'Но — читай внимательно, ведь это готовит следующую главу — он **ещё не в клетке**. У него остался один ход, и хороший. Наша карта даёт каждому слову *ровно один* вектор. Одна точка, одна позиция, навсегда. Теперь подумай о слове «bank». Оно значит берег реки *и* место, где держат деньги, — два по-настоящему разных смысла, — а наш эмбеддинг вынужден впихнуть оба в одну точку. Поэтому «bank» оказывается в безнадёжном среднем между «river» и «money», размазанным между двумя значениями, толком не близким ни к одному. «Apple» фрукт и «Apple» компания; «python» змея и «python» язык; «spring» весна, пружина, источник — каждое схлопнуто в одну точку.',
          'Это **полисемия**, и это последний редут Гремлина. Статический эмбеддинг — word2vec, GloVe, каждый метод этой главы — назначает один вектор на *тип* слова, слепой к тому, что одна и та же строка значит разное в разных предложениях. «Я сидел на берегу реки» и «Я внёс наличные в банк» вручают модели одинаковый вектор для «bank», и она не может их различить. Чтобы добить Гремлина, понадобится вектор, что *меняется с контекстом*, — представление, где «bank» рядом с «river» и «bank» рядом с «money» становятся разными точками. Это контекстный эмбеддинг, и это весь замысел следующей главы. Гремлин загнан в угол. Клетка — это L6.',
        ],
        tt: [
          'Бер адым артка чигенеп, без **Лексик Гремлин**га нәрсә эшләгәнне кара. Өч бүлек дәвамында ул бер нәрсә аңлаткан, ләкин башкача язылган һәр сүз пары арасына кирпеч стена кыстырды — «диван» белән «софа» шома ноль алды, «диван» белән «крокодил» кебек ерак. Карта аның стенасын вата. «диван» белән «софа» хәзер күршеләр, «cat» белән «dog» 0.922 косинуста утыра, синонимнар кластерлаша, һәм төгәл язылыш язмыш булудан туктады. Ул почмакка кысылды. Беренче тапкыр ул оттыра.',
          'Әмма — моны игътибар белән укы, чөнки бу киләсе бүлекне әзерли — ул **әле читлектә түгел**. Аның бер йөреше калды, һәм яхшысы. Безнең карта һәр сүзгә *нәкъ бер* вектор бирә. Бер нокта, бер позиция, мәңгегә. Хәзер «bank» сүзе турында уйла. Ул елга ярын *да*, акча тоткан урынны *да* аңлата — чыннан да ике төрле мәгънә, — ә безнең эмбеддинг икесен дә бер урынга кысарга мәҗбүр. Шуңа «bank» «river» белән «money» арасындагы өметсез уртачага эләгә, ике мәгънә арасында ягылган, икесенә дә рәтләп якын түгел. «Apple» җиләк-җимеш һәм «Apple» компания; «python» елан һәм «python» тел; «spring» яз, пружина, чишмә — һәркайсы бер ноктага йомылган.',
          'Бу — **полисемия**, һәм бу Гремлинның соңгы ныгытмасы. Статик эмбеддинг — word2vec, GloVe, бу бүлектәге һәр метод — сүз *төренә* бер вектор билгели, бер үк юл төрле җөмләләрдә төрле нәрсә аңлатканга сукыр. «Мин елга ярында утырдым» һәм «Мин банкка акча салдым» моделгә «bank» өчен бер үк векторны бирә, һәм ул аларны аера алмый. Гремлинны бетерер өчен безгә *контекст белән үзгәрә* торган вектор кирәк булачак — «river» янындагы «bank» белән «money» янындагы «bank» төрле нокталарга әйләнгән күрсәтмә. Бу — контекстлы эмбеддинг, һәм бу — киләсе бүлекнең бөтен максаты. Гремлин почмакка кысылды. Аны читлеккә ябу — L6.',
        ],
      },
    },
    {
      id: 'payoff-map-drawn', kind: 'prose',
      heading: { en: 'The map is drawn', ru: 'Карта нарисована', tt: 'Карта сызылды' },
      img: 'L5/L5-14-map-drawn.png', imgPos: 'hero',
      imgAlt: {
        en: 'The finished Map of Meaning unfurled, with Sir Cosine riding across it, words clustered into labelled islands of meaning.',
        ru: 'Готовая Карта смысла развёрнута, по ней едет Сэр Косинус, слова собраны в подписанные острова смысла.',
        tt: 'Әзер Мәгънә картасы җәелгән, аның буйлап Сэр Косинус бара, сүзләр исемләнгән мәгънә утрауларына җыелган.',
      },
      imgCaption: {
        en: 'Words have coordinates; near means related; Sir Cosine rides the map he can finally measure. The alien, at last, has a place.',
        ru: 'У слов есть координаты; близко значит связано; Сэр Косинус едет по карте, которую наконец может мерить. У инопланетянина наконец есть место.',
        tt: 'Сүзләрнең координаталары бар; якын — бәйле дигән сүз; Сэр Косинус ниһаять үлчи ала торган карта буйлап бара. Чит планеталының ниһаять урыны бар.',
      },
      body: {
        en: [
          "So tally the expedition. We started with symbols that knew no nearness — \"couch\" and \"sofa\" exactly as unrelated as \"couch\" and \"crocodile\". We took Firth's old observation, *a word is known by the company it keeps*, and turned it into machinery: word2vec learning coordinates by predicting neighbours, negative sampling making it fast enough to matter, GloVe reaching the same map by counting. The relations fell out as directions — king to queen the very same arrow as man to woman, the analogy holding at cosine 0.861 on real vectors. Then the Cartographer folded the unseeable 300-D map down to a page: PCA keeping 37.7% of the variance honestly, t-SNE drawing the readable islands, with the strict warning never to over-read them. The **Map of Meaning is drawn**, and **Sir Cosine** — the ruler of nearness we forged back in First Contact — finally has a map worthy of his measure. He rides it from here through the rest of the course.",
          "And the alien? The word it said three chapters ago, the one our index had no slot for, the one that came back `[UNK]` — it finally has a *place*. Not an ID in a dictionary, but a position on the map, surrounded by the words that keep its company, near everything it means and far from everything it doesn't. First Contact is, at last, fully resolved.",
          "Two things travel with us to the next chapter. The map is gorgeous, but it's *static* — one frozen vector per word, and the Gremlin's last trick, \"bank\" with its two meanings crushed into one dot, still stands. And we drew the map; we haven't yet *searched* it at the scale of a billion vectors, which is its own hard problem down the road. The next chapter takes the first one head-on: we give the map **context**, so a word's coordinates can finally shift with the sentence around it — and the Gremlin, cornered here, gets caged for good. Words have coordinates now. Next, we teach them to read the room.",
        ],
        ru: [
          'Подведём итог экспедиции. Мы начали с символов, не знавших близости, — «диван» и «софа» ровно так же не связаны, как «диван» и «крокодил». Мы взяли старое наблюдение Фёрта, *слово узнаётся по компании, что оно водит*, и превратили его в механику: word2vec, учащий координаты предсказанием соседей, негативное сэмплирование, делающее это достаточно быстрым, GloVe, приходящий к той же карте подсчётом. Отношения выпали направлениями — king к queen та же стрелка, что man к woman, аналогия держится на косинусе 0.861 на настоящих векторах. Затем Картограф свернул невидимую 300-мерную карту до страницы: PCA, честно хранящий 37.7% дисперсии, t-SNE, рисующий читаемые острова, со строгим предостережением никогда их не перечитывать. **Карта смысла нарисована**, и у **Сэра Косинуса** — правителя близости, что мы выковали ещё в Первом контакте, — наконец есть карта, достойная его меры. Отсюда он едет по ней до конца курса.',
          'А инопланетянин? Слово, что оно сказало три главы назад, для которого у нашего индекса не было ячейки, что вернулось как `[UNK]`, — у него наконец есть *место*. Не ID в словаре, а позиция на карте, окружённая словами, что водят его компанию, близкая ко всему, что оно значит, и далёкая от всего, чем оно не является. Первый контакт наконец полностью разрешён.',
          'Две вещи едут с нами в следующую главу. Карта роскошна, но *статична* — один замороженный вектор на слово, и последний трюк Гремлина, «bank» с двумя смыслами, раздавленными в одну точку, всё ещё держится. И мы карту нарисовали; мы ещё не *искали* по ней на масштабе миллиарда векторов — это своя трудная задача дальше по дороге. Следующая глава берёт первое в лоб: мы даём карте **контекст**, чтобы координаты слова наконец сдвигались вместе с предложением вокруг, — и Гремлин, загнанный здесь в угол, отправляется в клетку насовсем. Теперь у слов есть координаты. Дальше учим их читать обстановку.',
        ],
        tt: [
          'Экспедицияне санап чыгыйк. Без якынлык белмәгән символлардан башладык — «диван» белән «софа» «диван» белән «крокодил» кебек үк бәйләнешсез. Без Фёртның иске күзәтүен, *сүзне ул йөрткән иптәше буенча белерсең*, алып, аны механикага әйләндердек: күршеләрне алдан әйтеп координаталарны өйрәнгән word2vec, аны мөһим дәрәҗәдә тиз иткән негатив сэмплинг, шул ук картага санап килгән GloVe. Мөнәсәбәтләр юнәлешләр булып килеп чыкты — king’тан queen’гә нәкъ man’нан woman’га булган шул ук ук, аналогия чын векторларда 0.861 косинуста тора. Аннары Картограф күренмәс 300-үлчәмле картаны биткә бөкте: дисперсиянең 37.7%’ын намуслы саклаган PCA, укылышлы утрауларны сызган t-SNE, аларны беркайчан артык укымаска дигән каты кисәтү белән. **Мәгънә картасы сызылды**, һәм **Сэр Косинус**ның — без Беренче контактта ясаган якынлык хакименең — ниһаять үз үлчәвенә лаек картасы бар. Моннан соң ул аның буйлап курсның калган өлешендә бара.',
          'Ә чит планеталы? Ул өч бүлек элек әйткән сүз, безнең индекста оясы булмаган, `[UNK]` булып кайткан сүз — аның ниһаять *урыны* бар. Сүзлектәге ID түгел, ә картадагы позиция, аның иптәшен йөрткән сүзләр белән уратылган, ул аңлаткан барысына якын, ул булмаган барысыннан ерак. Беренче контакт ниһаять тулысынча чишелде.',
          'Ике нәрсә безнең белән киләсе бүлеккә бара. Карта искиткеч, әмма ул *статик* — сүзгә бер катып калган вектор, һәм Гремлинның соңгы хәйләсе, ике мәгънәсе бер ноктага кысылган «bank», әле дә тора. Һәм без картаны сыздык; без аны әле миллиард вектор масштабында *эзләмәдек* — бу үзе алда торган авыр мәсьәлә. Киләсе бүлек беренчесен турыдан ала: без картага **контекст** бирәбез, сүзнең координаталары ниһаять тирәсендәге җөмлә белән шуышсын өчен, — һәм монда почмакка кысылган Гремлин мәңгегә читлеккә эләгә. Хәзер сүзләрнең координаталары бар. Алга таба аларны хәлне укырга өйрәтәбез.',
        ],
      },
    },
  ],
};
