// content/book/l6.js — "The Council of Attention" (L6): contextual embeddings, the Transformer,
// attention, positional encoding, the full encoder block, BERT pooling, and contrastive learning.
// Beats match narrative/L6.md (16, in order). Scrolly widgets: attention-e2e (l6-attention),
// positional-enc (l6-positional), transformer-block (no data), contrastive-space (l6-contrastive).
// Every displayed NUMBER comes from data/l6-attention.json + data/l6-positional.json +
// data/l6-contrastive.json (facts-gate). EN canonical + RU + TT (all written). KaTeX uses \lt/\gt,
// never a literal < or > inside math. Papers cite real links from data/papers.json.

export default {
  id: '06',
  catchphrase: 'The Council of Attention',
  beats: [
    {
      id: 'hook-council', kind: 'prose',
      heading: { en: 'The Council of Attention', ru: 'Совет внимания', tt: 'Игътибар Шурасы' },
      img: 'L6/L6-00-council-of-attention.png', imgPos: 'hero',
      imgAlt: {
        en: 'Serega seated at a round council table where each chair is a word and every councillor leans toward the others it chooses to heed.',
        ru: 'Серёга сидит за круглым столом совета, где каждый стул — это слово, и каждый советник склоняется к тем, кого решает слушать.',
        tt: 'Серёга түгәрәк шура өстәле янында утыра, анда һәр урындык — сүз, һәм һәр киңәшче үзе тыңларга сайлаганнарга таба иелә.',
      },
      imgCaption: {
        en: 'A round table of words. Each councillor leans toward whom it heeds — and the meaning of the meeting is the weighted blend of who listened to whom.',
        ru: 'Круглый стол из слов. Каждый советник склоняется к тому, кого слушает, — и смысл собрания есть взвешенная смесь того, кто кого слушал.',
        tt: 'Сүзләрнең түгәрәк өстәле. Һәр киңәшче үзе тыңлаганга таба иелә — һәм җыелышның мәгънәсе кем кемне тыңлаганның авырлыклы кушылмасы.',
      },
      body: {
        en: [
          "I'm Serega, and last chapter we drew the **Map of Meaning** — gave every word coordinates, watched \"couch\" and \"sofa\" drift into the same neighbourhood, and cornered the **Lexical Gremlin** at last. But we left the room with one move still on his side of the board, and he knows it. The map gives each word *exactly one* vector. One point, forever. And some words refuse to hold still.",
          "Take \"bank\". Say it out loud in two sentences. *\"I sat on the river bank\"* — and *\"I deposited cash at the bank.\"* Same five letters, two genuinely different things, and our static map is forced to cram both into a single dot somewhere in the hopeless middle between \"river\" and \"money\", fully near to neither. The word's meaning isn't a fixed property of the word at all. It's decided, every time, by the *company in the sentence* — by who's sitting next to it at the table.",
          "So picture the sentence as a **council**. Each word is a councillor with a vote, and before any word fixes its meaning it looks around the table and decides *who to heed*. \"bank\" sitting next to \"river\" leans one way; \"bank\" sitting next to \"deposited\" leans the other. The whole chapter is the machinery of that council — a mechanism called **attention**, the engine called the **Transformer**, and the training that finally tunes the room *for search*. The crew has too many voices. Today we learn who to listen to.",
        ],
        ru: [
          'Я Серёга, и в прошлой главе мы нарисовали **Карту смысла** — дали каждому слову координаты, увидели, как «диван» и «софа» сходятся в один район, и наконец загнали **Лексического Гремлина** в угол. Но мы вышли из комнаты, оставив на его стороне доски один ход, и он это знает. Карта даёт каждому слову *ровно один* вектор. Одну точку, навсегда. А некоторые слова отказываются стоять смирно.',
          'Возьми «bank». Скажи его вслух в двух предложениях. *«Я сидел на берегу реки»* — и *«Я внёс наличные в банк».* Те же четыре буквы, две по-настоящему разные вещи, а наша статическая карта вынуждена впихнуть обе в одну точку где-то в безнадёжной середине между «river» и «money», толком не близкую ни к одной. Смысл слова вообще не его фиксированное свойство. Он решается каждый раз *компанией в предложении* — тем, кто сидит рядом с ним за столом.',
          'Так представь предложение как **совет**. Каждое слово — советник с голосом, и прежде чем зафиксировать смысл, оно оглядывает стол и решает, *кого слушать*. «bank» рядом с «river» клонится в одну сторону; «bank» рядом с «deposited» — в другую. Вся глава — это механика того совета: механизм под названием **внимание**, движок под названием **Трансформер** и обучение, что наконец настраивает зал *под поиск*. У команды слишком много голосов. Сегодня мы учимся, кого слушать.',
        ],
        tt: [
          'Мин — Серёга, һәм узган бүлектә без **Мәгънә картасын** сыздык — һәр сүзгә координаталар бирдек, «диван» белән «софа»ның бер районга җыелуын күрдек, һәм ниһаять **Лексик Гремлинны** почмакка кыстык. Әмма без бүлмәдән аның ягында тактада бер йөреш калдырып чыктык, һәм ул моны белә. Карта һәр сүзгә *нәкъ бер* вектор бирә. Бер нокта, мәңгегә. Ә кайбер сүзләр тик торудан баш тарта.',
          '«bank»’ны ал. Аны ике җөмләдә кычкырып әйт. *«Мин елга ярында утырдым»* — һәм *«Мин банкка акча салдым».* Шул ук дүрт хәреф, чыннан да ике төрле нәрсә, ә безнең статик карта икесен дә «river» белән «money» арасындагы өметсез уртага, икесенә дә рәтләп якын булмаган бер ноктага кысарга мәҗбүр. Сүзнең мәгънәсе аның беркетелгән сыйфаты түгел бөтенләй. Ул һәр тапкыр *җөмләдәге иптәш* белән хәл ителә — өстәл янында аның янында кем утырганы белән.',
          'Шуңа җөмләне **шура** итеп күз алдыңа китер. Һәр сүз — тавышлы киңәшче, һәм мәгънәсен беркеткәнче, ул өстәл буйлап карап, *кемне тыңларга* икәнен хәл итә. «river» янындагы «bank» бер якка иелә; «deposited» янындагы «bank» — икенче якка. Бөтен бүлек — шул шураның механикасы: **игътибар** дип аталган механизм, **Трансформер** дип аталган двигатель, һәм залны ниһаять *эзләү өчен* көйли торган өйрәтү. Командада тавышлар артык күп. Бүген без кемне тыңларга икәнен өйрәнәбез.',
        ],
      },
    },
    {
      id: 'problem-one-vector', kind: 'prose',
      heading: { en: 'One word, two minds', ru: 'Одно слово, два ума', tt: 'Бер сүз, ике акыл' },
      img: 'L6/L6-01-bank-two-meanings.png', imgPos: 'scene',
      imgAlt: {
        en: 'The word "bank" pulled in two directions at once — toward a river on one side and a stack of money on the other — stuck at a smeared midpoint.',
        ru: 'Слово «bank» тянет сразу в две стороны — к реке с одной и к стопке денег с другой — застрявшее в размазанной середине.',
        tt: '«bank» сүзе бер үк вакытта ике якка тартыла — бер яктан елгага, икенче яктан акча өеменә — ягылган уртада ябышып калган.',
      },
      imgCaption: {
        en: 'A static embedding gives "bank" one vector — the average of river-bank and money-bank, a smear that is no good for either.',
        ru: 'Статический эмбеддинг даёт «bank» один вектор — среднее берега реки и денежного банка, размазню, не годную ни для того, ни для другого.',
        tt: 'Статик эмбеддинг «bank»’ка бер вектор бирә — елга яры белән акча банкының уртачасы, икесенә дә ярамый торган ягылма.',
      },
      body: {
        en: [
          "Let's make the Gremlin's last move precise, because the whole chapter is built to defeat exactly this. A static embedding — word2vec, GloVe, every method from last chapter — is a fixed lookup table: one row per word *type*, learned once, frozen. \"bank\" maps to a single vector \\(v_{\\text{bank}}\\), end of story. The model trained that vector on every sentence \"bank\" ever appeared in, the riverbanks and the savings banks all averaged together, so \\(v_{\\text{bank}}\\) ends up at a blurry compromise that's a bad description of *both* senses. This is **polysemy**, and a single vector simply cannot hold two meanings at once.",
          "Why does this wreck search specifically? Because retrieval lives or dies on matching *intent*, and intent is carried by context. A query \"river bank erosion\" and a document about \"central bank interest rates\" share the token \"bank\" — and with a static embedding their \"bank\" vectors are *identical*, nudging the two toward a false match. The thing that should disambiguate them — the surrounding words — is exactly the thing a per-type vector throws away. \"apple\" the fruit vs \"Apple\" the company; \"python\" the snake vs \"python\" the language; \"jaguar\" the cat vs the car: every one of them is a landmine in a search index built on frozen vectors.",
          "So the fix writes itself, even if building it is the hard part. We need an embedding that is **not a property of the word, but a function of the word *in its sentence*** — a vector for \"bank\" that comes out *different* when \"river\" is nearby than when \"deposited\" is. A vector computed fresh, on the spot, from the company the word is actually keeping right now. That is a **contextual embedding**, and producing one is the job of the machine we spend this chapter building. The static map was a phone book; we're about to make it read the room.",
        ],
        ru: [
          'Сделаем последний ход Гремлина точным, ведь вся глава построена, чтобы победить именно его. Статический эмбеддинг — word2vec, GloVe, каждый метод прошлой главы — это фиксированная таблица: одна строка на *тип* слова, выучена однажды, заморожена. «bank» отображается в единственный вектор \\(v_{\\text{bank}}\\), и точка. Модель учила этот вектор на всех предложениях, где когда-либо встречалось «bank», — берега рек и сберегательные банки усреднены вместе, — поэтому \\(v_{\\text{bank}}\\) оказывается размытым компромиссом, плохо описывающим *оба* смысла. Это **полисемия**, и один вектор просто не может держать два значения сразу.',
          'Почему это калечит именно поиск? Потому что поиск держится на сопоставлении *намерения*, а намерение несёт контекст. Запрос «эрозия берега реки» и документ про «процентные ставки центрального банка» делят токен «bank» — и со статическим эмбеддингом их векторы «bank» *идентичны*, толкая эту пару к ложному совпадению. То, что должно их различать, — окружающие слова — ровно то, что вектор-на-тип выбрасывает. «apple» фрукт против «Apple» компании; «python» змея против «python» языка; «jaguar» кошка против машины: каждое — мина в поисковом индексе на замороженных векторах.',
          'Так что лечение пишет себя само, даже если построить его — самое трудное. Нужен эмбеддинг, что **не свойство слова, а функция слова *в его предложении*** — вектор для «bank», что выходит *разным*, когда рядом «river», и когда рядом «deposited». Вектор, вычисленный заново, на месте, из компании, что слово реально водит прямо сейчас. Это **контекстный эмбеддинг**, и его производство — работа машины, что мы строим всю главу. Статическая карта была телефонной книгой; сейчас мы научим её читать обстановку.',
        ],
        tt: [
          'Гремлинның соңгы йөрешен төгәл итик, чөнки бөтен бүлек нәкъ шуны җиңәр өчен корылган. Статик эмбеддинг — word2vec, GloVe, узган бүлектәге һәр метод — беркетелгән таблица: сүз *төренә* бер юл, бер тапкыр өйрәнелгән, катып калган. «bank» бердәнбер \\(v_{\\text{bank}}\\) векторына чагыла, шул гына. Модель бу векторны «bank» очраган барлык җөмләләрдә өйрәтте — елга ярлары һәм җыем банклары бергә уртачаланган, — шуңа \\(v_{\\text{bank}}\\) *ике* мәгънәне дә начар тасвирлаган томанлы килешүгә әйләнә. Бу — **полисемия**, һәм бер вектор ике мәгънәне берьюлы тота алмый.',
          'Ни өчен бу нәкъ эзләүне имгәтә? Чөнки эзләү *ниятне* туры китерүгә таяна, ә ниятне контекст йөртә. «елга яры эрозиясе» соравы һәм «үзәк банк процент ставкалары» турындагы документ «bank» токенын уртаклаша — һәм статик эмбеддинг белән аларның «bank» векторлары *бертөрле*, бу парны ялган туры килүгә этәрә. Аларны аерырга тиешле нәрсә — тирәдәге сүзләр — нәкъ менә төргә-вектор ташлый торган нәрсә. «apple» җиләк-җимеш «Apple» компаниягә каршы; «python» елан «python» телгә каршы; «jaguar» мәче машинага каршы: һәркайсы — катып калган векторларга корылган эзләү индексындагы мина.',
          'Шуңа дәвалау үзен үзе яза, аны төзү иң авыры булса да. Безгә **сүзнең сыйфаты түгел, ә *җөмләсендәге* сүзнең функциясе** булган эмбеддинг кирәк — «river» янәшә булганда «deposited» янәшә булганнан *башка* килеп чыга торган «bank» векторы. Сүз нәкъ хәзер чынлап йөрткән иптәшеннән, урынында, яңадан исәпләнгән вектор. Бу — **контекстлы эмбеддинг**, һәм аны җитештерү — без бөтен бүлек дәвамында корган машинаның эше. Статик карта телефон китабы иде; хәзер без аны хәлне укырга өйрәтәбез.',
        ],
      },
    },
    {
      id: 'turn-contextual', kind: 'prose',
      heading: { en: 'A vector per context', ru: 'Вектор на контекст', tt: 'Контекстка вектор' },
      body: {
        en: [
          "Here's the shift in one sentence: stop asking *\"what does this word mean?\"* and start asking *\"what does this word mean **here**?\"* A contextual embedding is a vector produced for a specific *occurrence* of a word — \"bank\" in *this* sentence, at *this* position — not for the word in the abstract. Feed the model \"I sat on the river bank\" and it returns a \"bank\" vector that has drifted toward the water; feed it \"I deposited cash at the bank\" and the same input token comes back pointing at money. One word type, as many vectors as it has contexts.",
          "It is worth pausing on how strong a claim that is. The static map had a fixed vocabulary of frozen points; the contextual model has *no fixed vector for \"bank\" at all*. It has a **process** that, given a sentence, computes a vector for every token on the fly, each one shaped by all the others. The vocabulary lookup is still there at the very bottom — \"bank\" still starts as some initial embedding — but that's just the raw clay. The output is sculpted by context before you ever see it.",
          "And it pays off precisely where the Gremlin lives. \"couch\" and \"sofa\" in similar sentences now produce nearly identical contextual vectors — synonymy handled. \"bank\" in two different sentences now produces two well-separated vectors — polysemy handled, the move that static embeddings couldn't make. The only question left is the mechanism: *how* does a model let every token's vector depend on every other token in the sentence? The answer is the central idea of modern NLP, and it is shockingly simple. It's called attention.",
        ],
        ru: [
          'Вот сдвиг в одном предложении: перестань спрашивать *«что значит это слово?»* и начни спрашивать *«что значит это слово **здесь**?»* Контекстный эмбеддинг — это вектор, произведённый для конкретного *вхождения* слова: «bank» в *этом* предложении, на *этой* позиции, — а не для слова в абстракции. Скорми модели «Я сидел на берегу реки», и она вернёт вектор «bank», уплывший к воде; скорми «Я внёс наличные в банк», и тот же входной токен вернётся, указывая на деньги. Один тип слова — столько векторов, сколько у него контекстов.',
          'Стоит задержаться на том, насколько это сильное утверждение. У статической карты был фиксированный словарь замороженных точек; у контекстной модели *вообще нет фиксированного вектора для «bank»*. У неё есть **процесс**, что по предложению вычисляет вектор для каждого токена на лету, и каждый формируется всеми остальными. Поиск по словарю всё ещё есть в самом низу — «bank» по-прежнему стартует как некий начальный эмбеддинг, — но это лишь сырая глина. Выход вылеплен контекстом ещё до того, как ты его увидишь.',
          'И это окупается ровно там, где живёт Гремлин. «диван» и «софа» в похожих предложениях теперь дают почти одинаковые контекстные векторы — синонимия решена. «bank» в двух разных предложениях теперь даёт два хорошо разделённых вектора — полисемия решена, тот ход, что статическим эмбеддингам был не по силам. Остался один вопрос — механизм: *как* модель позволяет вектору каждого токена зависеть от каждого другого токена в предложении? Ответ — центральная идея современного NLP, и он поразительно прост. Он называется вниманием.',
        ],
        tt: [
          'Менә үзгәреш бер җөмләдә: *«бу сүз нәрсә аңлата?»* дип сораудан туктап, *«бу сүз **монда** нәрсә аңлата?»* дип сорый башла. Контекстлы эмбеддинг — сүзнең конкрет *очравы* өчен җитештерелгән вектор: *бу* җөмләдәге, *бу* позициядәге «bank», — абстракттагы сүз өчен түгел. Моделгә «Мин елга ярында утырдым»’ны бир, ул суга таба шуышкан «bank» векторын кайтарыр; «Мин банкка акча салдым»’ны бир, шул ук керем токены акчага күрсәтеп кайтыр. Бер сүз төре — никадәр контексты булса, шулкадәр вектор.',
          'Бу никадәр көчле дәгъва икәнен карап торырга кирәк. Статик картада катып калган нокталарның беркетелгән сүзлеге бар иде; контекстлы модельнең *«bank» өчен беркетелгән векторы бөтенләй юк*. Аның **процессы** бар: җөмлә бирелгәч, ул һәр токен өчен векторны очышта исәпли, һәркайсы калганнар белән формалаша. Сүзлек эзләве әле дә иң аста бар — «bank» һаман берәр башлангыч эмбеддинг булып старт ала, — әмма бу бары чи балчык. Чыгыш син аны күргәнче үк контекст белән сыкланган.',
          'Һәм бу нәкъ Гремлин яшәгән җирдә файда китерә. Охшаш җөмләләрдәге «диван» белән «софа» хәзер диярлек бертөрле контекст векторлары бирә — синонимия чишелде. Ике төрле җөмләдәге «bank» хәзер яхшы аерылган ике вектор бирә — полисемия чишелде, статик эмбеддинглар эшли алмаган йөреш. Бер генә сорау калды — механизм: модель һәр токен векторын җөмләдәге һәр башка токенга бәйле итеп *ничек* эшли? Җавап — заманча NLP’ның үзәк идеясе, һәм ул гаҗәп гади. Ул игътибар дип атала.',
        ],
      },
    },
    {
      id: 'turn-attention', kind: 'prose',
      heading: { en: 'Let each token attend', ru: 'Пусть каждый токен внимает', tt: 'Һәр токен игътибар итсен' },
      body: {
        en: [
          "The attention idea, stripped to its bones: **a token's new meaning is a weighted blend of all the tokens in the sentence — including itself.** That's it. To compute the contextual vector for \"bank\", we don't reach for a fixed lookup; we look at every other word in the sentence, decide how *relevant* each one is to \"bank\" right now, and mix their vectors together in proportion to that relevance. \"river\" gets a big weight, \"the\" gets almost none, and the blend that comes out *is* \"bank\"-in-this-sentence.",
          "Go back to the council. Each councillor, before speaking, polls the whole table: *how much should I weight what each of you is saying?* A word answers that poll with a set of weights — one per token — that are all positive and sum to one, a little probability distribution over \"who I'm listening to\". Then its new representation is just the weighted average of everyone's contribution under those weights. \"bank\" next to \"river\" pours most of its attention onto \"river\" and \"sat\", and barely any onto \"I\" or \"the\"; the resulting blend leans watery. \"bank\" next to \"deposited\" pours its attention elsewhere, and the blend leans monetary. Same machinery, different neighbours, different meaning out.",
          "Two things make this the right idea and not just a nice metaphor. First, it's **content-based**: the weights come from how well words *match*, not from fixed positions, so the model decides what's relevant on a case-by-case basis. Second, every token does this **in parallel** and **for itself** — forty tokens, forty simultaneous polls of the same table, forty contextual vectors out in one shot. The only thing left to specify is *how* a word decides how much to heed each neighbour. That calculation — turning a table of words into a table of weights and then into a blend — is **scaled dot-product attention**, and we'll now walk through it on real numbers, every step.",
        ],
        ru: [
          'Идея внимания, ободранная до костей: **новый смысл токена — взвешенная смесь всех токенов предложения, включая себя.** Вот и всё. Чтобы вычислить контекстный вектор «bank», мы не тянемся к фиксированному поиску; мы смотрим на каждое другое слово предложения, решаем, насколько каждое сейчас *релевантно* «bank», и смешиваем их векторы пропорционально этой релевантности. «river» получает большой вес, «the» — почти нулевой, и смесь на выходе *и есть* «bank»-в-этом-предложении.',
          'Вернись к совету. Каждый советник перед тем, как говорить, опрашивает весь стол: *насколько мне взвесить то, что говорит каждый из вас?* Слово отвечает на этот опрос набором весов — по одному на токен, — все положительные и в сумме единица, маленькое распределение вероятностей над «кого я слушаю». Тогда его новое представление — просто взвешенное среднее вкладов всех под этими весами. «bank» рядом с «river» льёт большую часть внимания на «river» и «sat» и почти ничего на «I» или «the»; итоговая смесь клонится к воде. «bank» рядом с «deposited» льёт внимание иначе, и смесь клонится к деньгам. Та же механика, другие соседи, другой смысл на выходе.',
          'Две вещи делают это правильной идеей, а не просто красивой метафорой. Первое: оно **на основе содержания** — веса берутся из того, насколько слова *совпадают*, а не из фиксированных позиций, так что модель решает, что релевантно, в каждом случае заново. Второе: каждый токен делает это **параллельно** и **для себя** — сорок токенов, сорок одновременных опросов того же стола, сорок контекстных векторов на выходе разом. Осталось задать одно — *как* слово решает, сколько слушать каждого соседа. Этот расчёт — превращение таблицы слов в таблицу весов, а затем в смесь — называется **масштабированным скалярным вниманием**, и мы сейчас пройдём его по настоящим числам, каждый шаг.',
        ],
        tt: [
          'Игътибар идеясе, сөягенә кадәр чистартылган: **токенның яңа мәгънәсе — җөмләдәге барлык токеннарның, үзен дә кертеп, авырлыклы кушылмасы.** Шул гына. «bank» өчен контекст векторын исәпләр өчен, без беркетелгән эзләүгә үрелмибез; без җөмләдәге һәр башка сүзгә карыйбыз, һәркайсы хәзер «bank»’ка никадәр *кагылышлы* икәнен хәл итәбез, һәм аларның векторларын шул кагылышлылыкка пропорциональ кушабыз. «river» зур авырлык ала, «the» — диярлек нуль, һәм чыгыштагы кушылма *үзе* — бу җөмләдәге «bank».',
          'Шурага кайт. Һәр киңәшче, сөйләр алдыннан, бөтен өстәлне сораштыра: *сезнең һәрберегез әйткәнне ничек авырлыкларга миңа?* Сүз бу сораштыруга авырлыклар җыелмасы белән җавап бирә — токенга берәр, — барысы уңай һәм суммасы бер, «мин кемне тыңлыйм» өстендәге кечкенә ихтималлык таралышы. Аннары аның яңа күрсәтмәсе — шул авырлыклар буенча барысының өлешенең авырлыклы уртачасы гына. «river» янындагы «bank» игътибарының күп өлешен «river» белән «sat»’ка коя, «I» яки «the»’гә диярлек юк; нәтиҗәдәге кушылма суга иелә. «deposited» янындагы «bank» игътибарын башкача коя, кушылма акчага иелә. Шул ук механика, башка күршеләр, башка мәгънә чыга.',
          'Ике нәрсә моны дөрес идея итә, бары матур метафора гына түгел. Беренче: ул **эчтәлеккә нигезләнгән** — авырлыклар сүзләрнең ничек *туры килгәненнән* килә, беркетелгән позицияләрдән түгел, шуңа модель нәрсә кагылышлы икәнен һәр очракта яңадан хәл итә. Икенче: һәр токен моны **параллель** һәм **үзе өчен** эшли — кырык токен, шул ук өстәлнең кырык бер үк вакытлы сораштыруы, кырык контекст векторы берьюлы чыга. Бер генә нәрсә калды — сүз һәр күршене никадәр тыңларга икәнен *ничек* хәл итә. Бу исәп — сүзләр таблицасын авырлыклар таблицасына, аннары кушылмага әйләндерү — **масштаблы скаляр игътибар** дип атала, һәм без аны хәзер чын саннарда, һәр адымны, үтәрбез.',
        ],
      },
    },
    { id: 'climb-attention', kind: 'scrolly', widget: 'attention-e2e', data: 'l6-attention' },
    {
      id: 'turn-selfattention', kind: 'prose',
      heading: { en: 'Self-attention: querying yourself', ru: 'Само-внимание: запрос к себе', tt: 'Үз-игътибар: үзеңә сорау' },
      body: {
        en: [
          "Let's name what we just did. Each token produced three vectors from its own embedding by multiplying it through three learned weight matrices: a **query** \\(q\\) (\"what am I looking for?\"), a **key** \\(k\\) (\"what do I offer to others?\"), and a **value** \\(v\\) (\"what do I actually contribute if attended to?\"). A token's query is dotted against *every* token's key to score relevance; those scores are scaled and softmaxed into weights; and the weights mix *every* token's value. Query, key, value — three roles every word plays at once.",
          "The crucial word in this chapter's title is **self**. In the worked example, \\(Q\\), \\(K\\), and \\(V\\) all came from the *same three tokens* — \"the\", \"cat\", \"sat\". Every token queried the same sequence it belongs to, itself included. That's **self-attention**: a sentence attending to itself, each word rebuilt from a blend of its sentence-mates. (Contrast it with *cross*-attention, where queries come from one sequence and keys/values from another — that's how a translation decoder peeks at the source sentence; we'll meet it later. Here, source and target are one and the same sequence.)",
          "Notice what self-attention bought us, concretely, in the numbers you just scrolled. The output row for \"cat\" was not \"cat\"'s original embedding — it was a *new* vector, \\((0.579,\\ 1.996,\\ 0.910,\\ 0.425)\\), built mostly (weight \\(0.665\\)) from \"cat\"'s own value but with real contributions from \"the\" and \"sat\". \"cat\" walked into the layer as a context-free embedding and walked out *contextualized* — its meaning now reflects the sentence it sits in. Do this, and the Gremlin's polysemy trick is broken: \"bank\" near \"river\" and \"bank\" near \"money\" leave the layer as different vectors, because they attended to different neighbours. One layer of self-attention is the whole engine of context. Stack a few, and you have a Transformer.",
        ],
        ru: [
          'Назовём то, что мы только что сделали. Каждый токен произвёл из своего эмбеддинга три вектора, прогнав его через три обучаемые весовые матрицы: **запрос** \\(q\\) («что я ищу?»), **ключ** \\(k\\) («что я предлагаю другим?») и **значение** \\(v\\) («что я реально вношу, если меня слушают?»). Запрос токена скалярно умножается на ключ *каждого* токена для оценки релевантности; эти оценки масштабируются и через softmax превращаются в веса; и веса смешивают значение *каждого* токена. Запрос, ключ, значение — три роли, что каждое слово играет разом.',
          'Ключевое слово в названии главы — **само**. В разобранном примере \\(Q\\), \\(K\\) и \\(V\\) все пришли из *тех же трёх токенов* — «the», «cat», «sat». Каждый токен запрашивал ту же последовательность, которой принадлежит, себя включая. Это **само-внимание**: предложение, внимающее себе, каждое слово перестроено из смеси соседей по предложению. (Сравни с *кросс*-вниманием, где запросы из одной последовательности, а ключи/значения из другой, — так декодер перевода подсматривает в исходное предложение; встретим позже. Здесь источник и цель — одна и та же последовательность.)',
          'Заметь, что само-внимание купило нам конкретно — в числах, что ты только что пролистал. Строка выхода для «cat» — не исходный эмбеддинг «cat», а *новый* вектор \\((0.579,\\ 1.996,\\ 0.910,\\ 0.425)\\), построенный в основном (вес \\(0.665\\)) из собственного значения «cat», но с реальными вкладами «the» и «sat». «cat» вошёл в слой как бесконтекстный эмбеддинг и вышел *контекстуализированным* — его смысл теперь отражает предложение, в котором он сидит. Сделай так — и трюк полисемии Гремлина сломан: «bank» рядом с «river» и «bank» рядом с «money» выходят из слоя разными векторами, ведь они внимали разным соседям. Один слой само-внимания — весь движок контекста. Сложи несколько — и у тебя Трансформер.',
        ],
        tt: [
          'Хәзер генә эшләгәнне атыйк. Һәр токен үз эмбеддингыннан өч өйрәнелгән авырлык матрицасы аша уздырып өч вектор җитештерде: **сорау** \\(q\\) («мин нәрсә эзлим?»), **ачкыч** \\(k\\) («мин башкаларга нәрсә тәкъдим итәм?») һәм **кыйммәт** \\(v\\) («мине тыңласалар, мин чынлап нәрсә кертәм?»). Токенның сораулары *һәр* токенның ачкычына кагылышлылыкны бәяләр өчен скаляр тапкырлана; бу бәяләр масштаблана һәм softmax аша авырлыкларга әйләнә; һәм авырлыклар *һәр* токенның кыйммәтен кушА. Сорау, ачкыч, кыйммәт — һәр сүз берьюлы уйнаган өч роль.',
          'Бүлек исемендәге төп сүз — **үз**. Карап чыккан мисалда \\(Q\\), \\(K\\) һәм \\(V\\) барысы да *шул ук өч токеннан* — «the», «cat», «sat»’тан килде. Һәр токен үзе кергән шул ук эзлеклелекне, үзен дә кертеп, сораштырды. Бу — **үз-игътибар**: үзенә игътибар иткән җөмлә, һәр сүз җөмләдәшләре кушылмасыннан яңадан корылган. (Аны *кросс*-игътибар белән чагыштыр, анда сораулар бер эзлеклелектән, ачкыч/кыйммәтләр икенчесеннән, — тәрҗемә декодеры чыганак җөмләгә шулай күз ташлый; соңрак очратырбыз. Монда чыганак белән максат — бер үк эзлеклелек.)',
          'Үз-игътибар безгә конкрет нәрсә алып бирде — син хәзер генә шудырган саннарда. «cat» өчен чыгыш юлы «cat»’ның башлангыч эмбеддингы түгел, ә *яңа* вектор \\((0.579,\\ 1.996,\\ 0.910,\\ 0.425)\\), нигездә (авырлык \\(0.665\\)) «cat»’ның үз кыйммәтеннән корылган, әмма «the» белән «sat»’ның чын өлешләре белән. «cat» катламга контекстсыз эмбеддинг булып керде һәм *контекстлашкан* булып чыкты — аның мәгънәсе хәзер ул кергән җөмләне чагылдыра. Шулай эшлә — һәм Гремлинның полисемия хәйләсе сынды: «river» янындагы «bank» белән «money» янындагы «bank» катламнан төрле векторлар булып чыга, чөнки алар төрле күршеләргә игътибар итте. Үз-игътибарның бер катламы — контекстның бөтен двигателе. Берничәне өем — синдә Трансформер.',
        ],
      },
    },
    {
      id: 'climb-multihead', kind: 'prose',
      heading: { en: 'Many heads, many councils', ru: 'Много голов, много советов', tt: 'Күп баш, күп шура' },
      img: 'L6/L6-04-attention-weights.png', imgPos: 'scene',
      imgAlt: {
        en: 'Several attention-weight heatmaps side by side, each a different grid of who-attends-to-whom, fanned out as parallel councils.',
        ru: 'Несколько тепловых карт весов внимания рядом, каждая — своя сетка кто-кому-внимает, развёрнутые как параллельные советы.',
        tt: 'Берничә игътибар авырлыгы җылылык картасы янәшә, һәркайсы — кем-кемгә-игътибар-итә дигән үз челтәре, параллель шуралар булып җәелгән.',
      },
      imgCaption: {
        en: 'One head can only vote one way at a time. Run several in parallel — each its own Q/K/V — and the council can track syntax, coreference, and topic at once.',
        ru: 'Одна голова может голосовать лишь одним способом за раз. Запусти несколько параллельно — у каждой свои Q/K/V — и совет отслеживает синтаксис, кореференцию и тему сразу.',
        tt: 'Бер баш бер юлы бер генә төрле тавыш бирә ала. Берничәне параллель җибәр — һәркайсының үз Q/K/V — һәм шура синтаксисны, кореференцияне, теманы берьюлы күзәтә.',
      },
      body: {
        en: [
          "One round of self-attention has a quiet limitation: it produces *one* set of weights per token, so it can only express *one* notion of relevance at a time. But \"bank\" cares about its neighbours in several different ways at once — which word is its grammatical subject, which adjective modifies it, which earlier noun it refers back to. A single attention head, forced to average all of those into one weighting, blurs them together. So the Transformer runs **several heads in parallel**, and that is **multi-head attention**.",
          "Mechanically it's the same recipe, replicated. With \\(h\\) heads (the original Transformer used \\(h = 8\\); our worked example carried \\(2\\)), the model holds \\(h\\) independent sets of query/key/value matrices. Each head projects the tokens into its *own* lower-dimensional subspace, runs the full \\(\\mathrm{softmax}(QK^\\top/\\sqrt{d_k})V\\) there, and produces its own contextual blend. Crucially, because each head has its own learned projections, each one is free to specialize — head 1 can learn to track the subject-verb link, head 2 the adjective it modifies, head 3 long-range coreference — and they don't interfere, because they live in separate subspaces.",
          "Then you reassemble. The \\(h\\) per-head outputs are **concatenated** back into one wide vector and passed through a final learned projection matrix \\(W^O\\) that mixes the heads and returns to the model's working dimension: $$\\mathrm{MultiHead}(Q,K,V) = \\mathrm{Concat}(\\text{head}_1,\\dots,\\text{head}_h)\\,W^O.$$ In council terms: instead of one meeting, you convene several simultaneous sub-councils, each weighing the room by a different concern, and then a chair (\\(W^O\\)) blends their conclusions into one verdict. The cost is modest — splitting the dimension across heads keeps the total compute about the same — and the payoff is a representation that captures many *kinds* of relationship at once. That richer blend is what gets stacked into a Transformer.",
        ],
        ru: [
          'У одного раунда само-внимания тихое ограничение: он даёт *один* набор весов на токен, то есть может выразить лишь *одно* понятие релевантности за раз. Но «bank» заботят соседи сразу несколькими способами — какое слово его грамматический субъект, какое прилагательное его определяет, на какое раннее существительное он ссылается. Одна голова внимания, вынужденная усреднить всё это в один вес, смазывает их вместе. Поэтому Трансформер запускает **несколько голов параллельно** — это **многоголовое внимание**.',
          'Механически это тот же рецепт, размноженный. С \\(h\\) головами (исходный Трансформер брал \\(h = 8\\); наш пример нёс \\(2\\)) модель держит \\(h\\) независимых наборов матриц запрос/ключ/значение. Каждая голова проецирует токены в *своё* подпространство меньшей размерности, прогоняет там полный \\(\\mathrm{softmax}(QK^\\top/\\sqrt{d_k})V\\) и выдаёт свою контекстную смесь. Важно: раз у каждой головы свои обучаемые проекции, каждая вольна специализироваться — голова 1 учит связь субъект-глагол, голова 2 определяющее прилагательное, голова 3 дальнюю кореференцию, — и они не мешают друг другу, ведь живут в разных подпространствах.',
          'Затем собираешь обратно. \\(h\\) выходов голов **конкатенируются** в один широкий вектор и проходят через финальную обучаемую матрицу проекции \\(W^O\\), что смешивает головы и возвращает к рабочей размерности модели: $$\\mathrm{MultiHead}(Q,K,V) = \\mathrm{Concat}(\\text{head}_1,\\dots,\\text{head}_h)\\,W^O.$$ На языке совета: вместо одного собрания ты созываешь несколько одновременных под-советов, каждый взвешивает зал по своей заботе, а потом председатель (\\(W^O\\)) сводит их выводы в один вердикт. Цена скромна — деление размерности по головам держит суммарные вычисления примерно теми же, — а выигрыш в том, что представление схватывает много *видов* связи сразу. Эту более богатую смесь и складывают в Трансформер.',
        ],
        tt: [
          'Үз-игътибарның бер раундында тын чикләү бар: ул токенга *бер* авырлыклар җыелмасы бирә, димәк бер юлы *бер* генә кагылышлылык төшенчәсен белдерә ала. Әмма «bank»’ны күршеләре берьюлы берничә төрле кызыксындыра — кайсы сүз аның грамматик субъекты, кайсы сыйфат аны билгели, кайсы алдагы исемгә ул сылтана. Барысын бер авырлыкка уртачаларга мәҗбүр булган бер игътибар башы аларны бергә ягылдыра. Шуңа Трансформер **берничә башны параллель** җибәрә — бу **күпбашлы игътибар**.',
          'Механик яктан бу шул ук рецепт, күбәйтелгән. \\(h\\) баш белән (башлангыч Трансформер \\(h = 8\\) алды; безнең мисал \\(2\\) йөртте) модель сорау/ачкыч/кыйммәт матрицаларының \\(h\\) бәйсез җыелмасын тота. Һәр баш токеннарны *үз* кечерәк үлчәмле асокеңлегенә проекцияли, анда тулы \\(\\mathrm{softmax}(QK^\\top/\\sqrt{d_k})V\\) җибәрә һәм үз контекст кушылмасын бирә. Мөһиме: һәр башның үз өйрәнелгән проекцияләре булганга, һәркайсы белгечләшә ала — баш 1 субъект-фигыль бәйләнешен өйрәнә, баш 2 билгеләүче сыйфатны, баш 3 ерак кореференцияне, — һәм алар бер-берсенә комачауламый, чөнки төрле асокеңлектә яши.',
          'Аннары кире җыясың. Башларның \\(h\\) чыгышы бер киң векторга **конкатенацияләнә** һәм башларны кушкан, модельнең эш үлчәменә кайтарган соңгы өйрәнелгән проекция матрицасы \\(W^O\\) аша уза: $$\\mathrm{MultiHead}(Q,K,V) = \\mathrm{Concat}(\\text{head}_1,\\dots,\\text{head}_h)\\,W^O.$$ Шура телендә: бер җыелыш урынына син берничә бер үк вакытлы аша-шура чакырасың, һәркайсы залны үз кайгысы буенча авырлыклый, аннары рәис (\\(W^O\\)) аларның нәтиҗәләрен бер карарга җыя. Бәясе аз — үлчәмне башлар буенча бүлү гомуми исәпләүне якынча шул ук кала, — ә отышы шунда: күрсәтмә берьюлы бәйләнешнең күп *төрен* эләктерә. Шул баерак кушылма Трансформерга өелә.',
        ],
      },
    },
    {
      id: 'turn-positional', kind: 'prose',
      heading: { en: 'Attention is order-blind', ru: 'Внимание слепо к порядку', tt: 'Игътибар тәртипкә сукыр' },
      body: {
        en: [
          "Now a flaw, and it's a fundamental one. Look again at how attention works: every token's query is dotted against every token's key, the weights are softmaxed, the values are blended. Nowhere in that computation does the *order* of the tokens enter. Shuffle the words in the sentence and feed them in a different order, and — apart from the labels moving with them — the math produces the exact same set of blends. Self-attention is **permutation-invariant**: to it, a sentence is a *bag* of tokens, not a sequence.",
          "That is a catastrophe for language, where order *is* meaning. \"dog bites man\" and \"man bites dog\" contain the identical multiset of words; only the order distinguishes a normal Tuesday from front-page news. \"The cat sat on the mat\" and \"The mat sat on the cat\" — same bag, very different scenes. A model that genuinely cannot see order would treat all of these as interchangeable, which makes it useless for anything beyond keyword soup. The very property that lets attention process all tokens in parallel — treating them as an unordered set — is the property that blinds it to sequence.",
          "So we have to *put the order back in by hand*. Since the attention mechanism itself won't look at position, we inject position into the **input vectors** before attention ever runs: we add, to each token's embedding, a special vector that depends only on *where* the token sits — first, second, seventeenth. Now \"cat\" in position 3 and \"cat\" in position 8 arrive at the attention layer as slightly different vectors, and the model can finally tell where each word is. The question is what those position vectors should be — and the original Transformer's answer is a beautiful little trick with sines and cosines, which we'll see next, exact.",
        ],
        ru: [
          'Теперь изъян, и он фундаментальный. Посмотри ещё раз, как работает внимание: запрос каждого токена скалярно умножается на ключ каждого, веса через softmax, значения смешиваются. Нигде в этом расчёте не входит *порядок* токенов. Перемешай слова предложения и подай в другом порядке — и, если не считать ярлыков, едущих с ними, математика выдаст ровно тот же набор смесей. Само-внимание **инвариантно к перестановке**: для него предложение — это *мешок* токенов, а не последовательность.',
          'Для языка, где порядок *и есть* смысл, это катастрофа. «собака кусает человека» и «человек кусает собаку» содержат идентичный мультимножество слов; только порядок отличает обычный вторник от передовицы. «Кот сел на коврик» и «Коврик сел на кота» — тот же мешок, очень разные сцены. Модель, что вправду не видит порядка, считала бы всё это взаимозаменяемым, а значит, бесполезна для чего угодно сверх супа из ключевых слов. То самое свойство, что позволяет вниманию обрабатывать все токены параллельно — обращаясь с ними как с неупорядоченным множеством, — это свойство и ослепляет его к последовательности.',
          'Так что порядок приходится *вернуть руками*. Раз механизм внимания сам на позицию не смотрит, мы впрыскиваем позицию во **входные векторы** ещё до того, как внимание запустится: к эмбеддингу каждого токена прибавляем особый вектор, зависящий только от того, *где* токен сидит, — первый, второй, семнадцатый. Теперь «cat» в позиции 3 и «cat» в позиции 8 приходят на слой внимания чуть разными векторами, и модель наконец различает, где какое слово. Вопрос — какими быть этим векторам позиций, — и ответ исходного Трансформера — изящный трючок с синусами и косинусами, который мы сейчас увидим, точно.',
        ],
        tt: [
          'Хәзер кимчелек, һәм ул нигез ташы. Игътибар ничек эшләгәненә тагын кара: һәр токенның сораулары һәр токенның ачкычына скаляр тапкырлана, авырлыклар softmax аша, кыйммәтләр кушыла. Бу исәптә токеннарның *тәртибе* беркайда керми. Җөмләдәге сүзләрне болгат һәм башка тәртиптә бир — һәм, алар белән барган тамгалардан тыш, математика нәкъ шул ук кушылмалар җыелмасын бирә. Үз-игътибар **урын алмаштыруга инвариант**: аның өчен җөмлә — токеннар *капчыгы*, эзлеклелек түгел.',
          'Тәртип *үзе* мәгънә булган тел өчен бу — фаҗига. «эт кешене тешли» һәм «кеше этне тешли» сүзләрнең бертөрле күплеген эченә ала; гадәти сишәмбене баш биттәге яңалыктан бары тәртип аера. «Песи паласка утырды» һәм «Палас песигә утырды» — шул ук капчык, бик төрле күренеш. Чыннан да тәртипне күрмәгән модель моның барысын алмаштырып булырлык дип санар иде, димәк ачкыч сүз шулпасыннан тыш бернәрсәгә яраксыз. Игътибарга барлык токеннарны параллель эшкәртергә мөмкинлек биргән шул ук сыйфат — аларны тәртипсез күплек итеп карау — аны эзлеклелеккә сукырайта торган сыйфат.',
          'Шуңа тәртипне *кул белән кире кайтарырга* кирәк. Игътибар механизмы үзе позициягә карамаганга, без позицияне игътибар җибәрелгәнче үк **керем векторларына** кертәбез: һәр токенның эмбеддингына бары токен *кайда* утырганга гына бәйле махсус вектор өстибез — беренче, икенче, унҗиденче. Хәзер 3 нче позициядәге «cat» белән 8 нче позициядәге «cat» игътибар катламына бераз төрле векторлар булып килә, һәм модель ниһаять кайсы сүз кайда икәнен аера. Сорау — бу позиция векторлары нинди булырга тиеш, — һәм башлангыч Трансформерның җавабы — синус белән косинуслы зәвыклы хәйлә, аны без хәзер төгәл күрербез.',
        ],
      },
    },
    { id: 'climb-positional', kind: 'scrolly', widget: 'positional-enc', data: 'l6-positional' },
    {
      id: 'turn-block', kind: 'prose',
      heading: { en: 'Assemble the block', ru: 'Собираем блок', tt: 'Блокны җыябыз' },
      body: {
        en: [
          "Step back and count what we have. Multi-head self-attention lets every token rebuild itself from the whole sentence. Positional encoding tells it where everything sits. Those two pieces are the heart of the **Transformer** ([Vaswani et al., 2017, \"Attention Is All You Need\"](https://arxiv.org/abs/1706.03762)) — but they are not the whole engine. Attention is *one component* of a small, repeating unit, and the rest of that unit is what makes the thing actually trainable and deep.",
          "Here's the reveal: attention by itself has two practical problems. First, it's entirely *linear* in its values — a weighted average of vectors is still just a blend, with no way to apply a genuinely non-linear transformation to what it found. Second, stacking many attention layers on top of each other makes training unstable; the signal degrades and gradients misbehave as depth grows. The Transformer's design solves both with two extra ingredients wrapped around attention — a **feed-forward network** and **residual connections with layer normalization** — and those, plus attention, form the **block** that gets repeated \\(N\\) times to make a deep model.",
          "Think of it as upgrading the council from a single vote into a full deliberative chamber. Attention is the round of *listening* — each member gathering a weighted summary of the room. Then each member needs a round of private *thinking* (the feed-forward network), a way to *not forget what they already knew* while they update (the residual connection), and a *moderator who keeps everyone speaking at the same volume* (layer normalization). Run that whole procedure, then do it again, and again — depth by repetition. The next step assembles the block piece by piece, in order; let's watch it come together.",
        ],
        ru: [
          'Отступи и посчитай, что у нас есть. Многоголовое само-внимание даёт каждому токену перестроить себя из всего предложения. Позиционное кодирование говорит ему, где что сидит. Эти две части — сердце **Трансформера** ([Vaswani et al., 2017, «Attention Is All You Need»](https://arxiv.org/abs/1706.03762)), — но это не весь движок. Внимание — *один компонент* маленькой повторяющейся единицы, а остальное в этой единице и делает штуку реально обучаемой и глубокой.',
          'Вот раскрытие: у внимания самого по себе две практические проблемы. Первая: оно полностью *линейно* по своим значениям — взвешенное среднее векторов всё ещё лишь смесь, без способа применить по-настоящему нелинейное преобразование к найденному. Вторая: складывание многих слоёв внимания друг на друга делает обучение нестабильным; сигнал деградирует и градиенты шалят с ростом глубины. Дизайн Трансформера решает оба двумя добавочными ингредиентами, обёрнутыми вокруг внимания, — **сетью прямого прохода** и **остаточными связями с послойной нормализацией**, — и они, плюс внимание, образуют **блок**, что повторяется \\(N\\) раз ради глубокой модели.',
          'Считай это апгрейдом совета из одного голосования в полноценную совещательную палату. Внимание — это раунд *слушания*, каждый член собирает взвешенную сводку зала. Потом каждому нужен раунд личного *размышления* (сеть прямого прохода), способ *не забыть то, что уже знал*, пока обновляется (остаточная связь), и *модератор, что держит всех на одной громкости* (послойная нормализация). Прогони всю эту процедуру, потом снова, и снова — глубина повторением. Следующий шаг собирает блок по кусочку, по порядку; посмотрим, как он складывается.',
        ],
        tt: [
          'Бер адым артка чигенеп, бездә нәрсә барын сана. Күпбашлы үз-игътибар һәр токенга үзен бөтен җөмләдән яңадан корырга мөмкинлек бирә. Позиция кодлавы аңа нәрсә кайда утырганын әйтә. Бу ике өлеш — **Трансформер**ның йөрәге ([Vaswani et al., 2017, «Attention Is All You Need»](https://arxiv.org/abs/1706.03762)), — әмма бу бөтен двигатель түгел. Игътибар — кечкенә, кабатлана торган берәмлекнең *бер компоненты*, ә бу берәмлекнең калганы әйберне чынлап өйрәтелә һәм тирән итә.',
          'Менә ачылыш: игътибарның үзенең ике гамәли проблемасы бар. Беренче: ул кыйммәтләре буенча тулысынча *линеар* — векторларның авырлыклы уртачасы барыбер кушылма гына, тапканга чын линеар булмаган үзгәртү кулланырлык юл юк. Икенче: күп игътибар катламын бер-берсенә өю өйрәтүне тотрыксыз итә; тирәнлек үскән саен сигнал бозыла, градиентлар тилерә. Трансформер дизайны икесен дә игътибар тирәсенә төрелгән ике өстәмә состав белән чишә — **алга юнәлгән челтәр** һәм **катлам нормалаштыруы белән калдык бәйләнешләр**, — һәм алар, игътибар белән, тирән модель ясар өчен \\(N\\) тапкыр кабатлана торган **блокны** төзи.',
          'Моны шураны бер тавыштан тулы киңәшмә палатасына күтәрү дип сана. Игътибар — *тыңлау* раунды, һәр әгъза залның авырлыклы кыскача эчтәлеген җыя. Аннары һәркайсына шәхси *уйлану* раунды кирәк (алга юнәлгән челтәр), яңарганда *инде белгәнен онытмау* ысулы (калдык бәйләнеш), һәм *барысын бер тавыш дәрәҗәсендә тоткан модератор* (катлам нормалаштыруы). Бу бөтен процедураны җибәр, аннары тагын, тагын — кабатлау белән тирәнлек. Киләсе адым блокны өлешләп, тәртип белән җыя; аның ничек кушылуын карыйк.',
        ],
      },
    },
    { id: 'climb-block', kind: 'scrolly', widget: 'transformer-block' },
    {
      id: 'turn-contextual-payoff', kind: 'prose',
      heading: { en: 'From tokens to a sentence vector', ru: 'От токенов к вектору предложения', tt: 'Токеннардан җөмлә векторына' },
      img: 'L6/L6-09-transformer-block.png', imgPos: 'scene',
      imgAlt: {
        en: 'A stack of identical Transformer blocks; a sentence enters at the bottom and rises through them, every token vector growing more context-aware at each layer.',
        ru: 'Стопка одинаковых блоков Трансформера; предложение входит снизу и поднимается сквозь них, каждый вектор токена становится контекстнее на каждом слое.',
        tt: 'Бертөрле Трансформер блоклары өеме; җөмлә астан керә һәм алар аша күтәрелә, һәр катламда һәр токен векторы контекстлырак була бара.',
      },
      imgCaption: {
        en: 'Stack the block ×N and a sentence rises through, each layer deepening context. BERT pools the top layer — often the [CLS] token — into one sentence vector.',
        ru: 'Сложи блок ×N, и предложение поднимается сквозь, каждый слой углубляет контекст. BERT сворачивает верхний слой — часто токен [CLS] — в один вектор предложения.',
        tt: 'Блокны ×N өй, җөмлә аша күтәрелә, һәр катлам контекстны тирәнәйтә. BERT өске катламны — еш [CLS] токенын — бер җөмлә векторына җыя.',
      },
      body: {
        en: [
          "Stack that block a dozen or two dozen times, train it on a mountain of text, and you have **BERT** ([Devlin et al., 2019](https://arxiv.org/abs/1810.04805)) — a deep Transformer encoder that reads a whole sentence both directions at once and hands back, for every token, a richly contextual vector. \"bank\" near \"river\" and \"bank\" near \"deposited\" emerge from the top layer as genuinely different points. The polysemy that defeated static embeddings is, at the token level, solved. The map can finally read the room.",
          "But search usually wants *one* vector for a whole query or a whole document, not a vector per token. So how do we **pool** a sentence's worth of contextual token vectors into a single sentence embedding? BERT's classic recipe prepends a special token, **`[CLS]`**, to every input and trains it so that its top-layer vector serves as a summary of the entire sequence — read off `[CLS]`, and you have a one-vector representation of the sentence. The common, often-better alternative is **mean pooling**: just average all the token vectors from the top layer. Either way, a variable-length sentence collapses to a single fixed-length vector you can drop straight onto the Map of Meaning.",
          "And right there is the bridge to retrieval. Embed the query into one vector, embed every document into one vector, and search becomes nearest-neighbour on the Map — cosine again, **Sir Cosine** still measuring angles, but now over *contextual* vectors that actually understand polysemy and word order. This is the dense-retrieval dream. There is just one catch, and it's a sharp one: the vectors that fall out of an off-the-shelf BERT are *not yet good for search*. They were trained to predict masked words, not to make relevant query-document pairs land close. To fix that we need to train the space *for retrieval* — which is the last act of the chapter.",
        ],
        ru: [
          'Сложи этот блок дюжину или две дюжины раз, обучи на горе текста — и у тебя **BERT** ([Devlin et al., 2019](https://arxiv.org/abs/1810.04805)), глубокий энкодер-Трансформер, что читает всё предложение сразу в обе стороны и возвращает для каждого токена насыщенно контекстный вектор. «bank» рядом с «river» и «bank» рядом с «deposited» выходят с верхнего слоя по-настоящему разными точками. Полисемия, победившая статические эмбеддинги, на уровне токена решена. Карта наконец читает обстановку.',
          'Но поиску обычно нужен *один* вектор на весь запрос или весь документ, а не вектор на токен. Так как же **свернуть** все контекстные векторы токенов предложения в один эмбеддинг предложения? Классический рецепт BERT добавляет в начало каждого входа особый токен **`[CLS]`** и обучает его так, чтобы его вектор с верхнего слоя служил сводкой всей последовательности, — считай `[CLS]`, и у тебя одно-векторное представление предложения. Частая и нередко лучшая альтернатива — **mean pooling**: просто усредни все векторы токенов с верхнего слоя. Так или иначе, предложение переменной длины схлопывается в один вектор фиксированной длины, что ложится прямо на Карту смысла.',
          'И вот тут мост к поиску. Вложи запрос в один вектор, вложи каждый документ в один вектор — и поиск становится ближайшим соседом на Карте: снова косинус, **Сэр Косинус** всё мерит углы, но теперь над *контекстными* векторами, что вправду понимают полисемию и порядок слов. Это мечта плотного поиска. Есть лишь один подвох, и острый: векторы, что падают из BERT «из коробки», *ещё не годятся для поиска*. Их учили предсказывать замаскированные слова, а не сводить близко релевантные пары запрос-документ. Чтобы это исправить, нужно обучить пространство *под поиск* — это последний акт главы.',
        ],
        tt: [
          'Бу блокны унике яки егерме тапкыр өй, текст тавы өстендә өйрәт — һәм синдә **BERT** ([Devlin et al., 2019](https://arxiv.org/abs/1810.04805)), бөтен җөмләне берьюлы ике якка укыган һәм һәр токен өчен баерак контекст векторы кайтарган тирән энкодер-Трансформер. «river» янындагы «bank» белән «deposited» янындагы «bank» өске катламнан чыннан да төрле нокталар булып чыга. Статик эмбеддингларны җиңгән полисемия токен дәрәҗәсендә чишелде. Карта ниһаять хәлне укый.',
          'Әмма эзләүгә гадәттә бөтен сорау яки бөтен документ өчен *бер* вектор кирәк, токенга вектор түгел. Соң, җөмләнең барлык контекст токен векторларын бер җөмлә эмбеддингына ничек **җыярга**? BERT’ның классик рецепты һәр керем алдына махсус токен **`[CLS]`** өсти һәм аны өске катлам векторы бөтен эзлеклелекнең кыскача эчтәлеге булырлык итеп өйрәтә, — `[CLS]`’ны укы, синдә җөмләнең бер-векторлы күрсәтмәсе. Еш һәм еш кына яхшырак альтернатива — **mean pooling**: өске катламның барлык токен векторларын уртачала гына. Ничек кенә булса да, үзгәрә торган озынлыклы җөмлә Мәгънә картасына туры төшә торган бер беркетелгән озынлыклы векторга йомыла.',
          'Һәм менә монда эзләүгә күпер. Сорауны бер векторга сал, һәр документны бер векторга сал — һәм эзләү Картада иң якын күршегә әйләнә: тагын косинус, **Сэр Косинус** һаман почмакларны үлчи, әмма хәзер полисемияне һәм сүз тәртибен чынлап аңлаган *контекст* векторлары өстендә. Бу — тыгыз эзләү хыялы. Бер генә подвох бар, һәм үткер: «тартмадан» алынган BERT’тан төшкән векторлар *әле эзләүгә ярамый*. Аларны маскаланган сүзләрне алдан әйтергә өйрәткәннәр, кагылышлы сорау-документ парларын якын китерергә түгел. Моны төзәтер өчен киңлекне *эзләү өчен* өйрәтергә кирәк — бу бүлекнең соңгы пәрдәсе.',
        ],
      },
    },
    {
      id: 'turn-contrastive', kind: 'prose',
      heading: { en: 'Train the space for search', ru: 'Учим пространство под поиск', tt: 'Киңлекне эзләү өчен өйрәтәбез' },
      body: {
        en: [
          "Why aren't pre-trained BERT vectors good for search out of the box? Because of *what they were trained to do*. BERT's pre-training objective is masked-language-modelling: hide a word, predict it from context. That makes superb token representations for grammar and meaning — but nothing in that objective ever asks the model to place a *question* near its *answer*, or a query near a relevant document. The geometry that's perfect for filling in blanks is not the geometry where relevance equals nearness.",
          "What we actually want is a space with a single, blunt property: **a query and a document that answer it should be close; a query and an irrelevant document should be far.** Nearness must *mean* relevance, exactly the way it had to mean similarity on last chapter's map — but now tuned for the retrieval task specifically. We can't get there by predicting masked words. We have to state the goal directly and optimize for *it*: pull things that should match together, push things that shouldn't apart.",
          "That is **contrastive learning**, and it is the training principle behind every modern dense retriever — SBERT ([Reimers & Gurevych, 2019](https://arxiv.org/abs/1908.10084)), DPR ([Karpukhin et al., 2020](https://arxiv.org/abs/2004.04906)), and their descendants. You feed the model *pairs that belong together* (a query and its relevant passage, two paraphrases, a sentence and its translation) and *pairs that don't*, and you reshape the space until the belong-together pairs sit close and everything else sits far. **Sir Cosine** is the judge: the loss is written directly in terms of cosine similarity, so the model is optimized on the very metric search will use. The next step does the contrastive objective exactly, on real numbers.",
        ],
        ru: [
          'Почему предобученные векторы BERT не годятся для поиска из коробки? Из-за *того, чему их учили*. Цель предобучения BERT — masked-language-modelling: спрячь слово, предскажи его по контексту. Это даёт превосходные представления токенов для грамматики и смысла, — но ничто в этой цели не просит модель поставить *вопрос* рядом с его *ответом* или запрос рядом с релевантным документом. Геометрия, идеальная для заполнения пропусков, — не та геометрия, где релевантность равна близости.',
          'А хотим мы пространство с единственным грубым свойством: **запрос и документ, что на него отвечает, должны быть близки; запрос и нерелевантный документ — далеки.** Близость должна *значить* релевантность ровно так, как ей пришлось значить сходство на карте прошлой главы, — но теперь настроенная именно под задачу поиска. Предсказанием замаскированных слов туда не попасть. Надо заявить цель прямо и оптимизировать под *неё*: притянуть то, что должно совпадать, оттолкнуть то, что не должно.',
          'Это **контрастное обучение**, и это принцип обучения за каждым современным плотным ретривером — SBERT ([Reimers & Gurevych, 2019](https://arxiv.org/abs/1908.10084)), DPR ([Karpukhin et al., 2020](https://arxiv.org/abs/2004.04906)) и их потомками. Ты скармливаешь модели *пары, что вместе* (запрос и его релевантный пассаж, два парафраза, предложение и его перевод) и *пары, что нет*, и переформовываешь пространство, пока пары-вместе не сядут близко, а всё прочее далеко. **Сэр Косинус** — судья: лосс записан прямо через косинусное сходство, так что модель оптимизируют на той самой метрике, что использует поиск. Следующий шаг делает контрастную цель точно, на настоящих числах.',
        ],
        tt: [
          'Ни өчен алдан өйрәтелгән BERT векторлары тартмадан эзләүгә ярамый? *Аларны нәрсәгә өйрәткәнгә* күрә. BERT’ның алдан өйрәтү максаты — masked-language-modelling: сүзне яшер, аны контексттан алдан әйт. Бу грамматика һәм мәгънә өчен искиткеч токен күрсәтмәләре бирә, — әмма бу максатта бернәрсә дә моделдән *сорауны* аның *җавабы* янына, яки сорауны кагылышлы документ янына куюны сорамый. Бушлыкларны тутыруга идеаль геометрия — кагылышлылык якынлыкка тигез булган геометрия түгел.',
          'Ә без теләгәне — бер генә тупас сыйфатлы киңлек: **сорау һәм аңа җавап биргән документ якын булырга тиеш; сорау һәм кагылышсыз документ — ерак.** Якынлык кагылышлылыкны *аңлатырга* тиеш, нәкъ узган бүлек картасында охшашлыкны аңлатырга тиеш булган кебек, — әмма хәзер нәкъ эзләү бурычына көйләнгән. Маскаланган сүзләрне алдан әйтеп анда барып булмый. Максатны турыдан әйтеп, *аңа* оптимизацияләргә кирәк: туры килергә тиешне тарт, тиеш булмаганны этеп чыгар.',
          'Бу — **контраст өйрәнү**, һәм бу — һәр заманча тыгыз ретривер артындагы өйрәтү принцибы — SBERT ([Reimers & Gurevych, 2019](https://arxiv.org/abs/1908.10084)), DPR ([Karpukhin et al., 2020](https://arxiv.org/abs/2004.04906)) һәм аларның варислары. Син моделгә *бергә булырга тиешле парларны* (сорау һәм аның кагылышлы өзеге, ике парафраз, җөмлә һәм аның тәрҗемәсе) һәм *тиеш булмаган парларны* бирәсең, һәм бергә-парлар якын утырганчы, калганы ерак утырганчы киңлекне яңадан формалыйсың. **Сэр Косинус** — хөкемче: югалту турыдан косинус охшашлыгы аша язылган, шуңа модель эзләү куллана торган нәкъ шул метрикада оптимизацияләнә. Киләсе адым контраст максатны төгәл, чын саннарда эшли.',
        ],
      },
    },
    { id: 'climb-contrastive', kind: 'scrolly', widget: 'contrastive-space', data: 'l6-contrastive' },
    {
      id: 'catch-anisotropy', kind: 'prose',
      heading: { en: 'The cone of crowded vectors', ru: 'Конус тесных векторов', tt: 'Тыгыз векторлар конусы' },
      body: {
        en: [
          "Before we declare victory, one trap — and it's the reason the contrastive step isn't optional decoration but a *necessity*. Take a raw, un-tuned BERT and look at the geometry of its output vectors directly. You'd hope they spread out evenly over the sphere, pointing every which way. They don't. [Ethayarajh (2019)](https://arxiv.org/abs/1909.00512) measured it: contextual embeddings from BERT, ELMo, and GPT-2 crowd into a *narrow cone* — they're squeezed into one corner of the space, all pointing in roughly the same direction. This is **anisotropy**, and it is exactly the same pathology the Curse-of-Dimensionality Wraith whispered about back in L2: when everything points the same way, *every* pair of vectors looks similar, and your similarity measure loses its discriminating power.",
          "See why this is poison for cosine search. If two random, totally unrelated sentences already sit at cosine 0.8 *just because all BERT vectors crowd the same cone*, then a genuinely relevant pair at 0.85 is barely distinguishable from noise — the whole useful signal is squeezed into a sliver of the cosine range. The raw geometry inflates similarities across the board and flattens the contrast you actually need. A nearest-neighbour search on these vectors would be swamped by false neighbours, the high-dimensional crowding the Wraith promised.",
          "And this is precisely what contrastive training and normalization fix. By explicitly pushing negatives apart, the contrastive objective *spreads the cone open* — it forces unrelated things to point in genuinely different directions, restoring the dynamic range of cosine so that 0.92 and 0.37 mean something again. (Whitening and simple normalization help too, but contrastive fine-tuning does the heavy lifting.) So the contrastive step from the last beat isn't just \"nice to have\"; it's the cure for an anisotropy that would otherwise make dense retrieval quietly mediocre. Tune the space, open the cone — and *now* the vectors are ready for search.",
        ],
        ru: [
          'Прежде чем объявлять победу, одна ловушка — и это причина, почему контрастный шаг не опциональное украшение, а *необходимость*. Возьми сырой, ненастроенный BERT и посмотри на геометрию его выходных векторов напрямую. Ты бы надеялся, что они ровно разлетаются по сфере, указывая во все стороны. Нет. [Ethayarajh (2019)](https://arxiv.org/abs/1909.00512) измерил: контекстные эмбеддинги из BERT, ELMo и GPT-2 жмутся в *узкий конус* — стиснуты в один угол пространства, все указывают примерно в одну сторону. Это **анизотропия**, и это ровно та патология, о которой шептал Призрак проклятия размерности ещё в L2: когда всё указывает в одну сторону, *любая* пара векторов выглядит похожей, и твоя мера сходства теряет различающую силу.',
          'Смотри, почему это яд для косинусного поиска. Если два случайных, совершенно несвязанных предложения уже сидят на косинусе 0.8 *просто потому, что все векторы BERT толпятся в одном конусе*, то по-настоящему релевантная пара на 0.85 едва отличима от шума — весь полезный сигнал стиснут в щёлочку диапазона косинуса. Сырая геометрия завышает сходства поголовно и сплющивает контраст, что тебе реально нужен. Поиск ближайших соседей на этих векторах захлестнули бы ложные соседи — то многомерное скучивание, что обещал Призрак.',
          'И это ровно то, что чинят контрастное обучение и нормализация. Явно расталкивая негативы, контрастная цель *раскрывает конус* — заставляет несвязанное указывать в по-настоящему разные стороны, восстанавливая динамический диапазон косинуса, так что 0.92 и 0.37 снова что-то значат. (Отбеливание и простая нормализация тоже помогают, но основную работу делает контрастное дообучение.) Так что контрастный шаг из прошлого бита не просто «приятно иметь»; это лекарство от анизотропии, что иначе сделала бы плотный поиск тихо посредственным. Настрой пространство, раскрой конус — и *теперь* векторы готовы к поиску.',
        ],
        tt: [
          'Җиңүне игълан итәр алдыннан, бер тозак — һәм бу контраст адымы өстәмә бизәк түгел, ә *кирәклек* булуының сәбәбе. Чи, көйләнмәгән BERT ал һәм аның чыгыш векторларының геометриясенә турыдан кара. Син алар сфера буенча тигез таралып, һәр якка күрсәтер дип өметләнер идең. Юк. [Ethayarajh (2019)](https://arxiv.org/abs/1909.00512) үлчәде: BERT, ELMo һәм GPT-2’дан контекст эмбеддинглары *тар конуска* кысыла — киңлекнең бер почмагына кысылган, барысы якынча бер якка күрсәтә. Бу — **анизотропия**, һәм бу нәкъ L2’дә Үлчәмлек каргышы Җене пышылдаган патология: барысы бер якка күрсәткәндә, *теләсә кайсы* вектор пары охшаш күренә, һәм синең охшашлык үлчәвең аеру көчен югалта.',
          'Бу косинус эзләве өчен ни өчен агу икәнен кара. Әгәр ике очраклы, бөтенләй бәйләнешсез җөмлә *бары барлык BERT векторлары шул ук конуска тыгызланганга гына* инде 0.8 косинуста утырса, чыннан да кагылышлы пар 0.85’тә шау-шудан чак аерыла — бөтен файдалы сигнал косинус диапазонының ярыгына кысылган. Чи геометрия охшашлыкларны гомумән арттыра һәм сиңа чынлап кирәкле контрастны яссылый. Бу векторларда иң якын күрше эзләвен ялган күршеләр басар иде — Җен вәгъдә иткән күп үлчәмле тыгызлану.',
          'Һәм нәкъ менә шуны контраст өйрәнү белән нормалаштыру төзәтә. Негативларны ачыктан этеп, контраст максаты *конусны ача* — бәйләнешсезне чыннан да төрле якка күрсәтергә мәҗбүр итә, косинусның динамик диапазонын торгыза, шуңа 0.92 белән 0.37 яңадан нәрсәдер аңлата. (Агарту белән гади нормалаштыру да ярдәм итә, әмма төп эшне контраст өсти-өйрәтү башкара.) Шуңа узган биттәге контраст адымы бары «булса яхшы» түгел; ул — тыгыз эзләүне юкса тын гына уртакул итәр иде торган анизотропиянең дәвасы. Киңлекне көйлә, конусны ач — һәм *хәзер* векторлар эзләүгә әзер.',
        ],
      },
    },
    {
      id: 'payoff-gremlin-caged', kind: 'prose',
      heading: { en: 'The Gremlin, caged', ru: 'Гремлин в клетке', tt: 'Читлектәге Гремлин' },
      img: 'L6/L6-15-gremlin-caged.png', imgPos: 'hero',
      imgAlt: {
        en: 'The Lexical Gremlin locked inside a cage while "couch" and "sofa" sit together as one point just outside, finally collapsed into the same place.',
        ru: 'Лексический Гремлин заперт в клетке, а «диван» и «софа» сидят вместе одной точкой снаружи, наконец схлопнувшись в одно место.',
        tt: 'Лексик Гремлин читлектә бикле, ә «диван» белән «софа» тышта бер нокта булып бергә утыра, ниһаять бер урынга йомылган.',
      },
      imgCaption: {
        en: 'Six chapters of work end here: "couch" and "sofa" collapse to one place, polysemy is split apart, and the Lexical Gremlin is finally caged.',
        ru: 'Шесть глав работы кончаются здесь: «диван» и «софа» схлопываются в одно место, полисемия разведена, и Лексический Гремлин наконец в клетке.',
        tt: 'Алты бүлек хезмәт монда тәмамлана: «диван» белән «софа» бер урынга йомыла, полисемия аерыла, һәм Лексик Гремлин ниһаять читлектә.',
      },
      body: {
        en: [
          "Stand back and look at what the whole expedition just accomplished. Back in **First Contact** (L1), the **Lexical Gremlin** wedged a brick wall between every pair of words that meant the same thing but were spelled differently — \"couch\" and \"sofa\" scored a flat zero, as unrelated as \"couch\" and \"crocodile\". In L5 we cornered him: the static Map of Meaning let synonyms cluster, and \"couch\" and \"sofa\" finally drifted into the same neighbourhood. But he had one move left — *polysemy*, the single frozen vector that couldn't hold \"bank\"'s two minds. Today we took that move away.",
          "Watch both halves of the win close together. **Synonymy:** \"couch\" and \"sofa\" in similar sentences now produce nearly identical contextual vectors and collapse to essentially the same place — and on our worked numbers, contrastively-tuned, \"cat\" and \"kitten\" sit at cosine \\(0.639\\) while \"cat\" and \"airplane\" sit far off at \\(0.365\\). Near *means* related, with no synonym list anywhere. **Polysemy:** \"bank\" near \"river\" and \"bank\" near \"money\" now leave the encoder as *different* vectors, because self-attention rebuilt each from its actual neighbours. The two tricks that defined the Gremlin for six chapters — synonyms-far and senses-collapsed — are both broken. The Gremlin is **caged**.",
          "That's the big payoff of the whole arc, and it earns a clean statement of how we got here: contextual embeddings from a stacked **Transformer**, each token rebuilt by **multi-head self-attention** with **positional encoding** so order survives, pooled to a sentence vector, then **contrastively tuned** (InfoNCE, in-batch negatives, loss \\(0.1191\\) on our example) so nearness means relevance and the **anisotropic cone** is pried open. The crew finally knows who to listen to. But notice we built a *single* vector per query and per document — a **bi-encoder**, fast but coarse. What if, instead, the query and document could attend to *each other* before we score them? That richer, slower idea — the **cross-encoder** — and how to combine the two into a fast-then-accurate cascade is exactly where **L7** picks up. The council is seated; next, we send it to work on retrieval.",
        ],
        ru: [
          'Отступи и посмотри, чего добилась вся экспедиция. Ещё в **Первом контакте** (L1) **Лексический Гремлин** вставлял кирпичную стену между каждой парой слов, что значат одно, но написаны иначе, — «диван» и «софа» получали ровный ноль, так же несвязанные, как «диван» и «крокодил». В L5 мы загнали его в угол: статическая Карта смысла дала синонимам кластеризоваться, и «диван» с «софой» наконец сошлись в один район. Но один ход у него остался — *полисемия*, единственный замороженный вектор, что не мог держать два ума «bank». Сегодня мы отняли и этот ход.',
          'Смотри на обе половины победы вплотную. **Синонимия:** «диван» и «софа» в похожих предложениях теперь дают почти одинаковые контекстные векторы и схлопываются по сути в одно место, — а на наших разобранных числах, после контрастной настройки, «cat» и «kitten» сидят на косинусе \\(0.639\\), тогда как «cat» и «airplane» далеко, на \\(0.365\\). Близко *значит* связано, и нигде ни одного списка синонимов. **Полисемия:** «bank» рядом с «river» и «bank» рядом с «money» теперь выходят из энкодера *разными* векторами, ведь само-внимание перестроило каждый из его реальных соседей. Два трюка, что определяли Гремлина шесть глав, — синонимы-далеко и смыслы-схлопнуты — оба сломаны. Гремлин **в клетке**.',
          'Это большой выигрыш всей арки, и он заслуживает чёткой сводки, как мы сюда пришли: контекстные эмбеддинги из стопки **Трансформера**, каждый токен перестроен **многоголовым само-вниманием** с **позиционным кодированием**, чтобы порядок выжил, свёрнуты в вектор предложения, затем **контрастно настроены** (InfoNCE, in-batch негативы, лосс \\(0.1191\\) на нашем примере), чтобы близость значила релевантность, а **анизотропный конус** был раскрыт. Команда наконец знает, кого слушать. Но заметь: мы построили по *одному* вектору на запрос и на документ — **би-энкодер**, быстрый, но грубый. А что, если бы запрос и документ могли внимать *друг другу* перед тем, как мы их оценим? Эта более богатая, более медленная идея — **кросс-энкодер** — и как сплавить две в каскад «быстро-потом-точно» — ровно там подхватывает **L7**. Совет усажен; дальше отправляем его работать над поиском.',
        ],
        tt: [
          'Бер адым артка чигенеп, бөтен экспедиция нәрсә эшләгәненә кара. Әле **Беренче контактта** (L1) **Лексик Гремлин** бер нәрсә аңлаткан, ләкин башкача язылган һәр сүз пары арасына кирпеч стена кыстырды — «диван» белән «софа» шома ноль алды, «диван» белән «крокодил» кебек бәйләнешсез. L5’тә без аны почмакка кыстык: статик Мәгънә картасы синонимнарны кластерларга мөмкинлек бирде, һәм «диван» белән «софа» ниһаять бер районга җыелды. Әмма аның бер йөреше калды — *полисемия*, «bank»’ның ике акылын тота алмаган бердәнбер катып калган вектор. Бүген без бу йөрешне дә алдык.',
          'Җиңүнең ике яртысына да якыннан кара. **Синонимия:** охшаш җөмләләрдәге «диван» белән «софа» хәзер диярлек бертөрле контекст векторлары бирә һәм асылда бер урынга йомыла, — ә безнең карап чыккан саннарда, контраст белән көйләнгәч, «cat» белән «kitten» \\(0.639\\) косинуста утыра, ә «cat» белән «airplane» ерак, \\(0.365\\)’тә. Якын — *бәйле* дигән сүз, һәм беркайда бер генә синоним исемлеге дә юк. **Полисемия:** «river» янындагы «bank» белән «money» янындагы «bank» хәзер энкодердан *төрле* векторлар булып чыга, чөнки үз-игътибар һәркайсын аның чын күршеләреннән яңадан корды. Гремлинны алты бүлек билгеләгән ике хәйлә — синонимнар-ерак һәм мәгънәләр-йомылган — икесе дә сынды. Гремлин **читлектә**.',
          'Бу — бөтен арканың зур отышы, һәм ул монда ничек килүебезнең ачык кыскача эчтәлеген хаклый: өелгән **Трансформер**нан контекст эмбеддинглары, һәр токен **позиция кодлавы** белән **күпбашлы үз-игътибар** аша яңадан корылган, тәртип исән калсын өчен, җөмлә векторына җыелган, аннары **контраст белән көйләнгән** (InfoNCE, in-batch негативлар, безнең мисалда югалту \\(0.1191\\)), якынлык кагылышлылыкны аңлатсын һәм **анизотроп конус** ачылсын өчен. Команда ниһаять кемне тыңларга икәнен белә. Әмма игътибар ит: без сорауга һәм документка *берәр* вектор төзедек — **би-энкодер**, тиз, әмма тупас. Ә сорау белән документ, без аларны бәяләгәнче, *бер-берсенә* игътибар итә алса? Бу баерак, әкренрәк идея — **кросс-энкодер** — һәм икесен «тиз-аннары-төгәл» каскадына ничек кушу — нәкъ шунда **L7** дәвам итә. Шура утыртылды; алга таба аны эзләү өстендә эшләргә җибәрәбез.',
        ],
      },
    },
  ],
};
