    {
      id: 'mlm-nsp', kind: 'prose',
      heading: { en: "Mending the cloth from both edges", ru: "Штопаю полотно, глядя на оба края", tt: "Тукыманы ике кырыена да карап ямыйм" },
      body: {
        en: [
          "Here is how BERT actually *learns* to weave. I take a finished sheet of cloth, and before the model ever sees it I punch small holes: I hide about **15%** of the threads at random and dare it to guess each missing one back. That is *masked language modelling* — a fill-in-the-blank, cloze task. To mend the hole in *the cat \\([MASK]\\) on the mat*, the model must read the pattern from **both** edges at once — «cat» on the left, «on the mat» on the right — and only then reach for *sat*. This two-sided reading is the whole point: seeing the entire cloth is what makes BERT *bidirectional*.",
          "One honest wrinkle in the recipe. Of the hidden 15%, not all become a literal \\([MASK]\\): the split is **80%** \\([MASK]\\), **10%** a random thread, **10%** left untouched. Why the theatre? Because at fine-tuning time no \\([MASK]\\) ever appears — so if the loom only ever mended obvious holes, it would grow lazy everywhere else. The two special threads that frame every sheet, \\([CLS]\\) at the start and \\([SEP]\\) between segments, ride along untouched.",
          "The first BERT wove with a *second* objective too — **next-sentence prediction**: given segments A and B, does B truly follow A, or is it a random stranger? The verdict is read straight off the \\([CLS]\\) thread. I tell you this plainly because later weavers found NSP a **weak** signal — **RoBERTa** dropped it and improved. The instinct to model how sentences connect survived; this particular stitch did not.",
        ],
        ru: [
          "Вот как BERT на самом деле *учится* ткать. Беру готовое полотно и, прежде чем модель его увидит, пробиваю в нём дырки: случайно прячу около **15%** нитей и заставляю угадать каждую пропавшую. Это и есть *маскированное языковое моделирование* (masked language modelling) — задача «вставь пропущенное». Чтобы заштопать прореху в *the cat \\([MASK]\\) on the mat*, модель обязана читать узор сразу с **обоих** краёв — «cat» слева, «on the mat» справа — и лишь тогда потянуться за *sat*. Это двустороннее чтение — вся суть: именно потому, что BERT видит всё полотно, он и *двунаправленный*.",
          "Одна честная тонкость рецепта. Из спрятанных 15% не все становятся буквальным \\([MASK]\\): схема замены — **80%** \\([MASK]\\), **10%** случайная нить, **10%** оставляем как есть. Зачем этот театр? Потому что при дообучении (fine-tuning) токена \\([MASK]\\) нет вовсе — а станок, штопающий только явные дыры, разленился бы на всём остальном. Две особые нити, которые обрамляют каждое полотно, — \\([CLS]\\) в начале и \\([SEP]\\) между сегментами — проходят нетронутыми.",
          "Первый BERT ткал ещё и со *второй* целью обучения (objective) — **next-sentence prediction**: даны сегменты A и B — вправду ли B следует за A, или это случайный чужак? Вердикт снимается прямо с нити \\([CLS]\\). Говорю честно: позже ткачи признали NSP **слабым** сигналом — **RoBERTa** его убрала и стала лучше. Идея моделировать связь предложений уцелела; именно этот стежок — нет.",
        ],
        tt: [
          "Менә BERT чынлыкта ничек *тукырга өйрәнә*. Әзер тукыманы алам да, модель аны күргәнче, аңа тишекләр тишәм: якынча **15%** җепне очраклы рәвештә яшерәм һәм һәр югалганын кире табарга мәҗбүр итәм. Бу — *masked language modelling*, «калдырылганны куй» дигән cloze бурычы. *the cat \\([MASK]\\) on the mat* тишеген ямар өчен, модель үрнәкне **ике** кырдан да бердәм укырга тиеш — «cat» сулда, «on the mat» уңда — һәм шуннан соң гына *sat* нигә тартыла. Нәкъ шушы ике яклы уку — бөтен мәгънә: BERT бөтен тукыманы күргәнгә күрә *bidirectional* була.",
          "Рецептта бер намуслы нечкәлек. Яшерелгән 15% нең барысы да хәрефи \\([MASK]\\) булмый: алмаштыру схемасы — **80%** \\([MASK]\\), **10%** очраклы җеп, **10%** булган килеш калдырыла. Ни өчен бу театр? Чөнки fine-tuning вакытында \\([MASK]\\) бөтенләй юк — һәм станок бары ачык тишекләрне генә ямаса, ул калган бөтен урында «ялкауланыр» иде. Һәр тукыманы кыршаулаган ике аерым җеп — башында \\([CLS]\\) һәм сегментлар арасында \\([SEP]\\) — тимәгән килеш үтә.",
          "Беренче BERT тагын *икенче* objective белән дә тукыды — **next-sentence prediction**: A һәм B сегментлары бирелгән — B чыннан да A артыннан киләме, әллә ул очраклы чит кешеме? Хөкем турыдан-туры \\([CLS]\\) җебеннән укыла. Ачык әйтәм: соңрак тукучылар NSP'ны **көчсез** сигнал дип таптылар — **RoBERTa** аны алып ташлады һәм яхшыруга иреште. Җөмләләр бәйләнешен модельләштерү теләге исән калды; нәкъ шушы төймә — юк.",
        ],
      },
    },
