    {
      id: 'crag', kind: 'prose',
      heading: { en: 'CRAG: grade the retrieval', ru: 'CRAG: оцени извлечение', tt: 'CRAG: алуны бәялә' },
      img: 'L10/L10-14-crag-inspect.png', imgPos: 'float-right',
      imgAlt: {
        en: 'RAGdoll the Oracle holds each retrieved scrap up to a magnifying glass and stamps it ✓ / ✗ / ? before stitching, tossing a rejected scrap toward a "web" basket (CRAG grade-then-correct).',
        ru: 'Оракул RAGdoll подносит каждый извлечённый обрывок к лупе и ставит ✓ / ✗ / ? перед сшиванием, отбрасывая отвергнутый обрывок в корзину «web» (CRAG: оцени, затем исправь).',
        tt: 'RAGdoll Оракулы һәр алынган кисәкне зурайткычка тота һәм тегкәнче ✓ / ✗ / ? сугып билгели, кире кагылган кисәкне «web» кәрзиненә ыргыта (CRAG: бәялә, аннары төзәт).',
      },
      body: {
        en: [
          "Re-ranking reorders the shortlist but still trusts it. What if the retrieval is *bad* — the corpus simply does not contain the answer, or what it returned is off-topic? Stuffing it anyway invites the catch this lecture ends on: garbage in, fluent garbage out. **Corrective RAG** (CRAG; Yan, Gu, Zhu & Ling, arXiv:2401.15884, 2024) adds a checkpoint *between retrieve and generate* — a lightweight evaluator that grades the retrieval before the generator ever sees it.",
          "The evaluator scores each retrieval and sorts it into one of three grades. **Correct** — the evaluator's confidence is high (say, above an upper threshold around \\(0.7\\)): the retrieved context is good, so use it as-is. **Ambiguous** — confidence is middling (between a lower and upper threshold): the context is partially useful but thin, so *augment* it with a corrective web search and combine the two. **Wrong** — confidence is low (below a lower threshold around \\(0.3\\)): the context is off-base, so *discard* it and fall back to web search or a query rewrite rather than ground on noise.",
          "The thresholds here are illustrative, not measured — the point is the *three-way branch*, not the exact cutoffs. What matters is that CRAG turns retrieval from an unconditional input into a *graded* one: a confidence on the retrieval gates which of three actions the pipeline takes. Good retrieval flows straight through; thin retrieval gets reinforced; bad retrieval gets thrown out before it can poison the answer.",
          "That third branch is the load-bearing one. A plain RAG loop has no way to say *\"I don't have good evidence for this\"* — it grounds on whatever came back, however irrelevant. CRAG gives it an off-ramp: when the corpus fails, reach outside it (web search) or re-ask (rewrite) instead of confidently summarising noise. The corrective step is precisely the missing defense against the catch beat's failure mode — it inspects \\(R\\) before the generator commits to it.",
          "CRAG is the first member of the *self-correcting* family: the loop no longer trusts its own retrieval blindly but evaluates and repairs it. The next beat, Self-RAG, internalises this judgement *into the model itself* rather than bolting on a separate evaluator — and after that, Adaptive-RAG asks whether to retrieve at all. Each adds a layer of self-awareness to a loop that, until now, has marched straight through retrieve-augment-generate without ever questioning the middle.",
        ],
        ru: [
          "Переранжирование переупорядочивает шортлист, но всё ещё ему доверяет. А что если извлечение *плохое* — корпус попросту не содержит ответа, или то, что он вернул, не по теме? Впихнуть это всё равно — значит напроситься на ловушку, которой эта лекция кончается: мусор на входе — беглый мусор на выходе. **Корректирующий RAG** (CRAG; Янь, Гу, Чжу, Лин, Цао и Чжан, arXiv:2401.15884, 2024) добавляет контрольную точку *между извлечением и генерацией* — лёгкий оценщик, что оценивает извлечение прежде, чем генератор его увидит.",
          "Оценщик оценивает каждое извлечение и сортирует в одну из трёх оценок. **Верно** — уверенность оценщика высока (скажем, выше верхнего порога около \\(0{,}7\\)): извлечённый контекст хорош, поэтому используй как есть. **Неоднозначно** — уверенность средняя (между нижним и верхним порогом): контекст частично полезен, но тонок, поэтому *дополни* его корректирующим веб-поиском и скомбинируй два. **Неверно** — уверенность низка (ниже нижнего порога около \\(0{,}3\\)): контекст мимо, поэтому *отбрось* его и откатись к веб-поиску или переписыванию запроса, а не заземляйся на шуме.",
          "Пороги здесь иллюстративны, не измерены — суть в *трёхстороннем ветвлении*, не в точных порезах. Важно, что CRAG превращает извлечение из безусловного входа в *градуированный*: уверенность в извлечении решает, какое из трёх действий конвейер предпримет. Хорошее извлечение течёт насквозь; тонкое подкрепляется; плохое выбрасывается, прежде чем отравить ответ.",
          "Эта третья ветвь несущая. У простого цикла RAG нет способа сказать *«у меня нет хороших доказательств для этого»* — он заземляется на чём угодно, что вернулось, сколь угодно нерелевантном. CRAG даёт ему съезд: когда корпус подводит, тянись вовне (веб-поиск) или переспроси (переписывание), а не уверенно резюмируй шум. Корректирующий шаг — ровно недостающая защита от режима отказа из такта-ловушки: он осматривает \\(R\\) прежде, чем генератор на него обопрётся.",
          "CRAG — первый член *самокорректирующего* семейства: цикл больше не доверяет своему извлечению слепо, а оценивает и чинит его. Следующий такт, Self-RAG, интернализует это суждение *в саму модель*, а не прикручивает отдельный оценщик — а после Adaptive-RAG спрашивает, извлекать ли вообще. Каждый добавляет слой самоосознания циклу, который до сих пор маршировал прямо сквозь извлечь-дополнить-сгенерировать, ни разу не усомнившись в середине.",
        ],
        tt: [
          "Кабат ранжлау шортлистны яңадан тәртипли, ләкин аңа һаман ышана. Ә алу *начар* булса — корпус җавапны бөтенләй эченә алмаса, яки кайтарганы тема-тыш булса? Аны барыбер тутыру бу лекция тәмамлана торган тоткычка чакыру: чүп керсә — шома чүп чыга. **Төзәтүче RAG** (CRAG; Янь, Гу, Чжу, Лин, Цао һәм Чжан, arXiv:2401.15884, 2024) *алу белән генерация арасына* тикшерү ноктасы өсти — генератор аны күргәнче алуны бәяләүче җиңел бәяләгеч.",
          "Бәяләгеч һәр алуны бәяли һәм өч бәянең берсенә сортлый. **Дөрес** — бәяләгечнең ышанычы югары (әйтик, \\(0{,}7\\) тирәсе югары бусагадан өстә): алынган контекст яхшы, шуңа булганча куллан. **Икеле** — ышаныч уртача (түбән белән югары бусага арасында): контекст өлешчә файдалы, ләкин нечкә, шуңа аны төзәтүче веб-эзләү белән *өстә* һәм икесен куш. **Ялгыш** — ышаныч түбән (\\(0{,}3\\) тирәсе түбән бусагадан ким): контекст читтә, шуңа аны *ташла* һәм шауга нигезләнү урынына веб-эзләүгә яки сорауны яңадан язуга кире кайт.",
          "Биредәге бусагалар иллюстратив, үлчәнмәгән — мәгънә *өч яклы тармакланышта*, төгәл кисүләрдә түгел. Мөһиме: CRAG алуны шартсыз керүдән *градуаль* га әйләндерә: алудагы ышаныч пайплайн өч гамәлнең кайсын алуын хәл итә. Яхшы алу турыдан-туры ага; нечкә алу ныгытыла; начар алу җавапны агуларга өлгергәнче ташлана.",
          "Бу өченче тармак — йөк күтәрүче. Гади RAG циклында *«моңа минем яхшы дәлилем юк»* дип әйтер ысул юк — ул кайткан теләсә нәрсәгә нигезләнә, никадәр релевант булмаса да. CRAG аңа төшкел бирә: корпус ялгышканда, шауны ышанычлы гомумиләштерү урынына тышка үрел (веб-эзләү) яки яңадан сора (яңадан язу). Төзәтүче баскыч — тоткыч-битнең җимерелү режименнән нәкъ җитмәгән саклану: ул генератор аңа таянганчы \\(R\\) ны карый.",
          "CRAG — *үзен-үзе төзәтүче* гаиләнең беренче әгъзасы: цикл бүтән үз алуына сукырларча ышанмый, ә аны бәяли һәм төзәтә. Киләсе бит, Self-RAG, бу хөкемне аерым бәяләгеч борап түгел, ә *модельнең үзенә* эчке итә — ә аннан соң Adaptive-RAG гомумән алырга кирәкме дип сорый. Һәрберсе хәзергә кадәр алу-өстәү-генерация аша туры маршлап барган, уртасына бер тапкыр да шикләнмәгән циклга үзаң катламы өсти.",
        ],
      },
    },
