/* whiten-grid/logic.js — L18 "The Curved Map", act 02: the formula x̃ = (x−μ)W, W = UΛ^(−1/2),
   applied for once instead of merely displayed.

   Four cities: (9,7) (7,9) (3,5) (5,3). Every cosine below is EXACT arithmetic from
   data/l18-geometry.json → whitenToy (generated by _research/gen_l18.py), not a sampled estimate.

   The question this figure answers — the one the lecture never used to answer — is: I already
   centred, why whiten? Watch the two STRANGERS, cities 0 and 1. Raw they read 0.9692 and the whole
   cloud averages 0.9504: a cone. Centring kills the shared shift and the average drops to −0.3333 —
   but the strangers STILL read 0.60, because Σ = [[5,3],[3,5]] keeps an off-diagonal 3: the axes are
   still sheared. Only Λ^(−1/2) finishes the job: the diamond becomes a square and the strangers read
   EXACTLY 0.0000. Centring is half the repair.

   DRIVER-AGNOSTIC: setStep(k)/maxStep, binds NO keyboard/scroll. Built on _widget-base.js.

   Steps (maxStep = 5):
     0 → the four raw cities and their six pairwise cosines — a cone (mean 0.9504).       s0
     1 → subtract μ = (6,6): the mean drops to −0.3333, the strangers stay at 0.60.       s1
     2 → what is left: Σ = [[5,3],[3,5]], λ = 8 and 2, condition number 4.                s2
     3 → U rotates the paper onto the cloud's own axes.                                   s3
     4 → Λ^(−1/2) rescales each axis: the diamond becomes a square.                       s4
     5 → the cosines after: the strangers are EXACTLY 0; only true antipodes keep −1.     s5 */
import { defineWidget } from '../_widget-base.js';

export const mountWhitenGrid = defineWidget({
  id: 'whiten-grid',
  rootClass: 'wg-root',
  exportName: 'mountWhitenGrid',
  maxStep: 5,
  render({ host, data, labels, el }) {
    const T = (data && data.whitenToy) || {};
    const stages = T.stages || {};
    const raw = (stages.raw || {}).points || [];
    const cen = (stages.centered || {}).points || [];
    const wht = (stages.whitened || {}).points || [];
    const U = T.U || [[1, 0], [0, 1]];
    const SIG = T.sigma || [[0, 0], [0, 0]];
    const LAM = T.eigenvalues || [1, 1];
    const f4 = (x) => (typeof x === 'number' && isFinite(x) ? x.toFixed(4) : '—');
    const f2 = (x) => (typeof x === 'number' && isFinite(x) ? x.toFixed(2) : '—');

    // the intermediate ROTATED stage (step 3) is a pure drawing interpolation of the two data stages:
    // coordinates of the centred cloud read in the (u₁, u₂) basis, before Λ^(−1/2) rescales them.
    const rot = cen.map((p) => [p[0] * U[0][0] + p[1] * U[0][1], p[0] * U[1][0] + p[1] * U[1][1]]);
    const STAGE = [raw, cen, cen, rot, wht, wht];
    const SHOW_EIG = [false, false, true, true, false, false];
    // The LEDGER lags the DRAWING by one step on purpose: step 4 turns the rectangle into a square,
    // step 5 reads the new cosines off it. (Step 5 used to repeat step 4 verbatim — a dead step.)
    const COS_OF = [stages.raw, stages.centered, stages.centered, stages.centered, stages.centered, stages.whitened];

    const W = 700, H = 340;
    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, class: 'wgt-svg wg-svg', role: 'img',
      'aria-label': labels.alt || '' }, host);

    // ── LEFT: the map. One square window, origin always in frame. ─────────────────────────────
    const box = { x: 30, y: 34, w: 300, h: 272 };
    el('text', { x: box.x + box.w / 2, y: box.y - 14, class: 'wg-head', 'text-anchor': 'middle' }, svg)
      .textContent = labels.map || 'four cities on the map';

    // the deforming coordinate grid: 9 lines each way, drawn as paths so they can bend with the transform
    const GRID_N = 4;                                   // −4..+4 in unit steps around the origin
    const gridH = [], gridV = [];
    for (let i = -GRID_N; i <= GRID_N; i += 1) {
      gridH.push(el('path', { d: '', class: 'wg-grid' }, svg));
      gridV.push(el('path', { d: '', class: 'wg-grid' }, svg));
    }
    const axX = el('line', { x1: 0, y1: 0, x2: 0, y2: 0, class: 'wg-axis' }, svg);
    const axY = el('line', { x1: 0, y1: 0, x2: 0, y2: 0, class: 'wg-axis' }, svg);
    const eig1 = el('line', { x1: 0, y1: 0, x2: 0, y2: 0, class: 'wg-eig' }, svg);
    const eig2 = el('line', { x1: 0, y1: 0, x2: 0, y2: 0, class: 'wg-eig' }, svg);
    const rays = [0, 1].map(() => el('line', { x1: 0, y1: 0, x2: 0, y2: 0, class: 'wg-ray' }, svg));
    const cities = raw.map((_, i) => el('circle', { cx: 0, cy: 0, r: i < 2 ? 7 : 6,
      class: 'wg-city' + (i < 2 ? ' is-stranger' : '') }, svg));
    const cityLbls = raw.map((_, i) => {
      const t = el('text', { x: 0, y: 0, class: 'wg-citylbl' }, svg);
      t.textContent = String.fromCharCode(65 + i);
      return t;
    });

    // ── RIGHT: the six pairwise cosines + the covariance ledger ───────────────────────────────
    const rx = 380;
    el('text', { x: rx, y: box.y - 14, class: 'wg-head' }, svg).textContent = labels.cosines || 'all six pairwise cosines';
    const pairs = ((stages.raw || {}).cosines || {}).pairs || [];
    const rowLbl = pairs.map((p, i) => {
      const t = el('text', { x: rx, y: box.y + 16 + i * 22, class: 'wg-lbl' }, svg);
      t.textContent = `${String.fromCharCode(65 + p[0])}·${String.fromCharCode(65 + p[1])}`;
      return t;
    });
    const rowVal = pairs.map((_, i) => el('text', { x: rx + 52, y: box.y + 16 + i * 22, class: 'wg-val' }, svg));
    const meanLbl = el('text', { x: rx, y: box.y + 22 + pairs.length * 22 + 8, class: 'wg-mean' }, svg);
    const matLines = [0, 1, 2].map((i) =>
      el('text', { x: rx, y: box.y + 22 + pairs.length * 22 + 38 + i * 20, class: 'wg-mat' }, svg));
    if (!rowLbl.length) meanLbl.textContent = '';

    return function update(k) {
      const step = Math.max(0, Math.min(5, k));
      const pts = STAGE[step] || [];

      // view: a square window that always contains BOTH the origin and every city
      let lo = -1.6, hi = 1.6;
      pts.forEach((p) => { lo = Math.min(lo, p[0], p[1]); hi = Math.max(hi, p[0], p[1]); });
      const pad = (hi - lo) * 0.12 + 0.4;
      lo -= pad; hi += pad;
      const side = Math.min(box.w, box.h);
      const ox = box.x + (box.w - side) / 2, oy = box.y + (box.h - side) / 2;
      const sx = (v) => ox + ((v - lo) / (hi - lo)) * side;
      const sy = (v) => oy + side - ((v - lo) / (hi - lo)) * side;
      const zx = sx(0), zy = sy(0);

      // Grid pitch in data units. The window [lo, hi] is NOT symmetric about the origin (the raw
      // cities all sit in the positive quadrant), so the old "draw i·pitch for i = −4…+4" loop drew
      // lines far outside the window and they spilled out of the SVG frame (slide-viz OOB). Walk the
      // multiples of `pitch` that actually FALL INSIDE [lo, hi] instead, and park the spare paths.
      const want = Math.max(0.001, (hi - lo) / 8);
      const P = Math.max([0.25, 0.5, 1, 2, 5, 10, 20].find((v) => v >= want) || 20, (hi - lo) / 8);
      const iMin = Math.ceil(lo / P - 1e-9);
      for (let j = 0; j < gridH.length; j += 1) {
        const v = (iMin + j) * P;
        if (v > hi + 1e-9) {                              // past the right/top edge — park it
          gridH[j].setAttribute('d', ''); gridV[j].setAttribute('d', '');
          continue;
        }
        gridH[j].setAttribute('d', `M ${ox} ${sy(v).toFixed(1)} L ${(ox + side).toFixed(1)} ${sy(v).toFixed(1)}`);
        gridV[j].setAttribute('d', `M ${sx(v).toFixed(1)} ${oy} L ${sx(v).toFixed(1)} ${(oy + side).toFixed(1)}`);
      }
      axX.setAttribute('x1', ox); axX.setAttribute('y1', zy);
      axX.setAttribute('x2', ox + side); axX.setAttribute('y2', zy);
      axY.setAttribute('x1', zx); axY.setAttribute('y1', oy);
      axY.setAttribute('x2', zx); axY.setAttribute('y2', oy + side);

      const showEig = SHOW_EIG[step];
      const R = side * 0.44;
      [[eig1, U[0]], [eig2, U[1]]].forEach(([ln, u]) => {
        ln.setAttribute('x1', (zx - R * u[0]).toFixed(1));
        ln.setAttribute('y1', (zy + R * u[1]).toFixed(1));
        ln.setAttribute('x2', (zx + R * u[0]).toFixed(1));
        ln.setAttribute('y2', (zy - R * u[1]).toFixed(1));
        ln.setAttribute('opacity', showEig ? '1' : '0');
      });

      pts.forEach((p, i) => {
        cities[i].setAttribute('cx', sx(p[0]).toFixed(1));
        cities[i].setAttribute('cy', sy(p[1]).toFixed(1));
        cityLbls[i].setAttribute('x', (sx(p[0]) + 10).toFixed(1));
        cityLbls[i].setAttribute('y', (sy(p[1]) + 4).toFixed(1));
      });
      // the two strangers keep a ray to the origin — the angle between those rays IS their cosine
      [0, 1].forEach((i) => {
        const p = pts[i] || [0, 0];
        rays[i].setAttribute('x1', zx); rays[i].setAttribute('y1', zy);
        rays[i].setAttribute('x2', sx(p[0]).toFixed(1)); rays[i].setAttribute('y2', sy(p[1]).toFixed(1));
      });

      const ct = (COS_OF[step] || {}).cosines || {};
      const vals = ct.cos || [];
      rowVal.forEach((t, i) => {
        const v = vals[i];
        t.textContent = f4(v);
        t.setAttribute('class', 'wg-val' + (i === 0 ? (Math.abs(v) < 1e-9 ? ' is-cool' : ' is-hot') : ''));
      });
      meanLbl.textContent = `${labels.mean || 'mean'} = ${f4(ct.mean)}`;

      if (step === 2 || step === 3) {
        matLines[0].textContent = `Σ = [[${f2(SIG[0][0])}, ${f2(SIG[0][1])}], [${f2(SIG[1][0])}, ${f2(SIG[1][1])}]]`;
        matLines[1].textContent = `λ₁ = ${f2(LAM[0])}   λ₂ = ${f2(LAM[1])}   κ = ${f2(T.conditionNumber)}`;
        matLines[2].textContent = labels.offdiag || 'the off-diagonal is the leftover shear';
      } else if (step >= 4) {
        matLines[0].textContent = 'W = U Λ^(−1/2)';
        matLines[1].textContent = `1/√λ = ${f4((T.scale || [])[0])}, ${f4((T.scale || [])[1])}`;
        matLines[2].textContent = labels.square || 'the diamond is now a square';
      } else {
        matLines.forEach((t) => { t.textContent = ''; });
      }
    };
  },
});
