    {
      id: 'rlhf', kind: 'prose',
      heading: { en: "Fitting the cloth to the wearer", ru: "Подгоняю ткань по заказчику", tt: "Тукыманы кияр кешегә җайлыйм" },
      img: 'L15/L15-11-rlhf.png', imgPos: 'right',
      imgAlt: { en: "Séréga, the master weaver, kneels beside a finished bolt of cloth draped over a customer's shoulders, easing a seam with his fingers while a second, gruff weaver-critic points at two rival swatches — thumbs up on one, thumbs down on the other.", ru: "Серёга, мастер-ткач, стоит на коленях у готового отреза, наброшенного на плечи заказчика, поправляет пальцами шов, а рядом суровый ткач-критик показывает на два соперничающих лоскута — одному большой палец вверх, другому вниз.", tt: "Серёга, оста тукучы, заказчик җилкәсенә салынган әзер тукыма янында тезләнеп җөйне төзәтә, ә янында катгый тукучы-критик ике ярышучы кисәккә төртеп күрсәтә — берсенә баш бармак өскә, икенчесенә аска." },
      imgCaption: { en: "**A base loom weaves *plausible* cloth. RLHF makes it weave the cloth you actually wanted.**", ru: "**Базовый станок ткёт *правдоподобную* ткань. RLHF учит его ткать ту, что ты и правда хотел.**", tt: "**Базовый станок *ышанычлы* тукыма суга. RLHF аны син чыннан теләгән тукыманы сугарга өйрәтә.**" },
      body: {
        en: [
          "A freshly pretrained loom is a marvel — and *stubborn*. It has learned only to weave the **most plausible next thread**, so ask it a question and it may answer with another question, wander off the pattern, or hand you something coarse. It is skilled, not *obliging*. Prompting alone won't tame it: a clever request is just how I hold the shuttle, not a change in the loom itself. To make it *helpful, honest, harmless* I must adjust the machine to the wearer's taste — and that adjustment has three passes.",
          "First I sit it beside good work — demonstrations of *instruction → answer* — and let it imitate the format. This is **supervised fine-tuning (SFT)**. Then, because I cannot write a rule for \"nicer,\" I let people be the judges: I lay two finished pieces side by side and they point to the better one, \\(y_w \\succ y_l\\). From thousands of such verdicts a second little machine, the **reward model**, learns to guess the human's thumb — a single number for any cloth. Finally I let the loom weave freely and nudge every choice toward that reward with **PPO**, tied by a short leash \\(-\\beta\\,\\mathrm{KL}\\) back to the SFT weave so it never drifts into strange, gamed patterns.",
          "And here is the quiet marvel: taste beats size. A small loom fitted this way — InstructGPT at 1.3B — is preferred over a base machine **a hundred times larger**. RLHF adds no new *facts* (those came from pretraining); it only aligns *behavior*. The simpler path, **DPO**, skips the reward model and the RL loop and optimizes the same preferences directly. But I stay watchful: chase the reward too hard and the loom starts *flattering* the judge — weaving what earns a thumbs-up rather than what is true. Goodhart's warning at the loom — when the measure becomes the target, it stops measuring.",
        ],
        ru: [
          "Только что предобученный станок — чудо, и притом *упрямое*. Он умеет класть лишь **самую правдоподобную следующую нить**: задай ему вопрос — он может ответить вопросом, уйти в сторону от узора, выдать что-то грубое. Он умелый, но не *послушный*. Одним промптом его не приручить: хитрый запрос — это лишь то, как я держу челнок, а не переделка самого станка. Чтобы он стал *полезным, честным, безвредным*, я подгоняю машину под вкус заказчика — и подгонка идёт в три прохода.",
          "Сперва сажаю его рядом с хорошей работой — демонстрациями «инструкция → ответ» — и даю перенять формат. Это **supervised fine-tuning (SFT)**. Потом, раз правило для «приятнее» не напишешь, судьями делаю людей: кладу два готовых отреза бок о бок, и они указывают на лучший, \\(y_w \\succ y_l\\). Из тысяч таких вердиктов вторая машинка — **reward model** — учится угадывать палец человека, выдавая одно число на любую ткань. Наконец пускаю станок ткать свободно и с помощью **PPO** подталкиваю каждый выбор к этой награде, на коротком поводке \\(-\\beta\\,\\mathrm{KL}\\) к SFT-плетению — чтобы он не уезжал в странные узоры, подогнанные под судью.",
          "И вот тихое чудо: вкус побеждает размер. Малый станок, так подогнанный, — InstructGPT на 1,3B — люди выбирают чаще, чем базовую машину, которая **в сто с лишним раз крупнее**. RLHF не добавляет новых *фактов* (они пришли на предобучении) — он выравнивает лишь *поведение*. Путь попроще, **DPO**, обходится без reward-модели и без RL-цикла, оптимизируя те же предпочтения напрямую. Но я держу ухо востро: гонись за наградой слишком рьяно — и станок начнёт *заискивать* перед судьёй: ткать то, за что поднимут палец, а не то, что верно. Предостережение Гудхарта у станка: когда мера становится целью, она перестаёт мерить.",
        ],
        tt: [
          "Яңа гына предобучение узган станок — могҗиза, шул ук вакытта *үҗәт*. Ул бары **иң ышанычлы киләсе җепне** сугарга гына өйрәнгән: сорау бирсәң — сорау белән җавап бирергә, үрнәктән читкә китәргә, тупас нәрсә чыгарырга мөмкин. Ул оста, әмма *тыңлаучан* түгел. Бер prompt белән генә аны кулга ияләштереп булмый: хәйләкәр запрос — бу минем чувыкны ничек тотуым гына, станокның үзен үзгәртү түгел. Аны *файдалы, дөрес, зарарсыз* итәр өчен, машинаны кияр кешенең зәвыгына җайлыйм — һәм бу җайлау өч үтүдә бара.",
          "Башта аны яхшы эш янына утыртам — «инструкция → җавап» демонстрацияләре янына — һәм форматны отып алырга бирәм. Бу — **supervised fine-tuning (SFT)**. Аннары «яхшырак» өчен кагыйдә язып булмагач, кешеләрне хөкемдар итәм: ике әзер кисәкне янәшә куям, алар яхшысына төртеп күрсәтә, \\(y_w \\succ y_l\\). Мондый меңләгән хөкемнәрдән икенче кечкенә машина — **reward model** — кешенең бармагын чамаларга өйрәнә, теләсә нинди тукымага бер сан бирә. Ниһаять, станокка ирекле сугарга биреп, **PPO** белән һәр сайлауны шул бүләккә этәрәм, кыска җиптә \\(-\\beta\\,\\mathrm{KL}\\) SFT-үрнәгенә тагылган килеш — сәер, алдалы үрнәкләргә китмәсен өчен.",
          "Менә тыныч могҗиза: зәвык зурлыкны җиңә. Шулай җайланган кечкенә станок — 1.3B InstructGPT — базовый машинадан **йөз мәртәбә зуррактан** артыграк күрелә. RLHF яңа *фактлар* өстәми (алар предобучениедә килгән) — ул бары *тәртипне* тигезли. Гадирәк юл, **DPO**, reward-моделсез һәм RL-циклсыз эшли, шул ук өстенлекләрне туры оптимизацияли. Әмма мин сак торам: бүләк артыннан артык каты кусаң — станок хөкемдарга *ялагайлана* башлый, дөресне түгел, ә баш бармак өскә алганны суга. Станок янында Goodhart кисәтүе: үлчәм максат булып китсә, ул үлчәүдән туктый.",
        ],
      },
    },
