/* hub-toll/logic.js — L18 "The Curved Map", acts 03–04: the bridge the lecture was missing.

   Act 03 diagnoses hubness on a toy (n = 120, k = 5). Act 04 prescribes CSLS — and then immediately
   leaves for somebody else's benchmark. This figure runs the lecture's own cure on the lecture's own
   patient: the SAME cloud, two retrieval rules.

     raw   — rank candidates by distance d(q, y).
     CSLS  — rank by 2·d(q,y) − r̄(q) − r̄(y), where r̄(x) is the mean distance to x's K = 10 nearest,
             i.e. how crowded x's own neighbourhood is. A hub sits in a dense pocket, so it pays the
             biggest toll.

   At d = 20 the skew of N_k falls 2.5904 → 0.3923, the busiest point drops from 39 lists to 13, and
   the anti-hub tail from 12.5% to 2.5%. Steps 3–4 zoom into ONE query so the reader can watch a single
   rank flip: the hub is genuinely CLOSER (4.8211 vs 5.0820) and still loses, because its neighbourhood
   is 1.88 tighter. NOTE the metric — this toy is EUCLIDEAN, like Radovanović 2010.

   DRIVER-AGNOSTIC: setStep(k)/maxStep, binds NO keyboard/scroll. EVERY number comes from
   data/l18-geometry.json → hubToll (generated by _research/gen_l18.py). Built on _widget-base.js.

   Steps (maxStep = 5):
     0 → d = 2, raw kNN: the N_k histogram is nearly symmetric.                            s0
     1 → d = 20, raw kNN: the tail grows — one point is on 39 lists, 12.5% on none.         s1
     2 → the hub named, and its correlation with proximity to the centroid.                 s2
     3 → one query: the hub is the raw top-1, by 0.26 of distance.                          s3
     4 → the same query under CSLS: the rank flips to the honest candidate.                 s4
     5 → CSLS over the whole cloud: skew 2.5904 → 0.3923.                                   s5 */
import { defineWidget } from '../_widget-base.js';

export const mountHubToll = defineWidget({
  id: 'hub-toll',
  rootClass: 'ht-root',
  exportName: 'mountHubToll',
  maxStep: 5,
  render({ host, data, labels, el }) {
    // `data.phase` lets ONE widget serve two slides: the deck's act-03 mount walks the DIAGNOSIS
    // steps 0–2 and the act-04 mount (phase:"cure") walks the CURE steps 3–5, each declaring its own
    // data-max-step. The Book mounts the raw data/l18-geometry.json, which carries no phase, and
    // scrolls the whole six-step arc. It rides inside `data` because the deck-adapter forwards only
    // {data, labels, i18nAll} — a top-level mount arg would be dropped.
    const BASE = (data && data.phase) === 'cure' ? 3 : 0;
    const T = (data && data.hubToll) || {};
    const byDim = T.byDim || {};
    const edges = T.histEdges || [0, 1, 3, 6, 10, 15, 21, 40];
    const flip = T.flipExample || {};
    const f4 = (x) => (typeof x === 'number' && isFinite(x) ? x.toFixed(4) : '—');
    const f2 = (x) => (typeof x === 'number' && isFinite(x) ? x.toFixed(2) : '—');

    // step → { dim, rule, focus } — focus draws the single-query walk-through
    const PLAN = [
      { dim: 2, rule: 'raw', focus: false },
      { dim: 20, rule: 'raw', focus: false },
      { dim: 20, rule: 'raw', focus: false, nameHub: true },
      { dim: 20, rule: 'raw', focus: true },
      { dim: 20, rule: 'csls', focus: true },
      { dim: 20, rule: 'csls', focus: false },
    ];
    const entry = (dim) => byDim['d' + dim] || {};

    const W = 660, H = 400;
    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, class: 'wgt-svg ht-svg', role: 'img',
      'aria-label': labels.alt || '' }, host);

    // ── LEFT: the cloud. Radius = N_k, so a hub is literally fat. ─────────────────────────────
    const box = { x: 24, y: 32, w: 296, h: 244 };
    el('text', { x: box.x + box.w / 2, y: box.y - 12, class: 'ht-head', 'text-anchor': 'middle' }, svg)
      .textContent = labels.cloud || 'the cloud · circle size = N_k';
    const links = [0, 1].map(() => el('line', { x1: 0, y1: 0, x2: 0, y2: 0, class: 'ht-link', opacity: 0 }, svg));
    const N = (entry(20).points || []).length || 120;
    const dots = [];
    for (let i = 0; i < N; i += 1) dots.push(el('circle', { cx: box.x, cy: box.y, r: 2, class: 'ht-pt' }, svg));

    // ── RIGHT: the N_k histogram ──────────────────────────────────────────────────────────────
    const hb = { x: 380, y: 44, w: 250, h: 150 };
    el('text', { x: hb.x, y: hb.y - 14, class: 'ht-head' }, svg).textContent = labels.hist || 'how many points sit on N_k lists';
    el('line', { x1: hb.x, y1: hb.y + hb.h, x2: hb.x + hb.w, y2: hb.y + hb.h, class: 'ht-axis' }, svg);
    const nb = edges.length - 1;
    const bw = hb.w / nb - 3;
    const bars = [];
    for (let i = 0; i < nb; i += 1) {
      bars.push(el('rect', { x: hb.x + i * (hb.w / nb) + 1.5, width: bw, y: hb.y + hb.h, height: 0, class: 'ht-bar' }, svg));
      el('text', { x: hb.x + i * (hb.w / nb) + bw / 2 + 1.5, y: hb.y + hb.h + 14, class: 'ht-lbl',
        'text-anchor': 'middle' }, svg).textContent = i === nb - 1 ? `${edges[i]}+` : `${edges[i]}–${edges[i + 1] - 1}`;
    }

    // ── the three counters + the active rule ──────────────────────────────────────────────────
    const statX = [hb.x, hb.x + 92, hb.x + 178];
    const statLbls = [labels.skew || 'skew N_k', labels.maxNk || 'max N_k', labels.anti || 'anti-hubs'];
    const stats = statX.map((x, i) => {
      el('text', { x, y: hb.y + hb.h + 42, class: 'ht-statlbl' }, svg).textContent = statLbls[i];
      return el('text', { x, y: hb.y + hb.h + 62, class: 'ht-stat' }, svg);
    });
    const ruleLbl = el('text', { x: hb.x, y: hb.y + hb.h + 92, class: 'ht-rule' }, svg);
    const dimLbl = el('text', { x: box.x, y: box.y + box.h + 22, class: 'ht-head' }, svg);
    const corrLbl = el('text', { x: box.x, y: box.y + box.h + 42, class: 'ht-lbl' }, svg);
    const flipLines = [0, 1, 2, 3].map((i) =>
      el('text', { x: box.x, y: box.y + box.h + 42 + i * 19, class: 'ht-flip' }, svg));

    return function update(k) {
      const p = PLAN[Math.max(0, Math.min(PLAN.length - 1, BASE + k))];
      const e = entry(p.dim);
      const side = e[p.rule] || {};
      const pts = e.points || [];
      const nk = (p.rule === 'csls' ? e.nkCsls : e.nkRaw) || [];

      let lo = 0, hi = 0;
      pts.forEach((q) => { lo = Math.min(lo, q[0], q[1]); hi = Math.max(hi, q[0], q[1]); });
      const pad = (hi - lo) * 0.08 + 0.2;
      lo -= pad; hi += pad;
      const sq = Math.min(box.w, box.h);
      const ox = box.x + (box.w - sq) / 2, oy = box.y + (box.h - sq) / 2;
      const sx = (v) => ox + ((v - lo) / (hi - lo)) * sq;
      const sy = (v) => oy + sq - ((v - lo) / (hi - lo)) * sq;

      const maxNk = Math.max(1, ...(nk.length ? nk : [1]));
      dots.forEach((c, i) => {
        const q = pts[i] || [0, 0];
        const v = nk[i] || 0;
        c.setAttribute('cx', sx(q[0]).toFixed(1));
        c.setAttribute('cy', sy(q[1]).toFixed(1));
        c.setAttribute('r', (2.2 + 7 * Math.sqrt(v / maxNk)).toFixed(2));
        let cls = 'ht-pt';
        if (v === 0) cls += ' is-anti';
        if (i === e.hubId && (p.nameHub || p.focus || v >= maxNk)) cls += ' is-hub';
        if (p.focus && i === flip.alt) cls += ' is-alt';
        if (p.focus && i === flip.query) cls += ' is-query';
        c.setAttribute('class', cls);
      });

      // the single-query walk-through: two rays from the query, the winner solid green
      const showFlip = !!p.focus && pts.length > 0;
      [[flip.hub, 0], [flip.alt, 1]].forEach(([target, i]) => {
        const ln = links[i];
        if (!showFlip || target == null) { ln.setAttribute('opacity', 0); return; }
        const a = pts[flip.query] || [0, 0], b = pts[target] || [0, 0];
        ln.setAttribute('x1', sx(a[0]).toFixed(1)); ln.setAttribute('y1', sy(a[1]).toFixed(1));
        ln.setAttribute('x2', sx(b[0]).toFixed(1)); ln.setAttribute('y2', sy(b[1]).toFixed(1));
        ln.setAttribute('opacity', 1);
        const hubWins = p.rule === 'raw';
        const win = (i === 0) === hubWins;
        ln.setAttribute('class', 'ht-link ' + (win ? 'is-win' : 'is-lose'));
      });

      const hist = side.hist || [];
      const hmax = Math.max(1, ...(hist.length ? hist : [1]));
      bars.forEach((b, i) => {
        const h = ((hist[i] || 0) / hmax) * hb.h;
        b.setAttribute('y', (hb.y + hb.h - h).toFixed(1));
        b.setAttribute('height', h.toFixed(1));
      });

      const vals = [f4(side.skew), String(side.maxNk == null ? '—' : side.maxNk),
        `${side.antiHubPct == null ? '—' : side.antiHubPct}%`];
      stats.forEach((t, i) => {
        t.textContent = vals[i];
        t.setAttribute('class', 'ht-stat' + (p.rule === 'csls' ? ' is-good' : (p.dim >= 20 ? ' is-bad' : '')));
      });
      ruleLbl.textContent = p.rule === 'csls'
        ? (labels.ruleCsls || 'rule: CSLS = 2·d − r̄(q) − r̄(y)')
        : (labels.ruleRaw || 'rule: raw kNN by distance');
      dimLbl.textContent = `d = ${p.dim} · n = ${T.n || 120} · k = ${T.k || 5} · K = ${T.K || 10}`;

      if (showFlip) {
        corrLbl.textContent = '';
        const wins = p.rule === 'raw' ? labels.hubWins : labels.altWins;
        flipLines[0].textContent = `q=#${flip.query}: d(q,#${flip.hub}) = ${f4(flip.dHub)} · d(q,#${flip.alt}) = ${f4(flip.dAlt)}`;
        flipLines[1].textContent = `r̄(#${flip.hub}) = ${f4(flip.rHub)} · r̄(#${flip.alt}) = ${f4(flip.rAlt)}`;
        flipLines[2].textContent = p.rule === 'csls'
          ? `CSLS = ${f4(flip.cslsHub)} vs ${f4(flip.cslsAlt)}`
          : '';
        flipLines[3].textContent = wins || '';
        flipLines[3].setAttribute('class', 'ht-flip' + (p.rule === 'csls' ? ' is-win' : ''));
      } else {
        flipLines.forEach((t) => { t.textContent = ''; });
        corrLbl.textContent = p.nameHub
          ? `${labels.corr || 'corr(N_k, closeness to centroid)'} = ${f2(side.corrToCentroid)}`
          : '';
      }
    };
  },
});
